# Generated by Django 5.2.11 on 2026-03-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRifiuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'C - Carico'), ('O', 'O - Scarico originale'), ('M', 'M - Scarico effettivo'), ('R', 'R - Rettifica scarico')], db_index=True, max_length=1)),
                ('data', models.DateField(db_index=True)),
                ('id_registrazione', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('rif_op', models.CharField(blank=True, default='', max_length=200)),
                ('codice', models.CharField(blank=True, default='', max_length=100)),
                ('quantita', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('carico_scarico', models.CharField(blank=True, default='', max_length=10)),
                ('rentri_si_no', models.BooleanField(default=False)),
                ('salva', models.BooleanField(default=False)),
                ('note_rentri', models.TextField(blank=True, default='')),
                ('pericolosita', models.CharField(blank=True, default='', max_length=100)),
                ('rettifica_scarico', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('arrivo_fir', models.CharField(blank=True, default='', max_length=200)),
                ('aggiornato', models.DateTimeField(blank=True, null=True)),
                ('allegato', models.FileField(blank=True, null=True, upload_to='rentri/allegati/')),
                ('sharepoint_item_id', models.CharField(blank=True, default='', max_length=64)),
                ('inserito_da', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro Rifiuti',
                'verbose_name_plural': 'Registri Rifiuti',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
