# Generated by Django 5.2.11 on 2026-03-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentriImpostazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_iscrizione_rentri', models.CharField(blank=True, default='', help_text="Codice rilasciato dal sistema RENTRI all'atto dell'iscrizione.", max_length=50, verbose_name='Codice iscrizione RENTRI')),
                ('ragione_sociale', models.CharField(blank=True, default='', max_length=200, verbose_name='Ragione sociale')),
                ('responsabile_nome', models.CharField(blank=True, default='', max_length=200, verbose_name='Responsabile')),
                ('responsabile_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email responsabile')),
                ('note_generali', models.TextField(blank=True, default='', verbose_name='Note operative')),
            ],
            options={
                'verbose_name': 'Impostazioni Rentri',
                'verbose_name_plural': 'Impostazioni Rentri',
            },
        ),
    ]
