# Generated by Django 5.2.16 on 2026-09-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentri', '0004_rentriimpostazioni_responsabili'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentriRegistroCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Progressivo registro Rentri',
                'verbose_name_plural': 'Progressivi registro Rentri',
            },
        ),
    ]
