# Generated by Django 5.2.16 on 2026-10-07 07:49

import core.private_attachments
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentri', '0005_rentriregistrocounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrorifiuti',
            name='allegato',
            field=models.FileField(blank=True, null=True, storage=core.private_attachments.PrivateAttachmentStorage(download_hint='Allegato RENTRI: non esposto via URL.'), upload_to='rentri/allegati/'),
        ),
    ]
