# Generated by Django 5.2.11 on 2026-03-19 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('module_name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('schedule_hint', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_critical', models.BooleanField(db_index=True, default=False)),
                ('expected_max_interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_max_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('alert_after_consecutive_failures', models.PositiveIntegerField(default=3)),
                ('owners_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('acl', 'ACL'), ('ui', 'UI'), ('integration', 'Integration'), ('automation', 'Automation'), ('performance', 'Performance'), ('data', 'Data'), ('system', 'System'), ('user_report', 'Segnalazione utente')], db_index=True, max_length=24)),
                ('severity', models.CharField(choices=[('low', 'Bassa'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], db_index=True, max_length=16)),
                ('source', models.CharField(choices=[('web', 'Web'), ('automation', 'Automation'), ('user_manual', 'Utente'), ('system_watchdog', 'Watchdog')], db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('new', 'Nuova'), ('triage', 'In triage'), ('in_progress', 'In lavorazione'), ('resolved', 'Risolta'), ('ignored', 'Ignorata')], db_index=True, default='new', max_length=24)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('occurrences_count', models.PositiveIntegerField(default=1)),
                ('affected_users_count', models.PositiveIntegerField(default=0)),
                ('module_name', models.CharField(blank=True, default='', max_length=100)),
                ('current_url', models.CharField(blank=True, default='', max_length=500)),
                ('route_name', models.CharField(blank=True, default='', max_length=200)),
                ('release_version', models.CharField(blank=True, default='', max_length=64)),
                ('environment', models.CharField(blank=True, default='', max_length=64)),
                ('is_regression', models.BooleanField(default=False)),
                ('notes_internal', models.TextField(blank=True, default='')),
                ('resolution_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_issues_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_issues_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('failed', 'Failed'), ('missed', 'Missed')], db_index=True, default='warning', max_length=16)),
                ('trigger_type', models.CharField(choices=[('scheduler', 'Scheduler'), ('manual', 'Manual'), ('retry', 'Retry'), ('watchdog', 'Watchdog')], default='scheduler', max_length=16)),
                ('run_identifier', models.CharField(blank=True, max_length=128, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('exception_class', models.CharField(blank=True, default='', max_length=255)),
                ('traceback_text', models.TextField(blank=True, default='')),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('release_version', models.CharField(blank=True, default='', max_length=64)),
                ('environment', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='monitoring.automationjob')),
                ('related_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_executions', to='monitoring.issue')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IssueOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('web', 'Web'), ('automation', 'Automation'), ('user_manual', 'Utente'), ('system_watchdog', 'Watchdog')], max_length=24)),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('acl', 'ACL'), ('ui', 'UI'), ('integration', 'Integration'), ('automation', 'Automation'), ('performance', 'Performance'), ('data', 'Data'), ('system', 'System'), ('user_report', 'Segnalazione utente')], max_length=24)),
                ('severity', models.CharField(choices=[('low', 'Bassa'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], max_length=16)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, default='', max_length=16)),
                ('current_url', models.CharField(blank=True, default='', max_length=500)),
                ('route_name', models.CharField(blank=True, default='', max_length=200)),
                ('module_name', models.CharField(blank=True, default='', max_length=100)),
                ('view_name', models.CharField(blank=True, default='', max_length=255)),
                ('username_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('legacy_user_id', models.IntegerField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('message', models.TextField(blank=True, default='')),
                ('exception_class', models.CharField(blank=True, default='', max_length=255)),
                ('traceback_text', models.TextField(blank=True, default='')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=64)),
                ('extra_json', models.JSONField(blank=True, default=dict)),
                ('release_version', models.CharField(blank=True, default='', max_length=64)),
                ('environment', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='monitoring.issue')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_issue_occurrences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('current_url', models.CharField(blank=True, default='', max_length=500)),
                ('route_name', models.CharField(blank=True, default='', max_length=200)),
                ('module_name', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.TextField()),
                ('browser_info', models.CharField(blank=True, default='', max_length=500)),
                ('extra_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_problem_reports', to='monitoring.issue')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_problem_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status'], name='monitoring__status_da1438_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['severity'], name='monitoring__severit_358ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['last_seen_at'], name='monitoring__last_se_38df44_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['fingerprint'], name='monitoring__fingerp_8c0c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['started_at'], name='monitoring__started_842f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['status'], name='monitoring__status_2ec639_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['job', '-started_at'], name='monitoring__job_id_8561d0_idx'),
        ),
        migrations.AddIndex(
            model_name='issueoccurrence',
            index=models.Index(fields=['occurred_at'], name='monitoring__occurre_5ee079_idx'),
        ),
        migrations.AddIndex(
            model_name='issueoccurrence',
            index=models.Index(fields=['issue', '-occurred_at'], name='monitoring__issue_i_4447cd_idx'),
        ),
    ]
