# Generated by Django 5.2.11 on 2026-03-11 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('current_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['metric_code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('source_code', models.CharField(db_index=True, max_length=100)),
                ('operation_type', models.CharField(choices=[('insert', 'Insert'), ('update', 'Update')], db_index=True, max_length=20)),
                ('watched_field', models.CharField(blank=True, max_length=100, null=True)),
                ('trigger_scope', models.CharField(choices=[('all_inserts', 'All inserts'), ('all_updates', 'All updates'), ('specific_field', 'Specific field'), ('any_change', 'Any change')], db_index=True, max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_draft', models.BooleanField(db_index=True, default=True)),
                ('stop_on_first_failure', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('field_name', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not equals'), ('contains', 'Contains'), ('startswith', 'Starts with'), ('endswith', 'Ends with'), ('gt', 'Greater than'), ('gte', 'Greater than or equal'), ('lt', 'Less than'), ('lte', 'Less than or equal'), ('is_true', 'Is true'), ('is_false', 'Is false'), ('in_csv', 'In CSV'), ('not_in_csv', 'Not in CSV'), ('is_empty', 'Is empty'), ('is_not_empty', 'Is not empty'), ('changed', 'Changed'), ('changed_to', 'Changed to'), ('changed_from_to', 'Changed from to')], max_length=30)),
                ('expected_value', models.TextField(blank=True, default='')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('date', 'Date'), ('datetime', 'Datetime')], max_length=20)),
                ('compare_with_old', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='automazioni.automationrule')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('action_type', models.CharField(choices=[('send_email', 'Send email'), ('insert_record', 'Insert record'), ('update_record', 'Update record'), ('update_dashboard_metric', 'Update dashboard metric'), ('write_log', 'Write log')], max_length=40)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automazioni.automationrule')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_event_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('source_code', models.CharField(db_index=True, max_length=100)),
                ('operation_type', models.CharField(choices=[('insert', 'Insert'), ('update', 'Update')], db_index=True, max_length=20)),
                ('trigger_event_label', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('skipped', 'Skipped'), ('test', 'Test')], db_index=True, max_length=20)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('old_payload_json', models.JSONField(blank=True, null=True)),
                ('result_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('execution_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('is_test', models.BooleanField(db_index=True, default=False)),
                ('error_trace', models.TextField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_runs_initiated', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_logs', to='automazioni.automationrule')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('skipped', 'Skipped')], db_index=True, max_length=20)),
                ('result_message', models.TextField(blank=True, default='')),
                ('error_trace', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='automazioni.automationaction')),
                ('run_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='automazioni.automationrunlog')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
