# Generated by Django 5.2.11 on 2026-03-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='import_flow_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='import_source_package_version',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='import_source_rule_code',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
