# Generated by Django 5.2.11 on 2026-03-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automazioni', '0002_automationrule_import_flow_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationaction',
            name='action_type',
            field=models.CharField(choices=[('send_email', 'Send email'), ('insert_record', 'Insert record'), ('update_record', 'Update record'), ('update_dashboard_metric', 'Update dashboard metric'), ('write_log', 'Write log'), ('delay_schedule', 'Delay / Schedule (giorni)')], max_length=40),
        ),
    ]
