# Generated by Django 5.2.11 on 2026-04-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automazioni', '0006_automation_table_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationaction',
            name='action_type',
            field=models.CharField(choices=[('send_email', 'Send email'), ('insert_record', 'Insert record'), ('update_record', 'Update record'), ('update_trigger_record', 'Update triggering record'), ('update_dashboard_metric', 'Update dashboard metric'), ('write_log', 'Write log'), ('delay_schedule', 'Delay / Schedule'), ('http_request', 'HTTP request'), ('teams_webhook', 'Teams webhook')], max_length=40),
        ),
    ]
