# Generated by Django 5.2.11 on 2026-04-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automazioni', '0009_teams_webhook_preset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationDeliveryEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('endpoint_type', models.CharField(choices=[('teams_webhook_legacy', 'Teams webhook legacy'), ('teams_flow_webhook', 'Teams flow webhook')], db_index=True, max_length=40)),
                ('endpoint_url', models.TextField(verbose_name='Endpoint URL')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Attivo')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrizione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Endpoint delivery automazioni',
                'verbose_name_plural': 'Endpoint delivery automazioni',
                'ordering': ['name'],
            },
        ),
    ]
