# Generated by Django 5.2.11 on 2026-04-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automazioni', '0012_approvalmailboxmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalemailtemplate',
            name='approval_label',
            field=models.CharField(default='Approva', max_length=100, verbose_name='Label "Approva"'),
        ),
        migrations.AlterField(
            model_name='approvalemailtemplate',
            name='rejection_label',
            field=models.CharField(default='Rifiuta', max_length=100, verbose_name='Label "Rifiuta"'),
        ),
    ]
