# Generated by Django 5.2.11 on 2026-05-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automazioni', '0014_split_assenza_giornaliera_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationcondition',
            name='operator',
            field=models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not equals'), ('contains', 'Contains'), ('startswith', 'Starts with'), ('endswith', 'Ends with'), ('gt', 'Greater than'), ('gte', 'Greater than or equal'), ('lt', 'Less than'), ('lte', 'Less than or equal'), ('is_true', 'Is true'), ('is_false', 'Is false'), ('in_csv', 'In CSV'), ('not_in_csv', 'Not in CSV'), ('is_empty', 'Is empty'), ('is_not_empty', 'Is not empty'), ('changed', 'Changed'), ('changed_to', 'Changed to'), ('changed_from_to', 'Changed from to'), ('days_from_now_lte', 'Days from now ≤'), ('days_from_now_gte', 'Days from now ≥'), ('days_span_gt', 'Days span >'), ('days_span_gte', 'Days span ≥')], max_length=30),
        ),
    ]
