# Generated by Django 5.2.11 on 2026-06-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automazioni', '0016_alter_automationaction_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='exclusion_group',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Gruppo di esclusione: le regole con lo stesso gruppo che matchano lo stesso record si escludono a vicenda. Ne parte una sola, quella a priorita' piu' alta; se va in errore si prova la successiva del gruppo (fallback a cascata). Vuoto = nessuna esclusione.", max_length=80),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='priority',
            field=models.IntegerField(db_index=True, default=0, help_text="Priorita' nel gruppo di esclusione: valore piu' alto = valutata prima. Ignorata se exclusion_group e' vuoto."),
        ),
    ]
