# Generated by Django 5.2.11 on 2026-06-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automazioni', '0018_automationcooldowngroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationaction',
            name='action_type',
            field=models.CharField(choices=[('send_email', 'Send email'), ('insert_record', 'Insert record'), ('update_record', 'Update record'), ('update_trigger_record', 'Update triggering record'), ('split_assenza_giornaliera', 'Split assenza giornaliera'), ('update_dashboard_metric', 'Update dashboard metric'), ('write_log', 'Write log'), ('delay_schedule', 'Delay / Schedule'), ('http_request', 'HTTP request'), ('teams_webhook', 'Teams webhook'), ('send_anomalie_mail_action', 'Invia mail-action anomalie (token sicuro)'), ('send_anomalie_mail_action_by_op', "Invia mail-action anomalie a CC/CAR dell'OP (risolti automaticamente)"), ('send_approval', 'Richiedi Approvazione'), ('do_until', 'Do Until (Ripeti fino a condizione)'), ('for_each', 'Per Ogni Elemento (For Each)'), ('branch', 'Branch / Condizione If-Else'), ('count_branch', 'Conta record e confronta soglia (Count Branch)')], max_length=40),
        ),
    ]
