# Generated by Django 5.2.11 on 2026-06-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automazioni', '0019_alter_automationaction_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='operation_type',
            field=models.CharField(choices=[('insert', 'Insert'), ('update', 'Update'), ('manual', 'Manuale (on-demand)')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='automationrunlog',
            name='operation_type',
            field=models.CharField(choices=[('insert', 'Insert'), ('update', 'Update'), ('manual', 'Manuale (on-demand)')], db_index=True, max_length=20),
        ),
    ]
