# Generated by Django 5.2.11 on 2026-07-09 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automazioni', '0020_alter_automationrule_operation_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMailText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('subject', models.CharField(blank=True, default='', help_text='Oggetto personalizzato. Vuoto = oggetto predefinito del comando.', max_length=300)),
                ('intro', models.TextField(blank=True, default='', help_text="Paragrafo introduttivo sopra l'elenco scadenze. Vuoto = nessuna intro.")),
                ('footer', models.TextField(blank=True, default='', help_text='Nota a piè di pagina. Vuoto = nessuna nota.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testo mail task pianificato',
                'verbose_name_plural': 'Testi mail task pianificati',
            },
        ),
    ]
