# Generated by Django 5.2.16 on 2026-09-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automazioni', '0024_alter_automationaction_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationaction',
            name='action_type',
            field=models.CharField(choices=[('native_process', 'Esegui processo del modulo'), ('send_email', 'Send email'), ('insert_record', 'Insert record'), ('update_record', 'Update record'), ('update_trigger_record', 'Update triggering record'), ('split_assenza_giornaliera', 'Split assenza giornaliera'), ('update_dashboard_metric', 'Update dashboard metric'), ('write_log', 'Write log'), ('delay_schedule', 'Delay / Schedule'), ('http_request', 'HTTP request'), ('teams_webhook', 'Teams webhook'), ('send_anomalie_mail_action', 'Invia mail-action anomalie (token sicuro)'), ('send_anomalie_mail_action_by_op', "Invia mail-action anomalie a CC/CAR dell'OP (risolti automaticamente)"), ('send_meeting_minute', 'Invia minuta incontro KICK-OFF ai partecipanti'), ('send_meeting_invite', 'Invia convocazione incontro KICK-OFF (ordine del giorno)'), ('send_project_alert', 'Invia alert progetto KICK-OFF (sicurezza / VRF) a PM e capo commessa'), ('send_approval', 'Richiedi Approvazione'), ('do_until', 'Do Until (Ripeti fino a condizione)'), ('for_each', 'Per Ogni Elemento (For Each)'), ('branch', 'Branch / Condizione If-Else'), ('count_branch', 'Conta record e confronta soglia (Count Branch)')], max_length=40),
        ),
        migrations.CreateModel(
            name='ManagedFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('schedule', 'Pianificato'), ('event', 'Evento applicativo')], max_length=16)),
                ('schedule_type', models.CharField(choices=[('I', 'Ogni N minuti'), ('C', 'Calendario')], default='I', max_length=1)),
                ('minutes', models.PositiveIntegerField(default=1)),
                ('cron', models.CharField(blank=True, default='', max_length=100)),
                ('queued_task_id', models.BigIntegerField(blank=True, null=True)),
                ('running_until', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='managed_flow', to='automazioni.automationrule')),
            ],
        ),
    ]
