# Generated by Django 5.2.16 on 2026-09-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automazioni', '0025_alter_automationaction_action_type_managedflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerRecoveryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.UUIDField(db_index=True)),
                ('original_id', models.BigIntegerField()),
                ('key', models.CharField(max_length=100)),
                ('signed_payload', models.TextField()),
                ('original_lock', models.DateTimeField()),
                ('flow_code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
