# Generated by Django 5.2.16 on 2026-09-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automazioni', '0026_brokerrecoveryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterHeartbeat',
            fields=[
                ('instance', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cluster', models.CharField(db_index=True, max_length=100)),
                ('seen_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterWatchdogState',
            fields=[
                ('cluster', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('checked_at', models.DateTimeField(null=True)),
                ('unhealthy', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(null=True)),
                ('recovery_pending', models.BooleanField(default=False)),
            ],
        ),
    ]
