# Generated by Django 5.2.16 on 2026-10-07 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automazioni', '0027_clusterheartbeat_clusterwatchdogstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationapproval',
            name='branch_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='automationapproval',
            name='branch_progress',
            field=models.PositiveIntegerField(default=0, help_text="Numero di azioni del ramo gia' eseguite."),
        ),
        migrations.AddField(
            model_name='automationapproval',
            name='branch_status',
            field=models.CharField(blank=True, choices=[('', 'Nessuna'), ('running', 'In esecuzione'), ('done', 'Completate'), ('partial_error', 'Completate con errori')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='automationapproval',
            name='branch_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AutomationApprovalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.CharField(max_length=255)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_decision', models.CharField(blank=True, default='', max_length=20)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='automazioni.automationapproval')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
