# Generated by Django 5.2.11 on 2026-03-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_user_id', models.IntegerField(db_index=True)),
                ('pulsante_id', models.IntegerField()),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('legacy_user_id', 'pulsante_id')},
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_user_id', models.IntegerField(db_index=True)),
                ('modulo', models.CharField(max_length=100)),
                ('azione', models.CharField(max_length=100)),
                ('can_view', models.BooleanField(null=True)),
                ('can_edit', models.BooleanField(null=True)),
                ('can_delete', models.BooleanField(null=True)),
                ('can_approve', models.BooleanField(null=True)),
            ],
            options={
                'unique_together': {('legacy_user_id', 'modulo', 'azione')},
            },
        ),
    ]
