# Generated by Django 5.2.11 on 2026-03-01 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userdashboardconfig_userpermissionoverride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_path', models.CharField(max_length=300, unique=True)),
                ('target_route_name', models.CharField(blank=True, default='', max_length=120)),
                ('target_url_path', models.CharField(blank=True, default='', max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['legacy_path'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('section', models.CharField(db_index=True, default='topbar', max_length=40)),
                ('route_name', models.CharField(blank=True, default='', max_length=120)),
                ('url_path', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.IntegerField(default=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_items_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_items_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section', 'order', 'label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavigationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_snapshots_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NavigationRoleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_role_id', models.IntegerField(db_index=True)),
                ('can_view', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_accesses', to='core.navigationitem')),
            ],
            options={
                'unique_together': {('item', 'legacy_role_id')},
            },
        ),
    ]
