# Generated by Django 5.2.11 on 2026-03-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_legacyredirect_navigationitem_navigationsnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModuleVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_user_id', models.IntegerField(db_index=True)),
                ('modulo', models.CharField(max_length=100)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('legacy_user_id', 'modulo')},
            },
        ),
    ]
