# Generated by Django 5.2.11 on 2026-03-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usermodulevisibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('utente_display', models.CharField(blank=True, default='', max_length=200)),
                ('azione', models.CharField(db_index=True, max_length=100)),
                ('modulo', models.CharField(db_index=True, max_length=100)),
                ('dettaglio', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_user_id', models.IntegerField(db_index=True)),
                ('tipo', models.CharField(choices=[('assenza_approvata', 'Assenza approvata'), ('assenza_rifiutata', 'Assenza rifiutata'), ('assenza_in_attesa', 'Assenza in attesa di approvazione'), ('generico', 'Generico')], default='generico', max_length=50)),
                ('messaggio', models.CharField(max_length=500)),
                ('url_azione', models.CharField(blank=True, default='', max_length=255)),
                ('letta', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
