# Generated by Django 5.2.11 on 2026-03-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_anagraficarisposta_id_alter_anagraficavoce_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifica',
            name='tipo',
            field=models.CharField(choices=[('assenza_approvata', 'Assenza approvata'), ('assenza_rifiutata', 'Assenza rifiutata'), ('assenza_in_attesa', 'Assenza in attesa di approvazione'), ('anomalia_segnalata', 'Anomalia segnalata al cliente'), ('anomalia_chiusa', 'Anomalia chiusa'), ('generico', 'Generico')], default='generico', max_length=50),
        ),
    ]
