# Generated by Django 5.2.11 on 2026-03-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_notifica_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDashboardLayout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legacy_user_id", models.IntegerField(db_index=True, unique=True)),
                ("layout", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
