# Generated by Django 5.2.11 on 2026-03-17 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_navigationitem_icon_group_active_patterns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('topbar_color', models.CharField(default='#1e3a5f', help_text='Colore esadecimale background topbar (es. #1e3a5f).', max_length=20)),
                ('order', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Categoria modulo',
                'verbose_name_plural': 'Categorie moduli',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='active_patterns',
            field=models.CharField(blank=True, default='', help_text="View name Django separati da virgola per rilevamento stato attivo (es. admin_portale:utenti_list,admin_portale:utente_edit). Lascia vuoto per usare solo l'URL.", max_length=500),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='group',
            field=models.CharField(blank=True, default='', help_text='Gruppo visivo per separatori nella subnav (es. accessi, navigazione, hub). Voci con stesso gruppo sono raggruppate.', max_length=80),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoria del modulo (determina il colore topbar quando questa voce è attiva).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_items', to='core.modulecategory'),
        ),
    ]
