# Generated by Django 5.2.11 on 2026-03-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_modulecategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruipreference',
            name='sidebar_footer_actions',
            field=models.JSONField(blank=True, default=None, help_text='Ordine personalizzato delle azioni rapide nel footer della sidebar. Null = ordine predefinito.', null=True),
        ),
    ]
