# Generated by Django 5.2.11 on 2026-03-20 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_expand_navigation_icon_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permesso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(max_length=100)),
                ('azione', models.CharField(max_length=100)),
                ('ruolo_id', models.IntegerField()),
                ('consentito', models.IntegerField(blank=True, null=True)),
                ('can_view', models.IntegerField(blank=True, null=True)),
                ('can_edit', models.IntegerField(blank=True, null=True)),
                ('can_delete', models.IntegerField(blank=True, null=True)),
                ('can_approve', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permessi',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pulsante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codice', models.CharField(max_length=100)),
                ('nome_visibile', models.CharField(blank=True, max_length=200, null=True)),
                ('icona', models.CharField(blank=True, max_length=20, null=True)),
                ('modulo', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'pulsanti',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ruoli',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UtenteLegacy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(max_length=500)),
                ('ruolo', models.CharField(blank=True, max_length=100, null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('deve_cambiare_password', models.BooleanField(default=False)),
                ('ruolo_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utenti',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnagraficaDipendente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aliasusername', models.CharField(blank=True, max_length=200, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('cognome', models.CharField(blank=True, max_length=200, null=True)),
                ('mansione', models.CharField(blank=True, max_length=200, null=True)),
                ('reparto', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('email_notifica', models.CharField(blank=True, max_length=200, null=True)),
                ('utente', models.OneToOneField(blank=True, db_column='utente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anagrafica', to='core.utentelegacy')),
            ],
            options={
                'db_table': 'anagrafica_dipendenti',
                'abstract': False,
            },
        ),
    ]
