# Generated by Django 5.2.11 on 2026-03-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_legacy_managed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifica',
            name='popup_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notifica',
            name='tipo',
            field=models.CharField(choices=[('assenza_approvata', 'Assenza approvata'), ('assenza_rifiutata', 'Assenza rifiutata'), ('assenza_in_attesa', 'Assenza in attesa di approvazione'), ('anomalia_segnalata', 'Anomalia segnalata al cliente'), ('anomalia_chiusa', 'Anomalia chiusa'), ('dpi_approvata', 'DPI approvata'), ('dpi_rifiutata', 'DPI rifiutata'), ('dpi_consegnata', 'DPI consegnata'), ('generico', 'Generico')], default='generico', max_length=50),
        ),
    ]
