# Generated by Django 5.2.11 on 2026-03-30 10:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_admin_acl_canonico_subnav'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='Usa solo lettere minuscole, numeri e separatori . _ : - (es. assenze.view).', regex='^[a-z0-9]+(?:[._:-][a-z0-9]+)*$')])),
                ('label', models.CharField(max_length=160)),
                ('module', models.CharField(db_index=True, max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission Definition',
                'verbose_name_plural': 'Permission Definitions',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RolePermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_role_id', models.IntegerField(db_index=True)),
                ('enabled', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(db_column='permission_code', on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='core.permissiondefinition', to_field='code')),
            ],
            options={
                'verbose_name': 'Role Permission Grant',
                'verbose_name_plural': 'Role Permission Grants',
                'ordering': ['legacy_role_id', 'permission_id'],
                'unique_together': {('legacy_role_id', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='RoutePermissionBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('path_pattern', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('match_strategy', models.CharField(choices=[('exact', 'Exact'), ('prefix', 'Prefix'), ('regex', 'Regex')], db_index=True, default='exact', max_length=12)),
                ('source_app', models.CharField(blank=True, default='', max_length=80)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.PositiveIntegerField(db_index=True, default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(db_column='permission_code', on_delete=django.db.models.deletion.CASCADE, related_name='route_bindings', to='core.permissiondefinition', to_field='code')),
            ],
            options={
                'verbose_name': 'Route Permission Binding',
                'verbose_name_plural': 'Route Permission Bindings',
                'ordering': ['priority', 'route_name', 'path_pattern', 'id'],
                'unique_together': {('route_name', 'path_pattern')},
            },
        ),
        migrations.CreateModel(
            name='UserPermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_user_id', models.IntegerField(db_index=True)),
                ('enabled', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(db_column='permission_code', on_delete=django.db.models.deletion.CASCADE, related_name='user_grants', to='core.permissiondefinition', to_field='code')),
            ],
            options={
                'verbose_name': 'User Permission Grant',
                'verbose_name_plural': 'User Permission Grants',
                'ordering': ['legacy_user_id', 'permission_id'],
                'unique_together': {('legacy_user_id', 'permission')},
            },
        ),
    ]
