# Generated by Django 5.2.11 on 2026-04-01 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_subnav_acl_v2_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNavigationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_user_id', models.IntegerField(db_index=True)),
                ('enabled', models.BooleanField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='core.navigationitem')),
            ],
            options={
                'ordering': ['legacy_user_id', 'item__section', 'item__order'],
                'unique_together': {('legacy_user_id', 'item')},
            },
        ),
    ]
