# Generated by Django 5.2.11 on 2026-04-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_navigation_semantic_icon_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecategory',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Alias SVG (es. shield-check), emoji, testo breve o URL immagine (.ico, .png, .svg) mostrato nella sidebar per la categoria.', max_length=500),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Alias SVG (es. newspaper), emoji, testo breve o URL immagine (.ico, .png, .svg) mostrato accanto alla label.', max_length=500),
        ),
    ]
