# Generated by Django 5.2.11 on 2026-04-08 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_admin_subnav_branding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped', models.BooleanField(default=False, help_text="Se True, il wizard non viene mostrato (utente esentato dall'admin).")),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('email_contatto', models.EmailField(blank=True, default='', max_length=254)),
                ('cellulare_contatto', models.CharField(blank=True, default='', max_length=50)),
                ('notifiche_assenze_email', models.BooleanField(default=True)),
                ('notifiche_comunicazioni_email', models.BooleanField(default=True)),
                ('notifiche_scadenzari_email', models.BooleanField(default=True)),
                ('notifiche_ticket_email', models.BooleanField(default=False)),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding utente',
                'verbose_name_plural': 'Onboarding utenti',
                'db_table': 'core_useronboarding',
            },
        ),
    ]
