# Generated by Django 5.2.11 on 2026-04-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_useronboarding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useronboarding',
            name='notifiche_assenze_email',
        ),
        migrations.RemoveField(
            model_name='useronboarding',
            name='notifiche_comunicazioni_email',
        ),
        migrations.RemoveField(
            model_name='useronboarding',
            name='notifiche_scadenzari_email',
        ),
        migrations.RemoveField(
            model_name='useronboarding',
            name='notifiche_ticket_email',
        ),
        migrations.AddField(
            model_name='useronboarding',
            name='notifiche_config',
            field=models.JSONField(blank=True, default=dict, help_text='Preferenze notifiche email per tipo. Es: {"assenze": true, "ticket": false}'),
        ),
    ]
