# Generated by Django 5.2.11 on 2026-04-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_seed_anomalie_api_role_grants"),
    ]

    operations = [
        migrations.AddField(
            model_name="useruipreference",
            name="theme_mode",
            field=models.CharField(
                choices=[("light", "Chiaro"), ("dark", "Scuro")],
                default="light",
                max_length=5,
            ),
        ),
    ]
