# Generated by Django 5.2.11 on 2026-05-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_useruipreference_theme_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistesecuzione',
            name='tipo_checklist',
            field=models.CharField(choices=[('checkin', 'Check-in (Onboarding)'), ('checkout', 'Check-out (Offboarding)'), ('preposto_ispezione', 'Ispezione periodica preposto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='checklistvoce',
            name='tipo_checklist',
            field=models.CharField(choices=[('checkin', 'Check-in (Onboarding)'), ('checkout', 'Check-out (Offboarding)'), ('preposto_ispezione', 'Ispezione periodica preposto')], db_index=True, max_length=20),
        ),
    ]
