# Generated by Django 5.2.11 on 2026-05-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_checklistesecuzione_tipo_checklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifica',
            name='tipo',
            field=models.CharField(choices=[('assenza_approvata', 'Assenza approvata'), ('assenza_rifiutata', 'Assenza rifiutata'), ('assenza_in_attesa', 'Assenza in attesa di approvazione'), ('anomalia_segnalata', 'Anomalia segnalata al cliente'), ('anomalia_chiusa', 'Anomalia chiusa'), ('dpi_approvata', 'DPI approvata'), ('dpi_rifiutata', 'DPI rifiutata'), ('dpi_consegnata', 'DPI consegnata'), ('dpi_scadenza', 'DPI in scadenza'), ('ticket_sla', 'SLA ticket scaduto'), ('asset_scadenza', 'Scadenza asset'), ('generico', 'Generico')], default='generico', max_length=50),
        ),
    ]
