# Generated by Django 5.2.11 on 2026-05-23 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_notifica_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTablePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(db_index=True, max_length=100)),
                ('state_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferenza tabella',
                'verbose_name_plural': 'Preferenze tabelle',
                'db_table': 'core_usertablepreference',
                'indexes': [models.Index(fields=['user', 'table_id'], name='core_userta_user_id_36755d_idx')],
                'unique_together': {('user', 'table_id')},
            },
        ),
    ]
