# Generated by Django 5.2.13 on 2026-06-14 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_notifica_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('CORRETTIVA', 'Correttiva'), ('PREVENTIVA', 'Preventiva')], default='CORRETTIVA', max_length=20)),
                ('stato', models.CharField(choices=[('APERTA', 'Aperta'), ('IN_CORSO', 'In corso'), ('CHIUSA', 'Chiusa (da verificare)'), ('VERIFICATA', 'Verificata'), ('ANNULLATA', 'Annullata')], db_index=True, default='APERTA', max_length=20)),
                ('source_code', models.CharField(blank=True, db_index=True, default='manuale', max_length=64)),
                ('source_pk', models.CharField(blank=True, default='', max_length=64)),
                ('source_label', models.CharField(blank=True, default='', help_text="Descrizione leggibile dell'origine (snapshot al momento della creazione).", max_length=255)),
                ('source_url', models.CharField(blank=True, default='', help_text='Link al record di origine nel modulo sorgente.', max_length=255)),
                ('reparto', models.CharField(blank=True, default='', max_length=200)),
                ('data_scadenza', models.DateField(blank=True, db_index=True, null=True)),
                ('evidenza_chiusura', models.TextField(blank=True, default='', help_text='Descrizione di cosa è stato fatto per risolvere (obbligatoria alla chiusura).')),
                ('data_chiusura', models.DateTimeField(blank=True, null=True)),
                ('data_verifica', models.DateTimeField(blank=True, null=True)),
                ('note_verifica', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chiusa_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_chiuse', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_create', to=settings.AUTH_USER_MODEL)),
                ('responsabile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_assegnate', to=settings.AUTH_USER_MODEL)),
                ('verificata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_verificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Azione correttiva/preventiva (CAPA)',
                'verbose_name_plural': 'Azioni correttive/preventive (CAPA)',
                'db_table': 'core_actionitem',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_code', 'source_pk'], name='core_action_source__344969_idx'), models.Index(fields=['stato', 'data_scadenza'], name='core_action_stato_00e710_idx')],
            },
        ),
    ]
