# Generated by Django 5.2.11 on 2026-07-04 17:46

import core.hub_bacheca_storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_anagrafica_sidebar_subnav'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HubLinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text='Emoji, alias SVG o URL immagine.', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.IntegerField(default=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_categories_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_categories_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HubLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('file', 'Documento'), ('url', 'Collegamento esterno'), ('internal', 'Scorciatoia interna')], max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('icon', models.CharField(blank=True, default='', max_length=500)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('route_name', models.CharField(blank=True, default='', max_length=160)),
                ('route_kwargs', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, storage=core.hub_bacheca_storage.HubLinkStorage(), upload_to='hub_links/%Y/%m')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_links_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_links_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.hublinkcategory')),
            ],
            options={
                'ordering': ['order', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HubLinkRoleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_role_id', models.IntegerField(db_index=True)),
                ('can_view', models.BooleanField(default=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_accesses', to='core.hublink')),
            ],
            options={
                'unique_together': {('link', 'legacy_role_id')},
            },
        ),
    ]
