# Generated by Django 5.2.16 on 2026-08-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_ofi_registro_toplevel_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='oggetto_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Chiave primaria del record, come testo (le tabelle legacy non usano solo interi).', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='oggetto_tipo',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Etichetta del modello (es. «tickets.ticket») o chiave legacy concordata.', max_length=100),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['oggetto_tipo', 'oggetto_id', '-created_at'], name='core_audit_oggetto_recenti'),
        ),
    ]
