# Generated by Django 5.2.16 on 2026-09-10 16:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auditlog_riferimento_oggetto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(?:[._-][a-z0-9]+)*$', "Codice gruppo: minuscole, cifre e separatori . _ - (es. 'manutenzione').")])),
                ('label', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('priority', models.IntegerField(db_index=True, default=100, help_text="Piu' alto = pesa di piu' quando due gruppi dicono cose diverse.")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gruppo di accesso',
                'verbose_name_plural': 'Gruppi di accesso',
                'ordering': ['-priority', 'label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccessGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_user_id', models.IntegerField(db_index=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.accessgroup')),
            ],
            options={
                'verbose_name': 'Appartenenza a gruppo',
                'verbose_name_plural': 'Appartenenze a gruppi',
                'ordering': ['group_id', 'legacy_user_id'],
                'unique_together': {('group', 'legacy_user_id')},
            },
        ),
        migrations.CreateModel(
            name='GroupPermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='core.accessgroup')),
                ('permission', models.ForeignKey(db_column='permission_code', on_delete=django.db.models.deletion.CASCADE, related_name='group_grants', to='core.permissiondefinition', to_field='code')),
            ],
            options={
                'verbose_name': 'Grant permesso di gruppo',
                'verbose_name_plural': 'Grant permessi di gruppo',
                'ordering': ['group_id', 'permission_id'],
                'unique_together': {('group', 'permission')},
            },
        ),
    ]
