# Generated by Django 5.2.16 on 2026-10-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_admin_subnav_accessi_negati'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifica',
            name='archiviata',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='notifica',
            name='archiviata_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifica',
            name='archiviata_motivo',
            field=models.CharField(blank=True, choices=[('scadenza_non_letta', 'Non letta entro la scadenza'), ('scadenza_letta', 'Letta da tempo'), ('utente', "Archiviata dall'utente"), ('admin', "Archiviata dall'amministratore")], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='notifica',
            name='letta_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notifica',
            index=models.Index(fields=['legacy_user_id', 'archiviata', 'letta'], name='core_notif_user_stato_idx'),
        ),
    ]
