# Generated by Django 5.2.11 on 2026-03-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_preposto', '0002_segnalazionepreposto_codice_identificativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarioprepostoimpostazioni',
            name='acl_scrittura',
            field=models.JSONField(blank=True, default=list, help_text='Lista di username o email autorizzati alla scrittura (creazione/modifica/eliminazione), oltre agli admin legacy.'),
        ),
    ]
