# Generated by Django 5.2.11 on 2026-05-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_preposto', '0005_private_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarioprepostoimpostazioni',
            name='ispezione_frequenza_giorni',
            field=models.PositiveIntegerField(default=7, help_text='Frequenza attesa, in giorni, per le ispezioni periodiche del preposto.'),
        ),
    ]
