# Generated by Django 5.2.11 on 2026-07-12 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0080_maintenancerule_execution_mode_and_more'),
        ('security', '0009_aiknowledgeembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityasset',
            name='hub_asset',
            field=models.ForeignKey(blank=True, help_text='Asset del registro HUB collegato (match ip_address↔endpoint IP / hostname↔nome).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_assets', to='assets.asset'),
        ),
    ]
