# Generated by Django 5.2.11 on 2026-07-14 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_securityasset_hub_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_kind', models.CharField(db_index=True, max_length=32)),
                ('severity', models.CharField(blank=True, choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=24)),
                ('dedup_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('outcome', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('cooldown', 'Suppressed by cooldown')], db_index=True, max_length=16)),
                ('recipients_count', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='securitymailboxsource',
            name='expected_every_hours',
            field=models.PositiveSmallIntegerField(default=0, help_text='How often a report is expected from this source, in hours (0 = no expectation). A source that goes quiet raises an alert: the absence of a report is itself a signal, and it is the one failure the system cannot see by looking at what arrives.'),
        ),
        migrations.AddField(
            model_name='securitymailboxsource',
            name='require_verified_sender',
            field=models.BooleanField(default=False, help_text='Accept a message only if the receiving mail system authenticated the sender (DKIM or SPF pass, no DMARC failure). Requires a provider that exposes the Authentication-Results header, e.g. Microsoft Graph. Fail-closed: messages without the header are rejected.'),
        ),
        migrations.AddConstraint(
            model_name='securityalert',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['new', 'open', 'acknowledged', 'in_progress', 'snoozed', 'muted'])), fields=('source', 'dedup_hash'), name='uniq_active_alert_per_source_dedup'),
        ),
        migrations.AddConstraint(
            model_name='securityremediationticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['new', 'open', 'in_progress'])), fields=('source', 'dedup_hash'), name='uniq_active_ticket_per_source_dedup'),
        ),
        migrations.AddField(
            model_name='securitynotificationlog',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='security.securityalert'),
        ),
        migrations.AddField(
            model_name='securitynotificationlog',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='security.securitynotificationchannel'),
        ),
        migrations.AddField(
            model_name='securitynotificationlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='security.securityremediationticket'),
        ),
        migrations.AddIndex(
            model_name='securitynotificationlog',
            index=models.Index(fields=['channel', 'dedup_hash', 'event_kind', 'created_at'], name='security_se_channel_62d7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='securitynotificationlog',
            index=models.Index(fields=['outcome', 'created_at'], name='security_se_outcome_5304f0_idx'),
        ),
    ]
