# Generated by Django 5.2.16 on 2026-09-30 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_securitynotificationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityVpnAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('allowed', 'Consentito'), ('denied', 'Negato')], db_index=True, max_length=16)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source_ip', models.CharField(blank=True, db_index=True, max_length=64)),
                ('login_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('method', models.CharField(blank=True, max_length=64)),
                ('firebox_name', models.CharField(blank=True, max_length=120)),
                ('dedup_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpn_accesses', to='security.securityreport')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_accesses', to='security.securitysource')),
            ],
            options={
                'ordering': ['-login_at', '-id'],
                'indexes': [models.Index(fields=['source', 'login_at'], name='security_se_source__6fc861_idx'), models.Index(fields=['username', 'login_at'], name='security_se_usernam_da1415_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'dedup_hash'), name='uniq_vpn_access_source_hash')],
            },
        ),
    ]
