# Generated by Django 5.2.16 on 2026-09-30 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0014_repair_skipped_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAssetSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(blank=True, max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('dedup_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='security.securityasset')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_signals', to='security.securityreport')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securitysource')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['asset', 'kind', 'occurred_at'], name='security_se_asset_i_e6244e_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'dedup_hash'), name='uniq_asset_signal_hash')],
            },
        ),
    ]
