# Generated by Django 5.2.16 on 2026-10-01 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_securityassetsignal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securityremediationticket',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_cases_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityremediationticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityremediationticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_cases_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityremediationticket',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='securityremediationticket',
            name='origin',
            field=models.CharField(choices=[('auto', 'Automatico'), ('manual', 'Aperto a mano')], db_index=True, default='auto', max_length=16),
        ),
        migrations.AddField(
            model_name='securityremediationticket',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SecurityCaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='security.securityremediationticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityCaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('done', models.BooleanField(db_index=True, default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='security.securityremediationticket')),
            ],
            options={
                'ordering': ['done', 'created_at', 'id'],
            },
        ),
    ]
