# Generated by Django 5.2.16 on 2026-10-06 20:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0018_securityescalationrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('malware', 'Malware / ransomware'), ('phishing', 'Phishing / ingegneria sociale'), ('unauthorized_access', 'Accesso non autorizzato'), ('account_compromise', 'Account compromesso'), ('data_leak', 'Fuga o perdita di dati'), ('denial_of_service', 'Indisponibilità / DoS'), ('vulnerability_exploit', 'Sfruttamento di vulnerabilità'), ('misconfiguration', 'Errore di configurazione'), ('hardware_failure', 'Guasto hardware / infrastruttura'), ('physical', 'Evento fisico (furto, incendio, allagamento)'), ('other', 'Altro')], db_index=True, default='other', max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='warning', max_length=24)),
                ('status', models.CharField(choices=[('open', 'Aperto'), ('contained', 'Contenuto'), ('resolved', 'Risolto'), ('closed', 'Chiuso')], db_index=True, default='open', max_length=16)),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Momento in cui se ne è venuti a conoscenza: da qui partono le scadenze.')),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_significant', models.BooleanField(db_index=True, default=False)),
                ('significance_criteria', models.JSONField(blank=True, default=list)),
                ('significance_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('suspected_malicious', models.BooleanField(default=False)),
                ('cross_border', models.BooleanField(default=False)),
                ('personal_data_breach', models.BooleanField(db_index=True, default=False)),
                ('affected_services', models.TextField(blank=True)),
                ('affected_users_count', models.PositiveIntegerField(blank=True, null=True)),
                ('impact_description', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('actions_taken', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('early_warning_at', models.DateTimeField(blank=True, null=True)),
                ('notification_at', models.DateTimeField(blank=True, null=True)),
                ('final_report_at', models.DateTimeField(blank=True, null=True)),
                ('gdpr_notified_at', models.DateTimeField(blank=True, null=True)),
                ('csirt_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alerts', models.ManyToManyField(blank=True, related_name='incidents', to='security.securityalert')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incidents_owned', to=settings.AUTH_USER_MODEL)),
                ('significance_assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tickets', models.ManyToManyField(blank=True, related_name='incidents', to='security.securityremediationticket')),
            ],
            options={
                'ordering': ['-detected_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('actor', models.CharField(default='system', max_length=150)),
                ('body', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='security.securityincident')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['status', 'is_significant'], name='sec_incident_status_sig_idx'),
        ),
    ]
