# Generated by Django 5.2.16 on 2026-10-09 22:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0019_security_incidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityalertsuppressionrule',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='securityalertsuppressionrule',
            name='max_severity',
            field=models.CharField(blank=True, choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], max_length=24),
        ),
        migrations.AddField(
            model_name='securityalertsuppressionrule',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityalertsuppressionrule',
            name='revoked_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SecurityAlertDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=120)),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('fingerprint_fields', models.JSONField(blank=True, default=dict)),
                ('kind', models.CharField(choices=[('false_positive', 'Falso positivo'), ('not_relevant', 'Non rilevante'), ('accepted_risk', 'Rischio accettato'), ('mute', 'Silenziato')], max_length=24)),
                ('severity', models.CharField(blank=True, choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], max_length=24)),
                ('actor', models.CharField(max_length=120)),
                ('reason', models.TextField()),
                ('batch', models.CharField(blank=True, max_length=64)),
                ('counted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='security.securityalert')),
                ('learned_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissals', to='security.securityalertsuppressionrule')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securitysource')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fingerprint', 'counted', 'created_at'], name='sec_dismiss_fp_idx')],
            },
        ),
    ]
