# Generated by Django 5.2.16 on 2026-10-09 23:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0123_sidebar_inventario_it_codici_storici'),
        ('security', '0019_security_incidents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityCveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cvss', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=24)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('nvd_last_modified', models.DateTimeField(blank=True, null=True)),
                ('configurations', models.JSONField(blank=True, default=list)),
                ('ambiguous_configuration', models.BooleanField(default=False)),
                ('kev', models.BooleanField(db_index=True, default=False)),
                ('kev_added', models.DateField(blank=True, null=True)),
                ('kev_due', models.DateField(blank=True, null=True)),
                ('epss', models.FloatField(blank=True, null=True)),
                ('epss_percentile', models.FloatField(blank=True, null=True)),
                ('nvd_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('nvd_error', models.CharField(blank=True, max_length=300)),
                ('impact_computed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['cve_id'],
            },
        ),
        migrations.AddField(
            model_name='securityalertsuppressionrule',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='securityalertsuppressionrule',
            name='max_severity',
            field=models.CharField(blank=True, choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], max_length=24),
        ),
        migrations.AddField(
            model_name='securityalertsuppressionrule',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityalertsuppressionrule',
            name='revoked_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SecurityExternalFeedCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.CharField(db_index=True, max_length=24)),
                ('key', models.CharField(max_length=190)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('feed', 'key'), name='uniq_external_feed_key')],
            },
        ),
        migrations.CreateModel(
            name='SoftwareAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vendor', 'Vendor'), ('product', 'Prodotto')], max_length=16)),
                ('raw', models.CharField(max_length=160)),
                ('canonical', models.CharField(max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'raw'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'raw'), name='uniq_software_alias_kind_raw')],
            },
        ),
        migrations.CreateModel(
            name='SoftwareImportPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('source_kind', models.CharField(choices=[('watchguard', 'WatchGuard EPDR / Panda'), ('businesslog', 'BusinessLog'), ('other', 'Altro export')], default='other', max_length=24)),
                ('column_map', models.JSONField(blank=True, default=dict)),
                ('date_format', models.CharField(blank=True, max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareInventoryImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('watchguard', 'WatchGuard EPDR / Panda'), ('businesslog', 'BusinessLog'), ('other', 'Altro export')], default='other', max_length=24)),
                ('original_name', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(db_index=True, max_length=64)),
                ('stored_name', models.CharField(blank=True, max_length=255)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('column_map', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('preview', 'Anteprima'), ('imported', 'Importato'), ('failed', 'Fallito')], db_index=True, default='preview', max_length=16)),
                ('inventory_date', models.DateField(default=django.utils.timezone.localdate)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_imported', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('rows_new', models.PositiveIntegerField(default=0)),
                ('rows_marked_missing', models.PositiveIntegerField(default=0)),
                ('skipped_details', models.JSONField(blank=True, default=list)),
                ('hosts_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='security.softwareimportpreset')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedup_key', models.CharField(max_length=64, unique=True)),
                ('source_kind', models.CharField(choices=[('watchguard', 'WatchGuard EPDR / Panda'), ('businesslog', 'BusinessLog'), ('other', 'Altro export')], db_index=True, max_length=24)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('host_display', models.CharField(blank=True, max_length=255)),
                ('vendor_raw', models.CharField(blank=True, max_length=255)),
                ('product_raw', models.CharField(max_length=255)),
                ('vendor', models.CharField(blank=True, db_index=True, max_length=120)),
                ('product', models.CharField(db_index=True, max_length=160)),
                ('version_raw', models.CharField(blank=True, max_length=120)),
                ('version_norm', models.CharField(blank=True, max_length=120)),
                ('still_detected', models.BooleanField(db_index=True, default=True)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_inventory_date', models.DateField(default=django.utils.timezone.localdate)),
                ('hub_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_software', to='assets.asset')),
                ('security_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software', to='security.securityasset')),
                ('first_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='security.softwareinventoryimport')),
                ('last_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations', to='security.softwareinventoryimport')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAlertDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=120)),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('fingerprint_fields', models.JSONField(blank=True, default=dict)),
                ('kind', models.CharField(choices=[('false_positive', 'Falso positivo'), ('not_relevant', 'Non rilevante'), ('accepted_risk', 'Rischio accettato'), ('mute', 'Silenziato')], max_length=24)),
                ('severity', models.CharField(blank=True, choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], max_length=24)),
                ('actor', models.CharField(max_length=120)),
                ('reason', models.TextField()),
                ('batch', models.CharField(blank=True, max_length=64)),
                ('by_config_user', models.BooleanField(default=False)),
                ('counted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='security.securityalert')),
                ('learned_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissals', to='security.securityalertsuppressionrule')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securitysource')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fingerprint', 'counted', 'created_at'], name='sec_dismiss_fp_idx')],
            },
        ),
        migrations.CreateModel(
            name='SoftwareCpeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('product', models.CharField(max_length=160)),
                ('cpe_vendor', models.CharField(blank=True, max_length=120)),
                ('cpe_product', models.CharField(blank=True, max_length=160)),
                ('confirmed', models.BooleanField(db_index=True, default=False)),
                ('not_applicable', models.BooleanField(default=False)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vendor', 'product'],
                'indexes': [models.Index(fields=['cpe_vendor', 'cpe_product'], name='sec_cpe_pair_idx')],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'product'), name='uniq_software_cpe_vendor_product')],
            },
        ),
        migrations.CreateModel(
            name='SecurityCveImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('outcome', models.CharField(choices=[('impacts', 'Impatta'), ('not_impacted', 'Non impatta'), ('to_verify', 'Da verificare')], db_index=True, max_length=16)),
                ('explanation', models.TextField()),
                ('inventory_date', models.DateField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hub_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_cve_impacts', to='assets.asset')),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='security.securitycverecord')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cve_impacts', to='security.softwareinstallation')),
            ],
            options={
                'ordering': ['cve', 'outcome', 'host'],
                'constraints': [models.UniqueConstraint(fields=('cve', 'host'), name='uniq_cve_impact_host')],
            },
        ),
        migrations.AddIndex(
            model_name='softwareinstallation',
            index=models.Index(fields=['vendor', 'product', 'still_detected'], name='sec_sw_product_idx'),
        ),
        migrations.AddIndex(
            model_name='softwareinstallation',
            index=models.Index(fields=['source_kind', 'host'], name='sec_sw_source_host_idx'),
        ),
    ]
