# Generated by Django 5.2.16 on 2026-09-25 13:13

import django.db.models.deletion
import django.utils.timezone
import sistema_gestione.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestione_specifiche', '0013_registroofi_azioneofi_registro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlloIso27002',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=8, unique=True)),
                ('tema', models.CharField(choices=[('ORG', 'Controlli organizzativi'), ('PER', 'Controlli sulle persone'), ('FIS', 'Controlli fisici'), ('TEC', 'Controlli tecnologici')], max_length=3)),
                ('titolo', models.CharField(max_length=200)),
                ('ordine', models.PositiveIntegerField(db_index=True)),
            ],
            options={
                'verbose_name': 'Controllo ISO/IEC 27002',
                'verbose_name_plural': 'Controlli ISO/IEC 27002',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='SoaRevisione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Indice di revisione del MOD.165', unique=True)),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('PROPOSTA', 'Proposta alla Direzione'), ('APPROVATA', 'Approvata (in vigore)'), ('SUPERATA', 'Superata')], db_index=True, default='BOZZA', max_length=10)),
                ('motivo', models.CharField(blank=True, default='', help_text='Descrizione della revisione', max_length=255)),
                ('origine', models.CharField(blank=True, default='', help_text='Es. import dal PDF MOD.165', max_length=255)),
                ('proposta_il', models.DateTimeField(blank=True, null=True)),
                ('approvata_il', models.DateTimeField(blank=True, null=True)),
                ('copia_firmata', models.FileField(blank=True, storage=sistema_gestione.storage.PrivateSistemaGestioneStorage(), upload_to='sistema_gestione/soa/%Y/')),
                ('copia_firmata_nome', models.CharField(blank=True, default='', max_length=255)),
                ('copia_firmata_caricata_il', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approvata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('preparata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revisione SoA',
                'verbose_name_plural': 'Revisioni SoA',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('fonte', models.CharField(max_length=150)),
                ('informazione', models.TextField(help_text='Informazione o minaccia')),
                ('esito', models.CharField(choices=[('ACQUISITA', 'Informazione acquisita'), ('NON_PERTINENTE', 'Non pertinente'), ('AZIONE', 'Richiede azione')], default='ACQUISITA', max_length=15)),
                ('azione', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ofi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gestione_specifiche.registroofi')),
                ('registrato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attività di threat intelligence',
                'verbose_name_plural': 'Registro threat intelligence',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SoaVoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livello', models.PositiveSmallIntegerField(choices=[(0, '0 - Non applicato'), (1, '1'), (2, '2'), (3, '3'), (4, '4 - Pienamente applicato')], default=0)),
                ('vulnerabilita', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1 - Bassa'), (2, '2'), (3, '3'), (4, '4 - Alta')], default=0)),
                ('riferimenti', models.TextField(blank=True, default='', help_text='Procedure, moduli, evidenze interne')),
                ('giustificazione', models.TextField(blank=True, default='', help_text="Motivo dell'inclusione o dell'esclusione")),
                ('obbligo_legislativo', models.BooleanField(default=False)),
                ('obbligo_normativo', models.BooleanField(default=False)),
                ('obbligo_regolatorio', models.BooleanField(default=False)),
                ('obbligo_cliente', models.BooleanField(default=False)),
                ('buona_pratica', models.BooleanField(default=False)),
                ('azione', models.TextField(blank=True, default='')),
                ('responsabile', models.CharField(blank=True, default='', max_length=150)),
                ('scadenza', models.DateField(blank=True, null=True)),
                ('livello_atteso', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Non applicato'), (1, '1'), (2, '2'), (3, '3'), (4, '4 - Pienamente applicato')], null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggiornata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('controllo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voci', to='sistema_gestione.controlloiso27002')),
                ('ofi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gestione_specifiche.registroofi')),
                ('revisione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci', to='sistema_gestione.soarevisione')),
            ],
            options={
                'verbose_name': 'Voce SoA',
                'verbose_name_plural': 'Voci SoA',
                'ordering': ['controllo__ordine'],
                'constraints': [models.UniqueConstraint(fields=('revisione', 'controllo'), name='sg_soa_voce_unica_per_revisione')],
            },
        ),
    ]
