# Generated by Django 5.2.16 on 2026-09-25 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_specifiche', '0013_registroofi_azioneofi_registro'),
        ('sistema_gestione', '0003_audit_auditagenda_auditor_audit_auditor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auditesito',
            name='sg_esito_unico_audit_domanda',
        ),
        migrations.AddConstraint(
            model_name='auditesito',
            constraint=models.UniqueConstraint(condition=models.Q(('domanda__isnull', False)), fields=('audit', 'domanda'), name='sg_esito_unico_audit_domanda'),
        ),
    ]
