# Generated by Django 5.2.16 on 2026-09-28 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gestione', '0004_remove_auditesito_sg_esito_unico_audit_domanda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='processi_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('DIREZIONALE', 'Direzionale'), ('OPERATIVO', 'Operativo'), ('SUPPORTO', 'Supporto')], default='OPERATIVO', max_length=20)),
                ('enti', models.CharField(blank=True, max_length=255)),
                ('scopo', models.TextField(blank=True)),
                ('input', models.TextField(blank=True)),
                ('output', models.TextField(blank=True)),
                ('rischi', models.TextField(blank=True)),
                ('indicatori', models.TextField(blank=True)),
                ('procedure', models.TextField(blank=True)),
                ('punti_9100', models.CharField(blank=True, max_length=255)),
                ('punti_45001', models.CharField(blank=True, max_length=255)),
                ('punti_27001', models.CharField(blank=True, max_length=255)),
                ('punti_pdr125', models.CharField(blank=True, max_length=255)),
                ('frequenza_mesi', models.PositiveSmallIntegerField(default=12)),
                ('attivo', models.BooleanField(default=True)),
                ('revisione', models.PositiveIntegerField(default=1, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsabile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processi_sgi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Processi',
                'ordering': ['codice'],
            },
        ),
        migrations.AddField(
            model_name='audit',
            name='processi_catalogo',
            field=models.ManyToManyField(blank=True, related_name='audit', to='sistema_gestione.processo'),
        ),
        migrations.AddField(
            model_name='rigaprogramma',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='righe', to='sistema_gestione.processo'),
        ),
        migrations.CreateModel(
            name='ProcessoRevisione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('dati', models.JSONField(default=dict)),
                ('motivo', models.CharField(max_length=500)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('autore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisioni', to='sistema_gestione.processo')),
            ],
            options={
                'ordering': ['-numero'],
                'constraints': [models.UniqueConstraint(fields=('processo', 'numero'), name='sg_processo_rev_unica')],
            },
        ),
    ]
