# Generated by Django 5.2.16 on 2026-09-28 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gestione', '0005_audit_processi_snapshot_processo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditagenda',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attivita_audit', to='sistema_gestione.processo'),
        ),
    ]
