# Generated by Django 5.2.16 on 2026-09-28 11:08

import django.db.models.deletion
import sistema_gestione.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_specifiche', '0013_registroofi_azioneofi_registro'),
        ('sistema_gestione', '0006_auditagenda_processo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='riepilogo_generato',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditesito',
            name='campione',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditesito',
            name='data_verifica',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditesito',
            name='documento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditesito',
            name='domanda_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditesito',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='esiti_audit', to='sistema_gestione.processo'),
        ),
        migrations.AddField(
            model_name='auditesito',
            name='requisito_atteso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditesito',
            name='responsabile_azione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rilievi_audit_assegnati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditesito',
            name='revisione_documento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditesito',
            name='scadenza_azione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditesito',
            name='scostamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditesito',
            name='strutturato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditesito',
            name='versione',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processo',
            name='criticita',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bassa'), (2, 'Media'), (3, 'Alta')], default=2),
        ),
        migrations.CreateModel(
            name='AuditAllegato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=sistema_gestione.storage.PrivateSistemaGestioneStorage(), upload_to='sistema_gestione/evidenze/%Y/%m/')),
                ('nome', models.CharField(max_length=200)),
                ('sha256', models.CharField(max_length=64)),
                ('dimensione', models.PositiveIntegerField()),
                ('caricato_il', models.DateTimeField(auto_now_add=True)),
                ('caricato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('esito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allegati', to='sistema_gestione.auditesito')),
            ],
        ),
        migrations.CreateModel(
            name='AuditRapportoVersione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=500)),
                ('snapshot', models.JSONField(default=dict)),
                ('pdf', models.FileField(storage=sistema_gestione.storage.PrivateSistemaGestioneStorage(), upload_to='sistema_gestione/revisioni/%Y/')),
                ('copia_firmata', models.FileField(blank=True, storage=sistema_gestione.storage.PrivateSistemaGestioneStorage(), upload_to='')),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versioni_rapporto', to='sistema_gestione.audit')),
                ('autore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='AuditVerificaEfficacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risultato', models.CharField(choices=[('EFFICACE', 'Efficace'), ('NON_EFFICACE', 'Non efficace'), ('DA_RIVERIFICARE', 'Da riverificare')], max_length=16)),
                ('metodo', models.TextField()),
                ('evidenza', models.TextField()),
                ('data_verifica', models.DateField()),
                ('prossima_verifica', models.DateField(blank=True, null=True)),
                ('registrato_il', models.DateTimeField(auto_now_add=True)),
                ('esito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifiche_efficacia', to='sistema_gestione.auditesito')),
                ('verificato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registrato_il', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=30)),
                ('norma', models.CharField(choices=[('en9100', 'EN 9100'), ('iso45001', 'ISO 45001'), ('iso27001', 'ISO/IEC 27001'), ('pdr125', 'UNI/PdR 125')], default='en9100', max_length=12)),
                ('punti', models.CharField(max_length=100)),
                ('domanda', models.TextField()),
                ('criterio', models.TextField()),
                ('suggerimento', models.TextField(blank=True)),
                ('ordine', models.PositiveIntegerField(default=100)),
                ('revisione', models.PositiveIntegerField(default=1)),
                ('attiva', models.BooleanField(default=True)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist', to='sistema_gestione.processo')),
            ],
            options={
                'ordering': ['ordine', 'codice'],
            },
        ),
        migrations.AddField(
            model_name='auditesito',
            name='modello_processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema_gestione.checklistprocesso'),
        ),
        migrations.AddConstraint(
            model_name='auditesito',
            constraint=models.UniqueConstraint(condition=models.Q(('modello_processo__isnull', False)), fields=('audit', 'modello_processo'), name='sg_esito_unico_processo'),
        ),
        migrations.AddConstraint(
            model_name='auditrapportoversione',
            constraint=models.UniqueConstraint(fields=('audit', 'numero'), name='sg_rapporto_versione_unica'),
        ),
        migrations.AddConstraint(
            model_name='checklistprocesso',
            constraint=models.UniqueConstraint(fields=('processo', 'codice'), name='sg_check_processo_codice'),
        ),
    ]
