# Generated by Django 5.2.16 on 2026-09-28 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_specifiche', '0013_registroofi_azioneofi_registro'),
        ('sistema_gestione', '0007_audit_riepilogo_generato_auditesito_campione_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='fonte_documentale',
            field=models.TextField(blank=True, help_text='File, revisione, pagina e impronta della fonte; discrepanze da verificare.'),
        ),
        migrations.CreateModel(
            name='AuditPreparazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_precedenti', models.TextField(verbose_name='Audit precedenti: riferimenti ed esame, oppure assenza motivata')),
                ('car_cliente', models.TextField(verbose_name='CAR cliente: riferimenti e stato, oppure assenza motivata')),
                ('documenti_registrazioni', models.TextField(verbose_name='Documenti e registrazioni da campionare, revisioni e disponibilita')),
                ('obiettivi_carenze', models.TextField(verbose_name='Obiettivi della verifica e carenze da approfondire')),
                ('verificato_il', models.DateTimeField(auto_now=True)),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preparazione', to='sistema_gestione.audit')),
                ('verificato_da', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AzioneCorrettivaAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_richiesta', models.DateField(verbose_name='Data richiesta CAR')),
                ('causa', models.TextField(blank=True, verbose_name='Analisi della causa radice')),
                ('contenimento', models.TextField(blank=True, verbose_name='Azione di contenimento')),
                ('azione', models.TextField(blank=True, verbose_name='Azione correttiva e modifiche documentali')),
                ('analizzata_il', models.DateField(blank=True, null=True, verbose_name='Data valutazione cause e azioni')),
                ('evidenza_attuazione', models.TextField(blank=True, verbose_name='Evidenza di attuazione')),
                ('evidenza_efficacia', models.TextField(blank=True, verbose_name='Metodo, campione e risultato della verifica di efficacia')),
                ('proroga_al', models.DateField(blank=True, null=True)),
                ('motivo_proroga', models.TextField(blank=True)),
                ('proroga_il', models.DateTimeField(null=True)),
                ('approvata_il', models.DateTimeField(null=True)),
                ('approvazione_esterna', models.CharField(blank=True, max_length=250, verbose_name='Riferimento approvazione cliente/ente, se richiesta esterna')),
                ('origine_esterna', models.BooleanField(default=False, verbose_name='CAR richiesta da cliente/ente')),
                ('chiusa_il', models.DateTimeField(null=True)),
                ('versione', models.PositiveIntegerField(default=0)),
                ('approvata_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('chiusa_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proroga_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='car_procedurale', to='gestione_specifiche.registroofi')),
                ('responsabile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_assegnate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RilevazioneKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=40)),
                ('periodo_da', models.DateField()),
                ('periodo_a', models.DateField()),
                ('formula', models.CharField(choices=[('PERCENTUALE', 'Numeratore / denominatore x 100'), ('RAPPORTO', 'Numeratore / denominatore'), ('VENDOR', 'Vendor Rating: OTD x 0,30 + OQD x 0,70')], max_length=20)),
                ('numeratore', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Numeratore (per VR: consegne puntuali)')),
                ('denominatore', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Denominatore (per VR: consegne totali)')),
                ('pezzi_nc', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('pezzi_totali', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('fonte_filtri', models.TextField(verbose_name='Fonte, campo data, filtri ed esclusioni applicati')),
                ('target', models.DecimalField(decimal_places=4, max_digits=18)),
                ('verso', models.CharField(choices=[('MIN', 'Valore almeno pari al target'), ('MAX', 'Valore al massimo pari al target')], max_length=3)),
                ('valore_precedente', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('confrontabile', models.BooleanField(default=True)),
                ('motivo_non_confrontabilita', models.TextField(blank=True)),
                ('commento', models.TextField(verbose_name='Analisi, cause e azioni proposte')),
                ('riferimento_riesame', models.CharField(max_length=250, verbose_name='Riferimento VRS / obiettivo approvato')),
                ('registrata_il', models.DateTimeField(auto_now_add=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rilevazioni_kpi', to='sistema_gestione.processo')),
            ],
            options={
                'ordering': ['-periodo_a', '-pk'],
            },
        ),
    ]
