# Generated by Django 5.2.11 on 2026-03-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_refresh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurerevision',
            name='source_url',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='URL SharePoint'),
        ),
    ]
