# Generated by Django 5.2.11 on 2026-05-08 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_refresh', '0002_alter_procedurerevision_source_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Quiz post-lettura', max_length=200, verbose_name='Titolo')),
                ('questions', models.JSONField(blank=True, default=list, help_text='Lista di domande a risposta multipla con opzioni e indice risposta corretta.', verbose_name='Domande')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_quizzes_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='procedure_refresh.procedurerevision', verbose_name='Revisione')),
            ],
            options={
                'verbose_name': 'Quiz procedura',
                'verbose_name_plural': 'Quiz procedure',
                'ordering': ['-is_active', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=list, verbose_name='Risposte')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Punteggio')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Totale domande')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Inviato il')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User agent')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='procedure_refresh.procedureassignment', verbose_name='Assegnazione')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='procedure_refresh.procedurequiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Tentativo quiz procedura',
                'verbose_name_plural': 'Tentativi quiz procedure',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('quiz', 'assignment', 'user'), name='pr_unique_quiz_attempt_assignment_user')],
            },
        ),
    ]
