# Generated by Django 5.2.11 on 2026-07-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_refresh', '0003_procedurequiz_procedurequizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduredocument',
            name='escludi_dal_rag',
            field=models.BooleanField(db_index=True, default=False, help_text="Se attivo, il documento NON viene indicizzato dall'assistente AI (corpus RAG). Usare per i roster di persone abilitate/licenziate a una macchina (skill matrix / licensed operators): quel dato deve arrivare solo dal modulo Skill Matrix governato, non essere dedotto dai documenti (evita allucinazioni HR e bypass dei permessi).", verbose_name='Escludi dal RAG AI'),
        ),
    ]
