# Generated by Django 5.2.11 on 2026-07-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_refresh', '0004_proceduredocument_escludi_dal_rag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurereadevent',
            name='event_type',
            field=models.CharField(choices=[('opened', 'Aperta'), ('confirmed', 'Confermata'), ('reminder_sent', 'Reminder inviato'), ('reassigned', 'Riassegnata'), ('exported', 'Esportata'), ('overdue_marked', 'Marcata scaduta')], db_index=True, max_length=20, verbose_name='Tipo evento'),
        ),
    ]
