# Generated by Django 5.2.11 on 2026-07-06 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_refresh', '0005_alter_procedurereadevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(verbose_name='Proposta di modifica')),
                ('status', models.CharField(choices=[('aperta', 'Aperta'), ('in_carico', 'Presa in carico'), ('recepita', 'Recepita'), ('respinta', 'Respinta')], db_index=True, default='aperta', max_length=20, verbose_name='Stato')),
                ('risposta_gestore', models.TextField(blank=True, default='', verbose_name='Risposta del gestore')),
                ('gestita_il', models.DateTimeField(blank=True, null=True, verbose_name='Gestita il')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='procedure_refresh.procedureassignment', verbose_name='Assegnazione di origine')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_change_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Proponente')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='procedure_refresh.proceduredocument', verbose_name='Documento')),
                ('gestita_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_change_requests_gestite', to=settings.AUTH_USER_MODEL, verbose_name='Gestita da')),
                ('recepita_in_revisione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procedure_refresh.procedurerevision', verbose_name='Recepita nella revisione')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='procedure_refresh.procedurerevision', verbose_name='Revisione letta')),
            ],
            options={
                'verbose_name': 'Segnalazione di modifica',
                'verbose_name_plural': 'Segnalazioni di modifica',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'status'], name='pr_cr_document_status')],
            },
        ),
    ]
