# Generated by Django 5.2.11 on 2026-07-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_refresh', '0006_procedurechangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgiSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=64, verbose_name='ID esecuzione')),
                ('azione', models.CharField(choices=[('nuovo_doc', 'Nuovo documento'), ('nuova_revisione', 'Nuova revisione'), ('doc_sparito', 'Documento sparito dalla share')], db_index=True, max_length=20, verbose_name='Azione')),
                ('document_code', models.CharField(db_index=True, max_length=50, verbose_name='Codice documento')),
                ('revision_old', models.CharField(blank=True, default='', max_length=50, verbose_name='Revisione precedente')),
                ('revision_new', models.CharField(blank=True, default='', max_length=50, verbose_name='Revisione nuova')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='Note')),
                ('origine', models.CharField(default='auto', max_length=10, verbose_name='Origine')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Log sincronizzazione SGI',
                'verbose_name_plural': 'Log sincronizzazioni SGI',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
