# Generated by Django 5.2.16 on 2026-10-08 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_refresh', '0008_sgitestoestratto'),
        ('sistema_gestione', '0008_processo_fonte_documentale_auditpreparazione_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgiDocumentoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origine', models.CharField(choices=[('processo_testo', 'Testo del processo')], default='processo_testo', max_length=20, verbose_name='Origine')),
                ('codice_citato', models.CharField(blank=True, default='', max_length=60, verbose_name='Codice citato')),
                ('confermato', models.BooleanField(db_index=True, default=False, verbose_name='Confermato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processi_collegati', to='procedure_refresh.proceduredocument', verbose_name='Documento')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti_sgi', to='sistema_gestione.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Documento SGI di processo',
                'verbose_name_plural': 'Documenti SGI di processo',
                'constraints': [models.UniqueConstraint(fields=('documento', 'processo'), name='uq_sgi_doc_processo')],
            },
        ),
        migrations.CreateModel(
            name='SgiRiferimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_citato', models.CharField(db_index=True, max_length=60, verbose_name='Codice citato')),
                ('sezione', models.CharField(blank=True, default='', max_length=160, verbose_name='Sezione')),
                ('occorrenze', models.PositiveIntegerField(default=1, verbose_name='Occorrenze')),
                ('risolto', models.BooleanField(db_index=True, default=False, verbose_name='Risolto')),
                ('a_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riferimenti_entranti', to='procedure_refresh.proceduredocument', verbose_name='Documento citato')),
                ('da_revisione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riferimenti_uscenti', to='procedure_refresh.procedurerevision', verbose_name='Revisione che cita')),
            ],
            options={
                'verbose_name': 'Riferimento SGI',
                'verbose_name_plural': 'Riferimenti SGI',
                'constraints': [models.UniqueConstraint(fields=('da_revisione', 'codice_citato', 'sezione'), name='uq_sgi_rif')],
            },
        ),
    ]
