# Generated by Django 5.2.16 on 2026-10-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_refresh', '0009_sgiriferimento_sgidocumentoprocesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgiriferimento',
            name='tipo_risoluzione',
            field=models.CharField(blank=True, choices=[('esatto', 'Codice esatto'), ('normalizzato', 'Codice con altra grafia'), ('disambiguato', "Codice disambiguato dall'import"), ('allegato_base', 'Allegato sul documento base'), ('senza_cn', 'Citazione abbreviata senza CN'), ('famiglia', 'Famiglia di documenti (X_n)')], default='', max_length=20, verbose_name='Tipo di risoluzione'),
        ),
    ]
