# Generated by Django 5.2.11 on 2026-03-10 16:13

import django.db.models.deletion
import timbri.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatoreTimbri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('cognome', models.CharField(blank=True, default='', max_length=200)),
                ('matricola', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('reparto', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('ruolo', models.CharField(blank=True, default='', max_length=200)),
                ('email_notifica', models.CharField(blank=True, default='', max_length=200)),
                ('is_active_legacy', models.BooleanField(default=True)),
                ('is_manual', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('legacy', 'Legacy'), ('manual', 'Manuale'), ('sharepoint', 'SharePoint')], default='legacy', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cognome', 'nome', 'matricola', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroTimbro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_timbro', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('qualifica', models.CharField(blank=True, default='', max_length=200)),
                ('tipo_timbro', models.CharField(choices=[('FISICO', 'Fisico'), ('DIGITALE', 'Digitale'), ('FISICO_E_DIGITALE', 'Fisico e digitale'), ('ALTRO', 'Altro')], default='FISICO_E_DIGITALE', max_length=30)),
                ('data_consegna', models.DateField(blank=True, null=True)),
                ('data_ritiro', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('firma_testo', models.TextField(blank=True, default='')),
                ('is_attivo', models.BooleanField(db_index=True, default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('sharepoint_item_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('last_import_at', models.DateTimeField(blank=True, null=True)),
                ('edited_in_portal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timbri_registri_creati', to=settings.AUTH_USER_MODEL)),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registri', to='timbri.operatoretimbri')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timbri_registri_aggiornati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_attivo', '-data_consegna', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RegistroTimbroImmagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variante', models.CharField(choices=[('TIMBRO', 'Timbro'), ('FIRMA', 'Firma'), ('SIGLA', 'Sigla')], max_length=20)),
                ('image', models.ImageField(upload_to=timbri.models._registro_image_upload_to)),
                ('source_url', models.CharField(blank=True, default='', max_length=1000)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='timbri.registrotimbro')),
            ],
            options={
                'ordering': ['variante', 'id'],
                'unique_together': {('registro', 'variante')},
            },
        ),
    ]
