# Generated by Codex on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timbri", "0002_remove_operatoretimbri_is_manual_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimbriImportIssue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_file", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("csv_row_number", models.PositiveIntegerField(db_index=True)),
                ("sharepoint_item_id", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("operatore_label", models.CharField(blank=True, default="", max_length=200)),
                ("operatore_label_alt", models.CharField(blank=True, default="", max_length=200)),
                ("matricola", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("reparto", models.CharField(blank=True, default="", max_length=200)),
                ("qualifica", models.CharField(blank=True, default="", max_length=200)),
                ("codice_timbro", models.CharField(blank=True, default="", max_length=120)),
                ("tipo_timbro_raw", models.CharField(blank=True, default="", max_length=100)),
                ("attivo_raw", models.CharField(blank=True, default="", max_length=20)),
                ("motivo_scarto", models.TextField(blank=True, default="")),
                ("raw_payload", models.TextField(blank=True, default="")),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Scarto import timbri",
                "verbose_name_plural": "Scarti import timbri",
                "ordering": ["is_resolved", "operatore_label", "matricola", "csv_row_number", "id"],
                "unique_together": {("source_file", "csv_row_number")},
            },
        ),
    ]
