# Generated by Django 5.2.11 on 2026-03-16 21:25

import timbri.models
import timbri.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timbri', '0003_timbriimportissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotimbro',
            name='tipo_timbro',
            field=models.CharField(choices=[('FISICO', 'Fisico'), ('DIGITALE', 'Digitale'), ('FISICO_E_DIGITALE', 'Fisico e digitale'), ('ALTRO', 'Altro'), ('SOLO_FIRMA', 'Solo firma'), ('SOLO_SIGLA', 'Solo sigla')], default='FISICO_E_DIGITALE', max_length=30),
        ),
        migrations.AlterField(
            model_name='registrotimbroimmagine',
            name='image',
            field=models.ImageField(storage=timbri.storage.PrivateTimbriStorage, upload_to=timbri.models._registro_image_upload_to),
        ),
    ]
