# Generated by Django 5.2.11 on 2026-06-08 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timbri', '0004_private_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimbriUserPermOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azione', models.CharField(choices=[('timbri_copy', 'Copia immagine'), ('timbri_download', 'Scarica immagine')], max_length=40)),
                ('granted', models.BooleanField(help_text="True = forza permesso ON anche se il ruolo non ce l'ha; False = forza OFF.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timbri_perm_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Override permesso timbri utente',
                'verbose_name_plural': 'Override permessi timbri utenti',
                'ordering': ['user__username', 'azione'],
                'unique_together': {('user', 'azione')},
            },
        ),
    ]
