# Generated by Django 5.2.11 on 2026-07-07 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0077_subnav_mod128_processi'),
        ('timbri', '0005_timbri_user_perm_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrotimbro',
            name='abilitazione_processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timbri', to='anagrafica.abilitazioneprocesso'),
        ),
        migrations.AddField(
            model_name='registrotimbro',
            name='is_sospeso',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='registrotimbro',
            name='sospeso_al',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrotimbro',
            name='sospeso_dal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrotimbro',
            name='sospeso_motivo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='registrotimbro',
            name='sospeso_riferimento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
