# Generated by Django 5.2.11 on 2026-03-07 18:57

import anagrafica.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(max_length=200)),
                ('piva', models.CharField(blank=True, default='', max_length=11, verbose_name='P.IVA')),
                ('codice_fiscale', models.CharField(blank=True, default='', max_length=16)),
                ('indirizzo', models.CharField(blank=True, default='', max_length=255)),
                ('citta', models.CharField(blank=True, default='', max_length=100, verbose_name='Citta')),
                ('cap', models.CharField(blank=True, default='', max_length=5, verbose_name='CAP')),
                ('provincia', models.CharField(blank=True, default='', max_length=2)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('pec', models.EmailField(blank=True, default='', max_length=254, verbose_name='PEC')),
                ('website', models.URLField(blank=True, default='')),
                ('categoria', models.CharField(blank=True, choices=[('MATERIALI', 'Materiali'), ('SERVIZI', 'Servizi'), ('ATTREZZATURE', 'Attrezzature'), ('LOGISTICA', 'Logistica'), ('IT', 'IT / Informatica'), ('MANUTENZIONE', 'Manutenzione'), ('ALTRO', 'Altro')], default='', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitori',
                'ordering': ['ragione_sociale', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FornitoreDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('CONTRATTO', 'Contratto'), ('OFFERTA', 'Offerta'), ('CERTIFICAZIONE', 'Certificazione'), ('VISURA', 'Visura camerale'), ('ALTRO', 'Altro')], default='ALTRO', max_length=20)),
                ('file', models.FileField(upload_to=anagrafica.models._fornitore_documento_upload_to)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='anagrafica.fornitore')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornitore_documenti_caricati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento fornitore',
                'verbose_name_plural': 'Documenti fornitore',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FornitoreOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordine', models.CharField(blank=True, default='', max_length=50)),
                ('data_ordine', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('INVIATO', 'Inviato'), ('CONFERMATO', 'Confermato'), ('CONSEGNATO', 'Consegnato'), ('ANNULLATO', 'Annullato')], default='BOZZA', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornitore_ordini_creati', to=settings.AUTH_USER_MODEL)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='anagrafica.fornitore')),
            ],
            options={
                'verbose_name': 'Ordine fornitore',
                'verbose_name_plural': 'Ordini fornitore',
                'ordering': ['-data_ordine', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FornitoreValutazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('qualita', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Qualita')),
                ('puntualita', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntualita')),
                ('comunicazione', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutazioni', to='anagrafica.fornitore')),
                ('valutato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornitore_valutazioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valutazione fornitore',
                'verbose_name_plural': 'Valutazioni fornitore',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
