# Generated by Django 5.2.11 on 2026-03-08 09:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0001_initial'),
        ('assets', '0014_assetlabeltemplate_scope_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FornitoreAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MANUTENZIONE', 'Manutenzione'), ('ASSISTENZA', 'Assistenza tecnica'), ('NOLEGGIO', 'Noleggio'), ('FORNITURA', 'Fornitura')], default='MANUTENZIONE', max_length=20)),
                ('data_inizio', models.DateField(default=django.utils.timezone.now)),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornitori_manutenzione', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornitore_asset_assegnati', to=settings.AUTH_USER_MODEL)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assegnati', to='anagrafica.fornitore')),
            ],
            options={
                'verbose_name': 'Asset fornitore',
                'verbose_name_plural': 'Asset fornitore',
                'ordering': ['-data_inizio', '-id'],
                'constraints': [models.UniqueConstraint(fields=('fornitore', 'asset', 'tipo'), name='uniq_fornitore_asset_tipo')],
            },
        ),
    ]
