# Generated by Django 5.2.11 on 2026-03-16 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0002_fornitoreasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnagraficaStatPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesso', models.CharField(choices=[('TUTTI', 'Tutti gli utenti autenticati'), ('ADMIN', 'Solo amministratori'), ('RUOLI', 'Ruoli ACL specifici')], default='ADMIN', max_length=20)),
                ('ruolo_ids', models.JSONField(blank=True, default=list, help_text='Lista ruolo_id ACL legacy abilitati (usato solo se accesso=RUOLI)')),
            ],
            options={
                'verbose_name': 'Permessi statistiche anagrafica',
                'verbose_name_plural': 'Permessi statistiche anagrafica',
            },
        ),
        migrations.CreateModel(
            name='DipendenteStatLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_user_id', models.IntegerField(db_index=True, unique=True)),
                ('hidden', models.JSONField(blank=True, default=list, help_text='Lista widget_id nascosti')),
                ('order', models.JSONField(blank=True, default=list, help_text='Ordine dei widget_id')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Layout widget statistiche dipendente',
                'verbose_name_plural': 'Layout widget statistiche dipendente',
            },
        ),
        migrations.CreateModel(
            name='RuoloOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('colore', models.CharField(default='#64748b', help_text='Colore esadecimale es. #1d4ed8', max_length=7)),
                ('icona', models.CharField(blank=True, default='', help_text='Emoji o testo breve', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ruolo Operativo',
                'verbose_name_plural': 'Ruoli Operativi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DipendenteRuoloOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('assegnato_il', models.DateTimeField(auto_now_add=True)),
                ('assegnato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruoli_operativi_assegnati', to=settings.AUTH_USER_MODEL)),
                ('ruolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni', to='anagrafica.ruolooperativo')),
            ],
            options={
                'verbose_name': 'Ruolo operativo dipendente',
                'verbose_name_plural': 'Ruoli operativi dipendenti',
                'unique_together': {('legacy_anagrafica_id', 'ruolo')},
            },
        ),
    ]
