# Generated by Django 5.2.11 on 2026-03-16 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0003_anagraficastatpermission_dipendentestatlayout_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mansione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(blank=True, choices=[('OPERAIO', 'Operaio'), ('IMPIEGATO', 'Impiegato'), ('QUADRO', 'Quadro'), ('DIRIGENTE', 'Dirigente'), ('ALTRO', 'Altro')], default='', max_length=20)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('colore', models.CharField(default='#64748b', help_text='Colore esadecimale es. #1d4ed8', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mansione',
                'verbose_name_plural': 'Mansioni',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoQualifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('categoria', models.CharField(choices=[('SICUREZZA', 'Sicurezza'), ('PROFESSIONALE', 'Professionale'), ('GESTIONALE', 'Gestionale'), ('ALTRO', 'Altro')], default='ALTRO', max_length=20)),
                ('durata_mesi', models.PositiveSmallIntegerField(default=0, help_text='Durata validità in mesi. 0 = nessuna scadenza automatica.')),
                ('descrizione', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo qualifica',
                'verbose_name_plural': 'Tipi qualifica',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DipendenteQualifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('data_conseguimento', models.DateField(blank=True, null=True)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assegnato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifiche_assegnate', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni', to='anagrafica.tipoqualifica')),
            ],
            options={
                'verbose_name': 'Qualifica dipendente',
                'verbose_name_plural': 'Qualifiche dipendente',
                'ordering': ['data_scadenza', 'tipo__nome'],
            },
        ),
    ]
