# Generated by Django 5.2.13 on 2026-05-20 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0007_retribuzioni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoricoContratto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('tax_code', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('tipologia_contratto', models.CharField(blank=True, choices=[('INDETERMINATO', 'Tempo indeterminato'), ('DETERMINATO', 'Tempo determinato'), ('APPRENDISTATO', 'Apprendistato'), ('SOMMINISTRAZIONE', 'Somministrazione'), ('COLLABORAZIONE', 'Collaborazione'), ('STAGE', 'Stage / Tirocinio'), ('ALTRO', 'Altro')], default='', max_length=20)),
                ('qualifica_nome', models.CharField(blank=True, default='', max_length=150)),
                ('codice_livello', models.CharField(blank=True, choices=[('A1', 'A1'), ('B3', 'B3'), ('B2', 'B2'), ('B1', 'B1'), ('C3', 'C3'), ('C2', 'C2'), ('C1', 'C1'), ('D2', 'D2'), ('D1', 'D1'), ('DIR', 'DIR')], default='', max_length=10)),
                ('ccnl', models.CharField(blank=True, default='', max_length=100)),
                ('descrizione_livello', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Storico contrattuale',
                'verbose_name_plural': 'Storico contrattuale',
                'ordering': ['-data_inizio', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='voceretributiva',
            new_name='anagrafica__tax_cod_5694f7_idx',
            old_name='anagrafica_taxcode_payitem_idx',
        ),
        migrations.RenameIndex(
            model_name='voceretributiva',
            new_name='anagrafica__legacy__7af8ca_idx',
            old_name='anagrafica_legacyid_comp_idx',
        ),
        migrations.AddField(
            model_name='storicocontratto',
            name='importato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratti_importati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='storicocontratto',
            index=models.Index(fields=['legacy_anagrafica_id', 'data_inizio'], name='anagrafica__legacy__76aafa_idx'),
        ),
        migrations.AddIndex(
            model_name='storicocontratto',
            index=models.Index(fields=['tax_code', 'data_inizio'], name='anagrafica__tax_cod_fb1a27_idx'),
        ),
    ]
