# Generated by Django 5.2.13 on 2026-05-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0008_storico_contratti'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivelloContrattuale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10, unique=True)),
                ('descrizione', models.CharField(blank=True, default='', max_length=200)),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Livello contrattuale',
                'verbose_name_plural': 'Livelli contrattuali',
                'ordering': ['ordine', 'codice'],
            },
        ),
        migrations.AlterField(
            model_name='storicocontratto',
            name='codice_livello',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
