# Generated by Django 5.2.13 on 2026-05-20 15:03

from django.db import migrations, models


_TIPOLOGIE_INIZIALI = [
    ("INDETERMINATO", "Tempo indeterminato", 1),
    ("DETERMINATO", "Tempo determinato", 2),
    ("APPRENDISTATO", "Apprendistato", 3),
    ("SOMMINISTRAZIONE", "Somministrazione", 4),
    ("COLLABORAZIONE", "Collaborazione", 5),
    ("STAGE", "Stage / Tirocinio", 6),
    ("ALTRO", "Altro", 7),
]


def _popola_tipologie(apps, schema_editor):
    TipologiaContratto = apps.get_model("anagrafica", "TipologiaContratto")
    for codice, nome, ordine in _TIPOLOGIE_INIZIALI:
        TipologiaContratto.objects.get_or_create(codice=codice, defaults={"nome": nome, "ordine": ordine})


def _rimuovi_tipologie(apps, schema_editor):
    TipologiaContratto = apps.get_model("anagrafica", "TipologiaContratto")
    TipologiaContratto.objects.filter(codice__in=[c for c, _, _ in _TIPOLOGIE_INIZIALI]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0009_livello_contrattuale'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipologiaContratto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipologia contratto',
                'verbose_name_plural': 'Tipologie contratto',
                'ordering': ['ordine', 'codice'],
            },
        ),
        migrations.AlterField(
            model_name='storicocontratto',
            name='tipologia_contratto',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.RunPython(_popola_tipologie, _rimuovi_tipologie),
    ]
