# Generated by Django 5.2.11 on 2026-05-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0011_cambiamento_organizzativo_voce_manuale'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dipendentecambiamentoorganizzativo',
            new_name='anagrafica__legacy__1dc8f0_idx',
            old_name='anag_cambio_lid_tipo_dt_idx',
        ),
    ]
