# Generated by Django 5.2.11 on 2026-05-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0012_rename_anag_cambio_lid_tipo_dt_idx_anagrafica__legacy__1dc8f0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendenteanagraficaaziendale',
            name='badge',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='Badge'),
        ),
        migrations.AddField(
            model_name='dipendenteanagraficaaziendale',
            name='data_assunzione_ultima',
            field=models.DateField(blank=True, help_text='Inizio del rapporto di lavoro corrente (se diversa dalla prima assunzione)', null=True, verbose_name='Data assunzione corrente'),
        ),
        migrations.AddField(
            model_name='dipendenteanagraficaaziendale',
            name='data_cessazione',
            field=models.DateField(blank=True, help_text='Data di fine rapporto. Se valorizzata, il dipendente è considerato cessato.', null=True, verbose_name='Data cessazione'),
        ),
        migrations.AddField(
            model_name='dipendenteanagraficacivile',
            name='nazionalita',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nazionalità'),
        ),
        migrations.AddField(
            model_name='dipendenteanagraficacivile',
            name='provincia_nascita',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
