# Generated by Django 5.2.11 on 2026-05-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0013_dipendenteanagraficaaziendale_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipendenteanagraficacivile',
            name='provincia_nascita',
            field=models.CharField(blank=True, default='', help_text='Provincia di nascita: accetta sia sigla (2 lettere) sia nome esteso.', max_length=50),
        ),
    ]
