# Generated by Django 5.2.11 on 2026-05-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0015_cedolini'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='saldocedolino',
            new_name='anagrafica__legacy__92e92a_idx',
            old_name='anagrafica_saldo_lid_comp_idx',
        ),
        migrations.RenameIndex(
            model_name='saldocedolino',
            new_name='anagrafica__data_co_eba841_idx',
            old_name='anagrafica_saldo_comp_idx',
        ),
    ]
