# Generated by Django 5.2.11 on 2026-05-21

import anagrafica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafica", "0016_rename_anagrafica_saldo_lid_comp_idx_anagrafica__legacy__92e92a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dipendenteanagraficacivile",
            name="foto",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to=anagrafica.models._dipendente_foto_upload_to,
                verbose_name="Foto dipendente",
            ),
        ),
    ]
