# Generated by Django 5.2.11 on 2026-05-21 13:33

import anagrafica.models
import anagrafica.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0017_dipendenteanagraficacivile_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnagraficaVisiteMedichePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesso', models.CharField(choices=[('TUTTI', 'Tutti gli utenti autenticati'), ('ADMIN', 'Solo amministratori'), ('RUOLI', 'Ruoli ACL specifici')], default='ADMIN', max_length=20)),
                ('ruolo_ids', models.JSONField(blank=True, default=list, help_text='Lista ruolo_id ACL legacy abilitati (usato solo se accesso=RUOLI)')),
            ],
            options={
                'verbose_name': 'Permessi visite mediche',
                'verbose_name_plural': 'Permessi visite mediche',
            },
        ),
        migrations.CreateModel(
            name='DocumentoDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('tipo', models.CharField(choices=[('DPI_CONSEGNA', 'Modulo consegna DPI'), ('VISITA_MEDICA_REFERTO', 'Referto visita medica'), ('ALTRO', 'Altro')], db_index=True, default='ALTRO', max_length=30)),
                ('file', models.FileField(storage=anagrafica.storage.PrivateAnagraficaStorage(), upload_to=anagrafica.models._documento_dipendente_upload_to)),
                ('nome_originale', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_mime', models.CharField(blank=True, default='', max_length=100)),
                ('dimensione_bytes', models.PositiveIntegerField(default=0)),
                ('descrizione', models.CharField(blank=True, default='', max_length=300)),
                ('oggetto_riferimento_tipo', models.CharField(blank=True, default='', help_text="Riferimento sintetico all'entity di origine (es. 'dpi.consegna').", max_length=50)),
                ('oggetto_riferimento_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_display', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_dipendente_caricati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento dipendente',
                'verbose_name_plural': 'Documenti dipendente',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoVisitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('durata_mesi', models.PositiveSmallIntegerField(default=12, help_text="Periodicità in mesi: la scadenza parte dalla data dell'ultima visita.")),
                ('obbligatoria', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ruoli_operativi', models.ManyToManyField(blank=True, help_text='Ruoli operativi per cui questa visita è obbligatoria.', related_name='tipi_visita_medica', to='anagrafica.ruolooperativo')),
            ],
            options={
                'verbose_name': 'Tipo visita medica',
                'verbose_name_plural': 'Tipi visita medica',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='VisitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('data_svolgimento', models.DateField()),
                ('data_scadenza', models.DateField(blank=True, help_text='Calcolata automaticamente: data_svolgimento + durata_mesi del tipo.', null=True)),
                ('esito', models.CharField(choices=[('IDONEO', 'Idoneo'), ('IDONEO_PRESCR', 'Idoneo con prescrizioni'), ('NON_IDONEO_TEMP', 'Non idoneo (temporaneo)'), ('NON_IDONEO_DEF', 'Non idoneo (definitivo)')], default='IDONEO', max_length=20)),
                ('prescrizioni', models.TextField(blank=True, default='')),
                ('medico_competente', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visite_mediche_create', to=settings.AUTH_USER_MODEL)),
                ('referto_documento', models.ForeignKey(blank=True, help_text='DocumentoDipendente di tipo VISITA_MEDICA_REFERTO collegato.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='anagrafica.documentodipendente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visite', to='anagrafica.tipovisitamedica')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visite_mediche_modificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita medica',
                'verbose_name_plural': 'Visite mediche',
                'ordering': ['-data_svolgimento', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='documentodipendente',
            index=models.Index(fields=['legacy_anagrafica_id', 'tipo'], name='anagrafica__legacy__eda426_idx'),
        ),
        migrations.AddIndex(
            model_name='documentodipendente',
            index=models.Index(fields=['oggetto_riferimento_tipo', 'oggetto_riferimento_id'], name='anagrafica__oggetto_6949f6_idx'),
        ),
        migrations.AddIndex(
            model_name='visitamedica',
            index=models.Index(fields=['legacy_anagrafica_id', 'data_scadenza'], name='anagrafica__legacy__f59bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='visitamedica',
            index=models.Index(fields=['tipo', 'data_scadenza'], name='anagrafica__tipo_id_e20a53_idx'),
        ),
    ]
