# Generated by Django 5.2.13 on 2026-05-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0019_seed_tipi_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitamedica',
            name='esito',
            field=models.CharField(choices=[('IDONEO', 'Idoneo'), ('IDONEO_MANS', 'Idoneo mansione specifica'), ('IDONEO_PRESCR', 'Idoneo con prescrizioni'), ('IDONEO_LIM', 'Idoneo con limitazioni'), ('IDONEO_LIM_PRESCR', 'Idoneo con limitazioni e prescrizioni'), ('NON_IDONEO_TEMP', 'Non idoneo (temporaneo)'), ('NON_IDONEO_DEF', 'Non idoneo (definitivo)')], default='IDONEO', max_length=20),
        ),
    ]
