# Generated by Django 5.2.13 on 2026-05-21 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0020_alter_visitamedica_esito'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartellaDocumentoDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descrizione', models.CharField(blank=True, default='', max_length=300)),
                ('ordine', models.PositiveSmallIntegerField(default=0, help_text='Ordinamento nella lista.')),
                ('attiva', models.BooleanField(default=True, help_text='Se False non appare nel form di upload.')),
            ],
            options={
                'verbose_name': 'Cartella documenti dipendente',
                'verbose_name_plural': 'Cartelle documenti dipendente',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='documentodipendente',
            name='tipo',
            field=models.CharField(choices=[('DPI_CONSEGNA', 'Modulo consegna DPI'), ('VISITA_MEDICA_REFERTO', 'Referto visita medica'), ('MANUALE', 'Documento manuale'), ('ALTRO', 'Altro')], db_index=True, default='MANUALE', max_length=30),
        ),
        migrations.AddField(
            model_name='documentodipendente',
            name='cartella',
            field=models.ForeignKey(blank=True, help_text='Cartella virtuale di appartenenza. Null per documenti di sistema (DPI, referti).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti', to='anagrafica.cartelladocumentodipendente'),
        ),
    ]
