# Generated by Django 5.2.13 on 2026-05-21 19:07

import django.db.models.deletion
from django.db import migrations, models


def seed_system_links(apps, schema_editor):
    SubnavLinkAnagrafica = apps.get_model("anagrafica", "SubnavLinkAnagrafica")
    system_links = [
        dict(etichetta="Anagrafica HR", icona="", url_type="named", url_value="anagrafica:index",
             active_view_names="anagrafica:index", ordine=0, is_sistema=True),
        dict(etichetta="Dipendenti", icona="", url_type="named", url_value="anagrafica:dipendenti_list",
             active_view_names="anagrafica:dipendenti_list,anagrafica:dipendente_detail", ordine=10, is_sistema=True),
        dict(etichetta="📅 Ratei Ferie", icona="", url_type="named", url_value="anagrafica:ratei_list",
             active_view_names="anagrafica:ratei_list", ordine=20, is_sistema=True),
        dict(etichetta="🏥 Visite mediche", icona="", url_type="named", url_value="anagrafica:visite_mediche_dashboard",
             active_view_names="anagrafica:visite_mediche_dashboard,anagrafica:visite_mediche_nuova_sessione", ordine=30, is_sistema=True),
        dict(etichetta="📄 Documenti", icona="", url_type="named", url_value="anagrafica:documenti_list",
             active_view_names="anagrafica:documenti_list", ordine=40, is_sistema=True),
        dict(etichetta="⚙️ Impostazioni", icona="", url_type="named", url_value="anagrafica:impostazioni",
             active_view_names="anagrafica:impostazioni,anagrafica:mansioni_list,anagrafica:aree_list,anagrafica:ruoli_aziendali_list,anagrafica:ruoli_operativi_list,anagrafica:qualifiche_list,anagrafica:widget_permissions",
             ordine=99, is_sistema=True),
    ]
    for link_data in system_links:
        SubnavLinkAnagrafica.objects.get_or_create(
            url_value=link_data["url_value"],
            defaults={k: v for k, v in link_data.items() if k != "url_value"},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0021_cartelladocumentodipendente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubnavCategoriaAnagrafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('icona', models.CharField(blank=True, default='', help_text='Emoji o testo breve mostrato prima del nome.', max_length=20)),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria subnav anagrafica',
                'verbose_name_plural': 'Categorie subnav anagrafica',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SubnavLinkAnagrafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etichetta', models.CharField(max_length=80)),
                ('icona', models.CharField(blank=True, default='', max_length=20)),
                ('url_type', models.CharField(choices=[('named', 'URL Django (nome view)'), ('raw', 'URL diretto (path o esterno)')], default='named', max_length=10)),
                ('url_value', models.CharField(help_text="Nome view Django (es. 'anagrafica:dipendenti_list') oppure path/URL assoluto.", max_length=255)),
                ('active_view_names', models.CharField(blank=True, default='', help_text='Nomi view che rendono il link attivo (comma-separated). Solo per url_type=named.', max_length=500)),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
                ('apri_nuova_tab', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sistema', models.BooleanField(default=False, help_text='Se True il link è di sistema: non eliminabile, solo nascondibile/rinominabile.')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='anagrafica.subnavcategoriaanagrafica')),
            ],
            options={
                'verbose_name': 'Link subnav anagrafica',
                'verbose_name_plural': 'Link subnav anagrafica',
                'ordering': ['ordine', 'etichetta'],
            },
        ),
        migrations.RunPython(seed_system_links, migrations.RunPython.noop),
    ]
