# Generated by Django 5.2.11 on 2026-05-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0025_subnav_formazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourse',
            name='durata_ore_teorica',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='trainingcourseversion',
            name='durata_ore_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='trainingemployeerecord',
            name='duration_hours_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='trainingemployeerecord',
            name='ore_frequentate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='trainingenrollment',
            name='ore_frequentate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='traininglessonattendance',
            name='ore_effettive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='ore_totali_stimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
