# Generated by Django 5.2.11 on 2026-05-22 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0026_widen_training_decimal_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCorso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria corso',
                'verbose_name_plural': 'Categorie corso',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoria che lega il corso ai fattori di rischio. Null = nessuna derivazione.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corsi', to='anagrafica.categoriacorso'),
        ),
        migrations.CreateModel(
            name='FattoreRischio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('CHIMICO', 'Chimico'), ('FISICO', 'Fisico'), ('BIOLOGICO', 'Biologico'), ('ERGONOMICO', 'Ergonomico / MMC'), ('INFORTUNISTICO', 'Infortunistico'), ('ALTRO', 'Altro')], default='ALTRO', max_length=20)),
                ('descrizione', models.TextField(blank=True)),
                ('periodicita_formazione_mesi', models.PositiveSmallIntegerField(default=0, help_text='Frequenza rinnovo formazione in mesi. 0 = una tantum.')),
                ('periodicita_sorveglianza_mesi', models.PositiveSmallIntegerField(default=0, help_text='Frequenza visita medica in mesi. 0 = non prevista.')),
                ('richiede_formazione', models.BooleanField(default=True)),
                ('richiede_visita_medica', models.BooleanField(default=False)),
                ('richiede_dpi', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fattore di rischio',
                'verbose_name_plural': 'Fattori di rischio',
                'ordering': ['categoria', 'nome'],
                'indexes': [models.Index(fields=['categoria', 'is_active'], name='anagrafica__categor_4f41a3_idx')],
            },
        ),
        migrations.AddField(
            model_name='categoriacorso',
            name='fattori_rischio',
            field=models.ManyToManyField(blank=True, related_name='categorie_corso', to='anagrafica.fattorerischio'),
        ),
        migrations.CreateModel(
            name='EsposizioneRischio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esposizioni_rischio', to='anagrafica.areaaziendale')),
                ('mansione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esposizioni_rischio', to='anagrafica.mansione')),
                ('fattore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esposizioni', to='anagrafica.fattorerischio')),
            ],
            options={
                'verbose_name': 'Esposizione a rischio',
                'verbose_name_plural': 'Esposizioni a rischio',
                'indexes': [models.Index(fields=['fattore', 'is_active'], name='anagrafica__fattore_739b30_idx'), models.Index(fields=['mansione', 'is_active'], name='anagrafica__mansion_729eba_idx'), models.Index(fields=['area', 'is_active'], name='anagrafica__area_id_683f2f_idx')],
            },
        ),
    ]
