# Generated by Django 5.2.11 on 2026-05-26 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0030_offboarding_pratiche'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingOffboardingCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('OFFBOARDING', 'Offboarding')], db_index=True, max_length=20)),
                ('campo_key', models.CharField(max_length=120)),
                ('campo_label', models.CharField(max_length=160)),
                ('sezione', models.CharField(blank=True, default='', max_length=120)),
                ('categoria', models.CharField(choices=[('HR', 'HR'), ('IT', 'IT / Sistemi informatici'), ('RESPONSABILE', 'Responsabile reparto'), ('DPI', 'DPI / Sicurezza'), ('AMMINISTRAZIONE', 'Amministrazione'), ('ALTRO', 'Altro')], db_index=True, default='HR', max_length=30)),
                ('obbligatorio', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('ordine', models.PositiveIntegerField(default=50)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anagrafica_workflow_campi_aggiornati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campo onboarding/offboarding',
                'verbose_name_plural': 'Campi onboarding/offboarding',
                'ordering': ['fase', 'ordine', 'campo_label'],
                'indexes': [models.Index(fields=['fase', 'is_active', 'ordine'], name='anagrafica__fase_966ca7_idx')],
                'unique_together': {('fase', 'campo_key')},
            },
        ),
    ]
