# Generated by Django 5.2.11 on 2026-05-28 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0034_area_aziendale_reparto_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaaziendale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='esposizionerischio',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esposizioni_rischio', to='anagrafica.areaaziendale'),
        ),
        migrations.AlterField(
            model_name='trainingrequirementrule',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regole_formazione', to='anagrafica.areaaziendale'),
        ),
    ]
