# Generated by Django 5.2.11 on 2026-06-03 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0035_alter_areaaziendale_id_alter_esposizionerischio_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendenteanagraficacivile',
            name='figli_a_carico',
            field=models.BooleanField(default=False, help_text='Indica se il dipendente ha figli a carico. La quantità è data dai figli registrati.', verbose_name='Figli a carico'),
        ),
        migrations.CreateModel(
            name='FiglioACarico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=120, verbose_name='Nome')),
                ('data_nascita', models.DateField(verbose_name='Data di nascita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anagrafica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figli', to='anagrafica.dipendenteanagraficacivile', verbose_name='Anagrafica civile')),
            ],
            options={
                'verbose_name': 'Figlio a carico',
                'verbose_name_plural': 'Figli a carico',
                'ordering': ['data_nascita'],
            },
        ),
    ]
