# Generated by Django 5.2.11 on 2026-06-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0037_documentodipendente_retention_until'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentodipendente',
            new_name='anagrafica__retenti_ce067a_idx',
            old_name='anagrafica__retenti_idx',
        ),
    ]
