# Generated by Django 5.2.11 on 2026-06-11 15:36

import anagrafica.models
import anagrafica.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0038_rename_anagrafica__retenti_idx_anagrafica__retenti_ce067a_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipendenteanagraficacivile',
            name='foto',
            field=models.ImageField(blank=True, default='', help_text='Dato personale: salvata in ANAGRAFICA_PRIVATE_ROOT (fuori webroot). Servita solo dalla view protetta anagrafica:foto_dipendente.', storage=anagrafica.storage.PrivateAnagraficaStorage(), upload_to=anagrafica.models._dipendente_foto_upload_to, verbose_name='Foto dipendente'),
        ),
    ]
