# Generated by Django 5.2.11 on 2026-06-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0040_onboarding_pratiche'),
        ('dpi', '0005_firma_immagine_consegna'),
    ]

    operations = [
        migrations.AddField(
            model_name='fattorerischio',
            name='categorie_dpi',
            field=models.ManyToManyField(blank=True, help_text='Categorie DPI generate da questo fattore di rischio.', related_name='fattori_rischio', to='dpi.categoriadpi'),
        ),
        migrations.AddField(
            model_name='fattorerischio',
            name='tipi_visita',
            field=models.ManyToManyField(blank=True, help_text='Visite mediche generate da questo fattore di rischio.', related_name='fattori_rischio', to='anagrafica.tipovisitamedica'),
        ),
        migrations.AddField(
            model_name='mansione',
            name='dpi_richiesti',
            field=models.ManyToManyField(blank=True, help_text='Categorie DPI obbligatorie per questa mansione.', related_name='mansioni_richiedenti', to='dpi.categoriadpi'),
        ),
        migrations.AddField(
            model_name='mansione',
            name='visite_richieste',
            field=models.ManyToManyField(blank=True, help_text='Tipologie di visita medica obbligatorie per questa mansione.', related_name='mansioni_richiedenti', to='anagrafica.tipovisitamedica'),
        ),
    ]
