# Generated by Django 5.2.11 on 2026-06-29 10:50

import anagrafica.models
import anagrafica.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0041_fattorerischio_categorie_dpi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornitoredocumento',
            name='file',
            field=models.FileField(storage=anagrafica.storage.PrivateAnagraficaStorage(), upload_to=anagrafica.models._fornitore_documento_upload_to),
        ),
    ]
