# Generated by Django 5.2.11 on 2026-06-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0041_fattorerischio_categorie_dpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mansione',
            name='livello_rischio',
            field=models.CharField(blank=True, choices=[('B', 'Basso (8h)'), ('M', 'Medio (12h)'), ('A', 'Alto (16h)')], default='', help_text='Livello di rischio mansione (ASR): B=basso 8h, M=medio 12h, A=alto 16h.', max_length=1),
        ),
    ]
