# Generated by Django 5.2.11 on 2026-06-17 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0045_qualifiche_subnav_formazione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificaSessione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conseguimento', models.DateField()),
                ('data_scadenza', models.DateField(blank=True, help_text='Scadenza comune; se vuota è calcolata da durata_mesi del tipo.', null=True)),
                ('ente', models.CharField(blank=True, default='', help_text="Ente/provider che ha erogato o rilasciato l'abilitazione.", max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessioni', to='anagrafica.tipoqualifica')),
            ],
            options={
                'verbose_name': 'Sessione qualifica',
                'verbose_name_plural': 'Sessioni qualifica',
                'ordering': ['-data_conseguimento', '-id'],
            },
        ),
        migrations.AddField(
            model_name='dipendentequalifica',
            name='sessione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifiche', to='anagrafica.qualificasessione'),
        ),
    ]
