# Generated by Django 5.2.11 on 2026-06-17 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0047_qualifica_sessioni_subnav'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendentequalifica',
            name='record_formazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifiche_collegate', to='anagrafica.trainingemployeerecord'),
        ),
        migrations.AddField(
            model_name='qualificasessione',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessioni_qualifica', to='anagrafica.trainingsession'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='qualifica',
            field=models.ForeignKey(blank=True, help_text='Qualifica/abilitazione rilasciata o rinnovata da questo corso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corsi', to='anagrafica.tipoqualifica'),
        ),
    ]
