# Generated by Django 5.2.11 on 2026-06-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0048_dipendentequalifica_record_formazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingexportlog',
            name='tipo',
            field=models.CharField(choices=[('PIANI', 'Elenco piani formativi'), ('CORSI', 'Elenco corsi'), ('ISCRITTI', 'Iscritti sessione'), ('PRESENZE', 'Presenze lezione'), ('STORICO_DIP', 'Storico dipendente'), ('SCADENZARIO', 'Scadenzario formazione'), ('MATRICE', 'Matrice dipendente × corso'), ('KPI', 'Report KPI direzionale'), ('REPORT_FIRMA', 'Report firma lezione PDF'), ('ATTESTATO', 'Attestato di completamento')], max_length=20),
        ),
    ]
