# Generated by Django 5.2.11 on 2026-06-17 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0049_alter_trainingexportlog_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestatoFormazioneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intestazione_eyebrow', models.CharField(default='Formazione interna', max_length=80)),
                ('sezione_label', models.CharField(default='NOVICROM HUB · Attestazione formativa', max_length=120)),
                ('titolo_partecipazione', models.CharField(default='Attestato di partecipazione', max_length=120)),
                ('titolo_frequenza', models.CharField(default='Attestato di frequenza', max_length=120)),
                ('titolo_qualifica', models.CharField(default='Attestato di qualifica', max_length=120)),
                ('formula_attestazione', models.CharField(default='Si attesta che', max_length=200)),
                ('firma_responsabile_label', models.CharField(default='Il Responsabile del corso', max_length=80)),
                ('firma_dipendente_label', models.CharField(default='Il Dipendente', max_length=80)),
                ('responsabile_default', models.CharField(blank=True, help_text='Nome stampato sotto la firma del responsabile quando il corso non ha un docente registrato.', max_length=200)),
                ('mostra_dati_personali', models.BooleanField(default=True, help_text="Mostra C.F., luogo e data di nascita sull'attestato (utile per D.Lgs. 81/2008). Disattiva per minimizzazione GDPR.")),
                ('nota_legale', models.TextField(default='Documento valido ai fini della tracciabilità formativa interna, anche in relazione agli obblighi di informazione, formazione e addestramento previsti dal D.Lgs. 81/2008.')),
                ('logo_url', models.URLField(blank=True, help_text='URL del logo in intestazione. Vuoto = logo NOVICROM HUB predefinito.')),
                ('pie_organizzazione', models.CharField(default='NOVICROM HUB · Portale interno · Costruzioni Novicrom S.r.l.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impostazioni attestato formazione',
                'verbose_name_plural': 'Impostazioni attestato formazione',
            },
        ),
    ]
