# Generated by Django 5.2.11 on 2026-06-17 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0050_attestatoformazioneconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestatoformazioneconfig',
            name='auto_salva_attestato',
            field=models.BooleanField(default=False, help_text="Salva automaticamente l'attestato PDF nel box documenti del dipendente alla chiusura del corso (quando l'iscrizione passa a «Completato»)."),
        ),
        migrations.AddField(
            model_name='attestatoformazioneconfig',
            name='cartella_attestati',
            field=models.ForeignKey(blank=True, help_text='Cartella del box documenti in cui archiviare gli attestati. Vuoto = usa/crea la cartella predefinita «Attestati formazione».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='anagrafica.cartelladocumentodipendente'),
        ),
        migrations.AddField(
            model_name='attestatoformazioneconfig',
            name='rigenera_se_esiste',
            field=models.BooleanField(default=False, help_text="Se attivo, rigenera e sovrascrive l'attestato già archiviato per lo stesso completamento. Se disattivo, l'archiviazione è idempotente (non duplica)."),
        ),
    ]
