# Generated by Django 5.2.11 on 2026-06-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0051_attestatoformazioneconfig_auto_salva_attestato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestatoProtocolloCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contatore protocollo attestati',
                'verbose_name_plural': 'Contatori protocollo attestati',
            },
        ),
        migrations.AddField(
            model_name='trainingemployeerecord',
            name='numero_protocollo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
