# Generated by Django 5.2.11 on 2026-06-17 21:25

import anagrafica.models_formazione
import anagrafica.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0052_attestatoprotocollocounter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REGISTRO_FIRMATO', 'Registro firme firmato'), ('MATERIALE', 'Materiale didattico'), ('ALTRO', 'Altro')], db_index=True, default='REGISTRO_FIRMATO', max_length=20)),
                ('file', models.FileField(storage=anagrafica.storage.PrivateAnagraficaStorage(), upload_to=anagrafica.models_formazione._training_attachment_upload_to)),
                ('nome_originale', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_mime', models.CharField(blank=True, default='', max_length=100)),
                ('dimensione_bytes', models.PositiveIntegerField(default=0)),
                ('descrizione', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_display', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lezione', models.ForeignKey(blank=True, help_text='Lezione di riferimento. Vuoto = allegato a livello di sessione.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='anagrafica.traininglesson')),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='anagrafica.trainingsession')),
            ],
            options={
                'verbose_name': 'Allegato formazione',
                'verbose_name_plural': 'Allegati formazione',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['sessione', 'lezione'], name='anagrafica__session_e2e073_idx'), models.Index(fields=['tipo'], name='anagrafica__tipo_e1f49c_idx')],
            },
        ),
    ]
