# Generated by Django 5.2.11 on 2026-06-18 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0053_trainingattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEnrollmentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assegnato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turni', to='anagrafica.trainingenrollment')),
                ('lezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni', to='anagrafica.traininglesson')),
            ],
            options={
                'verbose_name': 'Assegnazione turno',
                'verbose_name_plural': 'Assegnazioni turni',
                'indexes': [models.Index(fields=['lezione'], name='anagrafica__lezione_9918cf_idx')],
                'unique_together': {('enrollment', 'lezione')},
            },
        ),
    ]
