# Generated by Django 5.2.11 on 2026-06-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0054_trainingenrollmentlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingenrollment',
            name='data_verifica',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='verifica_superata',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
