# Generated by Django 5.2.11 on 2026-06-18 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0055_trainingenrollment_data_verifica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='is_elearning',
            field=models.BooleanField(db_index=True, default=False, help_text='Micro-corso e-learning: slide sequenziali + quiz finale, fruibile in autonomia.'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='quiz_punteggio_minimo',
            field=models.PositiveSmallIntegerField(default=70, help_text='Percentuale minima di risposte corrette per superare il quiz finale (solo e-learning).'),
        ),
        migrations.CreateModel(
            name='TrainingElearningEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('stato', models.CharField(choices=[('ISCRITTO', 'Iscritto'), ('IN_CORSO', 'In corso'), ('COMPLETATO', 'Completato'), ('NON_SUPERATO', 'Non superato')], default='ISCRITTO', max_length=15)),
                ('data_iscrizione', models.DateTimeField(auto_now_add=True)),
                ('ultima_slide_ordine', models.PositiveSmallIntegerField(default=0, help_text='Avanzamento: ultima slide vista.')),
                ('n_slide_totali', models.PositiveSmallIntegerField(default=0)),
                ('best_punteggio_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('n_tentativi', models.PositiveSmallIntegerField(default=0)),
                ('data_completamento', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iscrizioni_elearning', to='anagrafica.trainingcourse')),
                ('record_completamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='anagrafica.trainingemployeerecord')),
            ],
            options={
                'verbose_name': 'Iscrizione e-learning',
                'verbose_name_plural': 'Iscrizioni e-learning',
            },
        ),
        migrations.CreateModel(
            name='TrainingQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('iniziato_il', models.DateTimeField(blank=True, null=True)),
                ('inviato_il', models.DateTimeField(auto_now_add=True)),
                ('punteggio_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('n_corrette', models.PositiveSmallIntegerField(default=0)),
                ('n_totali', models.PositiveSmallIntegerField(default=0)),
                ('superato', models.BooleanField(default=False)),
                ('risposte_json', models.JSONField(blank=True, default=dict)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_tentativi', to='anagrafica.trainingcourse')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentativi', to='anagrafica.trainingelearningenrollment')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_tentativi', to='anagrafica.trainingemployeerecord')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentativo quiz',
                'verbose_name_plural': 'Tentativi quiz',
                'ordering': ['-inviato_il'],
            },
        ),
        migrations.CreateModel(
            name='TrainingQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveSmallIntegerField(default=1)),
                ('testo', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_domande', to='anagrafica.trainingcourse')),
            ],
            options={
                'verbose_name': 'Domanda quiz',
                'verbose_name_plural': 'Domande quiz',
                'ordering': ['corso', 'ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingQuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveSmallIntegerField(default=1)),
                ('testo', models.CharField(max_length=500)),
                ('corretta', models.BooleanField(default=False)),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opzioni', to='anagrafica.trainingquizquestion')),
            ],
            options={
                'verbose_name': 'Opzione quiz',
                'verbose_name_plural': 'Opzioni quiz',
                'ordering': ['domanda', 'ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveSmallIntegerField(default=1, help_text='Posizione nella sequenza (1 = prima slide).')),
                ('titolo', models.CharField(max_length=300)),
                ('contenuto', models.TextField(blank=True, help_text='Contenuto in Markdown, reso lato server.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='anagrafica.trainingcourse')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Slide e-learning',
                'verbose_name_plural': 'Slide e-learning',
                'ordering': ['corso', 'ordine', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingelearningenrollment',
            index=models.Index(fields=['legacy_anagrafica_id', 'stato'], name='anagrafica__legacy__34d78e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingelearningenrollment',
            unique_together={('corso', 'legacy_anagrafica_id')},
        ),
        migrations.AddIndex(
            model_name='trainingquizattempt',
            index=models.Index(fields=['legacy_anagrafica_id', 'corso'], name='anagrafica__legacy__f951d6_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingquizattempt',
            index=models.Index(fields=['corso', 'superato'], name='anagrafica__corso_i_e39d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingquizquestion',
            index=models.Index(fields=['corso', 'ordine'], name='anagrafica__corso_i_7bded4_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingquizoption',
            index=models.Index(fields=['domanda'], name='anagrafica__domanda_ecece9_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingslide',
            index=models.Index(fields=['corso', 'ordine'], name='anagrafica__corso_i_3636d9_idx'),
        ),
    ]
