# Generated by Django 5.2.11 on 2026-06-18 17:31

import anagrafica.models_formazione
import anagrafica.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0057_subnav_corsi_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingslide',
            name='immagine',
            field=models.ImageField(blank=True, help_text='Slide-immagine (pagina importata da PPTX/PDF). Se valorizzata sostituisce il contenuto Markdown.', null=True, storage=anagrafica.storage.PrivateAnagraficaStorage(), upload_to=anagrafica.models_formazione._training_slide_upload_to),
        ),
    ]
