# Generated by Django 5.2.11 on 2026-06-18 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0059_subnav_elearning_gestione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElearningConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_punteggio_minimo_default', models.PositiveSmallIntegerField(default=70, help_text='Percentuale minima del quiz proposta di default ai nuovi micro-corsi (0–100).')),
                ('validita_mesi_default', models.PositiveSmallIntegerField(default=0, help_text='Validità in mesi proposta di default (0 = una tantum, nessun rinnovo).')),
                ('max_tentativi_quiz', models.PositiveSmallIntegerField(default=0, help_text='Numero massimo di tentativi del quiz per dipendente (0 = illimitati).')),
                ('libreoffice_path', models.CharField(blank=True, default='', help_text="Percorso dell'eseguibile LibreOffice (soffice) per l'import PowerPoint. Vuoto = usa LIBREOFFICE_PATH/variabile d'ambiente o auto-rilevamento.", max_length=400)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impostazioni e-learning',
                'verbose_name_plural': 'Impostazioni e-learning',
            },
        ),
    ]
