# Generated by Django 5.2.11 on 2026-06-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0060_elearning_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartelladocumentodipendente',
            name='retention_anni',
            field=models.PositiveSmallIntegerField(default=10, help_text='Anni di conservazione GDPR per i documenti manuali di questa cartella (impostazione del container; default 10). Applicata ai nuovi documenti.'),
        ),
    ]
