# Generated by Django 5.2.11 on 2026-06-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0061_cartella_retention_anni'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartelladocumentodipendente',
            name='solo_admin',
            field=models.BooleanField(default=False, help_text="Cartella riservata: nell'archivio i suoi documenti sono visibili solo ai super-amministratori (nascosti agli altri ruoli HR)."),
        ),
    ]
