# Generated by Django 5.2.11 on 2026-06-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0062_cartella_solo_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartelladocumentodipendente',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Cartella superiore. Vuoto = cartella di primo livello.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figlie', to='anagrafica.cartelladocumentodipendente'),
        ),
        migrations.AlterField(
            model_name='cartelladocumentodipendente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='cartelladocumentodipendente',
            unique_together={('parent', 'nome')},
        ),
    ]
