# Generated by Django 5.2.11 on 2026-06-19 08:13

import anagrafica.models
import anagrafica.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0064_subnav_qualifiche'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendentequalifica',
            name='documento',
            field=models.FileField(blank=True, help_text='Scansione/PDF del certificato (evidenza).', null=True, storage=anagrafica.storage.PrivateAnagraficaStorage(), upload_to=anagrafica.models._dipendente_qualifica_evidenza_upload_to),
        ),
        migrations.AddField(
            model_name='dipendentequalifica',
            name='documento_nome_originale',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dipendentequalifica',
            name='ente',
            field=models.CharField(blank=True, default='', help_text="Ente/organismo che ha rilasciato l'abilitazione.", max_length=200),
        ),
        migrations.AddField(
            model_name='dipendentequalifica',
            name='livello',
            field=models.CharField(blank=True, default='', help_text='Livello/categoria (es. antincendio liv. 2).', max_length=80),
        ),
        migrations.AddField(
            model_name='dipendentequalifica',
            name='numero',
            field=models.CharField(blank=True, default='', help_text='Numero del certificato/patentino.', max_length=100),
        ),
        migrations.AddField(
            model_name='dipendentequalifica',
            name='verificata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dipendentequalifica',
            name='verificata_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifiche_verificate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dipendentequalifica',
            name='verificata_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
