# Generated by Django 5.2.11 on 2026-06-19 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0065_dipendentequalifica_documento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DipendenteQualificaStorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conseguimento', models.DateField(blank=True, null=True)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, default='', max_length=100)),
                ('livello', models.CharField(blank=True, default='', max_length=80)),
                ('ente', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('origine', models.CharField(choices=[('MANUALE', 'Manuale'), ('SESSIONE', 'Sessione di rinnovo'), ('IMPORT', 'Import')], default='MANUALE', max_length=12)),
                ('registrato_il', models.DateTimeField(auto_now_add=True)),
                ('qualifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storico', to='anagrafica.dipendentequalifica')),
                ('registrato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Storico qualifica dipendente',
                'verbose_name_plural': 'Storico qualifiche dipendente',
                'ordering': ['-data_conseguimento', '-id'],
            },
        ),
    ]
