# Generated by Django 5.2.11 on 2026-06-19 09:34

import anagrafica.models
import anagrafica.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0066_dipendentequalificastorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendentequalificastorico',
            name='documento',
            field=models.FileField(blank=True, help_text='Evidenza documentale di questo rilascio/rinnovo (storicizzata).', null=True, storage=anagrafica.storage.PrivateAnagraficaStorage(), upload_to=anagrafica.models._dipendente_qualifica_storico_upload_to),
        ),
        migrations.AddField(
            model_name='dipendentequalificastorico',
            name='documento_nome_originale',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
