# Generated by Django 5.2.11 on 2026-06-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0067_dipendentequalificastorico_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartelladocumentodipendente',
            name='reparti',
            field=models.ManyToManyField(blank=True, help_text='Reparti a cui si applica la cartella. Vuoto = tutti i reparti.', related_name='cartelle_documenti', to='anagrafica.reparto'),
        ),
        migrations.AddField(
            model_name='cartelladocumentodipendente',
            name='ruoli_operativi',
            field=models.ManyToManyField(blank=True, help_text='Ruoli operativi a cui si applica la cartella. Vuoto = tutti i ruoli.', related_name='cartelle_documenti', to='anagrafica.ruolooperativo'),
        ),
    ]
