# Generated by Django 5.2.11 on 2026-06-29 12:52

import anagrafica.models
import anagrafica.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0070_subnav_proposta_a_pillars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornitoredocumento',
            name='file',
            field=models.FileField(storage=anagrafica.storage.PrivateAnagraficaStorage(), upload_to=anagrafica.models._fornitore_documento_upload_to),
        ),
    ]
