# Generated by Django 5.2.11 on 2026-06-25 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0070_subnav_proposta_a_pillars'),
        ('assets', '0079_assets_sidebar_clean_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagnaRefresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inizio', models.DateField()),
                ('periodo_fine', models.DateField(blank=True, null=True)),
                ('scadenza', models.DateField(blank=True, null=True)),
                ('reparto', models.CharField(blank=True, default='', max_length=120)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('avviatore_ruolo', models.CharField(blank=True, default='', help_text='Ruolo che innesca la tornata (solo trigger, NON approvatore).', max_length=120)),
                ('stato', models.CharField(choices=[('aperta', 'Aperta'), ('chiusa', 'Chiusa')], default='aperta', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campagna refresh',
                'verbose_name_plural': 'Campagne refresh',
                'ordering': ['-periodo_inizio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SkillMatrixConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soglia_operativa', models.CharField(choices=[('I', 'In formazione'), ('L', 'Intermedio'), ('U', 'Autonomo'), ('O', 'Formatore/Esperto')], default='U', help_text='Livello minimo (≥) per contare come operativo nel pool capacità.', max_length=1)),
                ('regola_multivoce', models.CharField(choices=[('MIN', 'Minimo delle voci (più rigoroso)'), ('MEDIA', 'Media delle voci'), ('BLOCCANTI', 'Minimo sulle sole voci bloccanti')], default='MIN', help_text='Come calcolare il livello complessivo di una macchina multivoce (da confermare in sessione CAR).', max_length=12)),
                ('finestra_continuita_mesi', models.PositiveSmallIntegerField(default=12)),
                ('preavviso_continuita_mesi', models.PositiveSmallIntegerField(default=9)),
                ('periodicita_refresh_mesi', models.PositiveSmallIntegerField(default=6)),
                ('soglia_uomo_solo', models.PositiveSmallIntegerField(default=2, help_text='Numero minimo di persone U/O per non essere a rischio uomo-solo (MT CN 06 §8.2.2).')),
                ('includi_car_come_riserva', models.BooleanField(default=False)),
                ('etichetta_i', models.CharField(default='In formazione', max_length=120)),
                ('etichetta_l', models.CharField(default='Intermedio', max_length=120)),
                ('etichetta_u', models.CharField(default='Autonomo', max_length=120)),
                ('etichetta_o', models.CharField(default='Formatore/Esperto', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurazione Skill Matrix',
                'verbose_name_plural': 'Configurazione Skill Matrix',
            },
        ),
        migrations.CreateModel(
            name='SkmCorsiAttivati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True, unique=True)),
                ('numero', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corsi attivati (contatore)',
                'verbose_name_plural': 'Corsi attivati (contatore)',
            },
        ),
        migrations.CreateModel(
            name='VoceMacchinaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=60, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('asset_type', models.CharField(blank=True, default='', help_text='Tipo macchina a cui si applica (vuoto = generica).', max_length=20)),
                ('bloccante', models.BooleanField(default=False, help_text='Conta per la regola multivoce BLOCCANTI.')),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Voce macchina (catalogo)',
                'verbose_name_plural': 'Voci macchina (catalogo)',
                'ordering': ['asset_type', 'ordine', 'codice'],
            },
        ),
        migrations.CreateModel(
            name='AbilitazioneMacchina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('livello', models.CharField(choices=[('I', 'In formazione'), ('L', 'Intermedio'), ('U', 'Autonomo'), ('O', 'Formatore/Esperto')], max_length=1)),
                ('in_lista', models.BooleanField(default=True, help_text="Chi non è in lista non opera su quell'asset.")),
                ('stato', models.CharField(choices=[('attiva', 'Attiva'), ('sospesa', 'Sospesa')], default='attiva', max_length=10)),
                ('conteggiabile_nel_carico', models.BooleanField(default=True, help_text='False per i CAR: visibili ma fuori dal pool capacità.')),
                ('livello_richiesto', models.CharField(blank=True, choices=[('I', 'In formazione'), ('L', 'Intermedio'), ('U', 'Autonomo'), ('O', 'Formatore/Esperto')], help_text="Livello atteso per la mansione su quell'asset (marker ▲).", max_length=1, null=True)),
                ('car_legacy_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('data_assegnazione', models.DateField(blank=True, null=True)),
                ('prossima_revisione', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abilitazioni_skm', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Abilitazione macchina',
                'verbose_name_plural': 'Abilitazioni macchina',
                'ordering': ['asset__name', 'legacy_anagrafica_id'],
            },
        ),
        migrations.CreateModel(
            name='AbilitazioneMacchinaStorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('livello', models.CharField(blank=True, choices=[('I', 'In formazione'), ('L', 'Intermedio'), ('U', 'Autonomo'), ('O', 'Formatore/Esperto')], default='', max_length=1)),
                ('data_rilevazione', models.DateField()),
                ('fonte', models.CharField(choices=[('import', 'Import baseline'), ('refresh', 'Refresh semestrale'), ('manuale', 'Manuale')], default='import', max_length=10)),
                ('car_legacy_id', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('registrato_il', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abilitazioni_skm_storico', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Storico abilitazione macchina',
                'verbose_name_plural': 'Storico abilitazioni macchina',
                'ordering': ['-data_rilevazione', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompetenzaSkm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competenza_key', models.CharField(max_length=120, unique=True)),
                ('display', models.CharField(blank=True, default='', max_length=255)),
                ('tipo', models.CharField(choices=[('macchina', 'Macchina'), ('processo', 'Processo'), ('contatore', 'Contatore')], db_index=True, default='macchina', max_length=12)),
                ('alias_storici', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('match_confidenza', models.CharField(blank=True, choices=[('esatto', 'Esatto'), ('parziale', 'Parziale'), ('assente', 'Assente'), ('na', 'Non applicabile')], default='na', max_length=10)),
                ('match_strategia', models.CharField(blank=True, default='', max_length=20)),
                ('match_confermato', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, help_text='Asset risolto (solo tipo=macchina).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competenze_skm', to='assets.asset')),
                ('tipo_qualifica', models.ForeignKey(blank=True, help_text='Qualifica collegata (solo tipo=processo, se corrispondente).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competenze_skm', to='anagrafica.tipoqualifica')),
            ],
            options={
                'verbose_name': 'Competenza Skill Matrix',
                'verbose_name_plural': 'Competenze Skill Matrix',
                'ordering': ['tipo', 'competenza_key'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoCriticoContinuita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('riferimento_normativo', models.CharField(blank=True, default='', max_length=200)),
                ('finestra_mesi', models.PositiveSmallIntegerField(blank=True, help_text='Override della finestra di config (vuoto = usa config).', null=True)),
                ('preavviso_mesi', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('tipo_qualifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processi_continuita', to='anagrafica.tipoqualifica')),
            ],
            options={
                'verbose_name': 'Processo critico (continuità)',
                'verbose_name_plural': 'Processi critici (continuità)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContinuitaOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('ultima_esecuzione', models.DateField(blank=True, help_text='Ultima esecuzione reale di produzione (popolata in F5).', null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abilitazione', models.ForeignKey(blank=True, help_text='Abilitazione che viene sospesa se la continuità è persa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuita', to='anagrafica.abilitazionemacchina')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuita', to='anagrafica.processocriticocontinuita')),
            ],
            options={
                'verbose_name': 'Continuità operativa',
                'verbose_name_plural': 'Continuità operative',
                'ordering': ['processo__nome', 'legacy_anagrafica_id'],
            },
        ),
        migrations.CreateModel(
            name='AbilitazioneMacchinaVoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livello', models.CharField(choices=[('I', 'In formazione'), ('L', 'Intermedio'), ('U', 'Autonomo'), ('O', 'Formatore/Esperto')], max_length=1)),
                ('abilitazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci', to='anagrafica.abilitazionemacchina')),
                ('voce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='anagrafica.vocemacchinacatalogo')),
            ],
            options={
                'verbose_name': 'Voce abilitazione macchina',
                'verbose_name_plural': 'Voci abilitazione macchina',
            },
        ),
        migrations.AddConstraint(
            model_name='abilitazionemacchina',
            constraint=models.UniqueConstraint(fields=('legacy_anagrafica_id', 'asset'), name='skm_uniq_abilitazione_persona_asset'),
        ),
        migrations.AddIndex(
            model_name='abilitazionemacchinastorico',
            index=models.Index(fields=['legacy_anagrafica_id', 'asset', 'data_rilevazione'], name='skm_idx_storico_persona_asset'),
        ),
        migrations.AddConstraint(
            model_name='continuitaoperativa',
            constraint=models.UniqueConstraint(fields=('legacy_anagrafica_id', 'processo'), name='skm_uniq_continuita_persona_processo'),
        ),
        migrations.AddConstraint(
            model_name='abilitazionemacchinavoce',
            constraint=models.UniqueConstraint(fields=('abilitazione', 'voce'), name='skm_uniq_abilitazione_voce'),
        ),
    ]
