# Generated by Django 5.2.11 on 2026-07-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0074_subnav_skill_matrix_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmatrixconfig',
            name='preavviso_refresh_giorni',
            field=models.PositiveSmallIntegerField(default=60, help_text='Giorni prima di prossima_revisione entro cui un reparto è «in arrivo» nello scadenzario abilitazioni.'),
        ),
    ]
