# Generated by Django 5.2.11 on 2026-07-06 20:27

import anagrafica.models_mpq
import anagrafica.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0075_skillmatrixconfig_preavviso_refresh_giorni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilitazioneProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('is_qualificato', models.BooleanField(default=True)),
                ('is_addetto', models.BooleanField(default=False)),
                ('is_controllore', models.BooleanField(default=False)),
                ('is_part145', models.BooleanField(default=False)),
                ('stato', models.CharField(choices=[('ATTIVA', 'Attiva'), ('SOSPESA', 'Sospesa'), ('REVOCATA', 'Revocata'), ('DISMESSA', 'Dismessa')], db_index=True, default='ATTIVA', max_length=10)),
                ('data_ingresso', models.DateField(blank=True, null=True)),
                ('data_dismissione', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dipendente_qualifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abilitazioni_mpq', to='anagrafica.dipendentequalifica')),
            ],
            options={
                'verbose_name': 'Abilitazione processo (MPQ)',
                'verbose_name_plural': 'Abilitazioni processo (MPQ)',
                'ordering': ['processo', 'legacy_anagrafica_id'],
            },
        ),
        migrations.CreateModel(
            name='ClienteQualificante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('ENTE_ACCREDITAMENTO', 'Ente di accreditamento'), ('ENTE_ESTERNO', 'Ente esterno'), ('ORGANISMO_CERTIFICAZIONE', 'Organismo di certificazione')], db_index=True, default='CLIENTE', max_length=24)),
                ('codice', models.CharField(blank=True, default='', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificatore', models.ForeignKey(blank=True, help_text='Organismo che certifica/accredita questo ente (opzionale).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enti_certificati', to='anagrafica.clientequalificante')),
            ],
            options={
                'verbose_name': 'Cliente/ente qualificante (MPQ)',
                'verbose_name_plural': 'Clienti/enti qualificanti (MPQ)',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CertificazioneIndividuale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.CharField(help_text='Schema di certificazione (es. ITA, ASNT).', max_length=60)),
                ('numero', models.CharField(blank=True, default='', max_length=120)),
                ('livello', models.CharField(blank=True, default='', max_length=40)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('documento', models.FileField(blank=True, help_text='Scansione/PDF del certificato individuale (evidenza).', null=True, storage=anagrafica.storage.PrivateAnagraficaStorage(), upload_to=anagrafica.models_mpq._certificazione_individuale_upload_to)),
                ('documento_nome_originale', models.CharField(blank=True, default='', max_length=255)),
                ('stato', models.CharField(choices=[('ATTIVA', 'Attiva'), ('SOSPESA', 'Sospesa'), ('REVOCATA', 'Revocata')], default='ATTIVA', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abilitazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificazioni', to='anagrafica.abilitazioneprocesso')),
                ('dipendente_qualifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificazioni_mpq', to='anagrafica.dipendentequalifica')),
                ('ente_certificatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificazioni', to='anagrafica.clientequalificante')),
            ],
            options={
                'verbose_name': 'Certificazione individuale (MPQ)',
                'verbose_name_plural': 'Certificazioni individuali (MPQ)',
                'ordering': ['abilitazione', 'schema'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoQualificato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('livello', models.CharField(blank=True, default='', help_text='Es. LVL2/LVL3.', max_length=40)),
                ('regime', models.CharField(choices=[('PART145', 'EASA Part 145'), ('NADCAP', 'NADCAP'), ('CLIENTE_SPECIFICO', 'Cliente-specifico'), ('SPECIALE', 'Processo speciale')], default='SPECIALE', max_length=20)),
                ('tipo_validita', models.CharField(choices=[('ILLIMITATA', 'Illimitata (salvo revoca/sospensione)'), ('PERIODO', 'Periodo (durata in mesi)'), ('DATA', 'Data di scadenza esplicita')], default='DATA', max_length=12)),
                ('data_conseguimento', models.DateField(blank=True, null=True)),
                ('durata_mesi', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('personale_modalita', models.CharField(choices=[('NOMINALE', 'Nominale (elenco persone)'), ('ORGANIZZATIVO', 'Organizzativa (rimando a dichiarazione)')], default='NOMINALE', max_length=14)),
                ('riferimento_dichiarazione', models.CharField(blank=True, default='', help_text='Per modalità organizzativa: rif. dichiarazione/approvazione.', max_length=255)),
                ('stato', models.CharField(choices=[('ATTIVO', 'Attivo'), ('SOSPESO', 'Sospeso'), ('REVOCATO', 'Revocato'), ('DISMESSO', 'Dismesso'), ('NON_RINNOVATO', 'Non più rinnovato')], db_index=True, default='ATTIVO', max_length=14)),
                ('motivo_stato', models.CharField(blank=True, default='', max_length=255)),
                ('riferimento_stato', models.CharField(blank=True, default='', help_text='Riferimento a supporto del cambio stato (es. comunicazione).', max_length=255)),
                ('numero_revisione', models.CharField(blank=True, default='', max_length=20)),
                ('responsabile_qualita', models.CharField(blank=True, default='', max_length=150)),
                ('data_revisione', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processi', to='anagrafica.clientequalificante')),
                ('clienti_addizionali', models.ManyToManyField(blank=True, related_name='processi_condivisi', to='anagrafica.clientequalificante')),
                ('ente_certificatore', models.ForeignKey(blank=True, help_text='Ente/organismo che certifica o accredita il processo (opzionale).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processi_certificati', to='anagrafica.clientequalificante')),
                ('reparti', models.ManyToManyField(blank=True, related_name='processi_qualificati', to='anagrafica.reparto', verbose_name='Distribuzione a reparto')),
                ('tipo_qualifica', models.ForeignKey(blank=True, help_text='Tipo qualifica di catalogo collegato (opzionale).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processi_mpq', to='anagrafica.tipoqualifica')),
            ],
            options={
                'verbose_name': 'Processo qualificato (MPQ)',
                'verbose_name_plural': 'Processi qualificati (MPQ)',
                'ordering': ['cliente__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MpqStorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=200)),
                ('dettaglio', models.TextField(blank=True, default='')),
                ('origine', models.CharField(choices=[('MANUALE', 'Manuale'), ('IMPORT', 'Import'), ('SISTEMA', 'Sistema')], default='MANUALE', max_length=10)),
                ('registrato_il', models.DateTimeField(auto_now_add=True)),
                ('abilitazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storico', to='anagrafica.abilitazioneprocesso')),
                ('registrato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storico', to='anagrafica.processoqualificato')),
            ],
            options={
                'verbose_name': 'Storico MPQ',
                'verbose_name_plural': 'Storico MPQ',
                'ordering': ['-registrato_il', '-id'],
            },
        ),
        migrations.AddField(
            model_name='abilitazioneprocesso',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilitazioni', to='anagrafica.processoqualificato'),
        ),
        migrations.CreateModel(
            name='RiferimentoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('APPROVAZIONE', 'Approvazione'), ('SPECIFICA', 'Specifica'), ('CERTIFICATO', 'Certificato'), ('DICHIARAZIONE', 'Dichiarazione')], default='APPROVAZIONE', max_length=14)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riferimenti', to='anagrafica.processoqualificato')),
            ],
            options={
                'verbose_name': 'Riferimento processo (MPQ)',
                'verbose_name_plural': 'Riferimenti processo (MPQ)',
                'ordering': ['processo', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='abilitazioneprocesso',
            constraint=models.UniqueConstraint(fields=('legacy_anagrafica_id', 'processo'), name='mpq_uniq_abilitazione_persona_processo'),
        ),
    ]
