# Generated by Django 5.2.11 on 2026-07-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0077_subnav_mod128_processi'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='abilitazioneprocesso',
            name='mpq_uniq_abilitazione_persona_processo',
        ),
        migrations.AddField(
            model_name='abilitazioneprocesso',
            name='nominativo_esterno',
            field=models.CharField(blank=True, default='', help_text='Qualificatore esterno (non a organico): usato al posto di legacy_anagrafica_id.', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='abilitazioneprocesso',
            constraint=models.UniqueConstraint(fields=('legacy_anagrafica_id', 'nominativo_esterno', 'processo'), name='mpq_uniq_abilitazione_persona_processo'),
        ),
    ]
