# Generated by Django 5.2.11 on 2026-07-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0078_remove_abilitazioneprocesso_mpq_uniq_abilitazione_persona_processo_and_more'),
        ('dpi', '0005_firma_immagine_consegna'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoqualificato',
            name='corsi_richiesti',
            field=models.ManyToManyField(blank=True, help_text="Corsi di formazione richiesti per l'idoneità al processo.", related_name='processi_richiedenti', to='anagrafica.trainingcourse'),
        ),
        migrations.AddField(
            model_name='processoqualificato',
            name='dpi_richiesti',
            field=models.ManyToManyField(blank=True, help_text='Categorie DPI obbligatorie per il processo.', related_name='processi_richiedenti', to='dpi.categoriadpi'),
        ),
        migrations.AddField(
            model_name='processoqualificato',
            name='visite_richieste',
            field=models.ManyToManyField(blank=True, help_text='Tipologie di visita medica obbligatorie per il processo.', related_name='processi_richiedenti', to='anagrafica.tipovisitamedica'),
        ),
    ]
