# Generated by Django 5.2.11 on 2026-07-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0071_alter_fornitoredocumento_file'),
        ('anagrafica', '0076_subnav_skill_matrix_scadenzario'),
        ('anagrafica', '0082_dipendente_area_aziendale_fk'),
    ]

    operations = [
    ]
