# Generated by Django 5.2.11 on 2026-07-15 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0083_merge_20260713_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruolooperativo',
            options={'ordering': ['nome'], 'verbose_name': 'Ruolo', 'verbose_name_plural': 'Ruoli'},
        ),
        migrations.AddField(
            model_name='ruolooperativo',
            name='certificazione_competenza',
            field=models.CharField(blank=True, default='', help_text='Certificazione/qualifica associata al ruolo (opzionale).', max_length=200, verbose_name='Certificazione di competenza'),
        ),
        migrations.AddField(
            model_name='ruolooperativo',
            name='riporta_a',
            field=models.ForeignKey(blank=True, help_text='Ruolo sovraordinato nella gerarchia (es. i capireparto riportano al coordinamento). Relazione tra RUOLI, non tra persone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riporti', to='anagrafica.ruolooperativo', verbose_name='Riporta a'),
        ),
    ]
