# Generated by Django 5.2.11 on 2026-07-16 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0085_merge_ruoli_aziendali_in_operativi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaSessione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_svolgimento', models.DateField()),
                ('medico_competente', models.CharField(blank=True, default='', max_length=200)),
                ('luogo', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visite_sessioni_create', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessione visite mediche',
                'verbose_name_plural': 'Sessioni visite mediche',
                'ordering': ['-data_svolgimento', '-id'],
            },
        ),
        migrations.AddField(
            model_name='visitamedica',
            name='sessione',
            field=models.ForeignKey(blank=True, help_text='Giornata visite in cui è stata registrata (opzionale).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visite', to='anagrafica.visitasessione'),
        ),
    ]
