# Generated by Django 5.2.11 on 2026-07-22 16:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0086_visitasessione_visitamedica_sessione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitingCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('rubrica', models.TextField(blank=True, default='', help_text='Definizione operativa dei livelli 1-5 con esempi. Una rubrica esplicita rende il criterio difendibile in un audit UNI/PdR 125.')),
                ('peso_percentuale', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('ordine', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Criterio di valutazione (Recruiting)',
                'verbose_name_plural': 'Criteri di valutazione (Recruiting)',
                'ordering': ['ordine', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RecruitingPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesso', models.CharField(choices=[('TUTTI', 'Tutti gli utenti autenticati'), ('ADMIN', 'Solo amministratori'), ('RUOLI', 'Ruoli ACL specifici')], default='ADMIN', max_length=20)),
                ('ruolo_ids', models.JSONField(blank=True, default=list, help_text='Lista ruolo_id ACL legacy abilitati (usato solo se accesso=RUOLI)')),
            ],
            options={
                'verbose_name': 'Permessi Recruiting',
                'verbose_name_plural': 'Permessi Recruiting',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome', models.CharField(db_index=True, max_length=120)),
                ('nome', models.CharField(db_index=True, max_length=120)),
                ('cellulare', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('localita', models.CharField(blank=True, default='', max_length=120)),
                ('provincia', models.CharField(blank=True, default='', max_length=4)),
                ('canale_provenienza', models.CharField(choices=[('AUTOCANDIDATURA', 'Autocandidatura'), ('AGENZIA', 'Agenzia interinale'), ('COLLOCAMENTO_MIRATO', 'Collocamento mirato'), ('SEGNALAZIONE', 'Segnalazione'), ('ANNUNCIO', 'Annuncio / portale online'), ('SCUOLA', 'Scuola / università'), ('ALTRO', 'Altro')], db_index=True, default='AUTOCANDIDATURA', max_length=32)),
                ('canale_dettaglio', models.CharField(blank=True, default='', help_text='Nome agenzia, portale o segnalatore (se pertinente).', max_length=160)),
                ('mansione_cercata', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('azienda_attuale', models.CharField(blank=True, default='', max_length=160)),
                ('mansione_attuale', models.CharField(blank=True, default='', max_length=160)),
                ('livello_contratto_attuale', models.CharField(blank=True, default='', max_length=120)),
                ('occupato_attualmente', models.BooleanField(blank=True, null=True)),
                ('eta', models.PositiveSmallIntegerField(blank=True, help_text='Dato informativo. Non concorre in alcun modo al punteggio.', null=True)),
                ('titolo_studio', models.CharField(blank=True, default='', max_length=160)),
                ('cittadinanza', models.CharField(blank=True, default='', help_text='Dato informativo. Non concorre in alcun modo al punteggio.', max_length=120)),
                ('data_primo_colloquio', models.DateField(blank=True, db_index=True, null=True)),
                ('cv_esito', models.CharField(blank=True, choices=[('OK', 'OK'), ('KO', 'Non idoneo')], default='', max_length=4)),
                ('colloquio_effettuato', models.BooleanField(default=False)),
                ('punteggio_ponderato', models.DecimalField(blank=True, decimal_places=2, help_text='Media pesata dei criteri attivi. Calcolata dal server, non modificabile a mano.', max_digits=4, null=True)),
                ('punteggio_aggiornato_il', models.DateTimeField(blank=True, null=True)),
                ('lingua_inglese_livello', models.CharField(blank=True, default='', max_length=60)),
                ('idoneita_tirocinio', models.BooleanField(blank=True, null=True)),
                ('idoneita_apprendistato', models.BooleanField(blank=True, null=True)),
                ('disponibilita', models.CharField(blank=True, default='', max_length=200)),
                ('motivo_cambio_lavoro', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('rischio_abbandono', models.PositiveSmallIntegerField(blank=True, help_text='Scala 1-10.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('giudizio_finale', models.CharField(blank=True, choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], db_index=True, default='', max_length=10)),
                ('data_secondo_colloquio', models.DateField(blank=True, null=True)),
                ('note_secondo_colloquio', models.TextField(blank=True, default='')),
                ('comunicazione_esito', models.CharField(blank=True, choices=[('SI', 'Esito comunicato'), ('NO', 'Non comunicato'), ('ACADEMY', 'Indirizzato ad academy'), ('RINUNCIA', 'Rinuncia del candidato')], default='', max_length=12)),
                ('data_assunzione', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('NUOVO', 'Nuovo (CV ricevuto)'), ('CV_VALUTATO', 'CV valutato'), ('COLLOQUIO_1', 'Primo colloquio effettuato'), ('COLLOQUIO_2', 'Secondo colloquio effettuato'), ('ASSUNTO', 'Assunto'), ('IN_DATABASE', 'In database per future opportunità'), ('SCARTATO', 'Non idoneo'), ('RINUNCIA', 'Rinuncia del candidato')], db_index=True, default='NUOVO', max_length=16)),
                ('legacy_anagrafica_id', models.IntegerField(blank=True, db_index=True, help_text='Id del dipendente creato in anagrafica quando il candidato viene assunto.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidati_creati', to=settings.AUTH_USER_MODEL)),
                ('onboarding_pratica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidati_recruiting', to='anagrafica.onboardingpratica')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidati_aggiornati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidato (Recruiting)',
                'verbose_name_plural': 'Candidati (Recruiting)',
                'ordering': ['-created_at', 'cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CandidatoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PUNTEGGIO', 'Punteggio criterio'), ('GIUDIZIO', 'Giudizio finale'), ('STATO', "Stato dell'iter")], db_index=True, max_length=12)),
                ('campo', models.CharField(max_length=120)),
                ('valore_prima', models.CharField(blank=True, default='', max_length=255)),
                ('valore_dopo', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('user_display', models.CharField(blank=True, default='', max_length=160)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_modifiche', to='anagrafica.candidato')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modifica tracciata (Recruiting)',
                'verbose_name_plural': 'Modifiche tracciate (Recruiting)',
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CandidatoPunteggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('peso_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punteggi', to='anagrafica.candidato')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punteggi', to='anagrafica.recruitingcriterio')),
            ],
            options={
                'verbose_name': 'Punteggio criterio (Recruiting)',
                'verbose_name_plural': 'Punteggi criteri (Recruiting)',
                'ordering': ['criterio__ordine', 'criterio__label'],
            },
        ),
        migrations.AddIndex(
            model_name='candidato',
            index=models.Index(fields=['stato', '-created_at'], name='recr_cand_stato_idx'),
        ),
        migrations.AddIndex(
            model_name='candidato',
            index=models.Index(fields=['cognome', 'nome'], name='recr_cand_nome_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidatopunteggio',
            constraint=models.UniqueConstraint(fields=('candidato', 'criterio'), name='recr_punteggio_unico_per_criterio'),
        ),
    ]
