# Generated by Django 5.2.11 on 2026-07-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0086_visitasessione_visitamedica_sessione'),
    ]

    operations = [
        migrations.AddField(
            model_name='esposizionerischio',
            name='legacy_anagrafica_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Esposizione assegnata direttamente a un singolo dipendente (1.9).', null=True),
        ),
        migrations.AddIndex(
            model_name='esposizionerischio',
            index=models.Index(fields=['legacy_anagrafica_id', 'is_active'], name='anagrafica__legacy__66efe9_idx'),
        ),
    ]
