# Generated by Django 5.2.13 on 2026-07-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0086_visitasessione_visitamedica_sessione'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagraficahrpermission',
            name='utente_ids',
            field=models.JSONField(blank=True, default=list, help_text='Lista UtenteLegacy.id sempre abilitati (concessione additiva a admin/ruoli)'),
        ),
        migrations.AddField(
            model_name='anagraficastatpermission',
            name='utente_ids',
            field=models.JSONField(blank=True, default=list, help_text='Lista UtenteLegacy.id sempre abilitati (concessione additiva a admin/ruoli)'),
        ),
        migrations.AddField(
            model_name='anagraficavisitemedichepermission',
            name='utente_ids',
            field=models.JSONField(blank=True, default=list, help_text='Lista UtenteLegacy.id sempre abilitati (concessione additiva a admin/ruoli)'),
        ),
    ]
