# Generated by Django 5.2.11 on 2026-07-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0089_subnav_recruiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='codice_riferimento',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cognome',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='stato',
            field=models.CharField(choices=[('NUOVO', 'Nuovo (CV ricevuto)'), ('CV_VALUTATO', 'CV valutato'), ('COLLOQUIO_1', 'Primo colloquio effettuato'), ('COLLOQUIO_2', 'Secondo colloquio effettuato'), ('ASSUNTO', 'Assunto'), ('IN_DATABASE', 'In database per future opportunità'), ('SCARTATO', 'Non idoneo'), ('RINUNCIA', 'Rinuncia del candidato'), ('ANNULLATO', 'Annullato / archiviato')], db_index=True, default='NUOVO', max_length=16),
        ),
    ]
