# Generated by Django 5.2.11 on 2026-07-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0087_esposizionerischio_legacy_anagrafica_id_and_more'),
        ('anagrafica', '0089_subnav_recruiting'),
    ]

    operations = [
    ]
