# Generated by Django 5.2.11 on 2026-07-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0090_merge_20260723_0952'),
        ('anagrafica', '0090_recruiting_lifecycle'),
    ]

    operations = [
    ]
