# Generated by Django 5.2.11 on 2026-07-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0087_anagraficahrpermission_utente_ids_and_more'),
        ('anagrafica', '0091_merge_20260723_1122'),
    ]

    operations = [
    ]
