# Generated by Django 5.2.11 on 2026-07-24 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0092_merge_20260723_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoQualifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('audit', 'Audit'), ('corso', 'Corso/Formazione'), ('certificato', 'Certificato'), ('esame', 'Esame'), ('esperienza', 'Esperienza'), ('visione', 'Test visivo'), ('dpi', 'DPI'), ('rif_normativo', 'Riferimento normativo'), ('altro', 'Altro')], default='altro', max_length=16)),
                ('descrizione', models.CharField(max_length=255)),
                ('obbligatorio', models.BooleanField(default=True, help_text="Se falso, la voce è informativa e non degrada l'esito.")),
                ('rif_normativo', models.CharField(blank=True, default='', max_length=200)),
                ('stato', models.CharField(choices=[('DA_VERIFICARE', 'Da verificare'), ('SODDISFATTO', 'Soddisfatto'), ('SCADUTO', 'Scaduto'), ('NON_APPLICABILE', 'Non applicabile')], db_index=True, default='DA_VERIFICARE', max_length=16)),
                ('data_conseguimento', models.DateField(blank=True, null=True)),
                ('periodicita_mesi', models.PositiveSmallIntegerField(blank=True, help_text='Ricorrenza in mesi (vuoto = una tantum).', null=True)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('evidenza_url', models.CharField(blank=True, default='', help_text="Link/riferimento all'evidenza (documento, registro, attestato).", max_length=500)),
                ('note', models.TextField(blank=True, default='')),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiti', to='anagrafica.processoqualificato')),
                ('tipo_qualifica', models.ForeignKey(blank=True, help_text='Tipo qualifica di catalogo collegato (opzionale).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiti_catalogo', to='anagrafica.tipoqualifica')),
            ],
            options={
                'verbose_name': 'Requisito qualifica (MPQ)',
                'verbose_name_plural': 'Requisiti qualifica (MPQ)',
                'ordering': ['processo', 'ordine', 'id'],
            },
        ),
    ]
