# Generated by Django 5.2.11 on 2026-07-24 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0093_requisitoqualifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenzaskm',
            name='corso_qualificante',
            field=models.ForeignKey(blank=True, help_text='Corso richiesto per superare il livello «In formazione» (I→L).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competenze_qualificate', to='anagrafica.trainingcourse'),
        ),
    ]
