# Generated by Django 5.2.11 on 2026-07-24 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0094_competenzaskm_corso_qualificante'),
        ('assets', '0085_repoint_work_machines_sidebar_to_asset_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='SogliaCopertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descrizione_ambito', models.CharField(blank=True, default='', help_text='Ambito libero (ruolo/processo critico) quando non è un asset/processo.', max_length=200)),
                ('livello_minimo', models.CharField(choices=[('I', 'In formazione'), ('L', 'Intermedio'), ('U', 'Autonomo'), ('O', 'Formatore/Esperto')], default='U', help_text='Livello minimo (≥) che conta come «coperto» (solo per soglie su asset).', max_length=1)),
                ('minimo_abilitati', models.PositiveSmallIntegerField(default=2, help_text='Numero minimo di persone abilitate richiesto.')),
                ('certificazione', models.CharField(blank=True, default='', help_text='Certificazione/standard di riferimento (es. «AS/EN 9100», «NADCAP AC7101»).', max_length=150)),
                ('rif_normativo', models.CharField(blank=True, default='', max_length=200)),
                ('attiva', models.BooleanField(default=True)),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soglie_copertura', to='assets.asset')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soglie_copertura', to='anagrafica.processoqualificato')),
            ],
            options={
                'verbose_name': 'Soglia copertura minima',
                'verbose_name_plural': 'Soglie copertura minima',
                'ordering': ['ordine', 'nome'],
            },
        ),
    ]
