# Generated by Django 5.2.16 on 2026-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0095_sogliacopertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglesson',
            name='pausa_minuti',
            field=models.PositiveSmallIntegerField(default=0, help_text="Minuti di interruzione non formativa (pausa pranzo, intervalli) da scalare dalla durata. Es. 08:00–17:00 con 60' di pausa = 8 ore formative."),
        ),
    ]
