# Generated by Django 5.2.16 on 2026-07-30 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0096_traininglesson_pausa_minuti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='edizione',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Etichetta libera che collega più sessioni della stessa erogazione del corso: un corso diviso in più gruppi per motivi logistici (stesso programma, iscritti diversi), o lo stesso corso ripetuto nel tempo. Vuota = sessione autonoma, non collegata ad altre. Vedi services.formazione_pianificazione.dividi_in_gruppi.', max_length=80),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['corso', 'edizione'], name='anagrafica__corso_i_de3bba_idx'),
        ),
    ]
