# Generated by Django 5.2.16 on 2026-07-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0097_trainingsession_edizione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dipendentecambiamentoorganizzativo',
            name='tipo',
            field=models.CharField(choices=[('MANSIONE', 'Mansione'), ('REPARTO', 'Reparto (legacy)'), ('AREA', 'Reparto'), ('RUOLO_AZIENDALE', 'Ruolo aziendale'), ('MATRICOLA', 'Matricola')], db_index=True, max_length=30),
        ),
    ]
