# Generated by Django 5.2.16 on 2026-08-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0098_alter_dipendentecambiamentoorganizzativo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='articolo_fonte',
            field=models.CharField(blank=True, default='', help_text='Punto specifico, se utile: es. «art. 37 c. 2», «§ 4.3».', max_length=100),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='fonte_obbligo',
            field=models.CharField(blank=True, choices=[('LEGGE', 'Norma di legge'), ('ACCORDO', 'Accordo Stato-Regioni'), ('CLIENTE', 'Specifica cliente'), ('NORMA', 'Norma di sistema (ISO, EN, AS…)'), ('INTERNO', 'Decisione interna')], db_index=True, default='', help_text="Da cosa discende l'obbligo di questo corso. Lasciare vuoto se non pertinente.", max_length=12),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='riferimento_fonte',
            field=models.CharField(blank=True, default='', help_text='Estremi della fonte: es. «D.Lgs 81/08», «Accordo Stato-Regioni 21/12/2011», «Avio 9070Q».', max_length=200),
        ),
    ]
