# Generated by Django 5.2.16 on 2026-08-05 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0099_trainingcourse_articolo_fonte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourseArgomento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
                ('argomento', models.CharField(max_length=300)),
                ('ore_previste', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('riferimento', models.CharField(blank=True, default='', help_text='Punto della fonte che impone il contenuto: es. «Allegato A, punto 3».', max_length=200)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programma', to='anagrafica.trainingcourse')),
            ],
            options={
                'verbose_name': 'Argomento del corso',
                'verbose_name_plural': 'Programma del corso',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSessionArgomento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
                ('argomento', models.CharField(max_length=300)),
                ('ore_previste', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('riferimento', models.CharField(blank=True, default='', max_length=200)),
                ('aggiunto', models.BooleanField(default=False, help_text="Vero se l'edizione ha integrato un argomento non previsto dal corso.")),
                ('origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='anagrafica.trainingcourseargomento')),
                ('sessione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programma', to='anagrafica.trainingsession')),
            ],
            options={
                'verbose_name': "Argomento dell'edizione",
                'verbose_name_plural': "Programma dell'edizione",
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.AddField(
            model_name='traininglesson',
            name='argomenti_svolti',
            field=models.ManyToManyField(blank=True, related_name='lezioni', to='anagrafica.trainingsessionargomento', verbose_name='Argomenti del programma svolti'),
        ),
    ]
