# Generated by Django 5.2.16 on 2026-08-05 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0100_trainingcourseargomento_trainingsessionargomento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='valutazione_efficacia_mesi',
            field=models.PositiveSmallIntegerField(default=0, help_text='Dopo quanti mesi dal completamento va verificato sul campo se la formazione è stata efficace. 0 = valutazione non richiesta.'),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='modalita_verifica',
            field=models.CharField(blank=True, choices=[('TEST', 'Test scritto'), ('ORALE', 'Colloquio orale'), ('PRATICA', 'Prova pratica'), ('OSSERVAZIONE', 'Osservazione sul campo')], default='', help_text="Come è stato verificato l'apprendimento.", max_length=12),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='punteggio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Punteggio conseguito, in percentuale.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='punteggio_minimo',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Soglia applicata a questa verifica. Serve a rileggere l'esito anni dopo con il criterio di allora, non con quello di oggi.", null=True),
        ),
        migrations.CreateModel(
            name='TrainingEfficacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('attesa_dal', models.DateField(db_index=True, help_text='Data dalla quale la valutazione è dovuta (completamento + mesi previsti).')),
                ('valutata_il', models.DateField(blank=True, null=True)),
                ('valutatore_nome', models.CharField(blank=True, default='', help_text="Snapshot di chi ha valutato: resta leggibile anche se l'utenza sparisce.", max_length=200)),
                ('esito', models.CharField(blank=True, choices=[('EFFICACE', 'Efficace'), ('PARZIALE', 'Parzialmente efficace'), ('NON_EFFICACE', 'Non efficace')], default='', max_length=14)),
                ('azione', models.TextField(blank=True, help_text="Cosa si è deciso di fare quando l'esito non è pieno: affiancamento, ripetizione, cambio mansione.")),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valutazioni_efficacia', to='anagrafica.trainingemployeerecord')),
                ('valutata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valutazione di efficacia',
                'verbose_name_plural': 'Valutazioni di efficacia',
                'ordering': ['attesa_dal', 'id'],
                'indexes': [models.Index(fields=['legacy_anagrafica_id', 'attesa_dal'], name='anagrafica__legacy__70a7b1_idx'), models.Index(fields=['esito'], name='anagrafica__esito_eba6d6_idx')],
            },
        ),
    ]
