# Generated by Django 5.2.16 on 2026-08-05 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0101_trainingcompletionrule_valutazione_efficacia_mesi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSignatureSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Identificativo stampato nel QR: riaggancia la scansione alla giornata senza che nessuno debba sceglierla a mano.', max_length=16, unique=True)),
                ('stato', models.CharField(choices=[('EMESSO', 'Emesso'), ('ACQUISITO', 'Scansione acquisita'), ('ANNULLATO', 'Annullato')], default='EMESSO', max_length=10)),
                ('righe', models.JSONField(blank=True, default=list, help_text='Elenco congelato alla stampa: [{n, legacy_id, nome}]. È ciò che rende la riga 7 della scansione la stessa persona di allora.')),
                ('geometria', models.JSONField(blank=True, default=dict, help_text="Posizione in mm delle celle firma sulla pagina, dall'angolo in alto a sinistra. Serve a leggere la scansione senza interpretare la scrittura.")),
                ('emesso_il', models.DateTimeField(auto_now_add=True)),
                ('acquisito_il', models.DateTimeField(blank=True, null=True)),
                ('emesso_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fogli_firme', to='anagrafica.traininglesson')),
                ('scansione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fogli_firme', to='anagrafica.trainingattachment')),
            ],
            options={
                'verbose_name': 'Foglio firme emesso',
                'verbose_name_plural': 'Fogli firme emessi',
                'ordering': ['-emesso_il', '-id'],
                'indexes': [models.Index(fields=['lezione', 'stato'], name='anagrafica__lezione_ee89b1_idx')],
            },
        ),
    ]
