# Generated by Django 5.2.16 on 2026-08-05 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0102_trainingsignaturesheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_file', models.CharField(blank=True, default='', max_length=255)),
                ('percorso', models.CharField(blank=True, default='', help_text="Dove è stato archiviato il file caricato, relativo allo storage privato dell'anagrafica.", max_length=500)),
                ('dimensione', models.PositiveIntegerField(default=0, help_text='Byte del file caricato.')),
                ('token_digitato', models.CharField(blank=True, default='', max_length=16)),
                ('token_letto', models.CharField(blank=True, default='', help_text="Token decodificato dal QR. Vuoto se il codice non è stato letto e l'operatore ha digitato a mano.", max_length=16)),
                ('esito', models.CharField(choices=[('OK', 'Letto'), ('ERRORE', 'Errore di lettura'), ('RIFIUTATO', 'Foglio non riconosciuto')], default='OK', max_length=10)),
                ('origine', models.CharField(choices=[('WEB', 'Caricamento dalla pagina'), ('CARTELLA', 'Cartella di acquisizione')], default='WEB', max_length=10)),
                ('messaggio', models.TextField(blank=True, default='', help_text="Motivo dell'errore, nelle stesse parole mostrate a chi ha caricato.")),
                ('n_righe', models.PositiveIntegerField(default=0)),
                ('n_firmati', models.PositiveIntegerField(default=0)),
                ('n_dubbie', models.PositiveIntegerField(default=0)),
                ('inclinazione', models.DecimalField(blank=True, decimal_places=2, help_text='Gradi di rotazione rilevati nella scansione.', max_digits=5, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('foglio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letture', to='anagrafica.trainingsignaturesheet')),
                ('lezione', models.ForeignKey(blank=True, help_text='Vuoto quando il foglio non è stato riconosciuto: il file resta comunque archiviato e ispezionabile.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scansioni_log', to='anagrafica.traininglesson')),
            ],
            options={
                'verbose_name': 'Lettura di scansione',
                'verbose_name_plural': 'Registro letture scansioni',
                'ordering': ['-creato_il', '-id'],
                'indexes': [models.Index(fields=['esito', '-creato_il'], name='anagrafica__esito_d67191_idx'), models.Index(fields=['lezione', '-creato_il'], name='anagrafica__lezione_706338_idx')],
            },
        ),
    ]
