# Generated by Django 5.2.16 on 2026-08-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0103_trainingscanlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingScanIntakeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attiva', models.BooleanField(default=False, help_text='Se spenta, il lavoro periodico non guarda la cartella. La lettura dalla pagina continua a funzionare comunque.')),
                ('cartella', models.CharField(blank=True, default='\\\\pclogsys\\PortaleNovicrom\\scansioni\\formazione', help_text="Percorso UNC della cartella dove la fotocopiatrice deposita le scansioni. Deve essere raggiungibile dall'utente con cui gira l'applicazione: una lettera di unità mappata non è visibile a un servizio.", max_length=500)),
                ('sposta_elaborati', models.BooleanField(default=True, help_text='Sposta i file letti in «elaborati» e quelli non riusciti in «errori», così la cartella di ingresso resta pulita e nulla viene riletto due volte.')),
                ('max_file_per_giro', models.PositiveIntegerField(default=25, help_text='Quanti file al massimo elaborare a ogni passaggio: un arretrato enorme non deve bloccare il lavoro periodico.')),
                ('conferma_automatica', models.BooleanField(default=False, help_text='Se accesa, una lettura pulita registra le presenze da sé senza attendere conferma. Da valutare con attenzione: la presenza a un corso è un atto con valore legale.')),
                ('auto_solo_senza_dubbie', models.BooleanField(default=True, help_text="Con la conferma automatica accesa, ferma comunque i fogli che hanno celle dubbie. Toglierla significa accettare che un segno incerto diventi una presenza senza che nessuno l'abbia guardato.")),
                ('auto_solo_se_tutti_firmati', models.BooleanField(default=False, help_text='Registra da sé solo se ogni iscritto atteso risulta firmato. Utile per accorgersi dei fogli letti a metà.')),
                ('ultima_esecuzione', models.DateTimeField(blank=True, null=True)),
                ('ultimo_esito', models.TextField(blank=True, default='', help_text="Riepilogo dell'ultimo passaggio, per capire dalla pagina se il meccanismo sta girando davvero.")),
            ],
            options={
                'verbose_name': 'Acquisizione scansioni da cartella',
                'verbose_name_plural': 'Acquisizione scansioni da cartella',
            },
        ),
        migrations.AddField(
            model_name='trainingscanlog',
            name='presenze_scritte',
            field=models.PositiveIntegerField(default=0, help_text='Presenze registrate automaticamente da questa lettura. Zero quando la conferma è rimasta a una persona, che è il comportamento normale.'),
        ),
    ]
