# Generated by Django 5.2.16 on 2026-08-07 06:37

import datetime

from django.db import migrations, models


def chiudi_periodi_storici(apps, schema_editor):
    """Backfill: le righe già presenti sono eventi di transizione senza data di fine.

    Per ogni (dipendente, tipo) le si ordina cronologicamente e si chiude ciascuna
    al giorno prima dell'inizio della successiva; l'ultima resta aperta (in corso).
    """
    Cambiamento = apps.get_model("anagrafica", "DipendenteCambiamentoOrganizzativo")
    righe = Cambiamento.objects.order_by(
        "legacy_anagrafica_id", "tipo", "data_effetto", "created_at"
    ).only("id", "legacy_anagrafica_id", "tipo", "data_effetto", "data_fine")

    da_aggiornare = []
    precedente = None
    for riga in righe.iterator(chunk_size=500):
        if (
            precedente is not None
            and precedente.legacy_anagrafica_id == riga.legacy_anagrafica_id
            and precedente.tipo == riga.tipo
        ):
            fine = riga.data_effetto - datetime.timedelta(days=1)
            if fine < precedente.data_effetto:
                fine = precedente.data_effetto
            precedente.data_fine = fine
            da_aggiornare.append(precedente)
        precedente = riga

    for i in range(0, len(da_aggiornare), 500):
        Cambiamento.objects.bulk_update(da_aggiornare[i:i + 500], ["data_fine"])


def riapri_periodi_storici(apps, schema_editor):
    """Reverse: il campo viene rimosso subito dopo, basta azzerarlo."""
    Cambiamento = apps.get_model("anagrafica", "DipendenteCambiamentoOrganizzativo")
    Cambiamento.objects.update(data_fine=None)


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0104_trainingscanintakeconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendentecambiamentoorganizzativo',
            name='data_fine',
            field=models.DateField(blank=True, help_text='Ultimo giorno in cui il valore è stato in vigore. Vuoto = assegnazione in corso.', null=True, verbose_name='Data fine'),
        ),
        migrations.AlterField(
            model_name='dipendentecambiamentoorganizzativo',
            name='data_effetto',
            field=models.DateField(help_text='Data da cui vale il nuovo valore (default: oggi)', verbose_name='Data inizio'),
        ),
        migrations.AlterField(
            model_name='dipendentecambiamentoorganizzativo',
            name='tipo',
            field=models.CharField(choices=[('MANSIONE', 'Mansione'), ('REPARTO', 'Reparto (legacy)'), ('AREA', 'Reparto'), ('AREA_AZIENDALE', 'Area aziendale'), ('RUOLO_AZIENDALE', 'Ruolo aziendale'), ('MATRICOLA', 'Matricola')], db_index=True, max_length=30),
        ),
        migrations.RunPython(chiudi_periodi_storici, riapri_periodi_storici),
    ]
