# Generated by Django 5.2.16 on 2026-08-06 21:09

import anagrafica.models_sorveglianza
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0105_dipendentecambiamentoorganizzativo_data_fine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasEsitoIdoneita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(help_text='Il giudizio come compare sul certificato, confrontato normalizzato.', max_length=200, unique=True)),
                ('esito', models.CharField(choices=anagrafica.models_sorveglianza._esiti_idoneita, max_length=20)),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alias esito di idoneità',
                'verbose_name_plural': 'Alias esiti di idoneità',
                'ordering': ['testo'],
            },
        ),
        migrations.CreateModel(
            name='RefertoIntakeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attiva', models.BooleanField(default=False, help_text='Se spenta, il lavoro periodico non guarda la cartella. Il caricamento dalla pagina continua a funzionare comunque.')),
                ('cartella', models.CharField(blank=True, default='\\\\pclogsys\\PortaleNovicrom\\scansioni\\referti', help_text="Percorso UNC dove la fotocopiatrice deposita le scansioni dei referti. Deve essere raggiungibile dall'utente con cui gira l'applicazione: una lettera di unità mappata non è visibile a un servizio.", max_length=500)),
                ('sposta_elaborati', models.BooleanField(default=True, help_text="Sposta i file letti in «elaborati» e quelli non riusciti in «errori», così la cartella d'ingresso resta pulita e niente viene riletto due volte.")),
                ('max_file_per_giro', models.PositiveIntegerField(default=25, help_text='Quanti file al massimo per passaggio: un arretrato grosso non deve bloccare il lavoro periodico. A ~2 secondi per referto, 25 file sono meno di un minuto.')),
                ('ocr_dpi', models.PositiveSmallIntegerField(default=200, help_text='Risoluzione di rasterizzazione della pagina. 200 è il valore misurato come migliore: le scansioni arrivano a ~150 dpi nativi e salire non aggiunge dettaglio, amplifica il rumore.')),
                ('ocr_psm', models.PositiveSmallIntegerField(default=6, help_text='Modalità di segmentazione della pagina di Tesseract. 6 tratta la pagina come un blocco uniforme e mantiene appaiate le colonne del protocollo sanitario; 11 le distrugge sistematicamente.')),
                ('ocr_lingua', models.CharField(default='ita', help_text='Pacchetto lingua di Tesseract.', max_length=20)),
                ('ocr_timeout_secondi', models.PositiveSmallIntegerField(default=30, help_text='Oltre questo tempo il singolo file va in errore e il giro prosegue: una pagina patologica non deve fermare tutte le altre.')),
                ('soglia_con_data_nascita', models.PositiveSmallIntegerField(default=70, help_text='Somiglianza minima del nominativo (0-100) quando la data di nascita letta coincide con quella in anagrafica. Può essere bassa: a confermare non è il nome, è la data.')),
                ('soglia_senza_data_nascita', models.PositiveSmallIntegerField(default=92, help_text='Somiglianza minima quando la data di nascita non è leggibile. Alta di proposito, e comunque valida solo con un unico candidato.')),
                ('conferma_automatica', models.BooleanField(default=False, help_text='Se accesa, un riconoscimento pulito registra le visite da sé. Anche accesa si ferma davanti a data di nascita discordante, candidati multipli, dipendente cessato, esame non a catalogo o nominativo letto dal riconoscimento di ripiego.')),
                ('ultima_esecuzione', models.DateTimeField(blank=True, null=True)),
                ('ultimo_esito', models.TextField(blank=True, default='', help_text="Riepilogo dell'ultimo passaggio, per capire dalla pagina se il meccanismo sta girando davvero.")),
            ],
            options={
                'verbose_name': 'Acquisizione referti sanitari',
                'verbose_name_plural': 'Acquisizione referti sanitari',
            },
        ),
        migrations.CreateModel(
            name='AliasEsameProtocollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(help_text='Il testo come compare sul certificato. Il confronto avviene normalizzato (maiuscole, accenti e spazi non contano).', max_length=200, unique=True)),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_intake', to='anagrafica.tipovisitamedica')),
            ],
            options={
                'verbose_name': 'Alias esame del protocollo',
                'verbose_name_plural': 'Alias esami del protocollo',
                'ordering': ['testo'],
            },
        ),
        migrations.CreateModel(
            name='RefertoIntakeRiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_file', models.CharField(blank=True, default='', max_length=255)),
                ('percorso', models.CharField(blank=True, default='', help_text="Dove è stato archiviato, relativo allo storage privato cifrato dell'anagrafica.", max_length=500)),
                ('dimensione', models.PositiveIntegerField(default=0, help_text='Byte del file.')),
                ('sha256', models.CharField(blank=True, db_index=True, default='', help_text='Impronta del contenuto: è così che lo stesso file ricaricato viene riconosciuto invece di essere rielaborato.', max_length=64)),
                ('pagina', models.PositiveSmallIntegerField(default=1, help_text="Quale pagina del PDF, per le scansioni che ne contengono più d'una: una pagina con blocco anagrafico è un certificato a sé.")),
                ('origine', models.CharField(choices=[('WEB', 'Caricamento dalla pagina'), ('CARTELLA', 'Cartella di acquisizione')], default='WEB', max_length=10)),
                ('esito', models.CharField(choices=[('OK', 'Registrato'), ('DA_RIVEDERE', 'Da rivedere'), ('DUPLICATO', 'Già presente'), ('RIFIUTATO', 'Non riconosciuto'), ('ERRORE', 'Errore di lettura'), ('SCARTATO', 'Scartato a mano')], db_index=True, default='DA_RIVEDERE', max_length=15)),
                ('messaggio', models.TextField(blank=True, default='', help_text='Perché è finito in questo stato, in parole leggibili da chi revisiona.')),
                ('letto_nominativo', models.CharField(blank=True, default='', max_length=200)),
                ('letto_data_nascita', models.DateField(blank=True, null=True)),
                ('letto_data_giudizio', models.DateField(blank=True, null=True)),
                ('letto_esito_testo', models.CharField(blank=True, default='', help_text="Il giudizio così com'è scritto sul certificato, prima della traduzione in codice.", max_length=200)),
                ('letto_mansione', models.CharField(blank=True, default='', max_length=200)),
                ('letto_protocollo', models.JSONField(blank=True, default=list, help_text="Esami del protocollo sanitario con la periodicità dichiarata: [{'esame': ..., 'periodicita': ...}]. Un certificato ne porta più d'uno.")),
                ('date_trovate', models.JSONField(blank=True, default=list, help_text="Tutte le occorrenze di data trovate nel documento. La data del giudizio si decide per consenso fra queste: l'OCR ne corrompe una ogni tanto, e le altre la salvano.")),
                ('nominativo_da_ripiego', models.BooleanField(default=False, help_text='Il nome viene dalla riga di firma invece che dal blocco anagrafico. Quella riga è attraversata dalla firma autografa e restituisce nomi verosimili ma sbagliati: una riga così non si conferma mai da sé.')),
                ('legacy_anagrafica_id_proposto', models.IntegerField(blank=True, db_index=True, null=True)),
                ('punteggio', models.PositiveSmallIntegerField(default=0, help_text='Somiglianza del nominativo col candidato proposto (0-100).')),
                ('data_nascita_conferma', models.BooleanField(default=False, help_text='La data di nascita letta coincide con quella in anagrafica. È la vera garanzia del riconoscimento, molto più della somiglianza del nome.')),
                ('candidati', models.JSONField(blank=True, default=list, help_text="Gli altri candidati sopra soglia, per chi revisiona: [{'legacy_id': ..., 'nominativo': ..., 'punteggio': ...}].")),
                ('divergenze', models.JSONField(blank=True, default=list, help_text='Scostamenti fra il certificato e il catalogo (tipicamente la periodicità dichiarata dal medico). Non bloccano, ma devono arrivare sotto gli occhi di qualcuno invece di essere sovrascritti.')),
                ('visite_create', models.PositiveSmallIntegerField(default=0, help_text='Quante VisitaMedica sono nate da questa riga: un certificato porta un intero protocollo, non una visita sola.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confermato_il', models.DateTimeField(blank=True, null=True)),
                ('confermato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referti_intake_confermati', to=settings.AUTH_USER_MODEL)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referti_intake_caricati', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(blank=True, help_text='Il referto archiviato nel fascicolo del dipendente, condiviso da tutte le visite nate da questo certificato.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='anagrafica.documentodipendente')),
            ],
            options={
                'verbose_name': 'Referto acquisito',
                'verbose_name_plural': 'Referti acquisiti',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['esito', '-created_at'], name='anagrafica__esito_4a2ff9_idx'), models.Index(fields=['legacy_anagrafica_id_proposto', 'letto_data_giudizio'], name='anagrafica__legacy__6d9c27_idx')],
            },
        ),
    ]
