# Generated by Django 5.2.16 on 2026-08-07 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0107_subnav_referti_sanitari'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DipendenteAssegnazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('data_inizio', models.DateField(verbose_name='Data inizio')),
                ('data_fine', models.DateField(blank=True, help_text='Vuoto = assegnazione senza termine (chiusa dallo spostamento successivo).', null=True, verbose_name='Data fine')),
                ('reparto', models.CharField(blank=True, default='', max_length=200, verbose_name='Reparto')),
                ('mansione', models.CharField(blank=True, default='', max_length=200, verbose_name='Mansione')),
                ('ruolo_aziendale', models.CharField(blank=True, default='', max_length=200, verbose_name='Ruolo aziendale')),
                ('attivata_il', models.DateTimeField(blank=True, help_text='Momento in cui i campi vivi del dipendente sono stati allineati.', null=True)),
                ('idoneita_esito', models.CharField(blank=True, default='', help_text='Esito della verifica competenze/DPI/visite al momento della registrazione.', max_length=10)),
                ('idoneita_mancanti', models.JSONField(blank=True, default=list)),
                ('idoneita_scaduti', models.JSONField(blank=True, default=list)),
                ('idoneita_verificata_il', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area_aziendale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assegnazioni', to='anagrafica.areaaziendale', verbose_name='Area aziendale')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assegnazioni_registrate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assegnazione organizzativa',
                'verbose_name_plural': 'Assegnazioni organizzative',
                'ordering': ['-data_inizio', '-created_at'],
                'indexes': [models.Index(fields=['legacy_anagrafica_id', '-data_inizio'], name='anagrafica__legacy__9c9f09_idx'), models.Index(fields=['attivata_il', 'data_inizio'], name='anagrafica__attivat_1a47be_idx')],
            },
        ),
    ]
