# Generated by Django 5.2.16 on 2026-08-07 15:35

import anagrafica.models_sorveglianza
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0108_dipendenteassegnazione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aliasesameprotocollo',
            options={'ordering': ['testo', 'periodicita'], 'verbose_name': 'Alias esame del protocollo', 'verbose_name_plural': 'Alias esami del protocollo'},
        ),
        migrations.AddField(
            model_name='aliasesameprotocollo',
            name='periodicita',
            field=models.CharField(blank=True, choices=anagrafica.models_sorveglianza._periodicita_note, default='', help_text="La cadenza dichiarata accanto all'esame sul certificato. Vuota = vale per qualsiasi cadenza (ripiego, usato solo se non c'è una riga con la periodicità esatta).", max_length=20),
        ),
        migrations.AlterField(
            model_name='aliasesameprotocollo',
            name='testo',
            field=models.CharField(help_text='Il testo come compare sul certificato. Il confronto avviene normalizzato (maiuscole, accenti e spazi non contano).', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='aliasesameprotocollo',
            constraint=models.UniqueConstraint(fields=('testo', 'periodicita'), name='uniq_alias_esame_testo_periodicita'),
        ),
    ]
