# Generated by Django 5.2.16 on 2026-08-26 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0110_riallinea_ruoli_aziendali_residui'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendenteruolooperativo',
            name='data_fine',
            field=models.DateField(blank=True, help_text='Data di fine. Vuota = ruolo in essere.', null=True, verbose_name='A'),
        ),
        migrations.AddField(
            model_name='dipendenteruolooperativo',
            name='data_inizio',
            field=models.DateField(blank=True, help_text='Data di decorrenza del ruolo. Vuota = non nota.', null=True, verbose_name='Da'),
        ),
        migrations.AddField(
            model_name='dipendenteruolooperativo',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('PRINCIPALE', 'Principale'), ('SECONDARIO', 'Secondario'), ('AD_INTERIM', 'Ad interim')], default='', help_text='Principale = è anche il «Ruolo aziendale» della scheda.', max_length=20, verbose_name='Tipologia associazione'),
        ),
        migrations.CreateModel(
            name='RuoloQualifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livello', models.CharField(blank=True, default='', help_text='Livello atteso, se il ruolo lo distingue (es. «Base», «2», «Esperto»).', max_length=50)),
                ('obbligatoria', models.BooleanField(default=True, help_text='Se attiva, la qualifica è un requisito; altrimenti è preferenziale.')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qualifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruoli_che_la_richiedono', to='anagrafica.tipoqualifica')),
                ('ruolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifiche_richieste', to='anagrafica.ruolooperativo')),
            ],
            options={
                'verbose_name': 'Qualifica richiesta dal ruolo',
                'verbose_name_plural': 'Qualifiche richieste dai ruoli',
                'ordering': ['qualifica__nome'],
                'unique_together': {('ruolo', 'qualifica')},
            },
        ),
    ]
