# Generated by Django 5.2.16 on 2026-08-27 13:42

import django.db.models.deletion
from django.db import migrations, models


def _promuovi_ragioni_sociali(apps, schema_editor):
    """Le ragioni sociali già digitate diventano aziende formative a catalogo.

    Il testo libero resta sul docente (dato storico), ma da qui in poi l'ente è
    un'entità sola: due docenti della stessa società puntano allo stesso record
    invece di riscriverne due varianti. Il raggruppamento è per nome normalizzato
    (spazi collassati, confronto case-insensitive) e la grafia vincente è la prima
    in ordine alfabetico, così l'esito non dipende dagli id.
    """
    TrainingProvider = apps.get_model("anagrafica", "TrainingProvider")
    TrainingInstructor = apps.get_model("anagrafica", "TrainingInstructor")

    gruppi: dict[str, list] = {}
    for istr in TrainingInstructor.objects.exclude(ragione_sociale="").exclude(ragione_sociale=None):
        nome = " ".join((istr.ragione_sociale or "").split())
        if not nome:
            continue
        gruppi.setdefault(nome.casefold(), []).append((nome, istr.pk))

    for varianti in gruppi.values():
        canonico = sorted({n for n, _ in varianti})[0]
        provider, _ = TrainingProvider.objects.get_or_create(nome=canonico)
        TrainingInstructor.objects.filter(pk__in=[pk for _, pk in varianti]).update(azienda=provider)


def _rimuovi_aziende(apps, schema_editor):
    """Rollback: il testo libero è rimasto sul docente, basta svuotare il catalogo."""
    apps.get_model("anagrafica", "TrainingInstructor").objects.update(azienda=None)
    apps.get_model("anagrafica", "TrainingProvider").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0113_assegnazione_ruolo_parallelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, unique=True, verbose_name='Ragione sociale')),
                ('partita_iva', models.CharField(blank=True, max_length=20, verbose_name='Partita IVA / C.F.')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('sito_web', models.CharField(blank=True, max_length=200)),
                ('indirizzo', models.CharField(blank=True, max_length=300)),
                ('accreditamento', models.CharField(blank=True, help_text='Estremi di accreditamento / albo (es. accreditamento regionale, n° iscrizione)', max_length=200)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Azienda formativa',
                'verbose_name_plural': 'Aziende formative',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='traininginstructor',
            name='ragione_sociale',
            field=models.CharField(blank=True, help_text="Ragione sociale libera: usata solo se l'azienda formativa non è a catalogo", max_length=300),
        ),
        migrations.AddField(
            model_name='traininginstructor',
            name='azienda',
            field=models.ForeignKey(blank=True, help_text='Ente di formazione di appartenenza (tipicamente per i docenti esterni)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='istruttori', to='anagrafica.trainingprovider', verbose_name='Azienda formativa'),
        ),
        migrations.RunPython(_promuovi_ragioni_sociali, _rimuovi_aziende),
    ]
