# Generated by Django 5.2.16 on 2026-08-27 14:20

import anagrafica.models_formazione
import anagrafica.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0114_trainingprovider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProviderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACCREDITAMENTO', 'Accreditamento / iscrizione albo'), ('CONTRATTO', 'Contratto / convenzione'), ('CV', 'Curriculum del docente'), ('QUALIFICA', 'Attestato di qualifica del docente'), ('ASSICURAZIONE', 'Polizza assicurativa'), ('ALTRO', 'Altro')], db_index=True, default='ACCREDITAMENTO', max_length=20)),
                ('file', models.FileField(storage=anagrafica.storage.PrivateAnagraficaStorage(), upload_to=anagrafica.models_formazione._training_provider_doc_upload_to)),
                ('nome_originale', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_mime', models.CharField(blank=True, default='', max_length=100)),
                ('dimensione_bytes', models.PositiveIntegerField(default=0)),
                ('descrizione', models.CharField(blank=True, default='', max_length=300)),
                ('data_scadenza', models.DateField(blank=True, help_text='Se il documento scade (accreditamento, polizza, qualifica a termine).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_display', models.CharField(blank=True, default='', max_length=200)),
                ('azienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='anagrafica.trainingprovider')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='anagrafica.traininginstructor')),
            ],
            options={
                'verbose_name': 'Documento ente/docente',
                'verbose_name_plural': 'Documenti enti e docenti',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['azienda', 'tipo'], name='anagrafica__azienda_0f721b_idx'), models.Index(fields=['docente', 'tipo'], name='anagrafica__docente_eb0a8e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('azienda__isnull', False), ('docente__isnull', True)), models.Q(('azienda__isnull', True), ('docente__isnull', False)), _connector='OR'), name='training_provider_doc_un_solo_proprietario')],
            },
        ),
    ]
