# Generated by Django 5.2.16 on 2026-08-28 07:51

from django.db import migrations, models


def _imposta_default_ccnl(apps, schema_editor):
    """Preseleziona il flag CCNL sui corsi già marcati obbligatori per legge o
    Accordo Stato-Regioni (la formazione sicurezza classica): sono i soli casi
    per cui l'esclusione dal monte ore è certa senza revisione manuale. I corsi
    obbligatori per altra fonte (cliente/norma/interno/non specificata) restano
    fuori dal flag: chi cura il catalogo li rivede caso per caso.
    """
    TrainingCourse = apps.get_model("anagrafica", "TrainingCourse")
    TrainingCourse.objects.filter(
        obbligatorio=True, fonte_obbligo__in=["LEGGE", "ACCORDO"]
    ).update(obbligatoria_ccnl=True)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0115_trainingproviderdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='obbligatoria_ccnl',
            field=models.BooleanField(default=False, help_text='Esclusa dal monte ore facoltativo del CCNL (24h ogni 3 anni). Spuntare per la formazione sicurezza da legge o Accordo Stato-Regioni; le altre concorrono al monte ore del dipendente.', verbose_name='Formazione obbligatoria (CCNL)'),
        ),
        migrations.RunPython(_imposta_default_ccnl, _noop),
    ]
