# Generated by Django 5.2.16 on 2026-08-31 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0116_add_obbligatoria_ccnl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglesson',
            name='docente_ente',
            field=models.ForeignKey(blank=True, help_text="Se il docente nominativo non è noto (es. webinar erogato dall'ente): traccia l'ente di formazione al posto della persona.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lezioni_come_docente', to='anagrafica.trainingprovider', verbose_name='Ente come docente'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='docente_ente',
            field=models.ForeignKey(blank=True, help_text="Se il docente nominativo non è noto (es. webinar erogato dall'ente): traccia l'ente di formazione al posto della persona.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessioni_come_docente', to='anagrafica.trainingprovider', verbose_name='Ente come docente'),
        ),
        migrations.AddConstraint(
            model_name='traininglesson',
            constraint=models.CheckConstraint(condition=models.Q(('docente__isnull', False), ('docente_ente__isnull', False), _negated=True), name='training_lesson_docente_o_ente_non_entrambi'),
        ),
        migrations.AddConstraint(
            model_name='trainingsession',
            constraint=models.CheckConstraint(condition=models.Q(('docente__isnull', False), ('docente_ente__isnull', False), _negated=True), name='training_session_docente_o_ente_non_entrambi'),
        ),
    ]
