# Generated by Django 5.2.16 on 2026-08-31 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0116_add_obbligatoria_ccnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='ente_formativo',
            field=models.ForeignKey(blank=True, help_text='Ente che eroga tipicamente questo corso. La singola sessione mostra il proprio docente quando è valorizzato; altrimenti si mostra questo ente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corsi_erogati', to='anagrafica.trainingprovider', verbose_name='Ente formativo'),
        ),
    ]
