# Generated by Django 5.2.16 on 2026-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0116_add_obbligatoria_ccnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='refertointakeconfig',
            name='giorni_tolleranza_associazione',
            field=models.PositiveSmallIntegerField(default=7, help_text='Una visita dello stesso dipendente e tipo, già presente e senza referto agganciato, entro questi giorni dalla data del giudizio letta sul certificato, viene considerata la stessa visita: il referto vi si aggancia invece di crearne una seconda. Serve perché la data registrata a mano (es. dalla Giornata visite) e quella scritta poi dal medico sul certificato («Espresso il») spesso non coincidono di un giorno o due, pur essendo lo stesso evento.'),
        ),
        migrations.AddField(
            model_name='refertointakeriga',
            name='visite_associate',
            field=models.PositiveSmallIntegerField(default=0, help_text='Quante VisitaMedica già registrate (senza referto agganciato) sono state riconosciute come lo stesso evento e collegate a questo certificato invece di generarne una seconda.'),
        ),
    ]
