# Generated by Django 5.2.16 on 2026-08-31 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0118_trainingcourse_ente_formativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendenteassegnazione',
            name='modificata_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assegnazioni_modificate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dipendenteassegnazione',
            name='modificata_il',
            field=models.DateTimeField(blank=True, help_text='Ultima correzione della card, anche su uno spostamento già attivo o concluso.', null=True),
        ),
    ]
