# Generated by Django 5.2.16 on 2026-09-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0119_dipendenteassegnazione_modificata_da_and_more'),
        ('core', '0071_auditlog_riferimento_oggetto'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaaziendale',
            name='responsabili',
            field=models.ManyToManyField(blank=True, help_text="Responsabili aggiuntivi dell'area. Se ne possono indicare più di uno.", related_name='aree_responsabile', to='core.anagraficadipendente', verbose_name='Responsabili'),
        ),
        migrations.AddField(
            model_name='reparto',
            name='responsabili',
            field=models.ManyToManyField(blank=True, help_text='Responsabili aggiuntivi del reparto. Se ne possono indicare più di uno.', related_name='reparti_responsabile', to='core.anagraficadipendente', verbose_name='Responsabili'),
        ),
    ]
