# Generated by Django 5.2.16 on 2026-09-15 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0121_merge_referti_intake_responsabili_multipli'),
    ]

    operations = [
        migrations.AddField(
            model_name='refertointakeriga',
            name='tipo_referto',
            field=models.CharField(choices=[('IDONEITA', 'Certificato di idoneità'), ('OCULISTICA', 'Certificato oculistico')], default='IDONEITA', help_text='Certificato di idoneità (stampato, letto per intero) o certificato oculistico (data, nome ed esito scritti a mano: si completano in coda).', max_length=12),
        ),
        migrations.AddField(
            model_name='refertointakeriga',
            name='tipo_visita_scelto',
            field=models.ForeignKey(blank=True, help_text='Per i certificati oculistici: il tipo di visita confermato in coda (il certificato non riporta la periodicità).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='anagrafica.tipovisitamedica'),
        ),
        migrations.AlterField(
            model_name='refertointakeriga',
            name='visite_create',
            field=models.PositiveSmallIntegerField(default=0, help_text='Quante VisitaMedica sono nate da questa riga: al più una. Il protocollo sanitario del certificato elenca i requisiti del lavoratore, non esami svolti in quella data.'),
        ),
        migrations.CreateModel(
            name='RequisitoVisitaDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('esame', models.CharField(help_text="L'esame come è scritto sul certificato.", max_length=200)),
                ('periodicita', models.CharField(blank=True, default='', max_length=20)),
                ('data_certificato', models.DateField(help_text='Data del giudizio del certificato di provenienza.')),
                ('attivo', models.BooleanField(db_index=True, default=True, help_text="Appartiene al protocollo dell'ultimo certificato del dipendente.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('riga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiti', to='anagrafica.refertointakeriga')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiti_dipendente', to='anagrafica.tipovisitamedica')),
            ],
            options={
                'verbose_name': 'Requisito di visita del dipendente',
                'verbose_name_plural': 'Requisiti di visita dei dipendenti',
                'ordering': ['legacy_anagrafica_id', '-data_certificato', 'esame'],
                'indexes': [models.Index(fields=['legacy_anagrafica_id', 'attivo'], name='anagrafica__legacy__4cd267_idx')],
            },
        ),
    ]
