# Generated by Django 5.2.16 on 2026-09-17 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0122_referti_requisiti_oculistica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourseCodeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contatore codice corso',
                'verbose_name_plural': 'Contatori codice corso',
                'ordering': ['-anno'],
            },
        ),
        migrations.AddField(
            model_name='trainingattachment',
            name='copiato_da',
            field=models.ForeignKey(blank=True, help_text='Allegato di corso da cui questa copia deriva. Serve a non riproporre due volte lo stesso materiale sulla stessa edizione.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copie', to='anagrafica.trainingattachment'),
        ),
        migrations.AddField(
            model_name='trainingattachment',
            name='corso',
            field=models.ForeignKey(blank=True, help_text='Corso di riferimento. Valorizzato = materiale del corso, riproposto in copia alla creazione di ogni nuova edizione.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='anagrafica.trainingcourse'),
        ),
        migrations.AddField(
            model_name='trainingattachment',
            name='proponi_a_nuova_edizione',
            field=models.BooleanField(default=True, help_text='Solo per gli allegati di corso: se spuntato viene pre-selezionato nella copia alla creazione di una nuova edizione.', verbose_name='Proponi alle nuove edizioni'),
        ),
        migrations.AlterField(
            model_name='trainingattachment',
            name='lezione',
            field=models.ForeignKey(blank=True, help_text='Lezione di riferimento. Vuoto = allegato a livello di edizione.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='anagrafica.traininglesson'),
        ),
        migrations.AlterField(
            model_name='trainingattachment',
            name='sessione',
            field=models.ForeignKey(blank=True, help_text='Edizione di riferimento. Vuoto = allegato a livello di corso.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='anagrafica.trainingsession'),
        ),
        migrations.AlterField(
            model_name='trainingattachment',
            name='tipo',
            field=models.CharField(choices=[('REGISTRO_FIRMATO', 'Registro firme firmato'), ('MATERIALE', 'Materiale didattico'), ('PROGRAMMA', 'Programma / dispensa'), ('ALTRO', 'Altro')], db_index=True, default='REGISTRO_FIRMATO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='trainingattachment',
            index=models.Index(fields=['corso'], name='anagrafica__corso_i_946c22_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('corso__isnull', False), ('sessione__isnull', True)), models.Q(('corso__isnull', True), ('sessione__isnull', False)), _connector='OR'), name='training_attachment_corso_o_sessione'),
        ),
        migrations.AddConstraint(
            model_name='trainingattachment',
            constraint=models.CheckConstraint(condition=models.Q(('lezione__isnull', True), ('sessione__isnull', False), _connector='OR'), name='training_attachment_lezione_richiede_sessione'),
        ),
    ]
