# Generated by Django 5.2.16 on 2026-09-18 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0123_trainingcoursecodecounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitamedica',
            name='referto_documento_secondario',
            field=models.ForeignKey(blank=True, help_text='Secondo referto della stessa visita (es. certificato oculistico scansionato su 2 fogli separati): non è una seconda visita.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='anagrafica.documentodipendente'),
        ),
    ]
