# Generated by Django 5.2.16 on 2026-09-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0124_visitamedica_referto_documento_secondario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipovisitamedica',
            name='categoria',
            field=models.CharField(blank=True, default='', help_text='Etichetta libera per raggruppare esami affini (es. "Rischio chimico"): serve a selezionarli insieme quando si configurano i requisiti di una mansione o di un ruolo, non è un catalogo a parte.', max_length=100),
        ),
    ]
