# Generated by Django 5.2.16 on 2026-09-21 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0125_tipovisitamedica_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DipendenteVisitaFacoltativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni_facoltative', to='anagrafica.tipovisitamedica')),
            ],
            options={
                'verbose_name': 'Visita facoltativa dipendente',
                'verbose_name_plural': 'Visite facoltative dipendente',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['legacy_anagrafica_id', 'is_active'], name='anagrafica__legacy__1daa2e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('legacy_anagrafica_id', 'tipo_visita'), name='uniq_dipendente_visita_facoltativa_attiva')],
            },
        ),
    ]
