# Generated by Django 5.2.16 on 2026-10-03 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0127_visitamedica_superata_e_famiglia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descrizione', models.CharField(blank=True, default='', max_length=300)),
                ('codice_sistema', models.CharField(blank=True, db_index=True, default='', help_text='Valorizzato solo sui modelli predefiniti (ripristinabili).', max_length=50)),
                ('titolo_documento', models.CharField(max_length=200)),
                ('sottotitolo', models.CharField(blank=True, default='', max_length=200)),
                ('destinatario', models.CharField(blank=True, default='', help_text='Cliente, ente di certificazione o funzione interna a cui è destinato il documento.', max_length=200)),
                ('norme', models.JSONField(blank=True, default=list)),
                ('riservatezza', models.CharField(choices=[('PUBBLICO', 'Pubblico'), ('INTERNO', 'Uso interno'), ('RISERVATO', 'Riservato'), ('DATI_PERSONALI', 'Riservato – contiene dati personali')], default='INTERNO', max_length=20)),
                ('periodo_tipo', models.CharField(choices=[('ULTIMI_12_MESI', 'Ultimi 12 mesi'), ('ANNO_CORRENTE', 'Anno in corso'), ('ANNO_PRECEDENTE', 'Anno precedente'), ('TRIMESTRE_PRECEDENTE', 'Trimestre precedente'), ('MESE_PRECEDENTE', 'Mese precedente'), ('PERSONALIZZATO', 'Date personalizzate')], default='ULTIMI_12_MESI', max_length=25)),
                ('data_da', models.DateField(blank=True, null=True)),
                ('data_a', models.DateField(blank=True, null=True)),
                ('filtri', models.JSONField(blank=True, default=dict)),
                ('redatto_da', models.CharField(blank=True, default='', max_length=120)),
                ('verificato_da', models.CharField(blank=True, default='', max_length=120)),
                ('approvato_da', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modello di report',
                'verbose_name_plural': 'Modelli di report',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ReportGenerato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modello_nome', models.CharField(blank=True, default='', max_length=150)),
                ('titolo', models.CharField(max_length=200)),
                ('destinatario', models.CharField(blank=True, default='', max_length=200)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel')], max_length=5)),
                ('data_da', models.DateField(blank=True, null=True)),
                ('data_a', models.DateField(blank=True, null=True)),
                ('parametri', models.JSONField(blank=True, default=dict)),
                ('contiene_dati_personali', models.BooleanField(default=False)),
                ('nome_file', models.CharField(max_length=200)),
                ('contenuto', models.BinaryField(max_length='max')),
                ('dimensione', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('generato_il', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modello', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generati', to='anagrafica.reportmodello')),
            ],
            options={
                'verbose_name': 'Report generato',
                'verbose_name_plural': 'Report generati',
                'ordering': ['-generato_il', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReportBlocco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('TESTO', 'Testo libero'), ('SEZIONE', 'Sezione dati'), ('PAGINA', 'Interruzione di pagina'), ('FIRME', 'Riquadro firme')], default='TESTO', max_length=10)),
                ('titolo', models.CharField(blank=True, default='', max_length=200)),
                ('testo', models.TextField(blank=True, default='')),
                ('sezione', models.CharField(blank=True, default='', max_length=60)),
                ('opzioni', models.JSONField(blank=True, default=dict)),
                ('modello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocchi', to='anagrafica.reportmodello')),
            ],
            options={
                'verbose_name': 'Blocco di report',
                'verbose_name_plural': 'Blocchi di report',
                'ordering': ['ordine', 'id'],
            },
        ),
    ]
