# Generated by Django 5.2.16 on 2026-10-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0129_reportistica_predefiniti_e_subnav'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodello',
            name='codice_documento',
            field=models.CharField(blank=True, default='', help_text='Codice del modulo di sistema, es. MOD.230.', max_length=50),
        ),
        migrations.AddField(
            model_name='reportmodello',
            name='excel_foglio_documento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportmodello',
            name='excel_foglio_indicatori',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportmodello',
            name='filigrana',
            field=models.CharField(blank=True, default='', help_text='Es. BOZZA o COPIA NON CONTROLLATA.', max_length=40),
        ),
        migrations.AddField(
            model_name='reportmodello',
            name='formato_predefinito',
            field=models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel')], default='pdf', max_length=5),
        ),
        migrations.AddField(
            model_name='reportmodello',
            name='mostra_frontespizio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportmodello',
            name='mostra_indice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportmodello',
            name='mostra_note_calcolo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportmodello',
            name='mostra_riferimenti',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportmodello',
            name='nome_file',
            field=models.CharField(blank=True, default='', help_text='Ammessi i segnaposto, es. {titolo}_{destinatario}_{data}.', max_length=150),
        ),
        migrations.AddField(
            model_name='reportmodello',
            name='orientamento',
            field=models.CharField(choices=[('ORIZZONTALE', 'Orizzontale'), ('VERTICALE', 'Verticale')], default='ORIZZONTALE', max_length=12),
        ),
        migrations.AddField(
            model_name='reportmodello',
            name='piede_pagina',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reportmodello',
            name='revisione',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
