# Generated by Django 5.2.16 on 2026-10-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0132_reportistica_chat_acl'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitamedica',
            name='scadenza_nota',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
