# Generated by Django 5.2.16 on 2026-10-07 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0133_visitamedica_scadenza_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdempimentoCambioMansione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('tipo', models.CharField(choices=[('VISITA', 'Visita medica'), ('FORMAZIONE', 'Formazione'), ('DPI', 'DPI'), ('SDS', 'Schede di sicurezza')], max_length=12)),
                ('riferimento_id', models.IntegerField(blank=True, null=True)),
                ('descrizione', models.CharField(max_length=300)),
                ('motivo', models.CharField(blank=True, default='', help_text='Perché è dovuto (nuovo rischio, mansione, regola…).', max_length=300)),
                ('obbligatorio', models.BooleanField(default=True)),
                ('entro_il', models.DateField(help_text='Di norma la decorrenza dello spostamento.')),
                ('stato', models.CharField(choices=[('APERTO', 'Da fare'), ('COMPLETATO', 'Fatto'), ('NON_NECESSARIO', 'Non necessario')], db_index=True, default='APERTO', max_length=15)),
                ('chiuso_il', models.DateTimeField(blank=True, null=True)),
                ('chiusura_automatica', models.BooleanField(default=False)),
                ('chiusura_nota', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assegnazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adempimenti', to='anagrafica.dipendenteassegnazione')),
                ('chiuso_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adempimento cambio mansione',
                'verbose_name_plural': 'Adempimenti cambio mansione',
                'ordering': ['stato', 'entro_il', 'tipo', 'descrizione'],
                'indexes': [models.Index(fields=['stato', 'entro_il'], name='anagrafica__stato_678e6c_idx')],
            },
        ),
    ]
