# Generated by Django 5.2.16 on 2026-10-07 15:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0136_subnav_cinque_pilastri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingtask',
            options={'ordering': ['ordine', 'id'], 'verbose_name': 'Task onboarding', 'verbose_name_plural': 'Task onboarding'},
        ),
        migrations.AddField(
            model_name='candidato',
            name='offerta_esito',
            field=models.CharField(blank=True, choices=[('', 'In attesa di risposta'), ('ACCETTATA', 'Accettata'), ('RIFIUTATA', 'Rifiutata')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='candidato',
            name='offerta_esito_il',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='offerta_inviata_il',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='offerta_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='onboardingpratica',
            name='fine_prova',
            field=models.DateField(blank=True, null=True, verbose_name='Fine periodo di prova'),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='chiusura_automatica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='chiusura_nota',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='fase',
            field=models.CharField(choices=[('PRE', "Prima dell'ingresso"), ('GIORNO1', 'Primo giorno'), ('SETTIMANA1', 'Prima settimana'), ('60GG', 'Primi 60 giorni'), ('PROVA', 'Fine periodo di prova')], db_index=True, default='PRE', max_length=12),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='ordine',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='riferimento_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='scadenza',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='tipo',
            field=models.CharField(choices=[('MANUALE', 'Manuale'), ('VISITA', 'Visita medica'), ('FORMAZIONE', 'Formazione'), ('DPI', 'DPI'), ('SDS', 'Schede di sicurezza'), ('ACCOUNT', 'Account portale')], default='MANUALE', max_length=12),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='data_assunzione',
            field=models.DateField(blank=True, help_text="Primo giorno di lavoro: da qui partono le scadenze dell'onboarding.", null=True, verbose_name='Data di ingresso'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='stato',
            field=models.CharField(choices=[('NUOVO', 'Nuovo (CV ricevuto)'), ('CV_VALUTATO', 'CV valutato'), ('COLLOQUIO_1', 'Primo colloquio effettuato'), ('COLLOQUIO_2', 'Secondo colloquio effettuato'), ('OFFERTA', 'Offerta inviata'), ('ASSUNTO', 'Assunto'), ('IN_DATABASE', 'In database per future opportunità'), ('SCARTATO', 'Non idoneo'), ('RINUNCIA', 'Rinuncia del candidato'), ('ANNULLATO', 'Annullato / archiviato')], db_index=True, default='NUOVO', max_length=16),
        ),
        migrations.AlterField(
            model_name='onboardingpratica',
            name='data_assunzione',
            field=models.DateField(blank=True, null=True, verbose_name='Data di ingresso'),
        ),
        migrations.AlterField(
            model_name='onboardingpratica',
            name='legacy_anagrafica_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='PosizioneAperta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=160)),
                ('mansione', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('reparto', models.CharField(blank=True, default='', max_length=200)),
                ('posti', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.CharField(choices=[('SOSTITUZIONE', 'Sostituzione'), ('INCREMENTO', 'Incremento organico'), ('NUOVO_RUOLO', 'Nuovo ruolo'), ('STAGIONALE', 'Picco / stagionale'), ('ALTRO', 'Altro')], default='SOSTITUZIONE', max_length=20)),
                ('richiesta_da', models.CharField(blank=True, default='', help_text='Chi ha chiesto la risorsa (es. responsabile di reparto).', max_length=160)),
                ('data_richiesta', models.DateField(db_index=True)),
                ('entro_il', models.DateField(blank=True, help_text='Data entro cui la risorsa serve in reparto.', null=True)),
                ('stato', models.CharField(choices=[('APERTA', 'Aperta'), ('SOSPESA', 'Sospesa'), ('COPERTA', 'Coperta'), ('ANNULLATA', 'Annullata')], db_index=True, default='APERTA', max_length=12)),
                ('chiusa_il', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posizioni_recruiting_create', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Posizione aperta (Recruiting)',
                'verbose_name_plural': 'Posizioni aperte (Recruiting)',
                'ordering': ['stato', 'entro_il', '-data_richiesta'],
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='posizione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidati', to='anagrafica.posizioneaperta', verbose_name='Posizione aperta'),
        ),
    ]
