# Generated by Django 5.2.16 on 2026-10-09 22:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0138_onboarding_fasi_dati_e_acl'),
        ('dpi', '0011_magazzino_movimenti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adempimentocambiomansione',
            name='annullato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adempimentocambiomansione',
            name='annullato_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adempimentocambiomansione',
            name='annullato_motivo',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='adempimentocambiomansione',
            name='attivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adempimentocambiomansione',
            name='chiave',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='adempimentocambiomansione',
            name='origine_tipo',
            field=models.CharField(blank=True, choices=[('MANSIONE_RISCHIO', 'Mansione di rischio'), ('OVERRIDE', 'Override individuale'), ('MANSIONE', 'Mansione lavorativa'), ('AREA', 'Area aziendale'), ('DIRETTA', 'Esposizione diretta'), ('ALTRO', 'Altro')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='adempimentocambiomansione',
            name='assegnazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adempimenti', to='anagrafica.dipendenteassegnazione'),
        ),
        migrations.AlterField(
            model_name='adempimentocambiomansione',
            name='stato',
            field=models.CharField(choices=[('APERTO', 'Da fare'), ('COMPLETATO', 'Fatto'), ('NON_NECESSARIO', 'Non necessario'), ('NON_PIU_DOVUTO', 'Non più dovuto'), ('ANNULLATO', 'Annullato')], db_index=True, default='APERTO', max_length=15),
        ),
        migrations.AlterField(
            model_name='mansione',
            name='dpi_richiesti',
            field=models.ManyToManyField(blank=True, help_text='DEPRECATO: usare le mansioni di rischio collegate.', related_name='mansioni_richiedenti', to='dpi.categoriadpi'),
        ),
        migrations.AlterField(
            model_name='mansione',
            name='visite_richieste',
            field=models.ManyToManyField(blank=True, help_text='DEPRECATO: usare le mansioni di rischio collegate.', related_name='mansioni_richiedenti', to='anagrafica.tipovisitamedica'),
        ),
        migrations.CreateModel(
            name='ConfigSicurezzaOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalita_visita_mancante', models.CharField(choices=[('SOLO_AVVISO', 'Solo avviso'), ('DEROGA_AMMESSA', 'Non idoneo a operare, salvo deroga motivata'), ('BLOCCO', 'Non idoneo a operare, nessuna deroga')], default='SOLO_AVVISO', help_text='Cosa succede se la decorrenza arriva senza la visita del cambio mansione.', max_length=20)),
                ('deroga_max_giorni', models.PositiveSmallIntegerField(default=30)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('aggiornata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configurazione sicurezza operativa',
                'verbose_name_plural': 'Configurazione sicurezza operativa',
            },
        ),
        migrations.CreateModel(
            name='DerogaOperativaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('motivo', models.CharField(max_length=500)),
                ('autorizzato_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('valida_fino', models.DateField()),
                ('attivo', models.BooleanField(default=True)),
                ('revocata_il', models.DateTimeField(blank=True, null=True)),
                ('revoca_motivo', models.CharField(blank=True, default='', max_length=300)),
                ('adempimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deroghe', to='anagrafica.adempimentocambiomansione')),
                ('autorizzato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revocata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deroga operativa visita',
                'verbose_name_plural': 'Deroghe operative visita',
                'ordering': ['-autorizzato_il'],
            },
        ),
        migrations.CreateModel(
            name='DipendenteMansioneRischioOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('azione', models.CharField(choices=[('ADD', 'Aggiunta individuale'), ('EXCLUDE', 'Esclusione individuale')], max_length=8)),
                ('motivo', models.CharField(max_length=500)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revocato_il', models.DateTimeField(blank=True, null=True)),
                ('revoca_motivo', models.CharField(blank=True, default='', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revocato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Override mansione di rischio',
                'verbose_name_plural': 'Override mansioni di rischio',
                'ordering': ['-attivo', '-data_inizio', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='adempimentocambiomansione',
            name='origine_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='anagrafica.dipendentemansionerischiooverride'),
        ),
        migrations.CreateModel(
            name='EventoSicurezzaDipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField()),
                ('tipo', models.CharField(choices=[('ASSEGNAZIONE_REGISTRATA', 'Spostamento registrato'), ('ASSEGNAZIONE_ANNULLATA', 'Spostamento annullato'), ('OVERRIDE_AGGIUNTO', 'Override mansione di rischio'), ('OVERRIDE_REVOCATO', 'Override revocato'), ('PIANO_AGGIORNATO', 'Piano di adeguamento aggiornato'), ('ADEMPIMENTO_CHIUSO', 'Adempimento chiuso'), ('ADEMPIMENTO_ANNULLATO', 'Adempimento annullato'), ('ADEMPIMENTO_NON_PIU_DOVUTO', 'Adempimento non più dovuto'), ('ADEMPIMENTO_RIAPERTO', 'Adempimento riaperto'), ('STATO_OPERATIVO', 'Stato operativo'), ('DEROGA_CONCESSA', 'Deroga concessa'), ('DEROGA_REVOCATA', 'Deroga revocata'), ('MIGRAZIONE', 'Migrazione dati')], max_length=30)),
                ('descrizione', models.CharField(max_length=300)),
                ('occorso_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_effetto', models.DateField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor_display', models.CharField(blank=True, default='', max_length=150)),
                ('oggetto_tipo', models.CharField(blank=True, default='', max_length=60)),
                ('oggetto_id', models.IntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento sicurezza dipendente',
                'verbose_name_plural': 'Eventi sicurezza dipendente',
                'ordering': ['-occorso_il', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MansioneRischio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('livello_rischio_dvr', models.CharField(blank=True, choices=[('B', 'Basso'), ('M', 'Medio'), ('A', 'Alto')], default='', help_text='Stima del rischio nel DVR. Informativo: le ore di formazione ASR restano sulla mansione lavorativa.', max_length=1, verbose_name='Livello di rischio (DVR)')),
                ('dvr_revisione', models.CharField(blank=True, default='', max_length=30, verbose_name='Revisione DVR')),
                ('dvr_data', models.DateField(blank=True, null=True, verbose_name='Data revisione DVR')),
                ('is_active', models.BooleanField(default=True)),
                ('origine_migrazione_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie_dpi', models.ManyToManyField(blank=True, related_name='mansioni_rischio', to='dpi.categoriadpi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fattori', models.ManyToManyField(blank=True, related_name='mansioni_rischio', to='anagrafica.fattorerischio')),
                ('origine_mansione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profili_rischio_migrati', to='anagrafica.mansione')),
                ('visite', models.ManyToManyField(blank=True, help_text='Protocollo sanitario: tipi di visita dovuti. La periodicità la decide il medico competente.', related_name='mansioni_rischio', to='anagrafica.tipovisitamedica')),
            ],
            options={
                'verbose_name': 'Mansione di rischio',
                'verbose_name_plural': 'Mansioni di rischio',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MansioneLavorativaRischio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('origine_migrazione', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mansione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_rischio', to='anagrafica.mansione')),
                ('mansione_rischio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='link_mansioni', to='anagrafica.mansionerischio')),
            ],
            options={
                'verbose_name': 'Collegamento mansione ↔ mansione di rischio',
                'verbose_name_plural': 'Collegamenti mansione ↔ mansione di rischio',
                'ordering': ['mansione', 'ordine', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='dipendentemansionerischiooverride',
            name='mansione_rischio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='override_dipendenti', to='anagrafica.mansionerischio'),
        ),
        migrations.AddField(
            model_name='adempimentocambiomansione',
            name='origine_mansione_rischio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='anagrafica.mansionerischio'),
        ),
        migrations.AddField(
            model_name='mansione',
            name='mansioni_rischio',
            field=models.ManyToManyField(blank=True, related_name='mansioni_lavorative', through='anagrafica.MansioneLavorativaRischio', to='anagrafica.mansionerischio'),
        ),
        migrations.AddField(
            model_name='trainingrequirementrule',
            name='mansione_rischio',
            field=models.ForeignKey(blank=True, help_text='Regola per una mansione di rischio (gruppo omogeneo DVR).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regole_formazione', to='anagrafica.mansionerischio'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirementrule',
            index=models.Index(fields=['mansione_rischio', 'is_active'], name='anagrafica__mansion_9ad23f_idx'),
        ),
        migrations.AddConstraint(
            model_name='derogaoperativavisita',
            constraint=models.CheckConstraint(condition=models.Q(('motivo', ''), _negated=True), name='ck_deroga_visita_motivo'),
        ),
        migrations.AddIndex(
            model_name='eventosicurezzadipendente',
            index=models.Index(fields=['legacy_anagrafica_id', '-occorso_il'], name='anagrafica__legacy__f1fd3f_idx'),
        ),
        migrations.AddIndex(
            model_name='mansionerischio',
            index=models.Index(fields=['is_active'], name='anagrafica__is_acti_d29f9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='mansionelavorativarischio',
            constraint=models.UniqueConstraint(fields=('mansione', 'mansione_rischio'), name='uniq_mansione_link_rischio'),
        ),
        migrations.AddIndex(
            model_name='dipendentemansionerischiooverride',
            index=models.Index(fields=['legacy_anagrafica_id', 'attivo'], name='anagrafica__legacy__e92cbd_idx'),
        ),
        migrations.AddConstraint(
            model_name='dipendentemansionerischiooverride',
            constraint=models.UniqueConstraint(condition=models.Q(('attivo', True)), fields=('legacy_anagrafica_id', 'mansione_rischio'), name='uniq_override_mansrischio_attivo'),
        ),
        migrations.AddConstraint(
            model_name='dipendentemansionerischiooverride',
            constraint=models.CheckConstraint(condition=models.Q(('data_fine__isnull', True), ('data_fine__gte', models.F('data_inizio')), _connector='OR'), name='ck_override_mansrischio_date'),
        ),
        migrations.AddConstraint(
            model_name='dipendentemansionerischiooverride',
            constraint=models.CheckConstraint(condition=models.Q(('motivo', ''), _negated=True), name='ck_override_mansrischio_motivo'),
        ),
    ]
