# Generated by Django 5.2.16 on 2026-10-10 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0142_mansioni_rischio_acl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adempimentocambiomansione',
            name='uniq_adempimento_cm_chiave_attivo',
        ),
        migrations.AddConstraint(
            model_name='adempimentocambiomansione',
            constraint=models.UniqueConstraint(condition=models.Q(('assegnazione__isnull', False), ('attivo', True)), fields=('assegnazione', 'chiave'), name='uniq_adempimento_cm_chiave_attivo'),
        ),
    ]
