# Generated by Django 5.2.16 on 2026-10-10 10:01

import anagrafica.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0145_elearning_sblocco_tentativi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='trainingelearningenrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='elearningconfig',
            name='conferma_fad_utente_ids',
            field=models.JSONField(blank=True, default=list, help_text='Utenti (utenti.id) autorizzati a confermare le regole FAD dei corsi (RSPP).'),
        ),
        migrations.AddField(
            model_name='elearningconfig',
            name='finestra_rinnovo_giorni',
            field=models.PositiveSmallIntegerField(default=60, help_text='Quanti giorni prima della scadenza si apre il ciclo di aggiornamento.'),
        ),
        migrations.AddField(
            model_name='elearningconfig',
            name='giorni_entro_default',
            field=models.PositiveSmallIntegerField(default=30, help_text='Scadenza di default delle assegnazioni automatiche (giorni).'),
        ),
        migrations.AddField(
            model_name='elearningconfig',
            name='video_max_mb',
            field=models.PositiveSmallIntegerField(default=500, help_text='Dimensione massima di un video (MB).'),
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='ciclo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='confermata_rspp_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='confermata_rspp_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='el_attesa_minuti_tra_tentativi',
            field=models.PositiveSmallIntegerField(default=0, help_text='Attesa minima tra due tentativi (minuti).'),
        ),
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='el_domande_estratte',
            field=models.PositiveSmallIntegerField(default=0, help_text='Domande estratte a caso dalla banca. 0 = tutte.'),
        ),
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='el_inattivita_secondi',
            field=models.PositiveSmallIntegerField(default=120, help_text='Oltre questa inattività il tempo non viene accreditato.'),
        ),
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='el_max_tentativi',
            field=models.PositiveSmallIntegerField(default=0, help_text='Tentativi massimi. 0 = valore globale delle impostazioni e-learning.'),
        ),
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='el_mescola',
            field=models.BooleanField(default=True, help_text='Ordine di domande e risposte casuale.'),
        ),
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='el_richiede_quiz',
            field=models.BooleanField(default=True, help_text='Il quiz finale va superato.'),
        ),
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='el_richiede_tutte_slide',
            field=models.BooleanField(default=True, help_text='Tutte le slide vanno completate.'),
        ),
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='el_secondi_minimi_slide',
            field=models.PositiveSmallIntegerField(default=0, help_text='Secondi minimi di permanenza su ciascuna slide. 0 = nessun minimo.'),
        ),
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='el_soglia_pct',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Soglia di superamento (%). Vuoto = quella del corso.', null=True),
        ),
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='el_tempo_minimo_minuti',
            field=models.PositiveSmallIntegerField(default=0, help_text='Tempo minimo di fruizione effettiva (minuti). 0 = nessun minimo.'),
        ),
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='el_tempo_quiz_minuti',
            field=models.PositiveSmallIntegerField(default=0, help_text='Durata massima del quiz (minuti). 0 = senza limite.'),
        ),
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='rspp_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainingelearningenrollment',
            name='ciclo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainingelearningenrollment',
            name='secondi_accreditati',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingelearningenrollment',
            name='versione_label_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingquizattempt',
            name='domande_servite_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingquizattempt',
            name='scade_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingquizattempt',
            name='stato',
            field=models.CharField(choices=[('APERTO', 'Aperto'), ('INVIATO', 'Inviato'), ('SCADUTO', 'Scaduto')], default='INVIATO', max_length=10),
        ),
        migrations.AddField(
            model_name='trainingquizattempt',
            name='token',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='trainingslide',
            name='durata_minima_secondi',
            field=models.PositiveSmallIntegerField(default=0, help_text='Permanenza minima su questa slide (secondi). 0 = vale la regola del corso.'),
        ),
        migrations.AddField(
            model_name='trainingslide',
            name='tipo',
            field=models.CharField(choices=[('TESTO', 'Testo'), ('IMMAGINE', 'Immagine'), ('VIDEO', 'Video')], default='TESTO', max_length=10),
        ),
        migrations.AddField(
            model_name='trainingslide',
            name='video',
            field=models.FileField(blank=True, help_text='Video MP4 (storage privato).', null=True, storage=anagrafica.storage.PrivateAnagraficaStorage(), upload_to='elearning/video/'),
        ),
        migrations.AlterField(
            model_name='trainingquizattempt',
            name='inviato_il',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='trainingassignment',
            unique_together={('corso', 'legacy_anagrafica_id', 'ciclo')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingelearningenrollment',
            unique_together={('corso', 'legacy_anagrafica_id', 'ciclo')},
        ),
        migrations.CreateModel(
            name='TrainingElearningCompletamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifica_json', models.JSONField(default=dict)),
                ('sha256', models.CharField(max_length=64)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='completamento', to='anagrafica.trainingelearningenrollment')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='completamento_elearning', to='anagrafica.trainingemployeerecord')),
                ('tentativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='anagrafica.trainingquizattempt')),
            ],
            options={
                'verbose_name': 'Completamento e-learning (registro)',
                'verbose_name_plural': 'Completamenti e-learning (registro)',
                'ordering': ['-creato_il'],
            },
        ),
        migrations.CreateModel(
            name='TrainingElearningSessione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avviata_il', models.DateTimeField(auto_now_add=True)),
                ('ultimo_beat_il', models.DateTimeField()),
                ('secondi_accreditati', models.PositiveIntegerField(default=0)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ua_hash', models.CharField(blank=True, default='', max_length=64)),
                ('chiusa', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessioni', to='anagrafica.trainingelearningenrollment')),
                ('slide_corrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='anagrafica.trainingslide')),
            ],
            options={
                'verbose_name': 'Sessione e-learning',
                'verbose_name_plural': 'Sessioni e-learning',
                'ordering': ['-avviata_il'],
                'indexes': [models.Index(fields=['enrollment', 'chiusa'], name='anagrafica__enrollm_bc705d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingElearningSlideView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prima_vista', models.DateTimeField(auto_now_add=True)),
                ('ultima_vista', models.DateTimeField(auto_now=True)),
                ('secondi', models.PositiveIntegerField(default=0)),
                ('completata', models.BooleanField(default=False)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_viste', to='anagrafica.trainingelearningenrollment')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viste', to='anagrafica.trainingslide')),
            ],
            options={
                'verbose_name': 'Slide vista',
                'verbose_name_plural': 'Slide viste',
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'slide'), name='uniq_elearning_slide_vista')],
            },
        ),
    ]
