# Generated by Django 5.2.16 on 2026-10-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0148_elearning_acl'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='elearning_self_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='elearningconfig',
            name='video_max_mb',
            field=models.PositiveSmallIntegerField(default=100, help_text='Dimensione massima di un video (MB); oltre il limite upload del server non serve.'),
        ),
    ]
