# Generated by Django 5.2.16 on 2026-10-10 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0150_elearning_domande_tipizzate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingemployeerecord',
            name='codice_verifica',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='trainingemployeerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('codice_verifica__gt', '')), fields=('codice_verifica',), name='uniq_record_codice_verifica'),
        ),
    ]
