# Generated by Django 5.2.16 on 2026-10-10 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0151_attestato_codice_verifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearningconfig',
            name='digest_responsabile_giorno',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (7, 'Mai')], default=0, help_text='Giorno del riepilogo settimanale al responsabile dei corsi in scadenza o scaduti.'),
        ),
        migrations.AddField(
            model_name='elearningconfig',
            name='promemoria_giorni_prima',
            field=models.CharField(blank=True, default='14,7,1', help_text='Giorni prima della scadenza in cui ricordare il corso al dipendente (es. 14,7,1). Vuoto = nessuno.', max_length=60),
        ),
        migrations.AddField(
            model_name='elearningconfig',
            name='solleciti_giorni_dopo',
            field=models.CharField(blank=True, default='1,7,14', help_text='Giorni dopo la scadenza in cui sollecitare dipendente e responsabile (es. 1,7,14). Vuoto = nessuno.', max_length=60),
        ),
        migrations.CreateModel(
            name='TrainingElearningAvviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(max_length=160, unique=True)),
                ('tipo', models.CharField(choices=[('PRIMA', 'Promemoria prima della scadenza'), ('SOLLECITO', 'Sollecito dopo la scadenza'), ('DIGEST', 'Digest settimanale al responsabile')], max_length=10)),
                ('legacy_anagrafica_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('ciclo', models.PositiveSmallIntegerField(default=1)),
                ('giorni', models.SmallIntegerField(default=0, help_text='Soglia della scaletta (giorni prima o dopo la scadenza).')),
                ('responsabile_legacy_id', models.IntegerField(blank=True, null=True)),
                ('email_inviata', models.BooleanField(default=False)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('corso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anagrafica.trainingcourse')),
            ],
            options={
                'verbose_name': 'Avviso e-learning inviato',
                'verbose_name_plural': 'Avvisi e-learning inviati',
                'ordering': ['-creato_il'],
            },
        ),
    ]
