# Generated by Django 5.2.16 on 2026-10-10 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0152_elearning_promemoria_scaletta'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearningconfig',
            name='gradimento_attivo',
            field=models.BooleanField(default=True, help_text='Proporre il questionario di gradimento a fine corso.'),
        ),
        migrations.AddField(
            model_name='elearningconfig',
            name='gradimento_domande',
            field=models.TextField(blank=True, default='I contenuti erano chiari\nGli argomenti sono utili per il mio lavoro\nLa durata era adeguata\nIl corso ha funzionato bene sul mio dispositivo', help_text='Una domanda per riga; il discente risponde da 1 (per niente) a 5 (del tutto).'),
        ),
        migrations.CreateModel(
            name='TrainingElearningGradimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True)),
                ('domande_json', models.JSONField(default=list)),
                ('voti_json', models.JSONField(default=list, help_text='Un voto da 1 a 5 per domanda, nello stesso ordine.')),
                ('media', models.DecimalField(decimal_places=2, max_digits=3)),
                ('commento', models.TextField(blank=True, default='')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anagrafica.trainingcourse')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gradimento_elearning', to='anagrafica.trainingemployeerecord')),
            ],
            options={
                'verbose_name': 'Gradimento e-learning',
                'verbose_name_plural': 'Gradimenti e-learning',
                'ordering': ['-creato_il'],
                'indexes': [models.Index(fields=['corso', 'creato_il'], name='anagrafica__corso_i_04b917_idx')],
            },
        ),
    ]
