# Generated by Django 5.2.16 on 2026-10-10 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0153_elearning_gradimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcompletionrule',
            name='el_nuova_versione',
            field=models.CharField(choices=[('MANTIENI', 'Restano validi'), ('RIASSEGNA', 'Devono rifare il corso')], default='MANTIENI', help_text='Chi ha completato una versione precedente quando i contenuti cambiano.', max_length=10),
        ),
        migrations.AddField(
            model_name='trainingcourseversion',
            name='contenuti_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trainingcourseversion',
            name='impronta',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='TrainingElearningModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveSmallIntegerField(default=1)),
                ('titolo', models.CharField(max_length=200)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moduli_elearning', to='anagrafica.trainingcourse')),
            ],
            options={
                'verbose_name': 'Modulo e-learning',
                'verbose_name_plural': 'Moduli e-learning',
                'ordering': ['corso', 'ordine', 'id'],
            },
        ),
        migrations.AddField(
            model_name='trainingslide',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='anagrafica.trainingelearningmodulo'),
        ),
    ]
