# Generated by Django 5.2.16 on 2026-10-10 15:02

import anagrafica.models_elearning
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0154_elearning_moduli_versioni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingElearningImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, storage=anagrafica.models_elearning._storage_privato, upload_to='elearning/import/')),
                ('nome_file', models.CharField(max_length=255)),
                ('stato', models.CharField(choices=[('IN_CODA', 'In coda'), ('IN_CORSO', 'In corso'), ('COMPLETATO', 'Completato'), ('ERRORE', 'Errore')], default='IN_CODA', max_length=10)),
                ('n_slide', models.PositiveSmallIntegerField(default=0)),
                ('errore', models.CharField(blank=True, default='', max_length=500)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('avviato_il', models.DateTimeField(blank=True, null=True)),
                ('finito_il', models.DateTimeField(blank=True, null=True)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='anagrafica.trainingcourse')),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import slide e-learning',
                'verbose_name_plural': 'Import slide e-learning',
                'ordering': ['-creato_il'],
            },
        ),
    ]
