# Generated by Django 5.2.11 on 2026-07-08 11:23

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0080_reparto_area_aziendale_inversione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionCorner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_sharepoint_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('da_portale', models.BooleanField(default=True)),
                ('anonima', models.BooleanField(default=False)),
                ('data_segnalazione', models.DateField(auto_now_add=True)),
                ('processo_libero', models.CharField(blank=True, max_length=255)),
                ('opportunity', models.TextField()),
                ('plan_testo', models.TextField(blank=True)),
                ('plan_eseguito', models.BooleanField(default=False)),
                ('data_limite_esecuzione', models.DateField(blank=True, null=True)),
                ('data_limite_controllo', models.DateField(blank=True, null=True)),
                ('do_testo', models.TextField(blank=True)),
                ('do_eseguito', models.BooleanField(default=False)),
                ('data_esecuzione_do', models.DateField(blank=True, null=True)),
                ('esito_do', models.CharField(blank=True, choices=[('SI', 'Sì'), ('NO', 'No')], max_length=8)),
                ('check_testo', models.TextField(blank=True)),
                ('check_eseguito', models.BooleanField(default=False)),
                ('data_esecuzione_check', models.DateField(blank=True, null=True)),
                ('esito_check', models.CharField(blank=True, choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo'), ('RINVIATO', 'Rinviato')], max_length=10)),
                ('vuoi_inserire_act', models.BooleanField(default=False)),
                ('act_testo', models.TextField(blank=True)),
                ('act_eseguito', models.BooleanField(default=False)),
                ('stato', django_fsm.FSMField(db_index=True, default='INSERITA', max_length=30, protected=True)),
                ('stato_sms', models.CharField(choices=[('DA_GESTIRE', 'Da gestire'), ('SMS_SI', 'SMS Sì'), ('SMS_NO', 'SMS No')], default='DA_GESTIRE', max_length=10)),
                ('sollecito_do_30', models.BooleanField(default=False)),
                ('sollecito_do_15', models.BooleanField(default=False)),
                ('sollecito_do_5', models.BooleanField(default=False)),
                ('sollecito_check_30', models.BooleanField(default=False)),
                ('sollecito_check_15', models.BooleanField(default=False)),
                ('sollecito_check_5', models.BooleanField(default=False)),
                ('escalation_do_inviata', models.BooleanField(default=False)),
                ('escalation_check_inviata', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controllore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suggestioncorner_check', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incaricato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suggestioncorner_do', to=settings.AUTH_USER_MODEL)),
                ('nuova_segnalazione_da_act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generata_da', to='suggestion_corner.suggestioncorner')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segnalazioni', to='anagrafica.processoqualificato')),
                ('reparto_destinazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='segnalazioni_destinazione', to='anagrafica.reparto')),
                ('reparto_provenienza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segnalazioni_provenienza', to='anagrafica.reparto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Segnalazione Suggestion Corner',
                'verbose_name_plural': 'Segnalazioni Suggestion Corner',
                'ordering': ['-data_segnalazione', '-id'],
            },
        ),
    ]
