# Generated by Django 5.2.11 on 2026-07-08 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion_corner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionCornerAllegato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='suggestion_corner/%Y/')),
                ('link_esterno', models.URLField(blank=True, max_length=500)),
                ('caricato_il', models.DateTimeField(auto_now_add=True)),
                ('caricato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('segnalazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='suggestion_corner.suggestioncorner')),
            ],
            options={
                'verbose_name': 'Allegato segnalazione',
                'verbose_name_plural': 'Allegati segnalazione',
            },
        ),
    ]
