# Generated by Django 5.2.11 on 2026-07-08 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion_corner', '0002_suggestioncornerallegato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionCornerStorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato_precedente', models.CharField(max_length=30)),
                ('stato_nuovo', models.CharField(max_length=30)),
                ('campo_modificato', models.CharField(blank=True, max_length=50)),
                ('valore_precedente', models.TextField(blank=True)),
                ('valore_nuovo', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('autore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('segnalazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storico', to='suggestion_corner.suggestioncorner')),
            ],
            options={
                'verbose_name': 'Voce storico segnalazione',
                'verbose_name_plural': 'Storico segnalazione',
                'ordering': ['-timestamp', '-id'],
            },
        ),
    ]
