# Generated by Django 5.2.11 on 2026-07-08 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0080_reparto_area_aziendale_inversione'),
        ('suggestion_corner', '0003_suggestioncornerstorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionCornerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorni_sollecito_1', models.PositiveIntegerField(default=30)),
                ('giorni_sollecito_2', models.PositiveIntegerField(default=15)),
                ('giorni_sollecito_3', models.PositiveIntegerField(default=5)),
                ('giorni_escalation_oltre_scadenza', models.PositiveIntegerField(default=7)),
                ('email_responsabile_escalation', models.EmailField(blank=True, max_length=254)),
                ('sms_team_group_name', models.CharField(default='SMS_TEAM', max_length=100)),
            ],
            options={
                'verbose_name': 'Configurazione Suggestion Corner',
                'verbose_name_plural': 'Configurazione Suggestion Corner',
            },
        ),
        migrations.CreateModel(
            name='SuggestionCornerProcessoMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_libero', models.CharField(max_length=255, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_mapping', to='anagrafica.processoqualificato')),
            ],
            options={
                'verbose_name': 'Mappatura processo',
                'verbose_name_plural': 'Mappature processi (Suggestion Corner)',
                'ordering': ['valore_libero'],
            },
        ),
    ]
