# Generated by Django 5.2.11 on 2026-07-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion_corner', '0004_suggestioncornerconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestioncorner',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='suggestioncorner',
            name='cliente_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='suggestioncorner',
            name='comunicazione_cliente_inviata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suggestioncorner',
            name='data_comunicazione_cliente',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
