# Generated by Django 5.2.11 on 2026-07-10 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0082_dipendente_area_aziendale_fk'),
        ('suggestion_corner', '0005_suggestioncorner_cliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestioncorner',
            name='area_destinazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='segnalazioni_area_destinazione', to='anagrafica.areaaziendale'),
        ),
        migrations.AddField(
            model_name='suggestioncorner',
            name='area_provenienza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='segnalazioni_area_provenienza', to='anagrafica.areaaziendale'),
        ),
        migrations.AlterField(
            model_name='suggestioncorner',
            name='reparto_provenienza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='segnalazioni_provenienza', to='anagrafica.reparto'),
        ),
    ]
