# Generated by Django 5.2.16 on 2026-10-07 07:49

import core.private_attachments
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion_corner', '0006_suggestioncorner_area_destinazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestioncornerallegato',
            name='file',
            field=models.FileField(blank=True, storage=core.private_attachments.PrivateAttachmentStorage(download_hint='Allegato segnalazione: non esposto via URL.'), upload_to='suggestion_corner/%Y/'),
        ),
    ]
