# Generated by Django 5.2.11 on 2026-04-21 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_system_roles(apps, schema_editor):
    RoleDefinition = apps.get_model("anomalie", "AnomalieRoleDefinition")
    RoleAccessRule = apps.get_model("anomalie", "AnomalieRoleAccessRule")
    seeds = (
        (
            "CC",
            "Capocommessa",
            "Ruolo collegato al campo Capocommessa dell'OP.",
            10,
            "EDIT_ASSIGNED",
        ),
        (
            "CAR",
            "CAR / Incaricato",
            "Ruolo collegato al campo Incaricato/CAR dell'OP.",
            20,
            "EDIT_ASSIGNED",
        ),
    )
    for code, name, description, order_index, access_level in seeds:
        RoleDefinition.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "description": description,
                "is_system": True,
                "is_active": True,
                "order_index": order_index,
            },
        )
        RoleAccessRule.objects.update_or_create(
            role_type=code,
            defaults={"access_level": access_level},
        )


def unseed_system_roles(apps, schema_editor):
    RoleDefinition = apps.get_model("anomalie", "AnomalieRoleDefinition")
    RoleAccessRule = apps.get_model("anomalie", "AnomalieRoleAccessRule")
    RoleDefinition.objects.filter(code__in=["CC", "CAR"], is_system=True).delete()
    RoleAccessRule.objects.filter(role_type__in=["CC", "CAR"]).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalieRoleAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(db_index=True, max_length=32, unique=True)),
                ('access_level', models.CharField(choices=[('NONE', 'Nessun accesso extra'), ('READ_ALL', 'Vede tutto'), ('EDIT_ASSIGNED', 'Modifica solo anomalie in carico'), ('EDIT_ALL', 'Modifica tutto')], db_index=True, default='NONE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regola accesso ruolo anomalie',
                'verbose_name_plural': 'Regole accesso ruoli anomalie',
                'ordering': ['role_type'],
            },
        ),
        migrations.CreateModel(
            name='AnomalieRoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order_index', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ruolo operativo anomalie',
                'verbose_name_plural': 'Ruoli operativi anomalie',
                'ordering': ['order_index', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnomalieUserAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('NONE', 'Nessun accesso extra'), ('READ_ALL', 'Vede tutto'), ('EDIT_ASSIGNED', 'Modifica solo anomalie in carico'), ('EDIT_ALL', 'Modifica tutto')], db_index=True, default='READ_ALL', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anomalie_access_rule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Override accesso utente anomalie',
                'verbose_name_plural': 'Override accesso utenti anomalie',
                'ordering': ['user__last_name', 'user__first_name', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='AnomalieRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalie_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role_type', 'user__last_name', 'user__first_name', 'user_id'],
                'unique_together': {('user', 'role_type')},
            },
        ),
        migrations.RunPython(seed_system_roles, unseed_system_roles),
    ]
