# Generated by Django 5.2.11 on 2026-04-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalieLegacyRoleAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_role_id', models.IntegerField(db_index=True, unique=True)),
                ('legacy_role_name', models.CharField(blank=True, default='', max_length=100)),
                ('access_level', models.CharField(choices=[('NONE', 'Nessun accesso extra'), ('READ_ALL', 'Vede tutto'), ('EDIT_ASSIGNED', 'Modifica solo anomalie in carico'), ('EDIT_ALL', 'Modifica tutto')], db_index=True, default='READ_ALL', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regola accesso ruolo aziendale anomalie',
                'verbose_name_plural': 'Regole accesso ruoli aziendali anomalie',
                'ordering': ['legacy_role_name', 'legacy_role_id'],
            },
        ),
    ]
