# Generated by Django 5.2.11 on 2026-06-04 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0036_dipendenteanagraficacivile_figli_a_carico_and_more'),
        ('anomalie', '0003_anomalie_list_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomalieroleaccessrule',
            options={'ordering': ['role_type', 'ruolo_operativo_id'], 'verbose_name': 'Regola accesso ruolo anomalie', 'verbose_name_plural': 'Regole accesso ruoli anomalie'},
        ),
        migrations.AddField(
            model_name='anomalieroleaccessrule',
            name='ruolo_operativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalie_access_rules', to='anagrafica.ruolooperativo'),
        ),
        migrations.AlterField(
            model_name='anomalieroleaccessrule',
            name='role_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
