# Generated by Django 5.2.11 on 2026-06-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalie', '0006_anomaliamailactiontoken_anomaliaactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomaliaPendingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('op_nominativo', models.CharField(blank=True, default='', max_length=255)),
                ('last_modified_at', models.DateTimeField(db_index=True)),
                ('last_modified_by', models.CharField(blank=True, default='', max_length=200)),
                ('updates_snapshot', models.JSONField(blank=True, default=list)),
                ('notified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notifica anomalie in attesa',
                'verbose_name_plural': 'Notifiche anomalie in attesa',
                'indexes': [models.Index(fields=['notified', 'last_modified_at'], name='anom_pending_notif_idx')],
            },
        ),
    ]
