# Generated by Django 5.2.11 on 2026-06-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalie', '0007_anomaliapendingnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaliapendingnotification',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anomaliapendingnotification',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
