# Generated by Django 5.2.16 on 2026-09-16 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalie', '0008_anomaliapendingnotification_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalieEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mail_action', 'Mail-action (link azione)'), ('conferma_aggiornamenti', 'Conferma aggiornamenti'), ('escalation_resoconto', 'Resoconto escalation'), ('alert_admin', 'Alert amministratori'), ('altro', 'Altro')], db_index=True, default='altro', max_length=32)),
                ('status', models.CharField(choices=[('sent', 'Inviata'), ('failed', 'Fallita')], db_index=True, default='sent', max_length=16)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('from_email', models.CharField(blank=True, default='', max_length=254)),
                ('to_emails', models.JSONField(blank=True, default=list)),
                ('cc_emails', models.JSONField(blank=True, default=list)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('op_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalie_email_logs', to=settings.AUTH_USER_MODEL)),
                ('resend_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resends', to='anomalie.anomalieemaillog')),
            ],
            options={
                'verbose_name': 'Log email anomalie',
                'verbose_name_plural': 'Log email anomalie',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='anom_maillog_created_idx')],
            },
        ),
    ]
