# Generated by Django 5.2.16 on 2026-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalie', '0009_anomalieemaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalieemaillog',
            name='kind',
            field=models.CharField(choices=[('mail_action', 'Mail-action (link azione)'), ('conferma_aggiornamenti', 'Conferma aggiornamenti'), ('escalation_resoconto', 'Resoconto escalation'), ('ricorrenza_pn', 'Difetto ricorrente per P/N'), ('digest_settimanale', 'Digest settimanale KPI'), ('op_completato', 'OP completato'), ('alert_admin', 'Alert amministratori'), ('altro', 'Altro')], db_index=True, default='altro', max_length=32),
        ),
        migrations.CreateModel(
            name='AnomalieAutomazioneMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('resoconto', 'Resoconto giornaliero inviato'), ('ricorrenza_pn', 'Allarme difetto ricorrente P/N'), ('digest', 'Digest settimanale inviato'), ('op_completato', 'OP completato notificato')], db_index=True, max_length=32)),
                ('chiave', models.CharField(max_length=255)),
                ('dettaglio', models.JSONField(blank=True, default=dict)),
                ('creato_il', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Marcatore automazione anomalie',
                'verbose_name_plural': 'Marcatori automazioni anomalie',
                'ordering': ['-creato_il'],
                'indexes': [models.Index(fields=['tipo', 'chiave'], name='anomalie_marker_tipo_chiave')],
            },
        ),
    ]
