# Generated by Django 5.2.16 on 2026-09-26 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Catalogo iniziale dei difetti tipici di lavorazione meccanica di precisione:
# modificabile da Configurazione > Qualita'. Idempotente (get_or_create per codice).
CATALOGO_INIZIALE = [
    ("fuori-tolleranza", "Fuori tolleranza dimensionale", "Dimensionale"),
    ("geometria", "Tolleranza geometrica non rispettata", "Dimensionale"),
    ("filettatura", "Filettatura non conforme", "Dimensionale"),
    ("lavorazione-mancante", "Lavorazione mancante o errata", "Lavorazione"),
    ("rugosita", "Rugosità non conforme", "Superficie"),
    ("difetto-superficiale", "Difetto superficiale (graffi, ammaccature, impronte)", "Superficie"),
    ("bave-spigoli", "Bave / spigoli non conformi", "Superficie"),
    ("trattamento", "Difetto di trattamento o finitura", "Trattamenti"),
    ("materiale", "Materiale non conforme", "Materiale"),
    ("movimentazione", "Danneggiamento da movimentazione", "Logistica"),
    ("marcatura-documenti", "Errore di marcatura o documentale", "Documentazione"),
    ("altro", "Altro", "Altro"),
]


def seed_catalogo(apps, schema_editor):
    Tipo = apps.get_model("anomalie", "AnomaliaTipoDifetto")
    for i, (codice, nome, famiglia) in enumerate(CATALOGO_INIZIALE, start=1):
        Tipo.objects.get_or_create(
            codice=codice, defaults={"nome": nome, "famiglia": famiglia, "ordine": i * 10},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0127_visitamedica_superata_e_famiglia'),
        ('anomalie', '0010_automazioni_marker'),
        ('gestione_specifiche', '0013_registroofi_azioneofi_registro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomaliaTipoDifetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.SlugField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('famiglia', models.CharField(blank=True, default='', max_length=80)),
                ('attivo', models.BooleanField(db_index=True, default=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo difetto anomalie',
                'verbose_name_plural': 'Catalogo tipi difetto anomalie',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AnomaliaSchedaQualita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomalia_id', models.IntegerField(db_index=True, unique=True)),
                ('protocollo', models.CharField(max_length=20, unique=True)),
                ('op_titolo', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('part_number', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('origine', models.CharField(blank=True, choices=[('PRODUZIONE', 'Interna - produzione'), ('CONTROLLO', 'Interna - controllo qualità'), ('FORNITORE', 'Fornitore / lavorazione esterna'), ('CLIENTE', 'Cliente'), ('AUDIT', 'Audit')], default='', max_length=12)),
                ('gravita', models.CharField(blank=True, choices=[('MINORE', 'Minore'), ('MAGGIORE', 'Maggiore'), ('CRITICA', 'Critica')], default='', max_length=10)),
                ('quantita_nc', models.PositiveIntegerField(blank=True, null=True)),
                ('quantita_scartata', models.PositiveIntegerField(blank=True, null=True)),
                ('disposizione', models.CharField(choices=[('DA_DEFINIRE', 'Da definire'), ('USO_TALE', "Uso così com'è"), ('RILAVORAZIONE', 'Rilavorazione'), ('RIPARAZIONE', 'Riparazione'), ('DEROGA', 'Concessione / deroga cliente'), ('SCARTO', 'Scarto'), ('RESO_FORNITORE', 'Reso al fornitore')], default='DA_DEFINIRE', max_length=16)),
                ('disposizione_auto', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registro_nc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schede_anomalie', to='gestione_specifiche.registroofi')),
                ('reparto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='anagrafica.reparto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_difetto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schede', to='anomalie.anomaliatipodifetto')),
            ],
            options={
                'verbose_name': 'Scheda qualità anomalia',
                'verbose_name_plural': 'Schede qualità anomalie',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['part_number', 'tipo_difetto'], name='anomalie_sq_pn_difetto')],
            },
        ),
        migrations.RunPython(seed_catalogo, migrations.RunPython.noop),
    ]
