# Generated by Django 5.2.16 on 2026-09-26 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def raggruppa_schede_per_op(apps, schema_editor):
    """Le schede gia' esistenti (una per anomalia) confluiscono in una NC per OP."""
    Scheda = apps.get_model("anomalie", "AnomaliaSchedaQualita")
    NC = apps.get_model("anomalie", "AnomaliaNC")
    per_op: dict = {}
    for s in Scheda.objects.filter(nc__isnull=True).order_by("anomalia_id"):
        per_op.setdefault((s.op_titolo or "").strip(), []).append(s)
    contatori: dict = {}
    for op, schede in per_op.items():
        if not op:
            continue
        anno = schede[0].created_at.year
        contatori[anno] = contatori.get(anno, 0) + 1
        nc = NC.objects.create(
            protocollo=f"NC-{anno}-{contatori[anno]:04d}",
            op_titolo=op[:100],
            part_number=schede[0].part_number,
        )
        Scheda.objects.filter(pk__in=[s.pk for s in schede]).update(nc=nc)

class Migration(migrations.Migration):

    dependencies = [
        ('anomalie', '0011_scheda_qualita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomaliaschedaqualita',
            name='protocollo',
        ),
        migrations.RemoveField(
            model_name='anomaliaschedaqualita',
            name='registro_nc',
        ),
        migrations.CreateModel(
            name='AnomaliaNC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocollo', models.CharField(max_length=20, unique=True)),
                ('op_titolo', models.CharField(db_index=True, max_length=100)),
                ('part_number', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('capocommessa', models.CharField(blank=True, default='', max_length=200)),
                ('car', models.CharField(blank=True, default='', max_length=200)),
                ('stato', models.CharField(choices=[('APERTA', 'Aperta'), ('CONTENIMENTO', 'Contenimento'), ('ANALISI', 'Analisi cause'), ('AZIONI', 'Azioni in corso'), ('VERIFICA', 'In verifica'), ('CHIUSA', 'Chiusa')], db_index=True, default='APERTA', max_length=14)),
                ('contenimento', models.TextField(blank=True, default='')),
                ('contenimento_data', models.DateField(blank=True, null=True)),
                ('contenimento_da', models.CharField(blank=True, default='', max_length=150)),
                ('analisi_metodo', models.CharField(blank=True, choices=[('CINQUE_PERCHE', '5 perché'), ('ISHIKAWA', 'Ishikawa (6M)'), ('ESTERNA', 'Documento esterno')], default='', max_length=14)),
                ('analisi_perche', models.JSONField(blank=True, default=list)),
                ('analisi_ishikawa', models.JSONField(blank=True, default=dict)),
                ('analisi_riferimento', models.CharField(blank=True, default='', max_length=300)),
                ('causa_radice', models.TextField(blank=True, default='')),
                ('analisi_data', models.DateField(blank=True, null=True)),
                ('analisi_da', models.CharField(blank=True, default='', max_length=150)),
                ('verifica_prevista', models.DateField(blank=True, null=True)),
                ('verifica_data', models.DateField(blank=True, null=True)),
                ('verifica_esito', models.CharField(blank=True, choices=[('EFFICACE', 'Efficace'), ('NON_EFFICACE', 'Non efficace')], default='', max_length=14)),
                ('verifica_note', models.TextField(blank=True, default='')),
                ('verifica_da', models.CharField(blank=True, default='', max_length=150)),
                ('chiusa_il', models.DateTimeField(blank=True, null=True)),
                ('note_chiusura', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chiusa_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('precedente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ricadute', to='anomalie.anomalianc')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Non conformità (per OP)',
                'verbose_name_plural': 'Non conformità (per OP)',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='anomaliaschedaqualita',
            name='nc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schede', to='anomalie.anomalianc'),
        ),
        migrations.CreateModel(
            name='AnomaliaNCAllegato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezione', models.CharField(choices=[('CONTENIMENTO', 'Contenimento'), ('ANALISI', 'Analisi cause'), ('AZIONI', 'Azioni'), ('VERIFICA', 'Verifica'), ('ALTRO', 'Altro')], default='ALTRO', max_length=12)),
                ('nome', models.CharField(max_length=255)),
                ('file_rel', models.CharField(max_length=400)),
                ('size', models.PositiveIntegerField(default=0)),
                ('mime', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='anomalie.anomalianc')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Allegato NC',
                'verbose_name_plural': 'Allegati NC',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnomaliaNCAzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField()),
                ('tipo', models.CharField(choices=[('CORRETTIVA', 'Correttiva'), ('PREVENTIVA', 'Preventiva')], default='CORRETTIVA', max_length=12)),
                ('responsabile_legacy_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('responsabile_nome', models.CharField(blank=True, default='', max_length=200)),
                ('scadenza', models.DateField(blank=True, db_index=True, null=True)),
                ('stato', models.CharField(choices=[('DA_FARE', 'Da fare'), ('IN_CORSO', 'In corso'), ('FATTA', 'Fatta'), ('ANNULLATA', 'Annullata')], db_index=True, default='DA_FARE', max_length=10)),
                ('completata_il', models.DateField(blank=True, null=True)),
                ('esito', models.TextField(blank=True, default='')),
                ('promemoria_il', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azioni', to='anomalie.anomalianc')),
            ],
            options={
                'verbose_name': 'Azione NC',
                'verbose_name_plural': 'Azioni NC',
                'ordering': ['scadenza', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnomaliaNCEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('testo', models.CharField(max_length=500)),
                ('user_nome', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='anomalie.anomalianc')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento NC',
                'verbose_name_plural': 'Eventi NC',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='anomalianc',
            index=models.Index(fields=['op_titolo', 'stato'], name='anomalie_nc_op_stato'),
        ),
        migrations.RunPython(raggruppa_schede_per_op, migrations.RunPython.noop),
    ]
