# Generated by Django 5.2.16 on 2026-10-05 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalie', '0012_nc_per_op'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomaliaSegnalazioneMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomalia_id', models.IntegerField(db_index=True, unique=True)),
                ('fase', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segnalazioni_fase', to='anomalie.anomalianc')),
            ],
            options={
                'verbose_name': 'Fase segnalazione anomalia',
                'verbose_name_plural': 'Fasi segnalazioni anomalie',
                'ordering': ['-id'],
            },
        ),
    ]
