# Generated by Django 5.2.16 on 2026-10-05 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalie', '0013_anomaliasegnalazionemeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomaliaDescrizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('seriali', models.JSONField(blank=True, default=list)),
                ('testo', models.TextField()),
                ('risposta_capocommessa', models.TextField(blank=True, default='')),
                ('risposta_da', models.CharField(blank=True, default='', max_length=200)),
                ('risposta_il', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segnalazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descrizioni', to='anomalie.anomaliasegnalazionemeta')),
            ],
            options={
                'verbose_name': 'Descrizione segnalazione anomalia',
                'verbose_name_plural': 'Descrizioni segnalazioni anomalie',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnomaliaDescrizioneAllegato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('file_rel', models.CharField(max_length=400)),
                ('size', models.PositiveIntegerField(default=0)),
                ('mime', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('descrizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='anomalie.anomaliadescrizione')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Allegato descrizione anomalia',
                'verbose_name_plural': 'Allegati descrizioni anomalia',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
