# Generated by Django 5.2.16 on 2026-10-06 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalie', '0014_anomaliadescrizione_anomaliadescrizioneallegato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomaliaBlocco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('fase', models.CharField(max_length=100)),
                ('seriali', models.JSONField(blank=True, default=list)),
                ('seriale_label', models.CharField(blank=True, default='', max_length=200)),
                ('stato_superficie', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blocco seriali controllo',
                'verbose_name_plural': 'Blocchi seriali controllo',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.AddField(
            model_name='anomaliasegnalazionemeta',
            name='ordine_nel_blocco',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anomaliasegnalazionemeta',
            name='blocco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segnalazioni', to='anomalie.anomaliablocco'),
        ),
        migrations.CreateModel(
            name='AnomaliaControllo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.CharField(db_index=True, max_length=100)),
                ('op_item_id', models.CharField(blank=True, default='', max_length=100)),
                ('fase', models.CharField(max_length=100)),
                ('mail_mode', models.CharField(choices=[('subito', 'A ogni salvataggio'), ('fine', 'Unica mail a fine controllo')], default='subito', max_length=10)),
                ('operatore_display', models.CharField(blank=True, default='', max_length=200)),
                ('terminato_at', models.DateTimeField(blank=True, null=True)),
                ('ultimo_salvataggio_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('da_notificare', models.JSONField(blank=True, default=list)),
                ('ultima_mail_at', models.DateTimeField(blank=True, null=True)),
                ('mail_tentativi', models.PositiveSmallIntegerField(default=0)),
                ('mail_errore', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Controllo OP',
                'verbose_name_plural': 'Controlli OP',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='anomaliablocco',
            name='controllo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocchi', to='anomalie.anomaliacontrollo'),
        ),
        migrations.AddField(
            model_name='anomaliasegnalazionemeta',
            name='controllo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segnalazioni', to='anomalie.anomaliacontrollo'),
        ),
    ]
