from django.urls import include, path

from . import api, views


app_name = "admin_portale"

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.index, name="home"),
    path("automazioni/", include("automazioni.urls")),
    path("utenti/", views.utenti_list, name="utenti_list"),
    path("utenti/create", views.utente_create, name="utente_create"),
    path("utenti/<int:user_id>/", views.utente_edit, name="utente_edit"),
    path("utenti/<int:user_id>/permessi/", views.utente_permessi_effettivi, name="utente_permessi_effettivi"),
    path("utenti/<int:user_id>/update", views.utente_update, name="utente_update"),
    path("utenti/<int:user_id>/quick-role", views.utente_quick_role, name="utente_quick_role"),
    path("utenti/<int:user_id>/toggle-active", views.utente_toggle_active, name="utente_toggle_active"),
    path("utenti/<int:user_id>/delete", views.utente_delete, name="utente_delete"),
    path("utenti/<int:user_id>/impersonate", views.utente_impersonate, name="utente_impersonate"),
    path(
        "utenti/<int:user_id>/force-change-password",
        views.utente_force_change_password,
        name="utente_force_change_password",
    ),
    path("utenti/bulk-role", views.utenti_bulk_role, name="utenti_bulk_role"),
    path("utenti/bulk-action", views.utenti_bulk_action, name="utenti_bulk_action"),
    path("permessi/", views.permessi, name="permessi"),
    path("pulsanti/", views.pulsanti, name="pulsanti"),
    path("topbar-live/", views.topbar_live, name="topbar_live"),
    path("navigation-builder/", views.navigation_builder, name="navigation_builder"),
    path("schema-dati/", views.schema_dati, name="schema_dati"),
    path("acl/", views.acl_diagnostica, name="acl_diagnostica"),
    path("ldap/", views.ldap_diagnostica, name="ldap_diagnostica"),
    path("api/permessi/toggle", api.api_permessi_toggle, name="api_permessi_toggle"),
    path("api/permessi/bulk", api.api_permessi_bulk, name="api_permessi_bulk"),
    path("api/permessi/modulo-set", views.api_permessi_modulo_set, name="api_permessi_modulo_set"),
    path("api/utenti/<int:user_id>/modulo-perm-set", views.api_user_modulo_perm_set, name="api_user_modulo_perm_set"),
    path("api/pulsanti/create", api.api_pulsanti_create, name="api_pulsanti_create"),
    path("api/pulsanti/update", api.api_pulsanti_update, name="api_pulsanti_update"),
    path("api/pulsanti/delete", api.api_pulsanti_delete, name="api_pulsanti_delete"),
    path("api/pulsanti/card-image", views.api_pulsanti_card_image, name="api_pulsanti_card_image"),
    path("wizard-pulsante/", views.wizard_pulsante, name="wizard_pulsante"),
    path("api/wizard/pulsante/submit/", views.api_wizard_pulsante_submit, name="api_wizard_pulsante_submit"),
    path("api/pulsanti/set-enabled", views.api_pulsanti_set_enabled, name="api_pulsanti_set_enabled"),
    path("api/modulo-crea-da-catalog/", views.api_modulo_crea_da_catalog, name="api_modulo_crea_da_catalog"),
    path("api/utenti/<int:user_id>/perm-override", views.api_user_perm_override, name="api_user_perm_override"),
    path("api/utenti/<int:user_id>/dashboard-toggle", views.api_user_dashboard_toggle, name="api_user_dashboard_toggle"),
    path("api/utenti/<int:user_id>/module-toggle", views.api_user_module_toggle, name="api_user_module_toggle"),
    path("api/utenti/<int:user_id>/extra-info", views.api_user_extra_info, name="api_user_extra_info"),
    path("api/utenti/<int:user_id>/asset-assignments", views.api_user_asset_assignments, name="api_user_asset_assignments"),
    path("api/navigation/create", views.api_navigation_item_create, name="api_navigation_item_create"),
    path("api/navigation/update", views.api_navigation_item_update, name="api_navigation_item_update"),
    path("api/navigation/delete", views.api_navigation_item_delete, name="api_navigation_item_delete"),
    path("api/navigation/reorder", views.api_navigation_reorder, name="api_navigation_reorder"),
    path("api/navigation/bootstrap-legacy", views.api_navigation_bootstrap_from_legacy, name="api_navigation_bootstrap_from_legacy"),
    path("api/navigation/publish", views.api_navigation_publish, name="api_navigation_publish"),
    path("api/navigation/restore", views.api_navigation_restore, name="api_navigation_restore"),
    path("api/navigation/redirect/upsert", views.api_legacy_redirect_upsert, name="api_legacy_redirect_upsert"),
    path("api/navigation/redirect/delete", views.api_legacy_redirect_delete, name="api_legacy_redirect_delete"),
    path("anagrafica-config/", views.anagrafica_config, name="anagrafica_config"),
    path("anagrafica-config/import-csv", views.anagrafica_import_csv, name="anagrafica_import_csv"),
    path("login-config/", views.login_config, name="login_config"),
    path("api/login-config/save", views.api_login_config_save, name="api_login_config_save"),
    path("api/login-config/logo/upload", views.api_login_logo_upload, name="api_login_logo_upload"),
    path("api/login-config/logo/remove", views.api_login_logo_remove, name="api_login_logo_remove"),
    path("api/login-config/banner/create", views.api_login_banner_create, name="api_login_banner_create"),
    path("api/login-config/banner/toggle", views.api_login_banner_toggle, name="api_login_banner_toggle"),
    path("api/login-config/banner/delete", views.api_login_banner_delete, name="api_login_banner_delete"),
    path("api/opzioni/create", views.api_opzione_create, name="api_opzione_create"),
    path("api/opzioni/update", views.api_opzione_update, name="api_opzione_update"),
    path("api/opzioni/toggle", views.api_opzione_toggle, name="api_opzione_toggle"),
    path("api/opzioni/delete", views.api_opzione_delete, name="api_opzione_delete"),
    path("api/reparto-capo/set",    views.api_reparto_capo_set,    name="api_reparto_capo_set"),
    path("api/reparto-capo/delete", views.api_reparto_capo_delete, name="api_reparto_capo_delete"),
    path("api/reparto-capo/sync",   views.api_reparto_capo_sync,   name="api_reparto_capo_sync"),
    path("api/anagrafica/voce/create", views.api_anagrafica_voce_create, name="api_anagrafica_voce_create"),
    path("api/anagrafica/voce/update", views.api_anagrafica_voce_update, name="api_anagrafica_voce_update"),
    path("api/anagrafica/voce/toggle", views.api_anagrafica_voce_toggle, name="api_anagrafica_voce_toggle"),
    path("api/anagrafica/voce/delete", views.api_anagrafica_voce_delete, name="api_anagrafica_voce_delete"),
    path("api/utenti/<int:user_id>/anagrafica-risposte", views.api_anagrafica_risposte_save, name="api_anagrafica_risposte_save"),
    path("checklist/", views.checklist_index, name="checklist_index"),
    path("checklist/utenti/<int:user_id>/", views.checklist_utente, name="checklist_utente"),
    path("api/checklist/voce/create", views.api_checklist_voce_create, name="api_checklist_voce_create"),
    path("api/checklist/voce/update", views.api_checklist_voce_update, name="api_checklist_voce_update"),
    path("api/checklist/voce/toggle", views.api_checklist_voce_toggle, name="api_checklist_voce_toggle"),
    path("api/checklist/voce/delete", views.api_checklist_voce_delete, name="api_checklist_voce_delete"),
    path("api/checklist/esegui/<int:user_id>", views.api_checklist_esegui, name="api_checklist_esegui"),
    path("audit/", views.audit_log_view, name="audit_log"),
    path("health/", views.admin_health_check, name="health_check"),
    path("accessi/", views.accessi_semplice, name="accessi"),
    path("accessi-semplice/", views.accessi_semplice, name="accessi_semplice"),
    path("accessi-avanzati/", views.accessi_dashboard, name="accessi_avanzati"),
    path("wizard-ruolo/", views.wizard_ruolo, name="wizard_ruolo"),
    path("guestportal-sso/", views.guestportal_sso, name="guestportal_sso"),
]
