# Generated by Django 5.2.11 on 2026-06-23 10:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0079_assets_sidebar_clean_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('nome', models.CharField(blank=True, default='', max_length=200)),
                ('cliente', models.CharField(blank=True, default='', max_length=200)),
                ('pezzo', models.CharField(blank=True, default='', max_length=200)),
                ('quantita', models.PositiveIntegerField(blank=True, null=True)),
                ('data_consegna', models.DateField(blank=True, db_index=True, null=True)),
                ('priorita', models.PositiveSmallIntegerField(choices=[(1, 'Bassa'), (2, 'Normale'), (3, 'Alta'), (4, 'Urgente')], default=2)),
                ('stato', models.CharField(choices=[('aperta', 'Aperta'), ('in_corso', 'In corso'), ('chiusa', 'Chiusa'), ('sospesa', 'Sospesa')], default='aperta', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commessa',
                'verbose_name_plural': 'Commesse',
                'ordering': ['-priorita', 'data_consegna', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FamigliaPezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Famiglia pezzo',
                'verbose_name_plural': 'Famiglie pezzo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CicloStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('nome', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('famiglia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cicli', to='gestione_carichi_macchina.famigliapezzo')),
            ],
            options={
                'verbose_name': 'Ciclo standard',
                'verbose_name_plural': 'Cicli standard',
                'ordering': ['codice', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Macchina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('4_axis', 'Macchine 4 assi'), ('5_axis', 'Macchine 5 assi'), ('torni', 'Torni'), ('torni_fresa', 'Torni fresa'), ('alesatrici', 'Alesatrici')], db_index=True, max_length=20)),
                ('attacco', models.CharField(choices=[('HSK', 'HSK'), ('ISO40', 'ISO40'), ('-', 'Non applicabile')], default='-', max_length=8)),
                ('n_assi', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ha_turno_notte', models.BooleanField(default=False)),
                ('ore_giorno_disponibili', models.DecimalField(decimal_places=1, default=Decimal('8.0'), max_digits=4)),
                ('stato_pianificazione', models.CharField(choices=[('attiva', 'Attiva'), ('guasto', 'Guasto'), ('manutenzione', 'Manutenzione')], db_index=True, default='attiva', max_length=16)),
                ('ordine_sezione', models.PositiveIntegerField(default=0)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(help_text='Asset esistente che questa riga di pianificazione rappresenta.', on_delete=django.db.models.deletion.PROTECT, related_name='profilo_carichi', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Macchina (profilo carichi)',
                'verbose_name_plural': 'Macchine (profili carichi)',
                'ordering': ['categoria', 'ordine_sezione', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MacchinaAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_foglio', models.CharField(db_index=True, max_length=64)),
                ('fonte', models.CharField(choices=[('asset_tag', 'Da asset_tag'), ('name', 'Da name'), ('manuale', 'Manuale')], default='manuale', max_length=16)),
                ('da_confermare', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('macchina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='gestione_carichi_macchina.macchina')),
            ],
            options={
                'verbose_name': 'Alias macchina',
                'verbose_name_plural': 'Alias macchina',
            },
        ),
        migrations.CreateModel(
            name='MacchinaFamigliaAffinita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occorrenze', models.PositiveIntegerField(default=0)),
                ('ore_medie', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ultima_data', models.DateField(blank=True, null=True)),
                ('pool_equivalenza', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('da_confermare', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('famiglia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinita', to='gestione_carichi_macchina.famigliapezzo')),
                ('macchina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinita', to='gestione_carichi_macchina.macchina')),
            ],
            options={
                'verbose_name': "Affinita' macchina/famiglia",
                'verbose_name_plural': "Affinita' macchina/famiglia",
                'ordering': ['-occorrenze'],
            },
        ),
        migrations.CreateModel(
            name='Operazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField(help_text='Numero op (op1, op2...).')),
                ('regola_sostituzione', models.TextField(blank=True, default='')),
                ('tempo_cent_cad', models.PositiveIntegerField(blank=True, help_text="Tempo standard in centesimi d'ora a pezzo.", null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operazioni', to='gestione_carichi_macchina.ciclostandard')),
                ('macchina_preferita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operazioni_preferite', to='gestione_carichi_macchina.macchina')),
                ('macchine_alternative', models.ManyToManyField(blank=True, related_name='operazioni_alternative', to='gestione_carichi_macchina.macchina')),
            ],
            options={
                'verbose_name': 'Operazione',
                'verbose_name_plural': 'Operazioni',
                'ordering': ['ciclo', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='Pianificazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('turno', models.CharField(choices=[('giorno', 'Giorno'), ('notte', 'Notte')], default='giorno', max_length=8)),
                ('qta', models.PositiveIntegerField(blank=True, null=True)),
                ('ore', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stato', models.CharField(choices=[('pianificata', 'Pianificata'), ('in_corso', 'In corso'), ('completata', 'Completata')], db_index=True, default='pianificata', max_length=16)),
                ('fase', models.CharField(blank=True, choices=[('', '—'), ('sgr', 'Sgrossatura'), ('fin', 'Finitura'), ('rip', 'Ripresa'), ('ass', 'Assemblaggio')], default='', max_length=8)),
                ('testo_originale', models.TextField(blank=True, default='')),
                ('settimane_presente', models.PositiveIntegerField(default=1)),
                ('fonte', models.CharField(choices=[('import', 'Import'), ('manuale', 'Manuale'), ('ai', 'AI')], default='import', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commessa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pianificazioni', to='gestione_carichi_macchina.commessa')),
                ('famiglia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pianificazioni', to='gestione_carichi_macchina.famigliapezzo')),
                ('macchina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pianificazioni', to='gestione_carichi_macchina.macchina')),
                ('operazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pianificazioni', to='gestione_carichi_macchina.operazione')),
            ],
            options={
                'verbose_name': 'Pianificazione',
                'verbose_name_plural': 'Pianificazioni',
                'ordering': ['data', 'macchina', 'turno'],
            },
        ),
        migrations.CreateModel(
            name='FamigliaAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=80)),
                ('famiglia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='gestione_carichi_macchina.famigliapezzo')),
            ],
            options={
                'verbose_name': 'Alias famiglia',
                'verbose_name_plural': 'Alias famiglia',
                'constraints': [models.UniqueConstraint(fields=('alias',), name='gcm_uniq_famiglia_alias')],
            },
        ),
        migrations.AddIndex(
            model_name='macchina',
            index=models.Index(fields=['categoria', 'ordine_sezione'], name='gestione_ca_categor_4f60c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='macchinaalias',
            constraint=models.UniqueConstraint(fields=('codice_foglio',), name='gcm_uniq_alias_codice_foglio'),
        ),
        migrations.AddIndex(
            model_name='macchinafamigliaaffinita',
            index=models.Index(fields=['pool_equivalenza'], name='gestione_ca_pool_eq_288812_idx'),
        ),
        migrations.AddConstraint(
            model_name='macchinafamigliaaffinita',
            constraint=models.UniqueConstraint(fields=('macchina', 'famiglia'), name='gcm_uniq_affinita_macchina_famiglia'),
        ),
        migrations.AddConstraint(
            model_name='operazione',
            constraint=models.UniqueConstraint(fields=('ciclo', 'seq'), name='gcm_uniq_operazione_ciclo_seq'),
        ),
        migrations.AddIndex(
            model_name='pianificazione',
            index=models.Index(fields=['macchina', 'data'], name='gestione_ca_macchin_b41d33_idx'),
        ),
        migrations.AddIndex(
            model_name='pianificazione',
            index=models.Index(fields=['data', 'turno'], name='gestione_ca_data_7525d2_idx'),
        ),
    ]
