# Generated by Django 5.2.11 on 2026-06-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_carichi_macchina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macchina',
            name='ha_secondo_turno',
            field=models.BooleanField(default=False, help_text='Secondo turno di giorno (T2): non tutte le macchine lo hanno.'),
        ),
        migrations.AlterField(
            model_name='pianificazione',
            name='turno',
            field=models.CharField(choices=[('giorno', '1° turno'), ('t2', '2° turno'), ('notte', 'Notturno')], default='giorno', max_length=8),
        ),
    ]
