# Generated by Django 5.2.11 on 2026-06-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_carichi_macchina', '0002_macchina_ha_secondo_turno_alter_pianificazione_turno'),
        ('tasks', '0031_taskimpostazioni_roles_source_seed_caporeparto'),
    ]

    operations = [
        migrations.AddField(
            model_name='commessa',
            name='kickoff_project',
            field=models.ForeignKey(blank=True, help_text='Progetto KICK-OFF collegato a questa commessa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carichi_commesse', to='tasks.project'),
        ),
        migrations.AddField(
            model_name='pianificazione',
            name='kickoff_task',
            field=models.ForeignKey(blank=True, help_text='Attivita KICK-OFF di origine (se la pianificazione viene dal kickoff).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carichi_pianificazioni', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='pianificazione',
            name='fonte',
            field=models.CharField(choices=[('import', 'Import'), ('manuale', 'Manuale'), ('ai', 'AI'), ('kickoff', 'KICK-OFF')], default='import', max_length=8),
        ),
    ]
