# Generated by Django 5.2.11 on 2026-06-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_carichi_macchina', '0003_commessa_kickoff_project_pianificazione_kickoff_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macchinafamigliaaffinita',
            options={'ordering': ['-occorrenze', 'id'], 'verbose_name': "Affinita' macchina/famiglia", 'verbose_name_plural': "Affinita' macchina/famiglia"},
        ),
        migrations.AlterModelOptions(
            name='pianificazione',
            options={'ordering': ['data', 'macchina', 'turno', 'id'], 'verbose_name': 'Pianificazione', 'verbose_name_plural': 'Pianificazioni'},
        ),
    ]
