# Generated by Django 5.2.11 on 2026-06-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_carichi_macchina', '0004_alter_macchinafamigliaaffinita_options_and_more'),
        ('gestione_carichi_macchina', '0004_turni_estesi_e_label_fasi'),
    ]

    operations = [
    ]
