# Generated by Django 5.2.11 on 2026-06-30 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_carichi_macchina', '0005_merge_20260630_1118'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('utente_nome', models.CharField(blank=True, default='', max_length=150)),
                ('azione', models.CharField(choices=[('crea', 'Creazione lavoro'), ('modifica', 'Modifica lavoro'), ('elimina', 'Eliminazione lavoro'), ('sposta', 'Spostamento (reschedule)'), ('duplica', 'Duplicazione lavoro'), ('config', 'Config macchina'), ('undo', 'Annulla spostamento')], db_index=True, max_length=16)),
                ('macchina_cod', models.CharField(blank=True, default='', max_length=64)),
                ('pianificazione_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descrizione', models.CharField(blank=True, default='', max_length=255)),
                ('macchina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='azioni', to='gestione_carichi_macchina.macchina')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carichi_azioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Azione piano (log)',
                'verbose_name_plural': 'Azioni piano (log)',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='gestione_ca_created_f65a34_idx'), models.Index(fields=['macchina', '-created_at'], name='gestione_ca_macchin_43e3d5_idx')],
            },
        ),
    ]
