# Generated by Django 5.2.16 on 2026-10-01 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_aichatfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(db_index=True, max_length=40)),
                ('azione', models.CharField(db_index=True, max_length=60)),
                ('oggetto_ref', models.CharField(db_index=True, max_length=80)),
                ('proposta', models.JSONField(blank=True, default=dict)),
                ('decisione', models.JSONField(blank=True, default=dict)),
                ('campi_corretti', models.JSONField(blank=True, default=list)),
                ('esito', models.CharField(choices=[('in_attesa', 'In attesa'), ('accettata', 'Accettata'), ('modificata', 'Corretta'), ('scartata', 'Scartata'), ('superata', 'Superata da una nuova proposta')], db_index=True, default='in_attesa', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deciso_il', models.DateTimeField(blank=True, null=True)),
                ('deciso_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_proposte_decise', to=settings.AUTH_USER_MODEL)),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_proposte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'proposta AI',
                'verbose_name_plural': 'proposte AI',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['modulo', 'azione', 'esito'], name='ai_assistan_modulo_c1d082_idx')],
            },
        ),
    ]
