# Generated by Django 5.2.11 on 2026-03-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_nav_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
