# Generated by Django 5.2.11 on 2026-03-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_project_capo_commessa_project_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskImpostazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsabile_email', models.EmailField(blank=True, default='', help_text='Indirizzo email per notifiche di sistema (scadenze, assegnazioni).', max_length=254, verbose_name='Email notifiche')),
                ('notifiche_scadenza_attive', models.BooleanField(default=False, help_text='Invia email di promemoria X giorni prima della scadenza di un task.', verbose_name='Notifiche scadenza attive')),
                ('giorni_preavviso', models.PositiveSmallIntegerField(default=3, verbose_name='Giorni preavviso scadenza')),
                ('note_generali', models.TextField(blank=True, default='', verbose_name='Note generali')),
            ],
            options={
                'verbose_name': 'Impostazioni Task',
                'verbose_name_plural': 'Impostazioni Task',
            },
        ),
    ]
