# Generated by Django 5.2.11 on 2026-04-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_project_kickoff_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskimpostazioni',
            options={'verbose_name': 'Impostazioni KICK-OFF', 'verbose_name_plural': 'Impostazioni KICK-OFF'},
        ),
    ]
