# Generated by Django 5.2.11 on 2026-04-19 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_taskimpostazioni_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VRFRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('total_p', models.FloatField(default=0.0)),
                ('total_i', models.FloatField(default=0.0)),
                ('total_c', models.FloatField(default=0.0)),
                ('dig_triggered', models.BooleanField(default=False)),
                ('compiled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compiled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vrf_assessments_compiled', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vrf_assessment', to='tasks.project')),
            ],
            options={
                'verbose_name': 'Valutazione rischi VRF',
                'verbose_name_plural': 'Valutazioni rischi VRF',
            },
        ),
    ]
