# Generated by Django 5.2.11 on 2026-04-19 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_vrf_risk_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_portal_enabled',
            field=models.BooleanField(default=True, help_text="Se attivo, crea un promemoria nel centro notifiche 'giorni_preavviso' prima della scadenza."),
        ),
        migrations.CreateModel(
            name='TaskCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, max_length=160, unique=True)),
                ('target_email', models.EmailField(max_length=254)),
                ('target_display_name', models.CharField(blank=True, default='', max_length=200)),
                ('due_date', models.DateField()),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=64)),
                ('graph_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('graph_event_web_link', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_calendar_events_created', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_user_id', models.IntegerField(db_index=True)),
                ('fire_at', models.DateField(db_index=True)),
                ('fired', models.BooleanField(db_index=True, default=False)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_reminders', to='tasks.task')),
            ],
            options={
                'ordering': ['fire_at', 'id'],
                'indexes': [models.Index(fields=['fired', 'fire_at'], name='tasks_taskr_fired_7fa25f_idx')],
            },
        ),
    ]
