# Generated by Django 5.2.11 on 2026-04-19 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_outlook_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('PM', 'Project manager'), ('CC', 'Capocommessa'), ('PRG', 'Programmatore')], db_index=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role_type', 'user__last_name', 'user__first_name', 'user_id'],
                'unique_together': {('user', 'role_type')},
            },
        ),
    ]
