# Generated by Django 5.2.11 on 2026-04-20 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0047_alter_assetdetailsectionlayout_code'),
        ('tasks', '0016_task_role_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('order_index', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo attivita',
                'verbose_name_plural': 'Tipi attivita',
                'ordering': ['order_index', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskcategory'),
        ),
        migrations.CreateModel(
            name='TaskCategoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=180)),
                ('field_type', models.CharField(choices=[('text', 'Testo'), ('number', 'Numero'), ('date', 'Data'), ('checkbox', 'Checkbox'), ('select', 'Menu a tendina'), ('multiselect', 'Scelta multipla'), ('user', 'Utente'), ('asset', 'Asset')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(db_index=True, default=0)),
                ('help_text', models.CharField(blank=True, default='', max_length=255)),
                ('placeholder', models.CharField(blank=True, default='', max_length=120)),
                ('choices_json', models.JSONField(blank=True, default=list)),
                ('depends_on_code', models.CharField(blank=True, default='', max_length=60)),
                ('depends_on_value', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tasks.taskcategory')),
            ],
            options={
                'verbose_name': 'Campo tipo attivita',
                'verbose_name_plural': 'Campi tipo attivita',
                'ordering': ['order_index', 'id'],
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaskExtraRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.CharField(db_index=True, max_length=60)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_extra_refs', to='assets.asset')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_refs', to='tasks.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_extra_refs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'field_code'], name='tasks_taske_asset_i_71141e_idx'), models.Index(fields=['user', 'field_code'], name='tasks_taske_user_id_f933ce_idx')],
            },
        ),
    ]
