# Generated by Django 5.2.11 on 2026-04-21 07:26

from django.db import migrations, models


def seed_system_task_roles(apps, schema_editor):
    TaskRoleDefinition = apps.get_model("tasks", "TaskRoleDefinition")
    for code, name, description, order_index in (
        ("PM", "Project manager", "Ruolo collegato al campo Project manager del kickoff.", 10),
        ("CC", "Capocommessa", "Ruolo collegato al campo Capocommessa del kickoff.", 20),
        ("PRG", "Programmatore", "Ruolo collegato al campo Programmatore del kickoff.", 30),
    ):
        TaskRoleDefinition.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "description": description,
                "is_system": True,
                "is_active": True,
                "order_index": order_index,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_task_access_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order_index', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ruolo operativo task',
                'verbose_name_plural': 'Ruoli operativi task',
                'ordering': ['order_index', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='role_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Ruolo operativo autorizzato per questo tipo attivita.', max_length=32),
        ),
        migrations.AlterField(
            model_name='taskroleaccessrule',
            name='role_type',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='taskroleassignment',
            name='role_type',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.RunPython(seed_system_task_roles, migrations.RunPython.noop),
    ]
