# Generated by Django 5.2.11 on 2026-05-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_meetingissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='safety_impact',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica se il progetto ha impatto sulla sicurezza', verbose_name='Impatto sulla sicurezza'),
        ),
    ]
