# Generated by Django 5.2.11 on 2026-07-06 09:24

from django.db import migrations, models


def _backfill_phase(apps, schema_editor):
    Project = apps.get_model("tasks", "Project")
    Task = apps.get_model("tasks", "Task")
    open_statuses = ("TODO", "IN_PROGRESS")
    for p in Project.objects.all().iterator():
        total = Task.objects.filter(project=p).count()
        open_count = Task.objects.filter(project=p, status__in=open_statuses).count()
        # Mirror di tasks.phase.derive_initial_phase (inline per freeze-safety)
        if total > 0 and open_count == 0:
            phase = "DONE"
        elif open_count > 0:
            phase = "EXEC"
        elif p.vrf_status == "UPLOADED":
            phase = "VRF"
        else:
            phase = "BOZZA"
        if p.phase != phase:
            p.phase = phase
            p.save(update_fields=["phase"])


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_taskimpostazioni_roles_source_seed_caporeparto'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('BOZZA', 'Bozza'), ('VRF', 'VRF'), ('EXEC', 'In esecuzione'), ('DONE', 'Completata')], db_index=True, default='BOZZA', max_length=10, verbose_name='Fase'),
        ),
        migrations.RunPython(_backfill_phase, _noop),
    ]
