# Generated by Django 5.2.11 on 2026-06-29 11:48

import tasks.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_taskimpostazioni_roles_source_seed_caporeparto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='vrf_file',
            field=models.FileField(blank=True, null=True, storage=tasks.storage.PrivateTasksStorage(), upload_to='tasks_vrf/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(storage=tasks.storage.PrivateTasksStorage(), upload_to='tasks_attachments/%Y/%m/'),
        ),
    ]
