# Generated by Django 5.2.11 on 2026-07-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_alter_project_vrf_file_alter_taskattachment_file'),
        ('tasks', '0032_project_phase'),
    ]

    operations = [
    ]
