# Generated by Django 5.2.16 on 2026-09-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_normalize_project_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickoffmeeting',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Marcato dal job periodico che avvisa i partecipanti il giorno prima; evita doppi invii.', null=True, verbose_name='Promemoria pre-incontro inviato il'),
        ),
    ]
