# Generated by Django 5.2.16 on 2026-09-04 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_kickoffmeeting_reminder_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kickoffmeeting',
            name='presenti_email_extra',
            field=models.TextField(blank=True, default='', help_text='Un indirizzo email per riga, fra quelli convocati.', verbose_name='Email presenti'),
        ),
        migrations.AddField(
            model_name='kickoffmeeting',
            name='presenti_utenti',
            field=models.ManyToManyField(blank=True, related_name='kickoff_meetings_as_presente', to=settings.AUTH_USER_MODEL, verbose_name='Presenti (portale)'),
        ),
        migrations.AddField(
            model_name='kickoffmeeting',
            name='presenze_registrate_at',
            field=models.DateTimeField(blank=True, help_text='Distingue «nessun presente» da «presenze mai registrate» (incontri storici).', null=True, verbose_name='Presenze registrate il'),
        ),
    ]
