# Generated by Django 5.2.16 on 2026-09-04 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_kickoffmeeting_presenti_email_extra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kickoffmeeting',
            name='minuta_chiusa_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Minuta approvata il'),
        ),
        migrations.AddField(
            model_name='kickoffmeeting',
            name='minuta_chiusa_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kickoff_meetings_minuta_chiusa', to=settings.AUTH_USER_MODEL, verbose_name='Minuta approvata da'),
        ),
        migrations.AddField(
            model_name='kickoffmeeting',
            name='minuta_riaperture',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Riaperture della minuta'),
        ),
    ]
