# Generated by Django 5.2.16 on 2026-09-04 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_kickoffmeeting_minuta_chiusa_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAgendaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome modello')),
                ('descrizione', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrizione')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='Punti')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Attivo')),
                ('order_index', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_agenda_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modello ordine del giorno',
                'verbose_name_plural': 'Modelli ordine del giorno',
                'ordering': ['order_index', 'nome'],
            },
        ),
    ]
