# Generated by Django 5.2.16 on 2026-09-04 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_meetingagendatemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Azione')),
                ('description', models.TextField(blank=True, default='', verbose_name='Dettaglio')),
                ('status', models.CharField(choices=[('OPEN', 'Da fare'), ('DONE', 'Fatta')], db_index=True, default='OPEN', max_length=12, verbose_name='Stato')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Scadenza')),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_actions_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Responsabile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_actions_created', to=settings.AUTH_USER_MODEL)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_actions_done', to=settings.AUTH_USER_MODEL)),
                ('linked_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_actions', to='tasks.task', verbose_name='Attività collegata')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_actions', to='tasks.project', verbose_name='Kickoff')),
                ('source_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_raised', to='tasks.kickoffmeeting', verbose_name='Incontro di origine')),
            ],
            options={
                'verbose_name': 'Azione incontro',
                'verbose_name_plural': 'Azioni incontri',
                'ordering': ['status', 'due_date', 'created_at', 'id'],
                'indexes': [models.Index(fields=['project', 'status'], name='tasks_meeti_project_8652e5_idx'), models.Index(fields=['source_meeting', 'status'], name='tasks_meeti_source__66490d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeetingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=400, verbose_name='Decisione')),
                ('dettaglio', models.TextField(blank=True, default='', verbose_name='Motivazione / contesto')),
                ('impatto', models.CharField(choices=[('BASSO', 'Basso'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], db_index=True, default='MEDIO', max_length=8, verbose_name='Impatto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_decisions_created', to=settings.AUTH_USER_MODEL)),
                ('decisa_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_decisions_taken', to=settings.AUTH_USER_MODEL, verbose_name='Decisa da')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='tasks.kickoffmeeting', verbose_name='Incontro')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_decisions', to='tasks.project', verbose_name='Kickoff')),
            ],
            options={
                'verbose_name': 'Decisione incontro',
                'verbose_name_plural': 'Decisioni incontri',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='tasks_meeti_project_678994_idx')],
            },
        ),
    ]
