# Generated by Django 5.2.16 on 2026-09-04 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_meetingactionitem_meetingdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAgendaProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200, verbose_name='Punto proposto')),
                ('nota', models.TextField(blank=True, default='', verbose_name='Nota')),
                ('stato', models.CharField(choices=[('PENDING', 'In attesa'), ('ACCEPTED', 'Accettata'), ('REJECTED', 'Rifiutata')], db_index=True, default='PENDING', max_length=10, verbose_name='Stato')),
                ('nota_decisione', models.CharField(blank=True, default='', max_length=255, verbose_name='Nota della decisione')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_agenda_proposals_decided', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_proposals', to='tasks.kickoffmeeting', verbose_name='Incontro')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_agenda_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Proposto da')),
            ],
            options={
                'verbose_name': 'Proposta ordine del giorno',
                'verbose_name_plural': 'Proposte ordine del giorno',
                'ordering': ['stato', 'created_at', 'id'],
                'indexes': [models.Index(fields=['meeting', 'stato'], name='tasks_meeti_meeting_480f68_idx')],
            },
        ),
    ]
