# Generated by Django 5.2.16 on 2026-09-14 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0042_project_team_multiplo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kickoffmeeting',
            name='cc_email_extra',
            field=models.TextField(blank=True, default='', help_text='Un indirizzo email per riga (per destinatari in copia non presenti nel portale).', verbose_name='Email in copia'),
        ),
        migrations.AddField(
            model_name='kickoffmeeting',
            name='cc_utenti',
            field=models.ManyToManyField(blank=True, related_name='kickoff_meetings_as_cc', to=settings.AUTH_USER_MODEL, verbose_name='In copia (portale)'),
        ),
    ]
