# Generated by Django 5.2.16 on 2026-09-14 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_kickoffmeeting_cc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskimpostazioni',
            name='cc_predefinite_email',
            field=models.TextField(blank=True, default='', help_text="Un indirizzo per riga, per chi non e' un utente del portale.", verbose_name='CC predefiniti (email)'),
        ),
        migrations.AddField(
            model_name='taskimpostazioni',
            name='cc_predefiniti_utenti',
            field=models.ManyToManyField(blank=True, help_text="Ricevono in copia convocazioni e minute quando l'incontro non indica dei CC propri.", related_name='kickoff_cc_predefinito', to=settings.AUTH_USER_MODEL, verbose_name='CC predefiniti (portale)'),
        ),
    ]
