# Generated by Django 5.2.11 on 2026-06-24 16:59

import django.db.models.deletion
import django_fsm
import gestione_specifiche.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0070_subnav_proposta_a_pillars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MOD133',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_chiusura_compilazione', models.DateTimeField(blank=True, null=True, verbose_name='Chiusura compilazione')),
                ('data_approvazione', models.DateTimeField(blank=True, null=True, verbose_name='Data approvazione')),
                ('esito', models.CharField(blank=True, choices=[('approvato', 'Approvato'), ('respinto', 'Respinto'), ('non_applicabile', 'Non applicabile')], max_length=20, null=True, verbose_name='Esito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approvatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod133_approvati', to=settings.AUTH_USER_MODEL, verbose_name='Approvatore')),
                ('compilatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod133_compilati', to=settings.AUTH_USER_MODEL, verbose_name='Compilatore')),
            ],
            options={
                'verbose_name': 'MOD.133',
                'verbose_name_plural': 'MOD.133',
            },
        ),
        migrations.CreateModel(
            name='RigaMOD133',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveSmallIntegerField(default=0, verbose_name='Ordine')),
                ('rif_paragrafo', models.CharField(blank=True, default='', max_length=100, verbose_name='Rif. paragrafo specifica')),
                ('argomento', models.CharField(blank=True, default='', max_length=300, verbose_name='Argomento')),
                ('descrizione_modifiche', models.TextField(blank=True, default='', verbose_name='Descrizione modifiche')),
                ('descrizione_impatto', models.TextField(blank=True, default='', verbose_name='Descrizione impatto')),
                ('rif_doc_cn', models.CharField(blank=True, default='', max_length=100, verbose_name='Rif. documento CN')),
                ('rif_paragrafo_cn', models.CharField(blank=True, default='', max_length=100, verbose_name='Rif. paragrafo CN')),
                ('tag_processo', models.CharField(blank=True, default='', max_length=120, verbose_name='TAG processo')),
                ('impatto_documenti', models.BooleanField(default=False, verbose_name='Impatto documenti')),
                ('impatto_operativo', models.BooleanField(default=False, verbose_name='Impatto operativo')),
                ('genera_ofi', models.BooleanField(default=False, verbose_name='Genera OFI')),
                ('ofi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero OFI (MOD.174)')),
                ('mod133', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='gestione_specifiche.mod133', verbose_name='MOD.133')),
            ],
            options={
                'verbose_name': 'Riga MOD.133',
                'verbose_name_plural': 'Righe MOD.133',
                'ordering': ['mod133', 'ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AzioneOFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofi', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero OFI (MOD.174)')),
                ('documento_cn', models.CharField(blank=True, default='', max_length=150, verbose_name='Documento CN')),
                ('tipo_azione', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo azione')),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('in_approvazione', 'In approvazione'), ('approvata', 'Approvata'), ('respinta', 'Respinta')], default='bozza', max_length=20, verbose_name='Stato azione')),
                ('modo_approvazione', models.CharField(choices=[('mod133_approver', 'Approvatore MOD.133'), ('car_flow', 'Flusso CAR'), ('rdd_dedicato', 'RDD dedicato')], max_length=30, verbose_name='Modo approvazione')),
                ('data_approvazione', models.DateTimeField(blank=True, null=True, verbose_name='Data approvazione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approvatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='azioni_ofi_approvate', to=settings.AUTH_USER_MODEL, verbose_name='Approvatore')),
                ('riga_mod133', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azioni_ofi', to='gestione_specifiche.rigamod133', verbose_name='Riga MOD.133')),
            ],
            options={
                'verbose_name': 'Azione OFI',
                'verbose_name_plural': 'Azioni OFI',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(db_index=True, max_length=100, verbose_name='Codice')),
                ('revisione', models.CharField(blank=True, default='', max_length=30, verbose_name='Revisione')),
                ('titolo', models.CharField(max_length=300, verbose_name='Titolo')),
                ('tipo', models.CharField(choices=[('specifica', 'Specifica tecnica'), ('comunicazione', 'Comunicazione'), ('piano_qualita', 'Piano di qualità')], default='specifica', max_length=20, verbose_name='Tipo')),
                ('fonte', models.CharField(choices=[('cliente', 'Cliente'), ('generica', 'Generica')], default='cliente', max_length=20, verbose_name='Fonte')),
                ('cliente', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Cliente')),
                ('tag', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='TAG processo')),
                ('stato', django_fsm.FSMField(choices=[('bozza', 'S1 · Bozza'), ('flow_down', 'S2 · Flow-down'), ('in_validita', 'S3 · In validità'), ('superato', 'S4 · Superato'), ('sospeso', 'S5 · Sospeso'), ('annullato', 'S6 · Annullato'), ('duplicato', 'S7 · Duplicato'), ('respinto', 'S8 · Respinto'), ('errore_tecnico', 'S9 · Errore tecnico')], db_index=True, default='bozza', max_length=30, protected=True, verbose_name='Stato')),
                ('stato_precedente', models.CharField(blank=True, default='', max_length=30, verbose_name='Stato precedente')),
                ('data_inserimento', models.DateTimeField(auto_now_add=True, verbose_name='Data inserimento')),
                ('data_verifica', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data verifica periodica')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('allegato', models.FileField(blank=True, max_length=255, null=True, storage=gestione_specifiche.storage.specifica_allegato_storage, upload_to=gestione_specifiche.storage.upload_to_specifica, verbose_name='Allegato')),
                ('commessa_ref', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Rif. commessa')),
                ('famiglia_ref', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Rif. famiglia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicati', to='gestione_specifiche.specifica', verbose_name='Specifica master (per duplicati)')),
                ('revisione_precedente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisioni_successive', to='gestione_specifiche.specifica', verbose_name='Revisione precedente')),
            ],
            options={
                'verbose_name': 'Specifica',
                'verbose_name_plural': 'Specifiche',
                'ordering': ['-data_inserimento', 'codice'],
            },
        ),
        migrations.AddField(
            model_name='mod133',
            name='specifica',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mod133', to='gestione_specifiche.specifica', verbose_name='Specifica'),
        ),
        migrations.CreateModel(
            name='EventoSpecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato_da', models.CharField(blank=True, default='', max_length=30, verbose_name='Stato da')),
                ('stato_a', models.CharField(max_length=30, verbose_name='Stato a')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('trigger', models.CharField(blank=True, default='', max_length=60, verbose_name='Trigger')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('attore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventi_specifiche', to=settings.AUTH_USER_MODEL, verbose_name='Attore')),
                ('specifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='gestione_specifiche.specifica', verbose_name='Specifica')),
            ],
            options={
                'verbose_name': 'Evento specifica (audit)',
                'verbose_name_plural': 'Eventi specifica (audit)',
                'ordering': ['specifica', 'timestamp', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Distribuzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canale', models.CharField(choices=[('email', 'Email'), ('notifica', 'Notifica in-app'), ('cartaceo', 'Cartaceo')], max_length=20, verbose_name='Canale')),
                ('presa_visione_richiesta', models.BooleanField(default=False, verbose_name='Presa visione richiesta')),
                ('cartacea', models.BooleanField(default=False, verbose_name='Copia cartacea')),
                ('n_copie_distribuite', models.PositiveSmallIntegerField(default=0, verbose_name='Copie distribuite')),
                ('n_copie_ritirate', models.PositiveSmallIntegerField(default=0, verbose_name='Copie ritirate')),
                ('deroga_giustificazione', models.TextField(blank=True, default='', verbose_name='Giustificazione deroga copie')),
                ('data_distribuzione', models.DateTimeField(blank=True, null=True, verbose_name='Data distribuzione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinatari', models.ManyToManyField(blank=True, related_name='distribuzioni_specifiche', to='anagrafica.reparto', verbose_name='Reparti destinatari')),
                ('specifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuzioni', to='gestione_specifiche.specifica', verbose_name='Specifica')),
            ],
            options={
                'verbose_name': 'Distribuzione',
                'verbose_name_plural': 'Distribuzioni',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigPresaVisione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('specifica', 'Specifica tecnica'), ('comunicazione', 'Comunicazione'), ('piano_qualita', 'Piano di qualità')], max_length=20, verbose_name='Tipo documento')),
                ('richiesta', models.BooleanField(default=False, verbose_name='Presa visione richiesta')),
                ('reparto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_presa_visione', to='anagrafica.reparto', verbose_name='Reparto (vuoto = tutti)')),
            ],
            options={
                'verbose_name': 'Config presa visione',
                'verbose_name_plural': 'Config presa visione',
                'constraints': [models.UniqueConstraint(fields=('tipo_documento', 'reparto'), name='gs_configpv_tipo_reparto_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='specifica',
            index=models.Index(fields=['codice'], name='gs_spec_codice_idx'),
        ),
        migrations.AddIndex(
            model_name='specifica',
            index=models.Index(fields=['stato'], name='gs_spec_stato_idx'),
        ),
        migrations.AddIndex(
            model_name='specifica',
            index=models.Index(fields=['tipo', 'stato'], name='gs_spec_tipo_stato_idx'),
        ),
        migrations.AddIndex(
            model_name='specifica',
            index=models.Index(fields=['data_verifica'], name='gs_spec_dataverif_idx'),
        ),
        migrations.AddIndex(
            model_name='eventospecifica',
            index=models.Index(fields=['specifica', 'timestamp'], name='gs_evt_spec_ts_idx'),
        ),
    ]
