# Generated by Django 5.2.11 on 2026-06-24 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_specifiche', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mod133',
            name='avviato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod133_avviati', to=settings.AUTH_USER_MODEL, verbose_name='Avviato da (DM)'),
        ),
        migrations.AddField(
            model_name='mod133',
            name='escalation_inviata',
            field=models.BooleanField(default=False, verbose_name='Escalation 14gg inviata'),
        ),
        migrations.AddField(
            model_name='mod133',
            name='reminder_inviato',
            field=models.BooleanField(default=False, verbose_name='Reminder 7gg inviato'),
        ),
        migrations.AddField(
            model_name='mod133',
            name='timer_anchor',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inizio timer flow-down'),
        ),
        migrations.AddField(
            model_name='mod133',
            name='timer_pausa_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Timer in pausa da'),
        ),
        migrations.AddField(
            model_name='specifica',
            name='verifica_reminder_inviata_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultimo reminder verifica'),
        ),
    ]
