# Generated by Django 5.2.11 on 2026-07-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_specifiche', '0002_mod133_avviato_da_mod133_escalation_inviata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specifica',
            name='percorso_esterno',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Percorso esterno (share UNC)'),
        ),
    ]
