# Generated by Django 5.2.11 on 2026-07-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_specifiche', '0004_specifica_stato_pre_errore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifica',
            name='stato_precedente',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Stato precedente (sospensione)'),
        ),
    ]
