# Generated by Django 5.2.11 on 2026-07-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_specifiche', '0005_alter_specifica_stato_precedente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCartellaShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200, unique=True, verbose_name='Cliente')),
                ('cartella', models.CharField(max_length=300, verbose_name='Cartella share (relativa alla radice)')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mappatura cliente-cartella share',
                'verbose_name_plural': 'Mappature cliente-cartella share',
                'ordering': ['cliente'],
            },
        ),
    ]
