# Generated by Django 5.2.11 on 2026-07-03 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_specifiche', '0006_clientecartellashare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoApprovazioneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attiva', models.BooleanField(default=False, verbose_name='Auto-approvazione attiva')),
                ('nota', models.CharField(blank=True, default='', max_length=300, verbose_name='Nota')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approvatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approvatore di riferimento (MSO)')),
            ],
            options={
                'verbose_name': 'Config auto-approvazione MOD.133',
                'verbose_name_plural': 'Config auto-approvazione MOD.133',
            },
        ),
    ]
