# Generated by Django 5.2.11 on 2026-07-03 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_specifiche', '0007_autoapprovazioneconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specifica',
            name='incaricato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specifiche_incaricato', to=settings.AUTH_USER_MODEL, verbose_name='Incaricato'),
        ),
        migrations.CreateModel(
            name='NotificaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reparto_in1', models.CharField(default='IN1', help_text='Reparto (area anagrafica) del gruppo IN1.', max_length=100, verbose_name='Reparto IN1')),
                ('email_attiva', models.BooleanField(default=True, verbose_name='Invia anche email')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utenti_aggiuntivi', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Nomi aggiuntivi assegnabili')),
            ],
            options={
                'verbose_name': 'Config notifiche/assegnazione',
                'verbose_name_plural': 'Config notifiche/assegnazione',
            },
        ),
    ]
