# Generated by Django 5.2.11 on 2026-07-03 14:16

import django.db.models.deletion
import gestione_specifiche.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_specifiche', '0008_specifica_incaricato_notificaconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimbroCapocommessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(help_text='Es. CNOT102', max_length=50, verbose_name='Codice timbro')),
                ('nome', models.CharField(blank=True, default='', max_length=150, verbose_name='Nome/descrizione')),
                ('file', models.FileField(storage=gestione_specifiche.storage.specifica_allegato_storage, upload_to=gestione_specifiche.storage.upload_to_timbro, verbose_name='File timbro (senza data)')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timbri_capocommessa', to=settings.AUTH_USER_MODEL, verbose_name='Capocommessa')),
            ],
            options={
                'verbose_name': 'Timbro capocommessa',
                'verbose_name_plural': 'Timbri capocommessa',
                'ordering': ['codice'],
            },
        ),
    ]
