# Generated by Django 5.2.11 on 2026-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_specifiche', '0009_timbrocapocommessa'),
    ]

    operations = [
        migrations.AddField(
            model_name='timbrocapocommessa',
            name='tipo',
            field=models.CharField(choices=[('ricevuto', 'RICEVUTO (sul documento originale)'), ('mod133', 'Firma MOD.133 (Revisore/Approvatore)')], db_index=True, default='ricevuto', max_length=20, verbose_name='Tipo'),
        ),
    ]
