# Generated by Django 5.2.11 on 2026-07-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_specifiche', '0010_timbrocapocommessa_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimbroApplicazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezione', models.CharField(choices=[('mod133', 'MOD.133'), ('originale', 'Documento originale')], default='originale', max_length=12)),
                ('pagina', models.PositiveIntegerField(default=0, help_text='Indice pagina nella sezione (0-based)')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('w', models.FloatField(default=120.0)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('specifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timbri_applicati', to='gestione_specifiche.specifica')),
                ('timbro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gestione_specifiche.timbrocapocommessa')),
            ],
            options={
                'ordering': ['sezione', 'pagina'],
            },
        ),
    ]
