# Generated by Django 5.2.11 on 2026-07-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_specifiche', '0011_timbroapplicazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='RigaMOD133Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_documento', models.CharField(max_length=150, verbose_name='Documento CN')),
                ('rif_paragrafo', models.CharField(blank=True, default='', max_length=100, verbose_name='Rif. paragrafo CN')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Note')),
                ('ordine', models.PositiveSmallIntegerField(default=0, verbose_name='Ordine')),
                ('riga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti', to='gestione_specifiche.rigamod133', verbose_name='Riga MOD.133')),
            ],
            options={
                'verbose_name': 'Documento CN riga MOD.133',
                'verbose_name_plural': 'Documenti CN riga MOD.133',
                'ordering': ['riga', 'ordine', 'id'],
            },
        ),
    ]
