# Generated by Django 5.2.11 on 2026-07-24 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestione_specifiche', '0012_rigamod133documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroOFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='N. OFI')),
                ('ref', models.CharField(blank=True, default='', max_length=100, verbose_name='REF')),
                ('data_apertura', models.DateField(verbose_name='Data apertura')),
                ('tipo', models.CharField(choices=[('OFI', 'Opportunità di miglioramento'), ('NC', 'Non conformità')], default='OFI', max_length=4)),
                ('norma_iso27001', models.BooleanField(default=False, verbose_name='ISO 27001')),
                ('norma_iso45001', models.BooleanField(default=False, verbose_name='ISO 45001')),
                ('norma_en9100', models.BooleanField(default=False, verbose_name='EN 9100')),
                ('rif_norma', models.CharField(blank=True, default='', max_length=200, verbose_name='Rif. norma/paragrafo')),
                ('processo', models.CharField(blank=True, default='', max_length=200, verbose_name='Processo/area')),
                ('opportunita', models.TextField(blank=True, default='', verbose_name='Opportunità / descrizione')),
                ('fase', models.CharField(choices=[('PLAN', 'Plan (pianifica)'), ('DO', 'Do (attua)'), ('CHECK', 'Check (verifica)'), ('ACT', 'Act (consolida)'), ('CHIUSO', 'Chiuso')], db_index=True, default='PLAN', max_length=8)),
                ('plan', models.TextField(blank=True, default='', verbose_name='PLAN')),
                ('do', models.TextField(blank=True, default='', verbose_name='DO')),
                ('verifica', models.TextField(blank=True, default='', verbose_name='CHECK')),
                ('act', models.TextField(blank=True, default='', verbose_name='ACT')),
                ('allegato_link', models.CharField(blank=True, default='', max_length=500, verbose_name='Allegato/link')),
                ('priorita', models.CharField(choices=[('BASSA', 'Bassa'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=6)),
                ('proprietario', models.CharField(blank=True, default='', max_length=150, verbose_name='Proprietario OFI')),
                ('owner_processo', models.CharField(blank=True, default='', max_length=150, verbose_name='Owner di processo')),
                ('data_richiesta', models.DateField(blank=True, null=True, verbose_name='Data richiesta chiusura')),
                ('data_chiusura', models.DateField(blank=True, null=True, verbose_name='Data chiusura')),
                ('reminder_attivo', models.BooleanField(default=True)),
                ('reminder_inviato', models.BooleanField(default=False)),
                ('modulo_origine', models.CharField(blank=True, default='', max_length=60)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Voce registro OFI (MOD.174)',
                'verbose_name_plural': 'Registro OFI (MOD.174)',
                'ordering': ['-numero'],
            },
        ),
        migrations.AddField(
            model_name='azioneofi',
            name='registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='azioni', to='gestione_specifiche.registroofi', verbose_name='Voce registro OFI'),
        ),
    ]
