# Generated by Django 5.2.11 on 2026-03-04 22:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('PC', 'PC'), ('NOTEBOOK', 'Notebook'), ('SERVER', 'Server'), ('VM', 'VM'), ('FIREWALL', 'Firewall'), ('STAMPANTE', 'Stampante'), ('HW', 'Hardware'), ('CNC', 'CNC'), ('CCTV', 'CCTV'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('reparto', models.CharField(blank=True, default='', max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=120, null=True)),
                ('model', models.CharField(blank=True, max_length=120, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In stock'), ('IN_USE', 'In use'), ('IN_REPAIR', 'In repair'), ('RETIRED', 'Retired')], default='IN_USE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('source_key', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('assignment_to', models.CharField(blank=True, default='', max_length=200)),
                ('assignment_reparto', models.CharField(blank=True, default='', max_length=120)),
                ('assignment_location', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'asset_tag', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssetITDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(blank=True, default='', max_length=120)),
                ('cpu', models.CharField(blank=True, default='', max_length=120)),
                ('ram', models.CharField(blank=True, default='', max_length=120)),
                ('disco', models.CharField(blank=True, default='', max_length=120)),
                ('domain_joined', models.BooleanField(default=False)),
                ('edr_enabled', models.BooleanField(default=False)),
                ('ad360_managed', models.BooleanField(default=False)),
                ('office_2fa_enabled', models.BooleanField(default=False)),
                ('bios_pwd_set', models.BooleanField(default=False)),
                ('vault_ref', models.CharField(blank=True, default='', max_length=200)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='it_details', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective'), ('SAFETY', 'Safety'), ('CALIBRATION', 'Calibration'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('resolution', models.TextField(blank=True, default='')),
                ('downtime_minutes', models.PositiveIntegerField(default=0)),
                ('cost_eur', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='assets.asset')),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_workorder_logs', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assets.workorder')),
            ],
            options={
                'ordering': ['-ts', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(blank=True, default='', max_length=255)),
                ('vlan', models.PositiveIntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=80, null=True)),
                ('switch_name', models.CharField(blank=True, default='', max_length=120)),
                ('switch_port', models.CharField(blank=True, default='', max_length=120)),
                ('punto', models.CharField(blank=True, default='', max_length=120)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='assets.asset')),
            ],
            options={
                'ordering': ['asset_id', 'endpoint_name', 'vlan', 'ip'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'endpoint_name', 'vlan', 'ip'), name='uniq_asset_endpoint')],
            },
        ),
    ]
