# Generated by Django 5.2.11 on 2026-03-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='extra_columns',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
