# Generated by Django 5.2.11 on 2026-03-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_extra_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('TEXT', 'Testo'), ('NUMBER', 'Numero'), ('DATE', 'Data'), ('BOOL', 'Si/No')], default='TEXT', max_length=20)),
                ('sort_order', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label', 'id'],
            },
        ),
    ]
