# Generated by Django 5.2.11 on 2026-03-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetcustomfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned_legacy_user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
