# Generated by Django 5.2.11 on 2026-03-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_assigned_legacy_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetActionButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('zone', models.CharField(choices=[('HEADER', 'Header'), ('QUICK', 'Quick Actions')], db_index=True, default='QUICK', max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('action_type', models.CharField(choices=[('LINK', 'Link'), ('PRINT', 'Print'), ('REFRESH', 'Refresh')], default='LINK', max_length=20)),
                ('target', models.CharField(blank=True, default='', help_text='URL/path con placeholder: {asset_id}, {asset_tag}, {asset_name}', max_length=500)),
                ('style', models.CharField(choices=[('DEFAULT', 'Default'), ('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('DANGER', 'Danger')], default='DEFAULT', max_length=20)),
                ('sort_order', models.IntegerField(default=100)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['zone', 'sort_order', 'label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssetListOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(choices=[('reparto', 'Reparto'), ('manufacturer', 'Manufacturer'), ('model', 'Model'), ('assignment_to', 'Assignment to'), ('assignment_reparto', 'Assignment reparto'), ('assignment_location', 'Assignment location')], db_index=True, max_length=50)),
                ('value', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['field_key', 'sort_order', 'value', 'id'],
                'constraints': [models.UniqueConstraint(fields=('field_key', 'value'), name='uniq_asset_listoption_field_value')],
            },
        ),
    ]
