# Generated by Django 5.2.11 on 2026-03-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assetactionbutton_assetlistoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSidebarButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('section', models.CharField(choices=[('MAIN', 'Main Navigation'), ('ANALYTICS', 'Analytics & Risk'), ('OPERATIONS', 'Operations')], db_index=True, default='MAIN', max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('target_url', models.CharField(blank=True, default='', help_text='URL o route prefissata con django: (es. django:assets:asset_list). Supporta {rows}.', max_length=500)),
                ('active_match', models.CharField(blank=True, default='', help_text='Substring opzionale per marcare il pulsante come attivo (es. asset_type=SERVER).', max_length=200)),
                ('is_subitem', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'sort_order', 'label', 'id'],
            },
        ),
    ]
