# Generated by Django 5.2.11 on 2026-03-06 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetsidebarbutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('PC', 'PC'), ('NOTEBOOK', 'Portatile'), ('SERVER', 'Server'), ('VM', 'Macchina virtuale'), ('FIREWALL', 'Firewall'), ('STAMPANTE', 'Stampante'), ('HW', 'Dispositivo'), ('CNC', 'CNC'), ('WORK_MACHINE', 'Macchina di lavoro'), ('CCTV', 'Videosorveglianza'), ('OTHER', 'Altro')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In magazzino'), ('IN_USE', 'In uso'), ('IN_REPAIR', 'In riparazione'), ('RETIRED', 'Dismesso')], default='IN_USE', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetactionbutton',
            name='action_type',
            field=models.CharField(choices=[('LINK', 'Collegamento'), ('PRINT', 'Stampa'), ('REFRESH', 'Aggiorna')], default='LINK', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetactionbutton',
            name='style',
            field=models.CharField(choices=[('DEFAULT', 'Predefinito'), ('PRIMARY', 'Primario'), ('SECONDARY', 'Secondario'), ('DANGER', 'Pericolo')], default='DEFAULT', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetactionbutton',
            name='zone',
            field=models.CharField(choices=[('HEADER', 'Intestazione'), ('QUICK', 'Azioni rapide')], db_index=True, default='QUICK', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetlistoption',
            name='field_key',
            field=models.CharField(choices=[('reparto', 'Reparto'), ('manufacturer', 'Produttore'), ('model', 'Modello'), ('assignment_to', 'Assegnato a'), ('assignment_reparto', 'Reparto assegnazione'), ('assignment_location', 'Posizione assegnazione')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='assetsidebarbutton',
            name='section',
            field=models.CharField(choices=[('MAIN', 'Navigazione principale'), ('ANALYTICS', 'Analisi e rischio'), ('OPERATIONS', 'Operativita')], db_index=True, default='MAIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='kind',
            field=models.CharField(choices=[('PREVENTIVE', 'Preventiva'), ('CORRECTIVE', 'Correttiva'), ('SAFETY', 'Sicurezza'), ('CALIBRATION', 'Taratura'), ('OTHER', 'Altro')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Aperta'), ('DONE', 'Chiusa'), ('CANCELED', 'Annullata')], default='OPEN', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('x_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('y_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('z_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('diameter_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('spindle_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('tmc', models.PositiveIntegerField(blank=True, null=True)),
                ('tcr_enabled', models.BooleanField(default=False)),
                ('pressure_bar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cnc_controlled', models.BooleanField(default=False)),
                ('five_axes', models.BooleanField(default=False)),
                ('accuracy_from', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_machine', to='assets.asset')),
            ],
            options={
                'ordering': ['asset__name', 'asset__asset_tag', 'asset_id'],
            },
        ),
    ]
