# Generated by Django 5.2.11 on 2026-03-06 14:35

from django.db import migrations


def seed_work_machine_sidebar_button(apps, schema_editor):
    AssetSidebarButton = apps.get_model("assets", "AssetSidebarButton")
    AssetSidebarButton.objects.get_or_create(
        code="work_machines",
        defaults={
            "section": "MAIN",
            "label": "Macchine di lavoro",
            "target_url": "django:assets:work_machine_list",
            "active_match": "/assets/work-machines/",
            "is_subitem": False,
            "sort_order": 55,
            "is_visible": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_alter_asset_asset_type_alter_asset_status_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_work_machine_sidebar_button, migrations.RunPython.noop),
    ]
