# Generated by Django 5.2.11 on 2026-03-06 15:20

from django.db import migrations


def seed_work_machine_dashboard_sidebar_button(apps, schema_editor):
    AssetSidebarButton = apps.get_model("assets", "AssetSidebarButton")
    AssetSidebarButton.objects.get_or_create(
        code="work_machines_dashboard",
        defaults={
            "section": "MAIN",
            "label": "Dashboard officina",
            "target_url": "django:assets:work_machine_dashboard",
            "active_match": "/assets/work-machines/dashboard/",
            "is_subitem": True,
            "sort_order": 56,
            "is_visible": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0008_seed_work_machine_sidebar_button"),
    ]

    operations = [
        migrations.RunPython(seed_work_machine_dashboard_sidebar_button, migrations.RunPython.noop),
    ]
