# Generated by Django 5.2.11 on 2026-03-06 13:29

import assets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_seed_work_machine_dashboard_sidebar_button'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workmachine',
            name='maintenance_reminder_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='workmachine',
            name='next_maintenance_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SPECIFICHE', 'Specifiche'), ('INTERVENTI', 'Interventi'), ('MANUALI', 'Manuali')], db_index=True, default='SPECIFICHE', max_length=20)),
                ('file', models.FileField(upload_to=assets.models._asset_document_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.asset')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', '-created_at', '-id'],
            },
        ),
    ]
