# Generated by Django 5.2.11 on 2026-03-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_workmachine_maintenance_reminder_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sharepoint_folder_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='asset',
            name='sharepoint_folder_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='sharepoint_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='sharepoint_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
