# Generated by Django 5.2.11 on 2026-03-06 19:56

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_asset_sharepoint_folder_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default='default', max_length=40, unique=True)),
                ('name', models.CharField(default='Etichetta predefinita', max_length=120)),
                ('page_width_mm', models.PositiveIntegerField(default=100)),
                ('page_height_mm', models.PositiveIntegerField(default=62)),
                ('qr_size_mm', models.PositiveIntegerField(default=24)),
                ('qr_position', models.CharField(choices=[('LEFT', 'QR a sinistra'), ('RIGHT', 'QR a destra')], default='RIGHT', max_length=10)),
                ('title_font_size_pt', models.PositiveIntegerField(default=16)),
                ('body_font_size_pt', models.PositiveIntegerField(default=8)),
                ('show_border', models.BooleanField(default=True)),
                ('border_radius_mm', models.PositiveIntegerField(default=4)),
                ('show_field_labels', models.BooleanField(default=True)),
                ('show_target_label', models.BooleanField(default=True)),
                ('show_help_text', models.BooleanField(default=True)),
                ('show_target_url', models.BooleanField(default=True)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('border_color', models.CharField(default='#111827', max_length=7)),
                ('text_color', models.CharField(default='#0F172A', max_length=7)),
                ('accent_color', models.CharField(default='#1D4ED8', max_length=7)),
                ('title_primary_field', models.CharField(default='asset_tag', max_length=40)),
                ('title_secondary_field', models.CharField(default='name', max_length=40)),
                ('body_fields', models.JSONField(blank=True, default=assets.models.default_asset_label_body_fields)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code', 'id'],
            },
        ),
    ]
