# Generated by Django 5.2.11 on 2026-03-06 20:17

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_assetlabeltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlabeltemplate',
            name='logo_alignment',
            field=models.CharField(choices=[('LEFT', 'Logo a sinistra'), ('CENTER', 'Logo centrato'), ('RIGHT', 'Logo a destra')], default='LEFT', max_length=10),
        ),
        migrations.AddField(
            model_name='assetlabeltemplate',
            name='logo_file',
            field=models.FileField(blank=True, default='', upload_to=assets.models._asset_label_logo_upload_to),
        ),
        migrations.AddField(
            model_name='assetlabeltemplate',
            name='logo_height_mm',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='assetlabeltemplate',
            name='show_logo',
            field=models.BooleanField(default=False),
        ),
    ]
