# Generated by Codex on 2026-03-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0013_assetlabeltemplate_logo_alignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetlabeltemplate",
            name="asset",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="label_template_override",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="assetlabeltemplate",
            name="asset_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PC", "PC"),
                    ("NOTEBOOK", "Portatile"),
                    ("SERVER", "Server"),
                    ("VM", "Macchina virtuale"),
                    ("FIREWALL", "Firewall"),
                    ("STAMPANTE", "Stampante"),
                    ("HW", "Dispositivo"),
                    ("CNC", "CNC"),
                    ("WORK_MACHINE", "Macchina di lavoro"),
                    ("CCTV", "Videosorveglianza"),
                    ("OTHER", "Altro"),
                ],
                db_index=True,
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assetlabeltemplate",
            name="scope",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "Generale"),
                    ("ASSET_TYPE", "Per tipologia asset"),
                    ("ASSET", "Per asset"),
                ],
                db_index=True,
                default="DEFAULT",
                max_length=20,
            ),
        ),
        migrations.AlterModelOptions(
            name="assetlabeltemplate",
            options={"ordering": ["scope", "asset_type", "code", "id"]},
        ),
    ]
