# Generated by Django 5.2.11 on 2026-03-09 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0002_fornitoreasset'),
        ('assets', '0015_plant_layout_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('frequency_months', models.PositiveIntegerField(default=12)),
                ('last_verification_date', models.DateField(blank=True, null=True)),
                ('next_verification_date', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assets', models.ManyToManyField(blank=True, related_name='periodic_verifications', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_periodic_verifications', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_verifications', to='anagrafica.fornitore')),
            ],
            options={
                'verbose_name': 'Verifica periodica',
                'verbose_name_plural': 'Verifiche periodiche',
                'ordering': ['name', 'id'],
            },
        ),
    ]
