# Generated by Codex on 2026-03-09

from django.db import migrations


def seed_periodic_verifications_sidebar_button(apps, schema_editor):
    AssetSidebarButton = apps.get_model("assets", "AssetSidebarButton")
    AssetSidebarButton.objects.get_or_create(
        code="periodic_verifications",
        defaults={
            "section": "MAIN",
            "label": "Verifiche periodiche",
            "target_url": "django:assets:periodic_verifications",
            "active_match": "/assets/verifiche-periodiche/",
            "is_subitem": False,
            "sort_order": 56,
            "is_visible": True,
        },
    )


def unseed_periodic_verifications_sidebar_button(apps, schema_editor):
    AssetSidebarButton = apps.get_model("assets", "AssetSidebarButton")
    AssetSidebarButton.objects.filter(code="periodic_verifications").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0016_periodicverification"),
    ]

    operations = [
        migrations.RunPython(
            seed_periodic_verifications_sidebar_button,
            unseed_periodic_verifications_sidebar_button,
        ),
    ]
