# Generated by Django 5.2.11 on 2026-03-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_seed_periodic_verifications_sidebar_button'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantlayout',
            options={'ordering': ['category', '-is_active', 'name', 'id']},
        ),
        migrations.AddField(
            model_name='assetsidebarbutton',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.assetsidebarbutton'),
        ),
        migrations.AddField(
            model_name='plantlayout',
            name='category',
            field=models.CharField(db_index=True, default='Officina', max_length=80),
        ),
    ]
