# Generated by Django 5.2.11 on 2026-03-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_seed_sidebar_parents_and_layout_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDetailField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('section', models.CharField(choices=[('METRICS', 'Metriche evidenza'), ('SPECS', 'Specifiche tecniche'), ('PROFILE', 'Profilo asset'), ('ASSIGNMENT', 'Responsabile attuale')], db_index=True, default='SPECS', max_length=20)),
                ('asset_scope', models.CharField(choices=[('ALL', 'Tutti gli asset'), ('STANDARD', 'Asset standard'), ('WORK_MACHINE', 'Macchine di lavoro')], db_index=True, default='ALL', max_length=20)),
                ('source_ref', models.CharField(help_text='Formato origine: asset:manufacturer, work_machine:x_mm, it:cpu, custom:rack, computed:travel_xyz', max_length=120)),
                ('value_format', models.CharField(choices=[('AUTO', 'Automatico'), ('TEXT', 'Testo'), ('BOOL', 'Si/No'), ('DATE', 'Data'), ('MM', 'Millimetri'), ('BAR', 'Bar')], default='AUTO', max_length=20)),
                ('sort_order', models.IntegerField(default=100)),
                ('show_if_empty', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'asset_scope', 'sort_order', 'label', 'id'],
            },
        ),
    ]
