# Generated by Django 5.2.11 on 2026-03-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_seed_asset_detail_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('base_asset_type', models.CharField(choices=[('PC', 'PC'), ('NOTEBOOK', 'Portatile'), ('SERVER', 'Server'), ('VM', 'Macchina virtuale'), ('FIREWALL', 'Firewall'), ('STAMPANTE', 'Stampante'), ('HW', 'Dispositivo'), ('CNC', 'CNC'), ('WORK_MACHINE', 'Macchina di lavoro'), ('CCTV', 'Videosorveglianza'), ('OTHER', 'Altro')], db_index=True, default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('detail_specs_title', models.CharField(blank=True, default='', max_length=120)),
                ('detail_profile_title', models.CharField(blank=True, default='', max_length=120)),
                ('detail_assignment_title', models.CharField(blank=True, default='', max_length=120)),
                ('detail_timeline_title', models.CharField(blank=True, default='', max_length=120)),
                ('detail_maintenance_title', models.CharField(blank=True, default='', max_length=120)),
                ('sort_order', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label', 'id'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetcategory'),
        ),
        migrations.CreateModel(
            name='AssetCategoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('TEXT', 'Testo'), ('TEXTAREA', 'Testo lungo'), ('NUMBER', 'Numero'), ('DATE', 'Data'), ('BOOL', 'Si/No')], default='TEXT', max_length=20)),
                ('detail_section', models.CharField(choices=[('METRICS', 'Metriche evidenza'), ('SPECS', 'Specifiche tecniche'), ('PROFILE', 'Profilo asset'), ('ASSIGNMENT', 'Responsabile attuale')], db_index=True, default='SPECS', max_length=20)),
                ('detail_value_format', models.CharField(choices=[('AUTO', 'Automatico'), ('TEXT', 'Testo'), ('BOOL', 'Si/No'), ('DATE', 'Data'), ('MM', 'Millimetri'), ('BAR', 'Bar')], default='AUTO', max_length=20)),
                ('placeholder', models.CharField(blank=True, default='', max_length=160)),
                ('help_text', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.IntegerField(default=100)),
                ('is_required', models.BooleanField(default=False)),
                ('show_in_form', models.BooleanField(default=True)),
                ('show_in_detail', models.BooleanField(default=True)),
                ('show_if_empty', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='assets.assetcategory')),
            ],
            options={
                'ordering': ['category__sort_order', 'category__label', 'sort_order', 'label', 'id'],
            },
        ),
    ]
