# Generated by Django 5.2.11 on 2026-03-09 22:34

from django.db import migrations, models


def seed_detail_section_layouts(apps, schema_editor):
    AssetDetailSectionLayout = apps.get_model("assets", "AssetDetailSectionLayout")
    rows = [
        ("SPECS", "WIDE", 100, True),
        ("TIMELINE", "WIDE", 110, True),
        ("MAINTENANCE", "FULL", 120, True),
        ("PROFILE", "HALF", 200, True),
        ("ASSIGNMENT", "HALF", 210, True),
        ("PERIODIC", "HALF", 220, True),
        ("DOCUMENTS", "WIDE", 230, True),
        ("QR", "HALF", 240, True),
        ("QUICK_ACTIONS", "HALF", 250, True),
        ("SHAREPOINT", "HALF", 260, True),
        ("MAP", "HALF", 270, True),
    ]
    for code, grid_size, sort_order, is_visible in rows:
        AssetDetailSectionLayout.objects.get_or_create(
            code=code,
            defaults={
                "grid_size": grid_size,
                "sort_order": sort_order,
                "is_visible": is_visible,
            },
        )


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_seed_header_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDetailSectionLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SPECS', 'Specifiche tecniche'), ('TIMELINE', 'Timeline ciclo di vita'), ('MAINTENANCE', 'Registro manutenzione'), ('PROFILE', 'Profilo asset'), ('PERIODIC', 'Verifiche periodiche'), ('QR', 'QR asset'), ('SHAREPOINT', 'Archivio SharePoint'), ('QUICK_ACTIONS', 'Azioni rapide'), ('ASSIGNMENT', 'Responsabile attuale'), ('MAP', 'Posizione in officina'), ('DOCUMENTS', 'Documenti')], max_length=24, unique=True)),
                ('grid_size', models.CharField(choices=[('THIRD', 'Compatta'), ('HALF', 'Media'), ('WIDE', 'Ampia'), ('FULL', 'Piena')], default='HALF', max_length=12)),
                ('sort_order', models.IntegerField(default=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='assetcategoryfield',
            name='detail_card_size',
            field=models.CharField(choices=[('THIRD', 'Compatta'), ('HALF', 'Media'), ('WIDE', 'Ampia'), ('FULL', 'Piena')], default='THIRD', max_length=12),
        ),
        migrations.AddField(
            model_name='assetdetailfield',
            name='card_size',
            field=models.CharField(choices=[('THIRD', 'Compatta'), ('HALF', 'Media'), ('WIDE', 'Ampia'), ('FULL', 'Piena')], default='THIRD', max_length=12),
        ),
        migrations.RunPython(seed_detail_section_layouts, noop),
    ]
