# Generated by Django 5.2.11 on 2026-03-18 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0030_assetreportdefinition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('component_type', models.CharField(blank=True, default='', max_length=120)),
                ('serial_number', models.CharField(blank=True, default='', max_length=120)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=120)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Componente asset',
                'verbose_name_plural': 'Componenti asset',
                'ordering': ['asset__name', '-is_active', 'name', 'code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssetAdministrativeDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_type', models.CharField(choices=[('REVISION', 'Revisione'), ('CERTIFICATE', 'Certificato'), ('ADMINISTRATIVE', 'Scadenza amministrativa'), ('TECHNICAL', 'Scadenza tecnica'), ('OTHER', 'Altro')], db_index=True, default='ADMINISTRATIVE', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('reference_code', models.CharField(blank=True, default='', max_length=120)),
                ('issuer', models.CharField(blank=True, default='', max_length=200)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(db_index=True)),
                ('warning_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_deadlines', to='assets.asset')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrative_deadlines', to='assets.assetcomponent')),
            ],
            options={
                'verbose_name': 'Scadenza asset',
                'verbose_name_plural': 'Scadenze asset',
                'ordering': ['due_date', 'asset__name', 'title', 'id'],
            },
        ),
    ]
