# Generated by Django 5.2.11 on 2026-03-19 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0032_seed_asset_component_deadline_sidebar_buttons'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceInterventionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_intervention_templates', to='assets.assetcategory')),
            ],
            options={
                'verbose_name': 'Template intervento manutenzione',
                'verbose_name_plural': 'Template interventi manutenzione',
                'ordering': ['sort_order', 'label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_type', models.CharField(choices=[('DAYS', 'Giorni'), ('HOURS', 'Ore'), ('KM', 'Km'), ('CYCLES', 'Cicli')], db_index=True, default='DAYS', max_length=20)),
                ('threshold_value', models.PositiveIntegerField()),
                ('sort_order', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_rules', to='assets.assetcategory')),
                ('intervention_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_rules', to='assets.maintenanceinterventiontemplate')),
            ],
            options={
                'verbose_name': 'Regola manutenzione',
                'verbose_name_plural': 'Regole manutenzione',
                'ordering': ['asset_category__sort_order', 'asset_category__label', 'sort_order', 'id'],
            },
        ),
    ]
