# Generated by Django 5.2.11 on 2026-03-19 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0034_seed_maintenance_sidebar_buttons'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRuleAssetOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_threshold_type', models.CharField(blank=True, choices=[('DAYS', 'Giorni'), ('HOURS', 'Ore'), ('KM', 'Km'), ('CYCLES', 'Cicli')], db_index=True, max_length=20, null=True)),
                ('override_threshold_value', models.PositiveIntegerField(blank=True, null=True)),
                ('is_disabled', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_rule_overrides', to='assets.asset')),
                ('base_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_overrides', to='assets.maintenancerule')),
                ('override_intervention_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_rule_overrides', to='assets.maintenanceinterventiontemplate')),
            ],
            options={
                'verbose_name': 'Override regola manutenzione asset',
                'verbose_name_plural': 'Override regole manutenzione asset',
                'ordering': ['asset__name', 'asset__asset_tag', 'base_rule__sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'base_rule'), name='uniq_maintenance_rule_asset_override')],
            },
        ),
    ]
