# Generated by Django 5.2.11 on 2026-03-19 11:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0004_mansione_tipoqualifica_dipendentequalifica'),
        ('assets', '0035_maintenanceruleassetoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerule',
            name='warning_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='workorder',
            name='covered_by_contract',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='intervention_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='labor_cost_eur',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='maintenance_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders', to='assets.maintenancerule'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='materials_cost_eur',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='AssistanceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('contract_type', models.CharField(choices=[('FULL_SERVICE', 'Full service'), ('ON_CALL', 'A chiamata'), ('WARRANTY', 'Garanzia'), ('RENTAL', 'Noleggio / service'), ('OTHER', 'Altro')], db_index=True, default='OTHER', max_length=20)),
                ('start_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sla_description', models.CharField(blank=True, default='', max_length=255)),
                ('coverage_summary', models.TextField(blank=True, default='')),
                ('periodic_cost_eur', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistance_contracts', to='assets.asset')),
                ('asset_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistance_contracts', to='assets.assetcategory')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistance_contracts', to='anagrafica.fornitoredocumento')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_contracts', to='anagrafica.fornitore')),
            ],
            options={
                'verbose_name': 'Contratto assistenza',
                'verbose_name_plural': 'Contratti assistenza',
                'ordering': ['-is_active', 'end_date', 'supplier__ragione_sociale', 'title', 'id'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='assistance_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders', to='assets.assistancecontract'),
        ),
        migrations.CreateModel(
            name='AssetMaintenanceRuleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_execution_date', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_rule_states', to='assets.asset')),
                ('base_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_states', to='assets.maintenancerule')),
                ('last_work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_rule_states', to='assets.workorder')),
            ],
            options={
                'verbose_name': 'Stato manutenzione asset',
                'verbose_name_plural': 'Stati manutenzione asset',
                'ordering': ['asset__name', 'base_rule__sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'base_rule'), name='uniq_asset_maintenance_rule_state')],
            },
        ),
    ]
