# Generated by Django 5.2.11 on 2026-04-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0042_assetdashboardconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcalendarevent',
            name='source_key',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
        ),
    ]
