# Generated by Django 5.2.11 on 2026-04-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0046_workorder_ticket_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdetailsectionlayout',
            name='code',
            field=models.CharField(choices=[('SPECS', 'Specifiche tecniche'), ('TIMELINE', 'Timeline ciclo di vita'), ('MAINTENANCE', 'Registro manutenzione'), ('TICKETS', 'Ticket collegati'), ('PROFILE', 'Profilo asset'), ('LICENSES', 'Licenze software'), ('PERIODIC', 'Manutenzione periodica'), ('QR', 'QR asset'), ('SHAREPOINT', 'Archivio SharePoint'), ('QUICK_ACTIONS', 'Azioni rapide'), ('ASSIGNMENT', 'Responsabile attuale'), ('MAP', 'Posizione in officina'), ('DOCUMENTS', 'Documenti')], max_length=24, unique=True),
        ),
    ]
