# Generated by Django 5.2.11 on 2026-04-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0052_sidebar_restructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='base_asset_type',
            field=models.CharField(choices=[('PC', 'PC'), ('NOTEBOOK', 'Portatile'), ('SERVER', 'Server'), ('VM', 'Macchina virtuale'), ('FIREWALL', 'Firewall'), ('STAMPANTE', 'Stampante'), ('HW', 'Dispositivo'), ('FONIA', 'Fonia'), ('CNC', 'CNC'), ('WORK_MACHINE', 'Macchina di lavoro'), ('CARROPONTE', 'Carroponte'), ('CCTV', 'Videosorveglianza'), ('OTHER', 'Altro')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetlabeltemplate',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('PC', 'PC'), ('NOTEBOOK', 'Portatile'), ('SERVER', 'Server'), ('VM', 'Macchina virtuale'), ('FIREWALL', 'Firewall'), ('STAMPANTE', 'Stampante'), ('HW', 'Dispositivo'), ('FONIA', 'Fonia'), ('CNC', 'CNC'), ('WORK_MACHINE', 'Macchina di lavoro'), ('CARROPONTE', 'Carroponte'), ('CCTV', 'Videosorveglianza'), ('OTHER', 'Altro')], db_index=True, default='', max_length=20),
        ),
    ]
