# Generated by Django 5.2.11 on 2026-05-02 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0056_fix_scoped_sidebar_active_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAdministrativeDeadlineCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_on', models.DateField(db_index=True)),
                ('cost_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_asset_administrative_deadlines', to=settings.AUTH_USER_MODEL)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='assets.assetadministrativedeadline')),
            ],
            options={
                'verbose_name': 'Esecuzione scadenza',
                'verbose_name_plural': 'Esecuzioni scadenze',
                'ordering': ['-completed_on', '-id'],
            },
        ),
    ]
