# Generated by Django 5.2.11 on 2026-05-04 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import assets.models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0057_asset_admin_deadline_completion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAdministrativeDeadlineCompletionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=assets.models._admin_deadline_completion_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assets.assetadministrativedeadlinecompletion')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_admin_deadline_completion_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
