# Generated by Django 5.2.11 on 2026-05-04 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0058_admin_deadline_completion_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='executed_by',
            field=models.ForeignKey(blank=True, help_text='Tecnico/manutentore che ha eseguito la manutenzione', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders_executed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Note aggiuntive sulla manutenzione'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='origin',
            field=models.CharField(choices=[('PERIODIC', 'Periodica'), ('MANUAL', 'Manuale'), ('TICKET', 'Da ticket')], db_index=True, default='MANUAL', help_text='Origine della manutenzione (periodica, manuale, da ticket)', max_length=20),
        ),
        migrations.AddField(
            model_name='workorder',
            name='reference_batch',
            field=models.CharField(blank=True, default='', help_text='Riferimento batch/regola per manutenzioni generate in blocco', max_length=100),
        ),
    ]
