# Generated by Django 5.2.11 on 2026-05-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0061_assetcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicverification',
            name='is_legacy',
            field=models.BooleanField(db_index=True, default=False, help_text='Se True, il trigger temporale è gestito da MaintenanceRule. Questo record rimane come riferimento fornitore/contratto.'),
        ),
    ]
