# Generated by Django 5.2.11 on 2026-05-08 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0062_periodicverification_is_legacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(db_index=True, default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorder_checklist_done', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='assets.workorder')),
            ],
            options={
                'verbose_name': 'Step checklist OdL',
                'verbose_name_plural': 'Step checklist OdL',
                'ordering': ['work_order', 'step_number', 'id'],
            },
        ),
    ]
