# Generated by Django 5.2.11 on 2026-05-08 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0063_workorderchecklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(choices=[('HOURS', 'Ore'), ('KM', 'Km'), ('CYCLES', 'Cicli'), ('OTHER', 'Altro')], db_index=True, max_length=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_label', models.CharField(blank=True, default='', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='assets.asset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_asset_meters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contatore asset',
                'verbose_name_plural': 'Contatori asset',
                'ordering': ['asset__name', 'meter_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssetMeterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assets.assetmeter')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_meter_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Storico contatore asset',
                'verbose_name_plural': 'Storico contatori asset',
                'ordering': ['-recorded_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='assetmeter',
            constraint=models.UniqueConstraint(fields=('asset', 'meter_type'), name='uniq_asset_meter_type'),
        ),
    ]
