# Generated by Django 5.2.11 on 2026-05-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0064_assetmeter_assetmeterhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='meter_value_at_close',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text="Valore del contatore (ore/km/cicli) al momento della chiusura dell'OdL. Compilato automaticamente dalla view di chiusura se l'asset ha un AssetMeter.", max_digits=12, null=True),
        ),
    ]
