# Generated by Django 5.2.11 on 2026-05-19 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0069_asset_public_share_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdocument',
            name='category',
            field=models.CharField(choices=[('SPECIFICHE', 'Specifiche'), ('INTERVENTI', 'Interventi'), ('MANUALI', 'Manuali')], db_index=True, default='SPECIFICHE', max_length=60),
        ),
        migrations.CreateModel(
            name='AssetCategoryDocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='assets.assetcategory')),
            ],
            options={
                'ordering': ['order', 'name', 'id'],
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
