# Generated by Django 5.2.11 on 2026-06-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0071_workorder_assigned_to_maintenancecheckliststep'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='internal_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
