# Generated by Django 5.2.11 on 2026-06-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0074_maintenance_sidebar_restructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
