# Generated by Django 5.2.11 on 2026-06-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0077_wm_map_edit_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsidebarbutton',
            name='section',
            field=models.CharField(choices=[('MAIN', 'Navigazione'), ('ANALYTICS', 'Analisi e rischio'), ('OPERATIONS', 'Strumenti e gestione')], db_index=True, default='MAIN', max_length=20),
        ),
    ]
