# Generated by Django 5.2.11 on 2026-07-10 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0082_dipendente_area_aziendale_fk'),
        ('assets', '0079_assets_sidebar_clean_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerule',
            name='execution_mode',
            field=models.CharField(choices=[('INTERNAL', 'Interna'), ('EXTERNAL', 'Esterna (ditta terza)')], db_index=True, default='INTERNAL', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancerule',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text="Ditta esterna che esegue l'intervento (solo per manutenzioni esterne).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_rules', to='anagrafica.fornitore'),
        ),
    ]
