# Generated by Django 5.2.11 on 2026-07-15 10:22

import assets.models
import assets.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0080_maintenancerule_execution_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdocument',
            name='file',
            field=models.FileField(storage=assets.storage.PrivateAssetDocumentStorage(), upload_to=assets.models._asset_document_upload_to),
        ),
        migrations.AlterField(
            model_name='workorderattachment',
            name='file',
            field=models.FileField(storage=assets.storage.PrivateAssetDocumentStorage(), upload_to=assets.models._workorder_attachment_upload_to),
        ),
    ]
