# Generated by Django 5.2.11 on 2026-07-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0081_alter_assetdocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='foto_targhetta',
            field=models.ImageField(blank=True, help_text="Foto della targhetta identificativa della macchina, mostrata in cima alla scheda dell'asset.", null=True, upload_to='assets/targhette/', verbose_name='Foto targhetta'),
        ),
    ]
