# Generated by Django 5.2.11 on 2026-07-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0082_asset_foto_targhetta'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='part_145',
            field=models.BooleanField(default=False, help_text="Indica se l'asset rientra nel regolamento aeronautico PART 145.", verbose_name='Rientra in PART 145'),
        ),
    ]
