# Generated by Django 5.2.11 on 2026-07-27 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0085_repoint_work_machines_sidebar_to_asset_list'),
        ('schede_sicurezza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='prodotto_chimico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_container', to='schede_sicurezza.prodottochimico'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('PC', 'PC'), ('NOTEBOOK', 'Portatile'), ('SERVER', 'Server'), ('VM', 'Macchina virtuale'), ('FIREWALL', 'Firewall'), ('STAMPANTE', 'Stampante'), ('HW', 'Dispositivo'), ('FONIA', 'Fonia'), ('CNC', 'CNC'), ('WORK_MACHINE', 'Macchina di lavoro'), ('CARROPONTE', 'Carroponte'), ('CCTV', 'Videosorveglianza'), ('PRODOTTO_CHIMICO', 'Prodotto chimico'), ('OTHER', 'Altro')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='base_asset_type',
            field=models.CharField(choices=[('PC', 'PC'), ('NOTEBOOK', 'Portatile'), ('SERVER', 'Server'), ('VM', 'Macchina virtuale'), ('FIREWALL', 'Firewall'), ('STAMPANTE', 'Stampante'), ('HW', 'Dispositivo'), ('FONIA', 'Fonia'), ('CNC', 'CNC'), ('WORK_MACHINE', 'Macchina di lavoro'), ('CARROPONTE', 'Carroponte'), ('CCTV', 'Videosorveglianza'), ('PRODOTTO_CHIMICO', 'Prodotto chimico'), ('OTHER', 'Altro')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetlabeltemplate',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('PC', 'PC'), ('NOTEBOOK', 'Portatile'), ('SERVER', 'Server'), ('VM', 'Macchina virtuale'), ('FIREWALL', 'Firewall'), ('STAMPANTE', 'Stampante'), ('HW', 'Dispositivo'), ('FONIA', 'Fonia'), ('CNC', 'CNC'), ('WORK_MACHINE', 'Macchina di lavoro'), ('CARROPONTE', 'Carroponte'), ('CCTV', 'Videosorveglianza'), ('PRODOTTO_CHIMICO', 'Prodotto chimico'), ('OTHER', 'Altro')], db_index=True, default='', max_length=20),
        ),
    ]
