# Generated by Django 5.2.16 on 2026-08-05 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0087_workorderexecutionday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceinterventiontemplate',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Durata indicativa usata per pianificare il carico di lavoro.'),
        ),
        migrations.AddField(
            model_name='maintenanceinterventiontemplate',
            name='maintenance_type',
            field=models.CharField(choices=[('ROUTINE', 'Manutenzione ordinaria'), ('INSPECTION', 'Controllo / ispezione'), ('LUBRICATION', 'Lubrificazione'), ('CLEANING', 'Pulizia tecnica'), ('REPLACEMENT', 'Sostituzione programmata'), ('ADJUSTMENT', 'Regolazione / taratura meccanica'), ('SAFETY', 'Sicurezza'), ('CALIBRATION', 'Taratura strumento'), ('OTHER', 'Altro')], db_index=True, default='ROUTINE', max_length=24),
        ),
        migrations.AddField(
            model_name='maintenanceinterventiontemplate',
            name='required_materials',
            field=models.TextField(blank=True, default='', help_text='Ricambi, consumabili o attrezzature normalmente necessari.'),
        ),
        migrations.AddField(
            model_name='maintenancerule',
            name='assets',
            field=models.ManyToManyField(blank=True, help_text="Usati solo quando l'ambito del piano e 'Solo asset selezionati'.", related_name='maintenance_plans', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='maintenancerule',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Manutentore interno predefinito per gli OdL generati dal piano.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerule',
            name='auto_generate_workorders',
            field=models.BooleanField(db_index=True, default=True, help_text="Genera automaticamente l'OdL quando il piano entra nella finestra di preavviso."),
        ),
        migrations.AddField(
            model_name='maintenancerule',
            name='first_due_date',
            field=models.DateField(blank=True, db_index=True, help_text='Prima scadenza del piano quando non esistono ancora esecuzioni.', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerule',
            name='legacy_periodic_verifications',
            field=models.ManyToManyField(blank=True, related_name='maintenance_rules', to='assets.periodicverification'),
        ),
        migrations.AddField(
            model_name='maintenancerule',
            name='scope_type',
            field=models.CharField(choices=[('CATEGORY', 'Tutti gli asset della categoria'), ('ASSETS', 'Solo asset selezionati')], db_index=True, default='CATEGORY', max_length=16),
        ),
    ]
