# Generated by Django 5.2.16 on 2026-08-25 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0090_remove_sharepoint_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='detail_timeline_manual_enabled',
            field=models.BooleanField(default=True, help_text="Consente l'inserimento manuale di voci nella timeline di vita degli asset di questa categoria."),
        ),
        migrations.CreateModel(
            name='AssetTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(db_index=True, help_text="Data in cui l'evento e' accaduto, non quella di inserimento.")),
                ('title', models.CharField(max_length=160)),
                ('tag', models.CharField(blank=True, default='', help_text='Etichetta breve accanto al titolo (es. FERMO, TRASLOCO, COLLAUDO).', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('meta', models.CharField(blank=True, default='', help_text='Riferimento libero: reparto, fornitore, persona.', max_length=120)),
                ('color', models.CharField(choices=[('blue', 'Blu (informativo)'), ('green', 'Verde (positivo)'), ('amber', 'Ambra (attenzione)')], default='blue', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_timeline_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-id'],
                'indexes': [models.Index(fields=['asset', 'event_date'], name='assettl_asset_date_idx')],
            },
        ),
    ]
