# Generated by Django 5.2.16 on 2026-08-27 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0091_assetcategory_detail_timeline_manual_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTimelineHiddenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(choices=[('assignment', 'Assegnazione'), ('inventory', 'Registrazione inventario'), ('provisioning', 'Acquisto / Provisioning'), ('machine_start', 'Messa in servizio macchina')], help_text="Chiave dell'evento automatico da non mostrare in timeline.", max_length=40)),
                ('hidden_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_hidden_events', to='assets.asset')),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_timeline_hidden_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_id', 'event_key'],
                'unique_together': {('asset', 'event_key')},
            },
        ),
    ]
