# Generated by Django 5.2.16 on 2026-09-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0092_assettimelinehiddenevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='is_waiting',
            field=models.BooleanField(db_index=True, default=False, help_text="Intervento in attesa (ricambio, fornitore, produzione, autorizzazione...). Non cambia lo status OPEN: e' un'informazione ortogonale per non alterare i filtri esistenti su STATUS_OPEN."),
        ),
        migrations.AddField(
            model_name='workorder',
            name='wait_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workorder',
            name='wait_reason',
            field=models.CharField(blank=True, choices=[('RICAMBIO', 'Ricambio'), ('FORNITORE', 'Fornitore'), ('PRODUZIONE', 'Produzione'), ('AUTORIZZAZIONE', 'Autorizzazione'), ('ALTRO', 'Altro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workorder',
            name='waiting_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
