# Generated by Django 5.2.16 on 2026-09-01 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0093_workorder_is_waiting_workorder_wait_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text="Data entro cui verificare un intervento chiuso come 'Risolto temporaneamente'.", null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='follow_up_of',
            field=models.ForeignKey(blank=True, help_text="Intervento originale di cui questo e' il follow-up di verifica.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='assets.workorder'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='outcome',
            field=models.CharField(blank=True, choices=[('RESOLVED', 'Risolto'), ('RESOLVED_TEMP', 'Risolto temporaneamente'), ('NOT_RESOLVED', 'Non risolto')], default='', help_text='Esito della chiusura (Risolto / Risolto temporaneamente / Non risolto). Vuoto per gli interventi ancora aperti o annullati.', max_length=20),
        ),
    ]
