# Generated by Django 5.2.16 on 2026-09-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0094_workorder_follow_up_date_workorder_follow_up_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='due_at',
            field=models.DateTimeField(blank=True, help_text="Scadenza esplicita entro cui l'intervento andrebbe concluso (opzionale).", null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('URGENT', 'Urgente'), ('NORMAL', 'Normale'), ('LOW', 'Bassa')], db_index=True, default='NORMAL', help_text="Urgenza dichiarata dell'intervento (non dedotta dall'anzianità di apertura).", max_length=10),
        ),
        migrations.AddField(
            model_name='workorder',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp di inizio lavorazione effettiva (bottone 'Inizia intervento').", null=True),
        ),
    ]
