# Generated by Django 5.2.16 on 2026-09-02 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0095_workorder_due_at_workorder_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancecheckliststep',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text="Step obbligatorio/di sicurezza: blocca la chiusura dell'OdL finché non è completo o saltato con motivazione."),
        ),
        migrations.AddField(
            model_name='maintenancecheckliststep',
            name='range_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='maintenancecheckliststep',
            name='range_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='maintenancecheckliststep',
            name='step_type',
            field=models.CharField(choices=[('YES_NO', 'Sì/No'), ('MEASURE', 'Misura'), ('TEXT', 'Testo'), ('PHOTO', 'Foto')], default='YES_NO', max_length=10),
        ),
        migrations.AddField(
            model_name='maintenancecheckliststep',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Unità di misura (solo step Misura).', max_length=20),
        ),
        migrations.AddField(
            model_name='workorder',
            name='failure_cause',
            field=models.CharField(blank=True, choices=[('ELECTRICAL', 'Elettrica'), ('MECHANICAL', 'Meccanica'), ('HYDRAULIC', 'Idraulica'), ('WEAR', 'Usura'), ('OPERATOR_ERROR', 'Errore operatore'), ('OTHER', 'Altro')], default='', help_text='Causa del guasto, per statistiche di ricorrenza (opzionale).', max_length=20),
        ),
        migrations.AddField(
            model_name='workorderattachment',
            name='checklist_item',
            field=models.ForeignKey(blank=True, help_text="Valorizzato quando l'allegato è la foto di uno step checklist di tipo Foto.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='assets.workorderchecklist'),
        ),
        migrations.AddField(
            model_name='workorderchecklist',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text="Step obbligatorio/di sicurezza: blocca la chiusura dell'OdL finché non è completo o saltato con motivazione."),
        ),
        migrations.AddField(
            model_name='workorderchecklist',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorderchecklist',
            name='range_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workorderchecklist',
            name='range_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workorderchecklist',
            name='skip_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workorderchecklist',
            name='skipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorderchecklist',
            name='skipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorder_checklist_skipped', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderchecklist',
            name='step_type',
            field=models.CharField(choices=[('YES_NO', 'Sì/No'), ('MEASURE', 'Misura'), ('TEXT', 'Testo'), ('PHOTO', 'Foto')], default='YES_NO', max_length=10),
        ),
        migrations.AddField(
            model_name='workorderchecklist',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Unità di misura (solo step Misura).', max_length=20),
        ),
        migrations.AddField(
            model_name='workorderchecklist',
            name='value_numeric',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workorderchecklist',
            name='value_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
