# Generated by Django 5.2.16 on 2026-09-04 12:52

import assets.models
import assets.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0120_responsabili_multipli_reparto_area'),
        ('assets', '0097_seed_il_mio_turno_sidebar_button'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gruppo asset',
                'verbose_name_plural': 'Gruppi asset',
                'ordering': ['sort_order', 'label', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='maintenanceinterventiontemplate',
            options={'ordering': ['sort_order', 'label', 'id'], 'verbose_name': 'Piano di manutenzione', 'verbose_name_plural': 'Piani di manutenzione'},
        ),
        migrations.AddField(
            model_name='maintenanceinterventiontemplate',
            name='attachment_required',
            field=models.BooleanField(db_index=True, default=False, help_text="Se attivo, l'occorrenza non si puo' chiudere senza allegato (obbligatorio per le amministrative)."),
        ),
        migrations.AddField(
            model_name='maintenanceinterventiontemplate',
            name='default_assignee',
            field=models.ForeignKey(blank=True, help_text='Manutentore interno predefinito.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_maintenance_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceinterventiontemplate',
            name='default_supplier',
            field=models.ForeignKey(blank=True, help_text="Ditta esterna predefinita (solo per piani eseguiti all'esterno).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_maintenance_plans', to='anagrafica.fornitore'),
        ),
        migrations.AddField(
            model_name='maintenanceinterventiontemplate',
            name='execution_mode',
            field=models.CharField(choices=[('INTERNAL', 'Interna'), ('EXTERNAL', 'Esterna (ditta terza)')], db_index=True, default='INTERNAL', help_text="Modalita' predefinita di esecuzione; ogni applicazione puo' sovrascriverla.", max_length=20),
        ),
        migrations.AddField(
            model_name='maintenanceinterventiontemplate',
            name='schedule_anchor',
            field=models.CharField(blank=True, choices=[('FROM_COMPLETION', 'Dalla data di esecuzione'), ('FIXED_CALENDAR', 'Dalla scadenza teorica')], default='', help_text='Vuoto = default per tipo: ordinaria dalla data di esecuzione, amministrativa dalla scadenza teorica (il ritardo non sposta il calendario).', max_length=20),
        ),
        migrations.AddField(
            model_name='workorder',
            name='follow_up_checklist_item',
            field=models.ForeignKey(blank=True, help_text='Step di checklist KO / fuori range che ha originato il follow-up.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='assets.workorderchecklist'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='follow_up_reason',
            field=models.TextField(blank=True, default='', help_text='Anomalia rilevata che ha generato il follow-up.'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_massive',
            field=models.BooleanField(db_index=True, default=False, help_text="OdL che organizza piu' occorrenze su asset diversi."),
        ),
        migrations.AddField(
            model_name='workorderattachment',
            name='execution_day',
            field=models.ForeignKey(blank=True, help_text="Giornata di esecuzione a cui appartiene il rapportino (un giorno puo' averne piu' di uno).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='assets.workorderexecutionday'),
        ),
        migrations.AddField(
            model_name='workorderexecutionday',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorderexecutionday',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_workorder_execution_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderexecutionday',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='maintenanceinterventiontemplate',
            name='asset_category',
            field=models.ForeignKey(blank=True, help_text='Categoria di riferimento (facoltativa). Il perimetro reale lo danno le applicazioni.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_intervention_templates', to='assets.assetcategory'),
        ),
        migrations.AlterField(
            model_name='maintenanceinterventiontemplate',
            name='maintenance_type',
            field=models.CharField(choices=[('ROUTINE', 'Manutenzione ordinaria'), ('INSPECTION', 'Controllo / ispezione'), ('LUBRICATION', 'Lubrificazione'), ('CLEANING', 'Pulizia tecnica'), ('REPLACEMENT', 'Sostituzione programmata'), ('ADJUSTMENT', 'Regolazione / taratura meccanica'), ('SAFETY', 'Sicurezza'), ('CALIBRATION', 'Taratura strumento'), ('ADMINISTRATIVE', 'Scadenza amministrativa'), ('OTHER', 'Altro')], db_index=True, default='ROUTINE', max_length=24),
        ),
        migrations.CreateModel(
            name='AssetGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_group_memberships_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='assets.assetgroup')),
            ],
            options={
                'verbose_name': 'Appartenenza a gruppo asset',
                'verbose_name_plural': 'Appartenenze a gruppi asset',
                'ordering': ['group__sort_order', 'asset__name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='assetgroup',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='asset_groups', through='assets.AssetGroupMembership', to='assets.asset'),
        ),
        migrations.CreateModel(
            name='MaintenanceOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(db_index=True)),
                ('warning_days', models.PositiveIntegerField(default=30)),
                ('schedule_anchor', models.CharField(choices=[('FROM_COMPLETION', 'Dalla data di esecuzione'), ('FIXED_CALENDAR', 'Dalla scadenza teorica')], default='FROM_COMPLETION', max_length=20)),
                ('previous_due_date', models.DateField(blank=True, help_text="Scadenza teorica da cui questa occorrenza deriva (serve all'ancoraggio a calendario).", null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Aperta'), ('DONE', 'Eseguita'), ('CANCELED', 'Annullata')], db_index=True, default='OPEN', max_length=12)),
                ('completed_on', models.DateField(blank=True, db_index=True, null=True)),
                ('completion_notes', models.TextField(blank=True, default='')),
                ('downtime_minutes', models.PositiveIntegerField(default=0, help_text="Fermo macchina imputato a questo asset (l'OdL massivo non basta: serve il dato per asset).")),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_notes', models.CharField(blank=True, default='', max_length=255)),
                ('report_received_at', models.DateField(blank=True, help_text="Data di arrivo del rapporto del fornitore (puo' essere posteriore all'esecuzione).", null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('SCHEDULER', 'Generata dallo scheduler'), ('MANUAL', 'Creata a mano'), ('MIGRATION', 'Migrata dal vecchio motore'), ('IMPORT', 'Importata')], db_index=True, default='SCHEDULER', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_occurrences', to='assets.asset')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenance_occurrences', to=settings.AUTH_USER_MODEL)),
                ('execution_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='assets.workorderexecutionday')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='assets.maintenanceinterventiontemplate')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_occurrences', to='anagrafica.fornitore')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='assets.workorder')),
            ],
            options={
                'verbose_name': 'Occorrenza di manutenzione',
                'verbose_name_plural': 'Occorrenze di manutenzione',
                'ordering': ['due_date', 'asset__name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='follow_up_occurrence',
            field=models.ForeignKey(blank=True, help_text="Occorrenza durante la quale e' emerso il problema.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='assets.maintenanceoccurrence'),
        ),
        migrations.CreateModel(
            name='MaintenanceOccurrenceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=assets.storage.PrivateAssetAdministrativeDeadlineStorage(), upload_to=assets.models._occurrence_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assets.maintenanceoccurrence')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_occurrence_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Allegato occorrenza',
                'verbose_name_plural': 'Allegati occorrenze',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('ASSET', 'Asset specifico'), ('GROUP', 'Gruppo asset'), ('CATEGORY', 'Categoria asset')], db_index=True, max_length=16)),
                ('frequency', models.CharField(choices=[('DAYS', 'Giorni'), ('WEEKS', 'Settimane'), ('MONTHS', 'Mesi'), ('YEARS', 'Anni')], default='DAYS', max_length=10)),
                ('interval', models.PositiveSmallIntegerField(default=1, help_text="Ogni quante unita' di frequenza si ripete (es. 3 mesi = MONTHS/3).")),
                ('weekday', models.SmallIntegerField(blank=True, help_text="0=lunedi ... 6=domenica. Usato per ricorrenze tipo 'primo lunedi del mese'.", null=True)),
                ('week_of_month', models.SmallIntegerField(blank=True, help_text='1..4 = prima..quarta settimana, -1 = ultima. Va usato con weekday.', null=True)),
                ('day_of_month', models.SmallIntegerField(blank=True, help_text='1..31 giorno fisso del mese, -1 = ultimo giorno del mese.', null=True)),
                ('month_of_year', models.SmallIntegerField(blank=True, help_text='1..12: mese fisso per le ricorrenze annuali (es. 31 dicembre).', null=True)),
                ('warning_days', models.PositiveIntegerField(default=30, help_text="Giorni di preavviso: da quando l'occorrenza diventa visibile e pianificabile.")),
                ('schedule_anchor', models.CharField(blank=True, choices=[('FROM_COMPLETION', 'Dalla data di esecuzione'), ('FIXED_CALENDAR', 'Dalla scadenza teorica')], default='', help_text='Vuoto = eredita dal Piano (ordinaria: dalla esecuzione, amministrativa: dalla scadenza teorica).', max_length=20)),
                ('first_due_date', models.DateField(blank=True, db_index=True, help_text="Prima scadenza quando non esiste ancora storico per l'asset.", null=True)),
                ('execution_mode', models.CharField(blank=True, choices=[('INTERNAL', 'Interna'), ('EXTERNAL', 'Esterna (ditta terza)')], default='', help_text='Vuoto = eredita dal Piano.', max_length=20)),
                ('is_excluded', models.BooleanField(db_index=True, default=False, help_text="Solo per applicazioni su asset singolo: esclude l'asset dal Piano ereditato dal gruppo.")),
                ('auto_generate', models.BooleanField(db_index=True, default=True, help_text='Genera automaticamente le occorrenze quando si entra nella finestra di preavviso.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plan_assignments', to='assets.asset')),
                ('asset_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plan_assignments', to='assets.assetcategory')),
                ('asset_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plan_assignments', to='assets.assetgroup')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_plan_assignments', to=settings.AUTH_USER_MODEL)),
                ('legacy_rule', models.ForeignKey(blank=True, help_text='Regola di origine, valorizzata dalla migrazione dal vecchio motore.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_assignments', to='assets.maintenancerule')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assets.maintenanceinterventiontemplate')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_plan_assignments', to='anagrafica.fornitore')),
            ],
            options={
                'verbose_name': 'Applicazione piano di manutenzione',
                'verbose_name_plural': 'Applicazioni piani di manutenzione',
                'ordering': ['plan__sort_order', 'plan__label', 'target_type', 'id'],
            },
        ),
        migrations.AddField(
            model_name='maintenanceoccurrence',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='assets.maintenanceplanassignment'),
        ),
        migrations.AddConstraint(
            model_name='assetgroupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'asset'), name='uniq_asset_group_membership'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplanassignment',
            index=models.Index(fields=['plan', 'is_active'], name='idx_plan_assignment_active'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplanassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('target_type', 'ASSET')), fields=('plan', 'asset'), name='uniq_plan_assignment_asset'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplanassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('target_type', 'GROUP')), fields=('plan', 'asset_group'), name='uniq_plan_assignment_group'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplanassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('target_type', 'CATEGORY')), fields=('plan', 'asset_category'), name='uniq_plan_assignment_category'),
        ),
        migrations.AddIndex(
            model_name='maintenanceoccurrence',
            index=models.Index(fields=['status', 'due_date'], name='idx_occurrence_status_due'),
        ),
        migrations.AddIndex(
            model_name='maintenanceoccurrence',
            index=models.Index(fields=['asset', 'due_date'], name='idx_occurrence_asset_due'),
        ),
        migrations.AddIndex(
            model_name='maintenanceoccurrence',
            index=models.Index(fields=['plan', 'due_date'], name='idx_occurrence_plan_due'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceoccurrence',
            constraint=models.UniqueConstraint(fields=('plan', 'asset', 'due_date'), name='uniq_maintenance_occurrence'),
        ),
    ]
