# Generated by Django 5.2.16 on 2026-09-14 09:31

import assets.models
import assets.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0104_sidebar_nascondi_il_mio_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdocument',
            name='file',
            field=models.FileField(max_length=255, storage=assets.storage.PrivateAssetDocumentStorage(), upload_to=assets.models._asset_document_upload_to),
        ),
    ]
