# Generated by Django 5.2.16 on 2026-09-25 13:40

import assets.models
import assets.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0127_visitamedica_superata_e_famiglia'),
        ('assets', '0111_sidebar_manutenzione_scadenze_amministrative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Voce di checklist (verifica periodica)',
                'verbose_name_plural': 'Voci di checklist (verifiche periodiche)',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodicCheckSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_on', models.DateField(db_index=True)),
                ('technician', models.CharField(blank=True, default='', max_length=120)),
                ('outcome', models.CharField(choices=[('OK', 'Conforme'), ('REMARKS', 'Conforme con rilievi'), ('KO', 'Non conforme'), ('ARCHIVE', 'Storico')], db_index=True, default='OK', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Da confermare'), ('CONFIRMED', 'Confermata')], db_index=True, default='CONFIRMED', max_length=10)),
                ('source', models.CharField(choices=[('MANUAL', 'Inserita a mano'), ('IMPORT', 'Importata dallo storico'), ('PARSER', 'Letta dal documento')], default='MANUAL', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('import_key', models.CharField(blank=True, default='', max_length=255)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_check_sessions_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_check_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_check_sessions', to='anagrafica.fornitore')),
            ],
            options={
                'verbose_name': 'Verifica periodica eseguita',
                'verbose_name_plural': 'Verifiche periodiche eseguite',
                'ordering': ['-performed_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodicCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ITEM', 'Voce di checklist'), ('REMARK', 'Rilievo / prescrizione')], default='ITEM', max_length=10)),
                ('label', models.CharField(max_length=255)),
                ('result', models.CharField(choices=[('OK', 'OK'), ('KO', 'Non OK'), ('NA', 'Non applicabile')], default='OK', max_length=4)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='assets.periodiccheckitem')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_check_results', to='assets.workorder')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assets.periodicchecksession')),
            ],
            options={
                'verbose_name': 'Esito verifica periodica',
                'verbose_name_plural': 'Esiti verifiche periodiche',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodicCheckAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=assets.storage.PrivatePeriodicCheckStorage(), upload_to=assets.models._periodic_check_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_check_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assets.periodicchecksession')),
            ],
            options={
                'verbose_name': 'Allegato verifica periodica',
                'verbose_name_plural': 'Allegati verifiche periodiche',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodicCheckSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, help_text='Asset proposto sugli ordini di lavoro nati dalle verifiche di questo impianto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_check_systems', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Impianto (verifiche periodiche)',
                'verbose_name_plural': 'Impianti (verifiche periodiche)',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodicCheckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reference_code', models.CharField(blank=True, default='', help_text='Codice del fornitore o interno (es. 005).', max_length=40)),
                ('method', models.CharField(choices=[('CHECKLIST', 'Checklist a voci'), ('REPORT', 'Verbale / rapporto esterno'), ('LAYOUT', 'Planimetria a punti'), ('MEASURES', 'Misure per punto')], default='REPORT', max_length=20)),
                ('frequency_months', models.PositiveSmallIntegerField(default=12)),
                ('warning_days', models.PositiveSmallIntegerField(default=30)),
                ('executor_label', models.CharField(blank=True, default='', help_text="Chi esegue, se non e' un fornitore in anagrafica.", max_length=120)),
                ('legal_reference', models.CharField(blank=True, default='', max_length=200)),
                ('instructions', models.TextField(blank=True, default='')),
                ('archive_folder', models.CharField(blank=True, default='', max_length=255)),
                ('next_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_check_types', to='anagrafica.fornitore')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_types', to='assets.periodicchecksystem')),
            ],
            options={
                'verbose_name': 'Tipo di verifica periodica',
                'verbose_name_plural': 'Tipi di verifica periodica',
                'ordering': ['system__sort_order', 'system__name', 'sort_order', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='periodicchecksession',
            name='check_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='assets.periodicchecktype'),
        ),
        migrations.AddField(
            model_name='periodiccheckitem',
            name='check_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.periodicchecktype'),
        ),
        migrations.AddConstraint(
            model_name='periodicchecktype',
            constraint=models.UniqueConstraint(fields=('system', 'name'), name='uniq_periodic_check_type_system_name'),
        ),
        migrations.AddConstraint(
            model_name='periodicchecksession',
            constraint=models.UniqueConstraint(condition=models.Q(('import_key__gt', '')), fields=('import_key',), name='uniq_periodic_check_session_import_key'),
        ),
    ]
