# Generated by Django 5.2.16 on 2026-09-25 16:52

import assets.models
import assets.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0127_visitamedica_superata_e_famiglia'),
        ('assets', '0113_sidebar_manutenzione_verifiche_periodiche'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicCheckPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('label_x', models.FloatField(blank=True, null=True)),
                ('label_y', models.FloatField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Punto di planimetria',
                'verbose_name_plural': 'Punti di planimetria',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='periodiccheckresult',
            name='category',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='periodicchecksession',
            name='reading',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='periodicchecksession',
            name='sheet_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='periodicchecktype',
            name='point_categories',
            field=models.TextField(blank=True, default='Non funzionante\nBassa autonomia'),
        ),
        migrations.AlterField(
            model_name='periodiccheckresult',
            name='kind',
            field=models.CharField(choices=[('ITEM', 'Voce di checklist'), ('REMARK', 'Rilievo / prescrizione'), ('POINT', 'Punto della planimetria')], default='ITEM', max_length=10),
        ),
        migrations.AlterField(
            model_name='periodicchecksession',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Inserita a mano'), ('IMPORT', 'Importata dallo storico'), ('PARSER', 'Foglio del portale')], default='MANUAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='periodicchecksession',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Foglio stampato, in attesa della scansione'), ('DRAFT', 'Da confermare'), ('CONFIRMED', 'Confermata')], db_index=True, default='CONFIRMED', max_length=10),
        ),
        migrations.CreateModel(
            name='PeriodicCheckLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_pdf', models.FileField(storage=assets.storage.PrivatePeriodicCheckStorage(), upload_to=assets.models._periodic_layout_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('page_index', models.PositiveSmallIntegerField(default=0)),
                ('exclude_areas', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('check_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='assets.periodicchecktype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planimetria di verifica periodica',
                'verbose_name_plural': 'Planimetrie di verifica periodica',
                'ordering': ['check_type_id', '-version'],
            },
        ),
        migrations.AddField(
            model_name='periodicchecksession',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='assets.periodicchecklayout'),
        ),
        migrations.AddConstraint(
            model_name='periodicchecksession',
            constraint=models.UniqueConstraint(condition=models.Q(('sheet_token__gt', '')), fields=('sheet_token',), name='uniq_periodic_check_session_sheet_token'),
        ),
        migrations.AddField(
            model_name='periodiccheckpoint',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='assets.periodicchecklayout'),
        ),
        migrations.AddField(
            model_name='periodiccheckresult',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='assets.periodiccheckpoint'),
        ),
        migrations.AddConstraint(
            model_name='periodicchecklayout',
            constraint=models.UniqueConstraint(fields=('check_type', 'version'), name='uniq_periodic_layout_type_version'),
        ),
        migrations.AddConstraint(
            model_name='periodiccheckpoint',
            constraint=models.UniqueConstraint(fields=('layout', 'code'), name='uniq_periodic_point_layout_code'),
        ),
    ]
