# Generated by Django 5.2.16 on 2026-09-25 21:44

import assets.models
import assets.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0114_verifiche_periodiche_planimetrie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicCheckIntakeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attiva', models.BooleanField(default=False, help_text='Se spenta, il lavoro periodico non guarda la cartella. Il caricamento dalla pagina della verifica funziona comunque.')),
                ('cartella', models.CharField(blank=True, default='\\\\pclogsys\\PortaleNovicrom\\scansioni\\verifiche', help_text="Percorso UNC della cartella dove lo scanner salva i fogli. Deve essere raggiungibile dall'utente con cui gira il portale: una lettera di unita' mappata non e' visibile a un servizio.", max_length=500)),
                ('sposta_elaborati', models.BooleanField(default=True, help_text='Sposta i file letti in «elaborati» e quelli non riusciti in «errori»: la cartella resta pulita e nulla viene riletto due volte.')),
                ('max_file_per_giro', models.PositiveIntegerField(default=25, help_text='Quanti file al massimo a ogni passaggio (un arretrato non blocca il lavoro).')),
                ('ultima_esecuzione', models.DateTimeField(blank=True, null=True)),
                ('ultimo_esito', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Acquisizione fogli di verifica da cartella',
                'verbose_name_plural': 'Acquisizione fogli di verifica da cartella',
            },
        ),
        migrations.CreateModel(
            name='PeriodicCheckIntakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('file_name', models.CharField(max_length=255)),
                ('page', models.PositiveSmallIntegerField(default=1)),
                ('source', models.CharField(default='CARTELLA', max_length=20)),
                ('outcome', models.CharField(choices=[('READ', 'Letto e associato'), ('UNMATCHED', 'Da smistare'), ('ERROR', 'Errore di lettura'), ('ASSIGNED', 'Associato a mano'), ('DISCARDED', 'Scartato')], db_index=True, max_length=10)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('token', models.CharField(blank=True, default='', max_length=16)),
                ('scan', models.FileField(blank=True, storage=assets.storage.PrivatePeriodicCheckStorage(), upload_to=assets.models._periodic_intake_upload_to)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_logs', to='assets.periodicchecksession')),
            ],
            options={
                'verbose_name': 'Scansione di verifica ricevuta',
                'verbose_name_plural': 'Scansioni di verifica ricevute',
                'ordering': ['-received_at', '-id'],
            },
        ),
    ]
