# Generated by Django 5.2.16 on 2026-09-25 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0115_verifiche_periodiche_acquisizione'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicCheckCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(choices=[('blue', 'Blu'), ('red', 'Rosso'), ('orange', 'Arancio'), ('green', 'Verde'), ('purple', 'Viola'), ('teal', 'Petrolio'), ('slate', 'Grigio')], default='blue', max_length=12)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria (verifiche periodiche)',
                'verbose_name_plural': 'Categorie (verifiche periodiche)',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='periodicchecktype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_types', to='assets.periodiccheckcategory'),
        ),
    ]
