# Generated by Django 5.2.16 on 2026-09-26 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0116_verifiche_periodiche_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodiccheckresult',
            name='values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='periodiccheckresult',
            name='kind',
            field=models.CharField(choices=[('ITEM', 'Voce di checklist'), ('REMARK', 'Rilievo / prescrizione'), ('POINT', 'Punto della planimetria'), ('MEASURE', 'Punto misurato')], default='ITEM', max_length=10),
        ),
        migrations.CreateModel(
            name='PeriodicCheckMeasureField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('unit', models.CharField(blank=True, default='', max_length=15)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('check_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure_fields', to='assets.periodicchecktype')),
            ],
            options={
                'verbose_name': 'Grandezza misurata (verifica periodica)',
                'verbose_name_plural': 'Grandezze misurate (verifiche periodiche)',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
