# Generated by Django 5.2.16 on 2026-09-26 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0118_acl_v2_verifiche_impianti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome report')),
                ('asset_type', models.CharField(blank=True, choices=[('PC', 'PC'), ('NOTEBOOK', 'Portatile'), ('SERVER', 'Server'), ('VM', 'Macchina virtuale'), ('FIREWALL', 'Firewall'), ('STAMPANTE', 'Stampante'), ('HW', 'Dispositivo'), ('FONIA', 'Fonia'), ('CNC', 'CNC'), ('WORK_MACHINE', 'Macchina di lavoro'), ('CARROPONTE', 'Carroponte'), ('CCTV', 'Videosorveglianza'), ('PRODOTTO_CHIMICO', 'Prodotto chimico'), ('OTHER', 'Altro')], max_length=20, verbose_name='Tipo asset')),
                ('reparto', models.CharField(blank=True, max_length=120, verbose_name='Reparto')),
                ('include_snmp', models.BooleanField(default=True, verbose_name='Includi MFC e monitor SNMP collegati')),
                ('export_pdf', models.BooleanField(default=True, verbose_name='PDF')),
                ('export_excel', models.BooleanField(default=True, verbose_name='Excel')),
                ('frequency', models.CharField(choices=[('ONCE', 'Una sola volta'), ('DAILY', 'Giornaliera'), ('WEEKLY', 'Settimanale'), ('MONTHLY', 'Mensile')], default='MONTHLY', max_length=10, verbose_name='Frequenza')),
                ('next_run', models.DateTimeField(verbose_name='Prossima estrazione')),
                ('anchor_day', models.PositiveSmallIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True, verbose_name='Attiva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.assetcategory', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AssetReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('enqueued_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('PENDING', 'In coda'), ('RUNNING', 'In elaborazione'), ('DONE', 'Disponibile'), ('ERROR', 'Errore')], default='PENDING', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('configuration', models.JSONField(default=dict)),
                ('scope_key', models.CharField(db_index=True, max_length=64)),
                ('snapshot', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('pdf_content', models.BinaryField(max_length='max', null=True)),
                ('excel_content', models.BinaryField(max_length='max', null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='assets.assetreportschedule')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'due_at'), name='asset_report_due_unique')],
            },
        ),
    ]
