# Generated by Django 5.2.16 on 2026-10-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0120_reportistica_acl'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='immagine',
            field=models.ImageField(blank=True, help_text="Foto o immagine dell'asset, mostrata come icona in cima alla scheda.", null=True, upload_to='assets/immagini/', verbose_name='Immagine asset'),
        ),
    ]
