# Generated by Django 5.2.16 on 2026-10-10 09:26
"""Storico campi asset (stato, assegnazione, rete) con lo stato attuale come baseline."""

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


CAMPI_ASSET = ["status", "reparto", "assigned_legacy_user_id", "assignment_to", "assignment_reparto", "assignment_location"]
CAMPI_ENDPOINT = ["endpoint_name", "ip", "vlan", "switch_name", "switch_port", "punto"]


def _testo(value):
    return "" if value is None else str(value).strip()


def baseline(apps, schema_editor):
    """Primo punto di storico: lo stato attuale con fonte "baseline", senza inventare cronologia."""
    Asset = apps.get_model("assets", "Asset")
    Endpoint = apps.get_model("assets", "AssetEndpoint")
    History = apps.get_model("assets", "AssetFieldHistory")
    db = schema_editor.connection.alias
    ora = django.utils.timezone.now()
    righe = []

    def flush(force=False):
        if righe and (force or len(righe) >= 500):
            History.objects.using(db).bulk_create(righe, batch_size=200)
            righe.clear()

    def riga(asset_id, campo, valore, endpoint_id=None, label=""):
        righe.append(History(asset_id=asset_id, campo=campo, valore_prima="", valore_dopo=valore,
                             endpoint_id=endpoint_id, endpoint_label=label[:255], fonte="baseline",
                             dettaglio="Stato al rilascio dello storico", cambiato_il=ora))
        flush()

    def pagine(qs, campi):
        # Pagine per pk, liste materializzate: su SQL Server (senza MARS) un cursore
        # aperto mentre si fanno gli INSERT blocca la connessione.
        ultimo = 0
        while True:
            pagina = list(qs.filter(pk__gt=ultimo).order_by("pk").values("id", *campi)[:1000])
            if not pagina:
                return
            yield from pagina
            ultimo = pagina[-1]["id"]

    for row in pagine(Asset.objects.using(db), CAMPI_ASSET):
        for campo in CAMPI_ASSET:
            valore = _testo(row[campo])
            if valore:
                riga(row["id"], campo, valore)
    for row in pagine(Endpoint.objects.using(db), ["asset_id", *CAMPI_ENDPOINT]):
        label = " · ".join(x for x in (_testo(row["endpoint_name"]), _testo(row["ip"]),
                                       f"VLAN {row['vlan']}" if row["vlan"] else "") if x)
        riga(row["asset_id"], "endpoint", "presente", row["id"], label)
        for campo in CAMPI_ENDPOINT:
            valore = _testo(row[campo])
            if valore:
                riga(row["asset_id"], f"endpoint.{campo}", valore, row["id"], label)
    flush(force=True)


def baseline_indietro(apps, schema_editor):
    pass  # la tabella viene eliminata dall'operazione CreateModel inversa


BINDING_NOTE = "[ASSET_STORICO] Storico campi asset"
BINDING_CODE = "legacy.assets.assets_view"


def binding(apps, schema_editor):
    """La route dello storico eredita il permesso del dettaglio asset."""
    Permission = apps.get_model("core", "PermissionDefinition")
    Binding = apps.get_model("core", "RoutePermissionBinding")
    db = schema_editor.connection.alias
    Permission.objects.using(db).get_or_create(
        code=BINDING_CODE, defaults={"module": "assets", "label": "Assets - Dettaglio asset", "is_active": True})
    Binding.objects.using(db).get_or_create(
        route_name="", path_pattern=r"^/assets/view/\d+/storico-campi",
        defaults={"permission_id": BINDING_CODE, "match_strategy": "regex", "source_app": "assets",
                  "priority": 100, "is_active": True, "note": BINDING_NOTE},
    )


def binding_indietro(apps, schema_editor):
    apps.get_model("core", "RoutePermissionBinding").objects.using(schema_editor.connection.alias).filter(
        note=BINDING_NOTE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0124_qr_link_pubblico_opt_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_permissiondefinition_rolepermissiongrant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFieldHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(db_index=True, max_length=40)),
                ('endpoint_id', models.IntegerField(blank=True, null=True)),
                ('endpoint_label', models.CharField(blank=True, default='', max_length=255)),
                ('valore_prima', models.TextField(blank=True, default='')),
                ('valore_dopo', models.TextField(blank=True, default='')),
                ('fonte', models.CharField(choices=[('form', 'Utente (scheda)'), ('bulk', 'Modifica in blocco'), ('import', 'Import'), ('admin', 'Amministrazione'), ('api', 'Integrazione'), ('job', 'Job automatico'), ('baseline', 'Stato iniziale')], db_index=True, max_length=16)),
                ('autore_display', models.CharField(blank=True, default='', max_length=200)),
                ('dettaglio', models.CharField(blank=True, default='', max_length=255)),
                ('cambiato_il', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_history', to='assets.asset')),
                ('autore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Storico campo asset',
                'verbose_name_plural': 'Storico campi asset',
                'ordering': ['-cambiato_il', '-id'],
                'indexes': [models.Index(fields=['asset', 'cambiato_il'], name='assets_hist_asset_when'), models.Index(fields=['asset', 'campo', 'cambiato_il'], name='assets_hist_asset_field')],
            },
        ),
        migrations.RunPython(baseline, baseline_indietro),
        migrations.RunPython(binding, binding_indietro),
    ]
