# Generated by Django 5.2.16 on 2026-10-10 09:48
"""Report salvati/pianificati del catalogo e binding ACL v2 di /assets/reports/catalogo."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

NOTE = "[ASSET_REPORT_CATALOGO] Catalogo report e report salvati"
CODE = "legacy.assets.assets_reports"


def binding(apps, schema_editor):
    Permission = apps.get_model("core", "PermissionDefinition")
    Binding = apps.get_model("core", "RoutePermissionBinding")
    db = schema_editor.connection.alias
    Permission.objects.using(db).get_or_create(code=CODE, defaults={"module": "assets", "label": "Assets - Reports", "is_active": True})
    Binding.objects.using(db).get_or_create(
        route_name="", path_pattern="/assets/reports/catalogo",
        defaults={"permission_id": CODE, "match_strategy": "prefix", "source_app": "assets", "priority": 100,
                  "is_active": True, "note": NOTE},
    )


def binding_indietro(apps, schema_editor):
    apps.get_model("core", "RoutePermissionBinding").objects.using(schema_editor.connection.alias).filter(note=NOTE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0125_storico_campi_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_permissiondefinition_rolepermissiongrant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(db_index=True, max_length=60)),
                ('nome', models.CharField(max_length=120)),
                ('filtri', models.JSONField(blank=True, default=dict)),
                ('condiviso', models.BooleanField(db_index=True, default=False)),
                ('frequenza', models.CharField(blank=True, choices=[('', 'Nessun invio'), ('DAILY', 'Ogni giorno'), ('WEEKLY', 'Ogni settimana'), ('MONTHLY', 'Ogni mese')], default='', max_length=10)),
                ('formato', models.CharField(choices=[('xlsx', 'Excel'), ('pdf', 'PDF')], default='xlsx', max_length=4)),
                ('prossimo_invio', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ultimo_invio', models.DateTimeField(blank=True, null=True)),
                ('ultimo_esito', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinatari', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_saved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report asset salvato',
                'verbose_name_plural': 'Report asset salvati',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.RunPython(binding, binding_indietro),
    ]
