# Generated by Django 5.2.11 on 2026-03-02 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notizie', '0002_nav_entry'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notiziaaudience',
            name='notizie_audience_notizia_role_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='notizialettura',
            name='notizie_lettura_notizia_user_ver_uniq',
        ),
        migrations.AlterUniqueTogether(
            name='notiziaaudience',
            unique_together={('notizia', 'legacy_role_id')},
        ),
        migrations.AlterUniqueTogether(
            name='notizialettura',
            unique_together={('notizia', 'legacy_user_id', 'versione_letta')},
        ),
    ]
