# Generated by Django 5.2.16 on 2026-10-07 07:49

import core.private_attachments
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notizie', '0003_remove_notiziaaudience_notizie_audience_notizia_role_uniq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notiziaallegato',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.private_attachments.PrivateAttachmentStorage(download_hint="Usa {% url 'notizie_allegato_download' a.id %}."), upload_to='notizie/allegati/'),
        ),
    ]
