# Generated by Django 5.2.11 on 2026-05-08 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0066_assetmaintenancebudget'),
        ('rilevazione_incidenti', '0005_rilevazioneincidente_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='rilevazioneincidente',
            name='planimetria_area',
            field=models.ForeignKey(blank=True, help_text="Area della planimetria associata all'evento (opzionale)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rilevazioni_sicurezza', to='assets.plantlayoutarea'),
        ),
        migrations.AddField(
            model_name='rilevazioneincidente',
            name='tipo_evento',
            field=models.CharField(choices=[('unsafe_condition', 'Unsafe condition / atto non sicuro'), ('near_miss', 'Near miss'), ('incidente', 'Incidente')], db_index=True, default='unsafe_condition', help_text='Categoria normalizzata per KPI: unsafe_condition, near_miss o incidente', max_length=30),
        ),
    ]
