# Generated by Django 5.2.11 on 2026-03-10 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0002_fornitoreasset'),
        ('assets', '0027_assetlistlayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketImpostazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IT', 'Ticket IT'), ('MAN', 'Ticket Manutenzione')], max_length=5, unique=True)),
                ('sharepoint_list_id', models.CharField(blank=True, max_length=100)),
                ('team_gestori', models.JSONField(default=list)),
                ('acl_apertura', models.JSONField(default=list)),
                ('acl_gestione', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impostazioni ticket',
                'verbose_name_plural': 'Impostazioni ticket',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(editable=False, max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('IT', 'Ticket IT'), ('MAN', 'Ticket Manutenzione')], db_index=True, max_length=5)),
                ('titolo', models.CharField(max_length=300)),
                ('descrizione', models.TextField()),
                ('categoria', models.CharField(max_length=30)),
                ('priorita', models.CharField(choices=[('BASSA', 'Bassa'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('incide_sicurezza', models.BooleanField(default=False)),
                ('stato', models.CharField(choices=[('APERTA', 'Aperta'), ('IN_CARICO', 'In carico'), ('RISOLTO', 'Risolto'), ('CHIUSO', 'Chiuso'), ('ANNULLATO', 'Annullato')], db_index=True, default='APERTA', max_length=15)),
                ('asset_descrizione_libera', models.CharField(blank=True, max_length=300)),
                ('richiedente_nome', models.CharField(max_length=200)),
                ('richiedente_email', models.CharField(blank=True, max_length=200)),
                ('richiedente_legacy_user_id', models.IntegerField(blank=True, null=True)),
                ('assegnato_a', models.CharField(blank=True, max_length=200)),
                ('assegnato_email', models.CharField(blank=True, max_length=200)),
                ('note_interne', models.TextField(blank=True)),
                ('sharepoint_item_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='assets.asset')),
                ('delegato_fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_delegati', to='anagrafica.fornitore')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAllegato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tickets/allegati/%Y/%m/')),
                ('nome_originale', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by_nome', models.CharField(max_length=200)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Allegato ticket',
                'verbose_name_plural': 'Allegati ticket',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketCommento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autore_nome', models.CharField(max_length=200)),
                ('autore_email', models.CharField(blank=True, max_length=200)),
                ('testo', models.TextField()),
                ('is_interno', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Commento ticket',
                'verbose_name_plural': 'Commenti ticket',
                'ordering': ['created_at'],
            },
        ),
    ]
