# Generated by Django 5.2.11 on 2026-03-31 10:30

import tickets.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketallegato",
            name="file",
            field=models.FileField(storage=tickets.storage.PrivateTicketStorage, upload_to="tickets/allegati/%Y/%m/"),
        ),
    ]
