# Generated by Django 5.2.11 on 2026-04-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='stato',
            field=models.CharField(choices=[('APERTA', 'Aperta'), ('IN_CARICO', 'In carico'), ('IN_ATTESA', 'In attesa'), ('RISOLTO', 'Risolto'), ('CHIUSO', 'Chiuso'), ('ANNULLATO', 'Annullato')], db_index=True, default='APERTA', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticketintervento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketstatolog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
