# Generated by Django 5.2.11 on 2026-05-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_costi_componenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='include_in_maintenance_register',
            field=models.BooleanField(default=True, help_text='Se attivo, il ticket manutentivo collegato a un asset compare nel registro manutenzione come manutenzione straordinaria.', verbose_name='Includi nel registro manutenzione'),
        ),
    ]
