# Generated by Django 5.2.16 on 2026-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_backfill_richiedente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketallegato',
            name='descrizione',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ticketallegato',
            name='nota_validazione',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='ticketallegato',
            name='origine',
            field=models.CharField(choices=[('PORTALE', 'Portale'), ('QR', 'QR code (senza login)')], default='PORTALE', max_length=10),
        ),
        migrations.AddField(
            model_name='ticketallegato',
            name='stato_validazione',
            field=models.CharField(choices=[('DA_VALIDARE', 'Da validare'), ('VALIDATO', 'Validato'), ('RIFIUTATO', 'Rifiutato')], db_index=True, default='VALIDATO', max_length=12),
        ),
        migrations.AddField(
            model_name='ticketallegato',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('RAPPORTINO', 'Rapportino di intervento'), ('FOTO', 'Foto'), ('ALTRO', 'Altro documento')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='ticketallegato',
            name='uploaded_by_ditta',
            field=models.CharField(blank=True, help_text='Ditta del tecnico che ha caricato il file (dal QR)', max_length=200),
        ),
        migrations.AddField(
            model_name='ticketallegato',
            name='uploaded_by_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticketallegato',
            name='validato_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketallegato',
            name='validato_da_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
