from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = "assets"

urlpatterns = [
    path("assets/", views.asset_dashboard, name="asset_dashboard"),
    path("assets/lista/", views.asset_list, name="asset_list"),
    path("assets/componenti/", views.asset_component_list, name="asset_component_list"),
    path("assets/componenti/new/", views.asset_component_create, name="asset_component_create"),
    path("assets/componenti/edit/<int:id>/", views.asset_component_edit, name="asset_component_edit"),
    path("assets/scadenze/", views.asset_administrative_deadline_list, name="asset_administrative_deadline_list"),
    path("assets/scadenze/new/", views.asset_administrative_deadline_create, name="asset_administrative_deadline_create"),
    path(
        "assets/scadenze/edit/<int:id>/",
        views.asset_administrative_deadline_edit,
        name="asset_administrative_deadline_edit",
    ),
    path("assets/manutenzione/templates/", views.maintenance_template_list, name="maintenance_template_list"),
    path("assets/manutenzione/templates/new/", views.maintenance_template_create, name="maintenance_template_create"),
    path(
        "assets/manutenzione/templates/edit/<int:id>/",
        views.maintenance_template_edit,
        name="maintenance_template_edit",
    ),
    path("assets/manutenzione/regole/", views.maintenance_rule_list, name="maintenance_rule_list"),
    path("assets/manutenzione/regole/new/", views.maintenance_rule_create, name="maintenance_rule_create"),
    path("assets/manutenzione/regole/edit/<int:id>/", views.maintenance_rule_edit, name="maintenance_rule_edit"),
    path("assets/manutenzione/prossime/", views.maintenance_schedule, name="maintenance_schedule"),
    path("assets/manutenzione/contratti/", views.assistance_contract_list, name="assistance_contract_list"),
    path("assets/licenze/", views.software_license_list, name="software_license_list"),
    path("assets/work-machines/", views.work_machine_list, name="work_machine_list"),
    path("assets/work-machines/dashboard/", views.work_machine_dashboard, name="work_machine_dashboard"),
    path("assets/work-machines/map/", views.plant_layout_map, name="plant_layout_map"),
    path("assets/work-machines/map/editor/", views.plant_layout_editor, name="plant_layout_editor"),
    path("assets/work-machines/new/", views.work_machine_create, name="work_machine_create"),
    path("assets/work-machines/edit/<int:id>/", views.work_machine_edit, name="work_machine_edit"),
    path("assets/view/", views.asset_detail, name="asset_view"),
    path("assets/view/<int:id>/", views.asset_detail, name="asset_view"),
    path("assets/view/<int:asset_id>/componenti/", views.asset_component_list, name="asset_component_list_for_asset"),
    path(
        "assets/manutenzione/asset-rules/<int:asset_id>/",
        views.asset_maintenance_rule_list,
        name="asset_maintenance_rule_list",
    ),
    path(
        "assets/manutenzione/asset-rule-overrides/new/<int:asset_id>/<int:rule_id>/",
        views.asset_maintenance_rule_override_create,
        name="asset_maintenance_rule_override_create",
    ),
    path(
        "assets/manutenzione/asset-rule-overrides/edit/<int:asset_id>/<int:id>/",
        views.asset_maintenance_rule_override_edit,
        name="asset_maintenance_rule_override_edit",
    ),
    path(
        "assets/manutenzione/asset-rule-overrides/reset/<int:asset_id>/<int:id>/",
        views.asset_maintenance_rule_override_reset,
        name="asset_maintenance_rule_override_reset",
    ),
    path("assets/view-layout/", views.asset_detail_layout_admin, name="asset_detail_layout_admin"),
    path("assets/view/<int:id>/report.pdf", views.asset_report_pdf, name="asset_report_pdf"),
    path("assets/view/<int:id>/qr-label/", views.asset_qr_label, name="asset_qr_label"),
    path("assets/labels/", views.asset_label_designer, name="asset_label_designer"),
    path("assets/new/", views.asset_create, name="asset_create"),
    path("assets/edit/", views.asset_edit, name="asset_edit"),
    path("assets/edit/<int:id>/", views.asset_edit, name="asset_edit"),
    path("assets/assign/", views.assignment_set, name="asset_assign"),
    path("assets/assign/<int:id>/", views.assignment_set, name="asset_assign"),
    path("assets/workorders/", views.workorder_list, name="wo_list"),
    path("assets/workorders/new/", views.workorder_create, name="wo_create"),
    path("assets/workorders/new/<int:id>/", views.workorder_create, name="wo_create"),
    path("assets/workorders/view/", views.workorder_detail, name="wo_view"),
    path("assets/workorders/view/<int:id>/", views.workorder_detail, name="wo_view"),
    path("assets/workorders/close/", views.workorder_close, name="wo_close"),
    path("assets/workorders/close/<int:id>/", views.workorder_close, name="wo_close"),
    path("assets/manutenzione/verifiche/", views.periodic_verification_list, name="periodic_verifications"),
    path(
        "assets/verifiche-periodiche/",
        RedirectView.as_view(pattern_name="assets:periodic_verifications", permanent=False),
    ),
    path("assets/reports/", views.reports_dashboard, name="reports"),
    path("assets/reports/manage/", views.report_template_admin, name="report_template_admin"),
    path(
        "assets/reports/work-machines/maintenance-month.pdf",
        views.work_machine_maintenance_month_pdf,
        name="work_machine_maintenance_month_pdf",
    ),
    path("assets/impostazioni/", views.gestione_admin, name="gestione_admin"),
    path("assets/gestione/", RedirectView.as_view(pattern_name="assets:gestione_admin", permanent=False)),
    path("assets/bulk-update/", views.asset_bulk_update, name="asset_bulk_update"),
    path("assets/dashboard/", RedirectView.as_view(pattern_name="assets:asset_dashboard", permanent=False)),
    path("api/assets/dashboard/config/", views.api_asset_dashboard_save_config, name="api_dashboard_save_config"),
]
