from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = "assets"

urlpatterns = [
    path("assets/", views.asset_dashboard, name="asset_dashboard"),
    path("assets/lista/", views.asset_list, name="asset_list"),
    path("assets/part-145/", views.asset_part_145_list, name="part_145_list"),
    path("assets/part-145/export.xlsx", views.asset_part_145_export_excel, name="part_145_export_excel"),
    path("assets/part-145/export.pdf", views.asset_part_145_export_pdf, name="part_145_export_pdf"),
    path("assets/componenti/", views.asset_component_list, name="asset_component_list"),
    path("assets/componenti/new/", views.asset_component_create, name="asset_component_create"),
    path("assets/componenti/edit/<int:id>/", views.asset_component_edit, name="asset_component_edit"),
    path("assets/scadenze/", views.asset_administrative_deadline_list, name="asset_administrative_deadline_list"),
    path(
        "assets/scadenze/allegati/<int:attachment_id>/download/",
        views.admin_deadline_attachment_download,
        name="admin_deadline_attachment_download",
    ),
    path("assets/scadenze/new/", views.asset_administrative_deadline_create, name="asset_administrative_deadline_create"),
    path(
        "assets/scadenze/edit/<int:id>/",
        views.asset_administrative_deadline_edit,
        name="asset_administrative_deadline_edit",
    ),
    path("assets/manutenzione/", views.maintenance_hub, name="maintenance_hub"),
    path("assets/manutenzione/storico/", views.maintenance_history, name="maintenance_history"),
    path("assets/manutenzione/scadenzario/", views.maintenance_scadenzario, name="maintenance_scadenzario"),
    path("assets/manutenzione/impostazioni/", views.maintenance_impostazioni, name="maintenance_impostazioni"),
    path("assets/manutenzione/fornitori/", views.maintenance_suppliers, name="maintenance_suppliers"),
    path(
        "assets/manutenzione/scheda/<int:asset_id>/<int:rule_id>/",
        views.maintenance_worksheet,
        name="maintenance_worksheet",
    ),
    path("assets/manutenzione/templates/", views.maintenance_template_list, name="maintenance_template_list"),
    path("assets/manutenzione/templates/new/", views.maintenance_template_create, name="maintenance_template_create"),
    path(
        "assets/manutenzione/templates/edit/<int:id>/",
        views.maintenance_template_edit,
        name="maintenance_template_edit",
    ),
    path("assets/manutenzione/regole/", views.maintenance_rule_list, name="maintenance_rule_list"),
    path("assets/manutenzione/regole/new/", views.maintenance_rule_create, name="maintenance_rule_create"),
    path("assets/manutenzione/regole/edit/<int:id>/", views.maintenance_rule_edit, name="maintenance_rule_edit"),
    path("assets/manutenzione/prossime/", views.maintenance_schedule, name="maintenance_schedule"),
    path("assets/manutenzione/contratti/", views.assistance_contract_list, name="assistance_contract_list"),
    path("assets/licenze/", views.software_license_list, name="software_license_list"),
    path("assets/dispositivi/", views.device_list, name="device_list"),
    path("assets/work-machines/", views.work_machine_list, name="work_machine_list"),
    path("assets/work-machines/dashboard/", views.work_machine_dashboard, name="work_machine_dashboard"),
    path("assets/work-machines/map/", views.plant_layout_map, name="plant_layout_map"),
    path("assets/work-machines/map/editor/", views.plant_layout_editor, name="plant_layout_editor"),
    path("assets/work-machines/export/", views.work_machine_export_excel, name="work_machine_export_excel"),
    path("assets/work-machines/export-pdf/", views.work_machine_export_pdf, name="work_machine_export_pdf"),
    path("assets/lista/export/", views.asset_list_export, name="asset_list_export"),
    path("assets/workorders/export/", views.workorder_list_export, name="workorder_list_export"),
    path("assets/view/<int:id>/export.xlsx", views.asset_detail_export_xlsx, name="asset_detail_export_xlsx"),
    path("assets/work-machines/new/", views.work_machine_create, name="work_machine_create"),
    path("assets/work-machines/edit/<int:id>/", views.work_machine_edit, name="work_machine_edit"),
    path("assets/internal-number/next/", views.asset_internal_number_next, name="internal_number_next"),
    path("assets/new/chimico/", views.chemical_asset_create, name="chemical_create"),
    path("assets/edit/chimico/<int:id>/", views.chemical_asset_edit, name="chemical_edit"),
    path("assets/view/", views.asset_detail, name="asset_view"),
    path("assets/view/<int:id>/", views.asset_detail, name="asset_view"),
    path("assets/view/<int:asset_id>/componenti/", views.asset_component_list, name="asset_component_list_for_asset"),
    path(
        "assets/manutenzione/asset-rules/<int:asset_id>/",
        views.asset_maintenance_rule_list,
        name="asset_maintenance_rule_list",
    ),
    path(
        "assets/manutenzione/asset-rule-overrides/new/<int:asset_id>/<int:rule_id>/",
        views.asset_maintenance_rule_override_create,
        name="asset_maintenance_rule_override_create",
    ),
    path(
        "assets/manutenzione/asset-rule-overrides/edit/<int:asset_id>/<int:id>/",
        views.asset_maintenance_rule_override_edit,
        name="asset_maintenance_rule_override_edit",
    ),
    path(
        "assets/manutenzione/asset-rule-overrides/reset/<int:asset_id>/<int:id>/",
        views.asset_maintenance_rule_override_reset,
        name="asset_maintenance_rule_override_reset",
    ),
    path("assets/view-layout/", views.asset_detail_layout_admin, name="asset_detail_layout_admin"),
    path("assets/view/<int:id>/report.pdf", views.asset_report_pdf, name="asset_report_pdf"),
    path("assets/view/<int:id>/qr-label/", views.asset_qr_label, name="asset_qr_label"),
    path("assets/documenti/<int:document_id>/download/", views.asset_document_download, name="asset_document_download"),
    path(
        "assets/workorders/allegati/<int:attachment_id>/download/",
        views.workorder_attachment_download,
        name="workorder_attachment_download",
    ),
    path("assets/labels/", views.asset_label_designer, name="asset_label_designer"),
    path("assets/new/", views.asset_create, name="asset_create"),
    path("assets/edit/", views.asset_edit, name="asset_edit"),
    path("assets/edit/<int:id>/", views.asset_edit, name="asset_edit"),
    path("assets/assign/", views.assignment_set, name="asset_assign"),
    path("assets/assign/<int:id>/", views.assignment_set, name="asset_assign"),
    path("assets/workorders/", views.workorder_list, name="wo_list"),
    path("assets/workorders/new/", views.workorder_create, name="wo_create"),
    path("assets/workorders/new/<int:id>/", views.workorder_create, name="wo_create"),
    path("assets/workorders/view/", views.workorder_detail, name="wo_view"),
    path("assets/workorders/view/<int:id>/", views.workorder_detail, name="wo_view"),
    path("assets/workorders/close/", views.workorder_close, name="wo_close"),
    path("assets/workorders/close/<int:id>/", views.workorder_close, name="wo_close"),
    path("assets/workorders/<int:id>/claim/", views.workorder_claim, name="wo_claim"),
    path("assets/workorders/<int:id>/checklist/add/", views.workorder_checklist_add, name="wo_checklist_add"),
    path("assets/workorders/<int:id>/checklist/<int:item_id>/toggle/", views.workorder_checklist_toggle, name="wo_checklist_toggle"),
    path("assets/workorders/<int:id>/checklist/<int:item_id>/delete/", views.workorder_checklist_delete, name="wo_checklist_delete"),
    path("assets/workorders/<int:id>/checklist/<int:item_id>/set-value/", views.workorder_checklist_set_value, name="wo_checklist_set_value"),
    path("assets/workorders/<int:id>/checklist/<int:item_id>/photo/", views.workorder_checklist_photo, name="wo_checklist_photo"),
    path("assets/workorders/<int:id>/checklist/<int:item_id>/skip/", views.workorder_checklist_skip, name="wo_checklist_skip"),
    path("assets/manutenzione/verifiche/", views.periodic_verification_list, name="periodic_verifications"),
    path(
        "assets/verifiche-periodiche/",
        RedirectView.as_view(pattern_name="assets:periodic_verifications", permanent=False),
    ),
    path("assets/manutenzione/todo/", views.maintenance_todo, name="maintenance_todo"),
    path("assets/<int:asset_id>/meters/", views.asset_meter_update, name="asset_meter_update"),
    path("assets/segnala/", views.asset_quick_report, name="asset_quick_report"),
    # Sotto il prefisso esente /assets/qr/pub/: il token QR e' la chiave d'accesso.
    path(
        "assets/qr/pub/<str:public_qr_token>/documenti/<int:document_id>/",
        views.asset_document_qr_download,
        name="asset_document_qr_download",
    ),
    path("assets/qr/pub/<str:public_qr_token>/", views.asset_qr_public_landing, name="asset_qr_public_landing"),
    path("assets/qr/<str:asset_tag>/", views.asset_qr_landing, name="asset_qr_landing"),
    path("assets/reports/", views.reports_dashboard, name="reports"),
    path("assets/reports/manage/", views.report_template_admin, name="report_template_admin"),
    path(
        "assets/reports/work-machines/maintenance-month.pdf",
        views.work_machine_maintenance_month_pdf,
        name="work_machine_maintenance_month_pdf",
    ),
    path("assets/impostazioni/", views.gestione_admin, name="gestione_admin"),
    path("assets/gestione/", RedirectView.as_view(pattern_name="assets:gestione_admin", permanent=False)),
    path("assets/bulk-update/", views.asset_bulk_update, name="asset_bulk_update"),
    path("assets/dashboard/", RedirectView.as_view(pattern_name="assets:asset_dashboard", permanent=False)),
    path("api/assets/dashboard/config/", views.api_asset_dashboard_save_config, name="api_dashboard_save_config"),
    # Calendario asset
    path("assets/calendario/", views.calendario_asset, name="calendario_asset"),
    path("api/assets/calendario/json/", views.calendario_asset_json, name="calendario_asset_json"),
    path("api/assets/view/<int:id>/calendario/json/", views.asset_calendar_json, name="asset_calendar_json"),
]
