"""Catalogo competenze MOD.187 (riferimento — NESSUN dato personale).

Generato da docs/anagrafica/skillmatrix/skm_catalogo_competenze.csv.
Imballato come modulo Python (non come CSV) per essere SEMPRE disponibile
in produzione: la cartella docs/ e i .csv sono esclusi dal pacchetto di
release. Contiene solo codici macchina/nomi processo, niente personale.
Totale: 84 competenze (42 macchine, 41 processi, 1 contatore).
"""
from __future__ import annotations

CATALOGO_MOD187 = [
    {"competenza_key": 'corsi attivati', "display": 'corsi attivati', "tipo": 'contatore', "codice": '', "alias_storici": '', "note": 'numero corsi attivati, NON livello I/L/U/O'},
    {"competenza_key": '35S', "display": '35S - AKEBONO ANCL 35 XL', "tipo": 'macchina', "codice": '35S', "alias_storici": '', "note": ''},
    {"competenza_key": 'AGV1', "display": 'AGV1 - SIP 8000', "tipo": 'macchina', "codice": 'AGV1', "alias_storici": '', "note": ''},
    {"competenza_key": 'AGV2', "display": 'AGV2 - SIP 4000', "tipo": 'macchina', "codice": 'AGV2', "alias_storici": '', "note": ''},
    {"competenza_key": 'AGV3', "display": 'AGV3 - SIP 640', "tipo": 'macchina', "codice": 'AGV3', "alias_storici": '', "note": ''},
    {"competenza_key": 'CNT1', "display": 'CNT1 - CNS VT-36BLMC-2000', "tipo": 'macchina', "codice": 'CNT1', "alias_storici": '', "note": ''},
    {"competenza_key": 'CNV', "display": 'CNV - CNS CNC KMV16', "tipo": 'macchina', "codice": 'CNV', "alias_storici": '', "note": ''},
    {"competenza_key": 'D1', "display": 'D1 - DIXI DHP 80', "tipo": 'macchina', "codice": 'D1', "alias_storici": '', "note": ''},
    {"competenza_key": 'DM1', "display": 'DM1 - DMG CTX Gamma 2000 TC', "tipo": 'macchina', "codice": 'DM1', "alias_storici": '', "note": ''},
    {"competenza_key": 'DM10', "display": 'DM10 - DMC 85 Duoblock', "tipo": 'macchina', "codice": 'DM10', "alias_storici": '', "note": ''},
    {"competenza_key": 'DM11', "display": 'DM11 - DMC 85 Monoblock', "tipo": 'macchina', "codice": 'DM11', "alias_storici": 'DM11 - DMG 85 Monoblock', "note": 'intestazione variata tra snapshot: match su CODICE asset'},
    {"competenza_key": 'DM12', "display": 'DM12 - DMC 160U Duoblock', "tipo": 'macchina', "codice": 'DM12', "alias_storici": 'DM12 - DMC160U Duoblock', "note": 'intestazione variata tra snapshot: match su CODICE asset'},
    {"competenza_key": 'DM13', "display": 'DM13 - DMC 75 Monoblock', "tipo": 'macchina', "codice": 'DM13', "alias_storici": 'DM13 - DMG 75 Monoblock', "note": 'intestazione variata tra snapshot: match su CODICE asset'},
    {"competenza_key": 'DM14', "display": 'DM14 - DMC 65 FD Monoblock', "tipo": 'macchina', "codice": 'DM14', "alias_storici": 'DM14 - DMG Mori DMC 65 FD Monoblock', "note": 'intestazione variata tra snapshot: match su CODICE asset'},
    {"competenza_key": 'DM15', "display": 'DM15 - DMG CTX beta 2000CT', "tipo": 'macchina', "codice": 'DM15', "alias_storici": '', "note": ''},
    {"competenza_key": 'DM2', "display": 'DM2 - ECOTURN 650', "tipo": 'macchina', "codice": 'DM2', "alias_storici": '', "note": ''},
    {"competenza_key": 'DM3', "display": 'DM3 - DMC 85 Monoblock', "tipo": 'macchina', "codice": 'DM3', "alias_storici": 'DM3 - DMG 85 Monoblock', "note": 'intestazione variata tra snapshot: match su CODICE asset'},
    {"competenza_key": 'DM4', "display": 'DM4 - DMG Gamma 3000 CTX', "tipo": 'macchina', "codice": 'DM4', "alias_storici": '', "note": ''},
    {"competenza_key": 'DM5', "display": 'DM5 - DMG CTXbeta1250CT', "tipo": 'macchina', "codice": 'DM5', "alias_storici": '', "note": ''},
    {"competenza_key": 'DM6', "display": 'DM6 - DMC 125U Duoblock', "tipo": 'macchina', "codice": 'DM6', "alias_storici": 'DM6 - DMC125U Duoblock', "note": 'intestazione variata tra snapshot: match su CODICE asset'},
    {"competenza_key": 'DM7', "display": 'DM7 - DMC 160U Duoblock', "tipo": 'macchina', "codice": 'DM7', "alias_storici": 'DM7 - DMC160U Duoblock', "note": 'intestazione variata tra snapshot: match su CODICE asset'},
    {"competenza_key": 'DM8', "display": 'DM8 - ECOTURN 650', "tipo": 'macchina', "codice": 'DM8', "alias_storici": '', "note": ''},
    {"competenza_key": 'DM9', "display": 'DM9 - DMG CTX beta 2000CT', "tipo": 'macchina', "codice": 'DM9', "alias_storici": '', "note": ''},
    {"competenza_key": 'ELT1', "display": 'ELT1 - Agie Charmille CUT 30', "tipo": 'macchina', "codice": 'ELT1', "alias_storici": '', "note": ''},
    {"competenza_key": 'HH', "display": 'HH - HERMLE C1200U', "tipo": 'macchina', "codice": 'HH', "alias_storici": '', "note": ''},
    {"competenza_key": 'HI', "display": 'HI - HITACHI NR 1742', "tipo": 'macchina', "codice": 'HI', "alias_storici": '', "note": ''},
    {"competenza_key": 'HY1', "display": 'HY1 - Hyundai L600 MA', "tipo": 'macchina', "codice": 'HY1', "alias_storici": '', "note": ''},
    {"competenza_key": 'MK1', "display": 'MK1 - MIKRON HSM 600U', "tipo": 'macchina', "codice": 'MK1', "alias_storici": '', "note": ''},
    {"competenza_key": 'MK2', "display": 'MK2 - MIKRON UCP 800', "tipo": 'macchina', "codice": 'MK2', "alias_storici": '', "note": ''},
    {"competenza_key": 'MK3', "display": 'MK3 - MIKRON HPM 1000U', "tipo": 'macchina', "codice": 'MK3', "alias_storici": '', "note": ''},
    {"competenza_key": 'MZ2', "display": 'MZ2 - MAZAK H800', "tipo": 'macchina', "codice": 'MZ2', "alias_storici": '', "note": ''},
    {"competenza_key": 'MZ3', "display": 'MZ3 - MAZAK H630N', "tipo": 'macchina', "codice": 'MZ3', "alias_storici": '', "note": ''},
    {"competenza_key": 'MZ5', "display": 'MZ5 - MAZAK FH6800', "tipo": 'macchina', "codice": 'MZ5', "alias_storici": '', "note": ''},
    {"competenza_key": 'MZ6', "display": 'MZ6 - MAZAK FH8800', "tipo": 'macchina', "codice": 'MZ6', "alias_storici": '', "note": ''},
    {"competenza_key": 'STZ', "display": 'STZ - Stozzatrice', "tipo": 'macchina', "codice": 'STZ', "alias_storici": '', "note": ''},
    {"competenza_key": 'TNZ', "display": 'TNZ - Omba - MN8', "tipo": 'macchina', "codice": 'TNZ', "alias_storici": '', "note": ''},
    {"competenza_key": 'ZEISS - CONTURA G2', "display": 'ZEISS - CONTURA G2', "tipo": 'macchina', "codice": '', "alias_storici": '', "note": 'codice ZEISS non univoco: match su nome completo'},
    {"competenza_key": 'ZEISS - DURAMAX - Matr. 14301', "display": 'ZEISS - DURAMAX - Matr. 14301', "tipo": 'macchina', "codice": '', "alias_storici": '', "note": 'codice ZEISS non univoco: match su nome completo'},
    {"competenza_key": 'ZEISS - DURAMAX Matr. 140642', "display": 'ZEISS - DURAMAX Matr. 140642', "tipo": 'macchina', "codice": '', "alias_storici": '', "note": 'codice ZEISS non univoco: match su nome completo'},
    {"competenza_key": 'ZEISS - PRISMO', "display": 'ZEISS - PRISMO', "tipo": 'macchina', "codice": '', "alias_storici": '', "note": 'codice ZEISS non univoco: match su nome completo'},
    {"competenza_key": 'ZEISS - PRISMO 10HTG VAST', "display": 'ZEISS - PRISMO 10HTG VAST', "tipo": 'macchina', "codice": '', "alias_storici": '', "note": 'codice ZEISS non univoco: match su nome completo'},
    {"competenza_key": 'ZEISS - PRISMO NAVIGATOR', "display": 'ZEISS - PRISMO NAVIGATOR', "tipo": 'macchina', "codice": '', "alias_storici": '', "note": 'codice ZEISS non univoco: match su nome completo'},
    {"competenza_key": 'ZEISS - PRISMO USS2', "display": 'ZEISS - PRISMO USS2', "tipo": 'macchina', "codice": '', "alias_storici": '', "note": 'codice ZEISS non univoco: match su nome completo'},
    {"competenza_key": 'Affilatura', "display": 'Affilatura', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Aggiustaggio generico', "display": 'Aggiustaggio generico', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Cleanliness Check', "display": 'Cleanliness Check', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Controlli di banco', "display": 'Controlli di banco', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Controllo conducibilità', "display": 'Controllo conducibilità', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Controllo configurazione finale', "display": 'Controllo configurazione finale', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Controllo durezza', "display": 'Controllo durezza', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Controllo marcatura', "display": 'Controllo marcatura', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Controllo montaggi', "display": 'Controllo montaggi', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Controllo visivo', "display": 'Controllo visivo', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Fresatrice generica', "display": 'Fresatrice generica', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Gestione documenti ingresso e uscita', "display": 'Gestione documenti ingresso e uscita', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Imballaggio', "display": 'Imballaggio', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Lapidello generico', "display": 'Lapidello generico', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Lappatrice generica', "display": 'Lappatrice generica', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Lavaggio', "display": 'Lavaggio', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Lavaggio condotti', "display": 'Lavaggio condotti', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Liquidi penetranti', "display": 'Liquidi penetranti', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Magazzino 02', "display": 'Magazzino 02', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Manutenzione', "display": 'Manutenzione', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Marcatura', "display": 'Marcatura', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Mascheratura', "display": 'Mascheratura', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Montaggio per accoppiamento termico', "display": 'Montaggio per accoppiamento termico', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Montaggio per aeronautica', "display": 'Montaggio per aeronautica', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Montaggio per automotive', "display": 'Montaggio per automotive', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Muletto', "display": 'Muletto', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Presetting', "display": 'Presetting', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Programmazione Offline', "display": 'Programmazione Offline', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Prova pressione', "display": 'Prova pressione', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Pulizie', "display": 'Pulizie', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Rettifica generica', "display": 'Rettifica generica', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Ritocchi', "display": 'Ritocchi', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Ritocchi Galvanici', "display": 'Ritocchi Galvanici', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Sala taglio', "display": 'Sala taglio', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Smontaggio trasmissioni', "display": 'Smontaggio trasmissioni', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Taratura strumenti', "display": 'Taratura strumenti', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Tornio tradizionale generico', "display": 'Tornio tradizionale generico', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Trapano a colonna generico', "display": 'Trapano a colonna generico', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Trasporti', "display": 'Trasporti', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Verniciatura', "display": 'Verniciatura', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
    {"competenza_key": 'Zoller', "display": 'Zoller', "tipo": 'processo', "codice": '', "alias_storici": '', "note": ''},
]
