# Generated by Django 5.2.11 on 2026-03-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificazionePresenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dipendente', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('entrata_mattina', models.TimeField()),
                ('uscita_mattina', models.TimeField()),
                ('turno_pomeriggio', models.BooleanField(default=False)),
                ('entrata_pomeriggio', models.TimeField(blank=True, null=True)),
                ('uscita_pomeriggio', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('inserito_da', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificazione presenza',
                'verbose_name_plural': 'Certificazioni presenza',
                'ordering': ['-data', 'nome_dipendente'],
            },
        ),
    ]
