# Generated by Django 5.2.11 on 2026-03-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assenze', '0001_initial_certificazione_presenza'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificazionepresenza',
            name='assenza_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificazionepresenza',
            name='capo_reparto_email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='certificazionepresenza',
            name='consenso',
            field=models.CharField(choices=[('In attesa', 'In attesa'), ('Approvato', 'Approvato'), ('Rifiutato', 'Rifiutato')], default='In attesa', max_length=20),
        ),
        migrations.AddField(
            model_name='certificazionepresenza',
            name='origine',
            field=models.CharField(choices=[('utente', 'Utente'), ('admin', 'Admin')], default='admin', max_length=10),
        ),
        migrations.AddField(
            model_name='certificazionepresenza',
            name='salta_approvazione',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificazionepresenza',
            name='sharepoint_item_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
