# Generated by Django 5.2.16 on 2026-09-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assenze', '0002_add_consenso_origine_to_certificazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssenzaSharePointOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assenza_id', models.IntegerField(unique=True)),
                ('azione', models.CharField(choices=[('upsert', 'Crea/aggiorna'), ('delete', 'Elimina')], default='upsert', max_length=10)),
                ('sharepoint_item_id', models.CharField(blank=True, default='', max_length=64)),
                ('versione', models.PositiveIntegerField(default=1)),
                ('tentativi', models.PositiveIntegerField(default=0)),
                ('ultimo_errore', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assenza da inviare a SharePoint',
                'verbose_name_plural': 'Assenze da inviare a SharePoint',
            },
        ),
    ]
