# Generated by Django 5.2.16 on 2026-09-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assenze', '0003_assenza_sharepoint_outbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssenzaOrigineSharePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assenza_id', models.IntegerField(unique=True)),
                ('sharepoint_item_id', models.CharField(blank=True, default='', max_length=64)),
                ('creata_su_sharepoint', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Origine assenza (SharePoint)',
                'verbose_name_plural': 'Origini assenze (SharePoint)',
            },
        ),
    ]
