# Generated by Django 5.2.16 on 2026-09-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assenze', '0004_assenza_origine_sharepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlessibilitaAbilitato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_anagrafica_id', models.IntegerField(db_index=True, unique=True)),
                ('nominativo', models.CharField(blank=True, default='', help_text="Copia del nominativo al momento dell'abilitazione, per leggibilità dello storico.", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Abilitato alla flessibilità',
                'verbose_name_plural': 'Abilitati alla flessibilità',
                'ordering': ['nominativo', 'legacy_anagrafica_id'],
            },
        ),
        migrations.CreateModel(
            name='FlessibilitaImpostazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orari_entrata', models.CharField(default='07:00,08:00,09:00', help_text='Elenco separato da virgola, formato HH:MM. Es. 07:00,08:00,09:00', max_length=200, verbose_name='Orari di entrata ammessi')),
                ('orari_uscita', models.CharField(default='16:00,17:00,18:00', help_text='Elenco separato da virgola, formato HH:MM. Es. 16:00,17:00,18:00', max_length=200, verbose_name='Orari di uscita ammessi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Impostazioni flessibilità',
                'verbose_name_plural': 'Impostazioni flessibilità',
            },
        ),
    ]
