# Generated by Django 5.2.11 on 2026-07-09 16:24

import django.db.models.deletion
import schede_sicurezza.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0082_dipendente_area_aziendale_fk'),
        ('dpi', '0005_firma_immagine_consegna'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdottoChimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome prodotto')),
                ('fornitore', models.CharField(blank=True, default='', max_length=200)),
                ('produttore', models.CharField(blank=True, default='', max_length=200)),
                ('famiglia', models.CharField(blank=True, default='', max_length=100)),
                ('sottocategoria', models.CharField(blank=True, default='', max_length=100)),
                ('numero_interno', models.CharField(blank=True, default='', max_length=50, verbose_name='Numero interno')),
                ('codice_prodotto', models.CharField(blank=True, default='', max_length=100, verbose_name='Codice prodotto')),
                ('ubicazione', models.CharField(blank=True, default='', max_length=200)),
                ('quantita_presente', models.CharField(blank=True, default='', max_length=100, verbose_name='Quantità presente')),
                ('tag_id', models.CharField(blank=True, default='', max_length=100)),
                ('asset_id_legacy', models.CharField(blank=True, default='', max_length=100)),
                ('new_asset_id_legacy', models.CharField(blank=True, default='', max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dpi_obbligatori', models.ManyToManyField(blank=True, related_name='prodotti_chimici', to='dpi.categoriadpi', verbose_name='DPI obbligatori')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prodotti_chimici', to='anagrafica.reparto', verbose_name='Reparto')),
            ],
            options={
                'verbose_name': 'Prodotto chimico',
                'verbose_name_plural': 'Prodotti chimici',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SchedaSicurezza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(storage=schede_sicurezza.storage.PrivateSchedaSicurezzaStorage(), upload_to=schede_sicurezza.storage.upload_to_scheda_pdf, verbose_name='PDF scheda')),
                ('versione', models.CharField(blank=True, default='', max_length=50)),
                ('data_revisione_fornitore', models.DateField(blank=True, null=True)),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
                ('is_corrente', models.BooleanField(db_index=True, default=False)),
                ('pittogrammi', models.JSONField(blank=True, default=list)),
                ('frasi_h', models.JSONField(blank=True, default=list)),
                ('frasi_p', models.JSONField(blank=True, default=list)),
                ('classificazione_clp', models.TextField(blank=True, default='')),
                ('dpi_testo', models.TextField(blank=True, default='', verbose_name='DPI (sezione 8, testo grezzo)')),
                ('primo_soccorso', models.TextField(blank=True, default='', verbose_name='Primo soccorso (sezione 4)')),
                ('incompatibilita', models.TextField(blank=True, default='', verbose_name='Incompatibilità (sezione 10)')),
                ('estratto_grezzo', models.JSONField(blank=True, default=dict, help_text='Mappa sezione -> testo estratto')),
                ('estrazione_stato', models.CharField(choices=[('non_eseguita', 'Non eseguita'), ('ok', 'OK'), ('parziale', 'Parziale'), ('fallita', 'Fallita')], db_index=True, default='non_eseguita', max_length=15)),
                ('caricata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schede_sicurezza_caricate', to=settings.AUTH_USER_MODEL)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schede', to='schede_sicurezza.prodottochimico', verbose_name='Prodotto')),
            ],
            options={
                'verbose_name': 'Scheda di sicurezza',
                'verbose_name_plural': 'Schede di sicurezza',
                'ordering': ['-data_caricamento'],
            },
        ),
        migrations.CreateModel(
            name='PresaVisioneScheda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_presa_visione', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prese_visione_schede_sicurezza', to=settings.AUTH_USER_MODEL, verbose_name='Operatore')),
                ('scheda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prese_visione', to='schede_sicurezza.schedasicurezza', verbose_name='Scheda')),
            ],
            options={
                'verbose_name': 'Presa visione scheda',
                'verbose_name_plural': 'Prese visione schede',
                'ordering': ['-data_presa_visione'],
            },
        ),
        migrations.AddIndex(
            model_name='schedasicurezza',
            index=models.Index(fields=['prodotto', 'is_corrente'], name='ss_scheda_prodotto_corrente'),
        ),
        migrations.AddConstraint(
            model_name='presavisionescheda',
            constraint=models.UniqueConstraint(fields=('scheda', 'operatore'), name='ss_unique_presa_visione_scheda_operatore'),
        ),
    ]
