# Generated by Django 5.2.16 on 2026-07-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schede_sicurezza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodottochimico',
            name='pittogrammi',
            field=models.JSONField(blank=True, default=list, help_text='Codici GHS dichiarati sul prodotto (la scheda corrente, se presente, ha la precedenza).', verbose_name='Pittogrammi di pericolo'),
        ),
    ]
