# Generated by Django 5.2.16 on 2026-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schede_sicurezza', '0002_prodottochimico_pittogrammi'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodottochimico',
            name='visite_qr',
            field=models.PositiveIntegerField(default=0, verbose_name='Visite QR pubblico'),
        ),
    ]
