# Generated by Django 5.2.11 on 2026-05-04 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0003_dpiimpostazioni_responsabili'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelloDPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('produttore', models.CharField(blank=True, default='', max_length=150)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='dpi/modelli/')),
                ('vita_utile_giorni', models.PositiveIntegerField(blank=True, help_text='Override della vita utile della categoria (se vuoto usa quella della categoria)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modello DPI',
                'verbose_name_plural': 'Modelli DPI',
                'ordering': ['tipo__categoria__order_index', 'tipo__ordine', 'codice', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='richiestadpi',
            name='modello_dpi',
            field=models.ForeignKey(blank=True, help_text='Modello DPI (opzionale, per selezione più specifica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='richieste', to='dpi.modellodpi'),
        ),
        migrations.CreateModel(
            name='TagliaDPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=50)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taglie', to='dpi.modellodpi')),
            ],
            options={
                'verbose_name': 'Taglia DPI',
                'verbose_name_plural': 'Taglie DPI',
                'ordering': ['modello__tipo__categoria__order_index', 'modello__tipo__ordine', 'ordine', 'valore'],
            },
        ),
        migrations.AddField(
            model_name='richiestadpi',
            name='taglia_dpi',
            field=models.ForeignKey(blank=True, help_text='Taglia DPI (opzionale, per selezione più specifica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='richieste', to='dpi.tagliadpi'),
        ),
        migrations.CreateModel(
            name='TipoDPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipi', to='dpi.categoriadpi')),
            ],
            options={
                'verbose_name': 'Tipo DPI',
                'verbose_name_plural': 'Tipi DPI',
                'ordering': ['categoria__order_index', 'categoria__nome', 'ordine', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='modellodpi',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelli', to='dpi.tipodpi'),
        ),
        migrations.AddField(
            model_name='richiestadpi',
            name='tipo_dpi',
            field=models.ForeignKey(blank=True, help_text='Tipo DPI (opzionale, per selezione più specifica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='richieste', to='dpi.tipodpi'),
        ),
        migrations.AddConstraint(
            model_name='tagliadpi',
            constraint=models.UniqueConstraint(fields=('modello', 'valore'), name='uniq_taglia_dpi_modello_valore'),
        ),
        migrations.AddConstraint(
            model_name='tipodpi',
            constraint=models.UniqueConstraint(fields=('categoria', 'nome'), name='uniq_tipo_dpi_categoria_nome'),
        ),
    ]
