# Generated by Django 5.2.11 on 2026-05-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0004_tipo_modello_taglia_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriadpi',
            name='obbligatoria_mansionario',
            field=models.BooleanField(default=False, help_text='Categoria richiesta dal mansionario per il report conformita DPI'),
        ),
        migrations.AddField(
            model_name='consegnadpi',
            name='firma_immagine',
            field=models.TextField(blank=True, default='', help_text='Firma digitale del ricevente (PNG base64, data URI)'),
        ),
    ]
