# Generated by Django 5.2.16 on 2026-09-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0005_firma_immagine_consegna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriadpi',
            name='icona_emoji',
            field=models.CharField(blank=True, default='vest', max_length=10),
        ),
    ]
