# Generated by Django 5.2.16 on 2026-09-21 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0006_alter_categoriadpi_icona_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='consegnadpi',
            name='data_sostituzione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consegnadpi',
            name='sostituita_da',
            field=models.ForeignKey(blank=True, help_text='Consegna successiva dello stesso tipo DPI che ha rimpiazzato questa (storico, mai cancellata).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sostituisce', to='dpi.consegnadpi'),
        ),
    ]
