# Generated by Django 5.2.16 on 2026-09-30 07:03

import django.db.models.deletion
import dpi.models
import dpi.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0007_consegnadpi_data_sostituzione_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoDPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.CharField(blank=True, default='', max_length=500)),
                ('file', models.FileField(max_length=400, storage=dpi.storage.PrivateDpiDocumentStorage(), upload_to=dpi.models._documento_dpi_upload_to)),
                ('nome_originale', models.CharField(blank=True, default='', max_length=255)),
                ('dimensione_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('caricato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_dpi_caricati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento DPI',
                'verbose_name_plural': 'Documenti DPI',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
