# Generated by Django 5.2.16 on 2026-09-30 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0008_documento_dpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentodpi',
            name='modello',
            field=models.ForeignKey(blank=True, help_text='DPI a cui si riferisce il documento (obbligatorio al caricamento).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documenti', to='dpi.modellodpi'),
        ),
    ]
