# Generated by Django 5.2.16 on 2026-09-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0009_documento_dpi_modello'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpiimpostazioni',
            name='amministrazione_emails',
            field=models.TextField(blank=True, default='', help_text='Avviso di consegna e report di consegna, uno per riga'),
        ),
        migrations.AddField(
            model_name='dpiimpostazioni',
            name='magazzino_emails',
            field=models.TextField(blank=True, default='', help_text='Avviso di consegna alla approvazione della richiesta, uno per riga'),
        ),
    ]
