# Generated by Django 5.2.16 on 2026-09-30 12:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpi', '0010_flusso_destinatari'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modellodpi',
            name='scorta_minima',
            field=models.PositiveIntegerField(default=0, help_text='Sotto questa giacenza il magazzino segnala «da riordinare» (0 = nessuna soglia).'),
        ),
        migrations.CreateModel(
            name='MovimentoMagazzinoDPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CARICO', 'Carico da DDT'), ('SCARICO', 'Consegna'), ('RETTIFICA', 'Rettifica inventario')], db_index=True, max_length=10)),
                ('quantita', models.IntegerField(help_text='Con segno: + carico, - scarico.')),
                ('data', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('ddt_numero', models.CharField(blank=True, default='', max_length=60)),
                ('fornitore', models.CharField(blank=True, default='', max_length=150)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modello', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimenti', to='dpi.modellodpi')),
                ('richiesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimenti_magazzino', to='dpi.richiestadpi')),
            ],
            options={
                'verbose_name': 'Movimento magazzino DPI',
                'verbose_name_plural': 'Movimenti magazzino DPI',
                'ordering': ['-data', '-id'],
                'indexes': [models.Index(fields=['modello', '-data'], name='dpi_movimen_modello_e46213_idx')],
            },
        ),
    ]
