from __future__ import annotations

from copy import deepcopy

from assenze.constants import TIPI_ASSENZA_UI


AUTOMAZIONI_MODULE_CODE = "automazioni"
AUTOMAZIONI_ACL_ACTIONS = (
    "automazioni_view",
    "automazioni_manage",
    "automazioni_logs",
    "automazioni_execute",
)


def _field(
    *,
    name: str,
    label: str,
    data_type: str,
    description: str,
    db_column: str | None = None,
    is_virtual: bool = False,
    aliases: list[str] | tuple[str, ...] | None = None,
    filterable: bool = True,
    usable_in_trigger: bool = True,
    usable_in_condition: bool = True,
    usable_in_template: bool = True,
    usable_in_action_mapping: bool = True,
    visible_in_admin: bool = True,
    allowed_values: list[str] | tuple[str, ...] | None = None,
    value_source_label: str = "",
    ui_control: str = "",
) -> dict[str, object]:
    return {
        "name": name,
        "label": label,
        "data_type": data_type,
        "filterable": filterable,
        "usable_in_trigger": usable_in_trigger,
        "usable_in_condition": usable_in_condition,
        "usable_in_template": usable_in_template,
        "usable_in_action_mapping": usable_in_action_mapping,
        "visible_in_admin": visible_in_admin,
        "description": description,
        "db_column": None if is_virtual else (db_column or name),
        "is_virtual": is_virtual,
        "aliases": list(aliases or []),
        "allowed_values": [str(value) for value in (allowed_values or []) if str(value).strip()],
        "value_source_label": str(value_source_label or "").strip(),
        "ui_control": str(ui_control or "").strip(),
    }


_SOURCE_REGISTRY: dict[str, dict[str, object]] = {
    "assenze": {
        "code": "assenze",
        "label": "Assenze",
        "source_app": "assenze",
        "table_name": "assenze",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": (
            "Richieste assenza legacy su SQL Server. "
            "Il concetto logico di utente e' mappato sul campo reale `dipendente_id`."
        ),
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria record assenza."),
            _field(
                name="dipendente_id",
                label="Dipendente / Utente",
                data_type="int",
                description="FK interna al dipendente; usata come equivalente conservativo di `utente_id`.",
                aliases=["utente_id", "employee_id"],
            ),
            _field(
                name="dipendente_nome",
                label="Dipendente",
                data_type="string",
                description="Nome visualizzato del dipendente associato alla richiesta assenza.",
                is_virtual=True,
                aliases=["dipendente", "employee_name", "copia_nome", "richiedente_nome"],
            ),
            _field(
                name="data_inizio",
                label="Data inizio",
                data_type="datetime",
                description="Data e ora di inizio della richiesta assenza.",
                aliases=["Data_x0020_inizio", "DATAINIZIO", "data", "inizio"],
            ),
            _field(
                name="data_fine",
                label="Data fine",
                data_type="datetime",
                description="Data e ora di fine della richiesta assenza.",
                aliases=["Datafine", "fine"],
            ),
            _field(
                name="tipo_assenza",
                label="Tipo assenza",
                data_type="string",
                description="Categoria assenza: ferie, permesso, malattia, ecc.",
                aliases=["Tipoassenza", "tipo", "category"],
                allowed_values=TIPI_ASSENZA_UI,
                value_source_label="Form richieste assenze - dropdown 'Tipo assenza'",
                ui_control="select",
            ),
            _field(
                name="motivazione_richiesta",
                label="Motivazione",
                data_type="string",
                description="Motivazione libera inserita dall'utente.",
                aliases=["Motivazionerichiesta", "motivazione"],
            ),
            _field(
                name="moderation_status",
                label="Stato approvazione",
                data_type="int",
                description="Stato tecnico workflow di approvazione della richiesta.",
                aliases=["ModerationStatus", "{ModerationStatus}", "status_approvazione"],
            ),
            _field(
                name="approvazione_datetime",
                label="Data/ora approvazione",
                data_type="datetime",
                description="Data e ora in cui la richiesta ferie/permessi e' stata approvata.",
                aliases=["data_approvazione", "approval_datetime", "approved_at"],
            ),
            _field(
                name="capo_reparto_id",
                label="Capo reparto",
                data_type="int",
                description="Responsabile approvatore associato alla richiesta.",
                aliases=["capo", "approvatore_id", "capo_id"],
            ),
            _field(
                name="capo_email",
                label="Caporeparto email",
                data_type="string",
                description="Email ereditata dal caporeparto selezionato nella richiesta.",
                is_virtual=True,
                aliases=["CAR", "capo_reparto_email", "responsabile_email"],
            ),
            _field(
                name="dipendente_email",
                label="Dipendente email",
                data_type="string",
                db_column="email_esterna",
                description="Email del dipendente collegata alla richiesta assenza.",
                aliases=["Email", "email", "email_esterna", "richiedente_email"],
            ),
            _field(
                name="salta_approvazione",
                label="Salta approvazione",
                data_type="bool",
                db_column="salta_approvazione",
                description="Flag che indica se la richiesta e' stata creata bypassando il flusso approvativo.",
                aliases=["Salta_x0020_approvazione", "SALTAAPPROVAZIONE", "skip_approval"],
            ),
        ],
    },
    "tasks": {
        "code": "tasks",
        "label": "Tasks (KICK-OFF)",
        "source_app": "tasks",
        "table_name": "tasks_task",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": "Task/VRF ORM Django del portale. I nomi reali colonna sono in inglese.",
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria del task.", aliases=["task_id"]),
            _field(name="title", label="Titolo", data_type="string", description="Titolo sintetico del task.", aliases=["titolo", "task_title", "subject"]),
            _field(name="status", label="Stato", data_type="string", description="Stato operativo del task (es. TODO, IN_PROGRESS, DONE).", aliases=["stato", "task_status"]),
            _field(
                name="old_status",
                label="Stato precedente",
                data_type="string",
                description="Valore precedente di `status` disponibile nel payload update del trigger tasks.",
                is_virtual=True,
                aliases=["previous_status"],
            ),
            _field(name="priority", label="Priorita'", data_type="string", description="Priorita' del task (es. LOW, MEDIUM, HIGH, CRITICAL).", aliases=["priorita", "task_priority"]),
            _field(name="description", label="Descrizione", data_type="string", description="Testo descrittivo del task.", aliases=["descrizione", "body"]),
            _field(name="assigned_to_id", label="Assegnato a (ID)", data_type="int", description="Utente Django assegnatario del task.", aliases=["assigned_to", "assegnato_a", "owner_id"]),
            _field(
                name="old_assigned_to_id",
                label="Assegnato a precedente (ID)",
                data_type="int",
                description="Valore precedente di `assigned_to_id` disponibile nel payload update del trigger tasks.",
                is_virtual=True,
                aliases=["previous_assigned_to_id"],
            ),
            _field(name="project_id", label="Progetto (ID)", data_type="int", description="Progetto/Kickoff collegato al task.", aliases=["project", "progetto", "kickoff_id"]),
            _field(name="due_date", label="Scadenza", data_type="date", description="Data scadenza del task.", aliases=["deadline", "data_scadenza"]),
            _field(
                name="old_due_date",
                label="Scadenza precedente",
                data_type="date",
                description="Valore precedente di `due_date` disponibile nel payload update del trigger tasks.",
                is_virtual=True,
                aliases=["previous_due_date"],
            ),
            _field(name="next_step_due", label="Prossimo step scadenza", data_type="date", description="Data scadenza del prossimo step pianificato.", aliases=["next_due"]),
            _field(name="next_step_text", label="Prossimo step", data_type="string", description="Descrizione del prossimo step pianificato.", aliases=["next_step"]),
            _field(name="tags", label="Tag", data_type="string", description="Tag/etichette associate al task.", aliases=["labels", "etichette"]),
            _field(name="created_by_id", label="Creato da (ID)", data_type="int", description="Utente Django che ha creato il task.", aliases=["created_by", "autore_id"]),
            _field(name="created_at", label="Creato il", data_type="datetime", description="Data e ora di creazione del task.", aliases=["creation_date", "data_creazione"]),
            _field(name="updated_at", label="Aggiornato il", data_type="datetime", description="Data e ora dell'ultimo aggiornamento del task.", aliases=["modified_at", "data_modifica"]),
        ],
    },
    "assets": {
        "code": "assets",
        "label": "Assets",
        "source_app": "assets",
        "table_name": "assets_asset",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": "Asset ORM Django (macchinari, attrezzature, IT, ecc.).",
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria asset.", aliases=["asset_id"]),
            _field(name="asset_tag", label="Codice asset", data_type="string", description="Codice univoco asset.", aliases=["codice", "code", "tag", "asset_code"]),
            _field(name="name", label="Nome", data_type="string", description="Nome dell'asset.", aliases=["nome_asset", "asset_name"]),
            _field(name="asset_type", label="Tipo asset", data_type="string", description="Tipo classificazione asset.", aliases=["tipo", "type"]),
            _field(name="asset_category_id", label="Categoria (ID)", data_type="int", description="Categoria asset configurata nel portale.", aliases=["category", "categoria"]),
            _field(name="status", label="Stato", data_type="string", description="Stato ciclo di vita asset (es. active, inactive, dismissed).", aliases=["stato", "asset_status"]),
            _field(name="manufacturer", label="Produttore", data_type="string", description="Produttore/marca dell'asset.", aliases=["marca", "brand"]),
            _field(name="model", label="Modello", data_type="string", description="Modello dell'asset.", aliases=["modello"]),
            _field(name="serial_number", label="Numero seriale", data_type="string", description="Numero di serie dell'asset.", aliases=["seriale", "sn", "serial"]),
            _field(name="assignment_location", label="Sede / Posizione", data_type="string", description="Posizione operativa dell'asset.", aliases=["sede", "ubicazione", "posizione", "location"]),
            _field(name="assignment_reparto", label="Reparto assegnazione", data_type="string", description="Reparto a cui e' assegnato l'asset.", aliases=["reparto_assegnazione", "department"]),
            _field(name="assignment_to", label="Assegnato a (nome)", data_type="string", description="Nome dell'assegnatario dell'asset.", aliases=["assegnatario_nome"]),
            _field(name="assigned_legacy_user_id", label="Assegnato a (ID legacy)", data_type="int", description="Legacy user ID assegnatario dell'asset.", aliases=["assegnatario_id", "utente_id", "assigned_to"]),
            _field(name="reparto", label="Reparto", data_type="string", description="Reparto di appartenenza dell'asset.", aliases=["department"]),
            _field(name="notes", label="Note", data_type="string", description="Note libere sull'asset.", aliases=["note", "commenti"]),
            _field(name="created_at", label="Creato il", data_type="datetime", description="Data e ora di creazione del record asset.", aliases=["data_creazione"]),
            _field(name="updated_at", label="Aggiornato il", data_type="datetime", description="Data e ora dell'ultimo aggiornamento.", aliases=["data_modifica"]),
        ],
    },
    "tickets": {
        "code": "tickets",
        "label": "Tickets",
        "source_app": "tickets",
        "table_name": "tickets_ticket",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": "Ticket ORM Django per IT e manutenzione.",
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria ticket.", aliases=["ticket_id"]),
            _field(name="numero_ticket", label="Numero ticket", data_type="string", description="Codice univoco del ticket (es. TKT-2026-0001).", aliases=["codice", "ticket_number"]),
            _field(name="tipo", label="Tipo", data_type="string", description="Tipo ticket (es. GUASTO, MANUTENZIONE, IT).", aliases=["ticket_type", "type"]),
            _field(name="titolo", label="Titolo", data_type="string", description="Titolo del ticket.", aliases=["title", "subject"]),
            _field(name="descrizione", label="Descrizione", data_type="string", description="Descrizione dettagliata del problema.", aliases=["description", "body"]),
            _field(name="categoria", label="Categoria", data_type="string", description="Categoria ticket.", aliases=["category"]),
            _field(name="priorita", label="Priorita'", data_type="string", description="Priorita' del ticket (BASSA, MEDIA, ALTA, CRITICA).", aliases=["priority", "ticket_priority"]),
            _field(name="stato", label="Stato", data_type="string", description="Stato workflow del ticket (APERTA, IN_CARICO, IN_ATTESA, CHIUSA, ANNULLATA).", aliases=["status", "ticket_status"]),
            _field(
                name="old_stato",
                label="Stato precedente",
                data_type="string",
                description="Valore precedente di `stato` disponibile nel payload update del trigger tickets.",
                is_virtual=True,
                aliases=["previous_status"],
            ),
            _field(name="incide_sicurezza", label="Incide sicurezza", data_type="bool", description="Flag: il guasto/problema ha impatti sulla sicurezza.", aliases=["safety_impact"]),
            _field(name="asset_id", label="Asset (ID)", data_type="int", description="Asset Django collegato al ticket.", aliases=["asset", "equipment_id"]),
            _field(name="asset_descrizione_libera", label="Asset descrizione libera", data_type="string", description="Descrizione libera dell'asset quando non collegato al registro.", aliases=["asset_descrizione", "equipment_name"]),
            _field(name="richiedente_nome", label="Richiedente nome", data_type="string", description="Nome completo di chi ha aperto il ticket.", aliases=["requester_name", "nome_richiedente"]),
            _field(name="richiedente_email", label="Richiedente email", data_type="string", description="Email del richiedente per notifiche.", aliases=["requester_email"]),
            _field(name="richiedente_legacy_user_id", label="Richiedente (ID legacy)", data_type="int", description="Legacy user ID di chi ha aperto il ticket.", aliases=["richiedente_id", "requester_id", "utente_id"]),
            _field(name="assegnato_a", label="Assegnato a", data_type="string", description="Nome libero dell'assegnatario corrente.", aliases=["assigned_to", "assegnatario", "owner"]),
            _field(
                name="old_assegnato_a",
                label="Assegnato a precedente",
                data_type="string",
                description="Valore precedente di `assegnato_a` disponibile nel payload update del trigger tickets.",
                is_virtual=True,
                aliases=["previous_assignee"],
            ),
            _field(name="assegnato_email", label="Assegnato email", data_type="string", description="Email dell'assegnatario per notifiche.", aliases=["assignee_email"]),
            _field(name="delegato_fornitore_id", label="Fornitore delegato (ID)", data_type="int", description="Fornitore anagrafica Django delegato alla risoluzione.", aliases=["fornitore_id", "supplier_id"]),
            _field(name="note_interne", label="Note interne", data_type="string", description="Note riservate ai tecnici, non visibili al richiedente.", aliases=["internal_notes", "note_tecniche"]),
            _field(name="componente", label="Componente", data_type="string", description="Componente/sotto-sistema interessato (es. Mandrino, Inverter, PLC).", aliases=["component", "subsystem"]),
            _field(name="causa_radice", label="Causa radice", data_type="string", description="Causa radice identificata a chiusura del ticket.", aliases=["root_cause"]),
            _field(name="tipo_fermo", label="Tipo fermo", data_type="string", description="Tipo di fermo produzione causato dal guasto (NESSUNO, PARZIALE, TOTALE).", aliases=["downtime_type"]),
            _field(name="ore_fermo_macchina", label="Ore fermo macchina", data_type="float", description="Ore totali di fermo macchina causate dal guasto.", aliases=["downtime_hours", "ore_fermo"]),
            _field(name="data_presa_in_carico", label="Data presa in carico", data_type="datetime", description="Timestamp del primo passaggio in stato IN_CARICO.", aliases=["taken_at", "presa_in_carico_at"]),
            _field(name="data_primo_intervento", label="Data primo intervento", data_type="datetime", description="Timestamp del primo intervento tecnico registrato.", aliases=["first_intervention_at"]),
            _field(name="risolto_da_nome", label="Risolto da", data_type="string", description="Nome del tecnico/manutentore che ha risolto il ticket.", aliases=["resolved_by", "resolved_by_name"]),
            _field(name="ricorrente", label="Ricorrente", data_type="bool", description="Il problema si e' gia' verificato in passato.", aliases=["is_recurring", "recurring"]),
            _field(name="data_prevista_risoluzione", label="Data prevista risoluzione", data_type="date", description="Data prevista risoluzione (valorizzata in stato IN_ATTESA).", aliases=["expected_resolution_date", "eta"]),
            _field(name="ticket_origine_id", label="Ticket origine (ID)", data_type="int", description="Ticket precedente da cui deriva se ricorrente.", aliases=["parent_ticket_id", "ticket_origine"]),
            _field(name="created_at", label="Creato il", data_type="datetime", description="Data e ora di creazione del ticket.", aliases=["creation_date", "data_creazione"]),
            _field(name="updated_at", label="Aggiornato il", data_type="datetime", description="Data e ora dell'ultimo aggiornamento.", aliases=["modified_at", "data_modifica"]),
            _field(name="closed_at", label="Chiuso il", data_type="datetime", description="Data e ora di chiusura del ticket.", aliases=["closure_date", "data_chiusura"]),
        ],
    },
    "anomalie": {
        "code": "anomalie",
        "label": "Anomalie",
        "source_app": "anomalie",
        "table_name": "anomalie",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": (
            "Anomalie legacy su SQL Server. Il catalogo espone solo colonne reali correnti: "
            "`OP` e `PN` sono mappati rispettivamente a `ex_op_nominativo` e `seriale`."
        ),
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria anomalia.", aliases=["anomalia_id"]),
            _field(
                name="ex_op_nominativo",
                label="OP",
                data_type="string",
                description="Ordine di produzione in formato testuale.",
                aliases=["op", "ordine_produzione", "op_id", "exopnominativo"],
            ),
            _field(
                name="op_lookup_id",
                label="OP lookup",
                data_type="int",
                description="Lookup tecnico verso ordini di produzione.",
                aliases=["op_lookup", "op_lookupid", "OP_x002d_IDLookupId"],
            ),
            _field(
                name="seriale",
                label="PN / Seriale",
                data_type="string",
                description="Riferimento tecnico disponibile a schema, usato come mapping conservativo del PN.",
                aliases=["pn", "sn", "part_number"],
            ),
            _field(
                name="avanzamento",
                label="Stato",
                data_type="string",
                description="Stato avanzamento dell'anomalia.",
                aliases=["status", "stato"],
            ),
            _field(
                name="chiudere",
                label="Da chiudere",
                data_type="bool",
                description="Flag booleano di chiusura anomalia.",
                aliases=["chiusa", "close", "da_chiudere"],
            ),
            _field(
                name="created_by",
                label="Responsabile / Autore",
                data_type="int",
                db_column="created_by_user_id",
                description="Utente autore disponibile nello schema corrente.",
                aliases=["created_by_user_id", "autore", "responsabile", "legacy_user_id"],
            ),
            _field(
                name="ordine_id",
                label="Ordine interno",
                data_type="int",
                description="Collegamento interno aggiuntivo presente nel database attivo.",
                aliases=["ordine_interno", "order_id"],
            ),
        ],
    },
    "notizie": {
        "code": "notizie",
        "label": "Notizie",
        "source_app": "notizie",
        "table_name": "notizie_notizia",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": "Notizie/comunicazioni della bacheca interna. Il cambio di `stato` (bozza → pubblicata) è l'evento principale.",
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria notizia.", aliases=["notizia_id"]),
            _field(
                name="titolo",
                label="Titolo",
                data_type="string",
                description="Titolo della notizia.",
                aliases=["title", "subject"],
            ),
            _field(
                name="stato",
                label="Stato",
                data_type="string",
                description="Stato pubblicazione: bozza, pubblicata, archiviata.",
                aliases=["status", "publication_status"],
            ),
            _field(
                name="obbligatoria",
                label="Obbligatoria",
                data_type="bool",
                description="Flag che indica se la notizia richiede conferma di lettura obbligatoria.",
                aliases=["mandatory", "requires_ack"],
            ),
            _field(
                name="versione",
                label="Versione",
                data_type="int",
                description="Numero di versione della notizia (incrementa a ogni modifica pubblicata).",
                aliases=["version"],
            ),
            _field(
                name="creato_da_id",
                label="Creato da",
                data_type="int",
                description="Utente Django che ha creato la notizia.",
                aliases=["created_by", "autore_id", "user_id"],
            ),
            _field(
                name="corpo",
                label="Corpo",
                data_type="string",
                description="Testo completo della notizia.",
                aliases=["body", "content", "testo"],
            ),
            _field(
                name="pubblicato_il",
                label="Pubblicato il",
                data_type="datetime",
                description="Data e ora di prima pubblicazione della notizia.",
                aliases=["published_at"],
            ),
            _field(name="created_at", label="Creato il", data_type="datetime", description="Data e ora di creazione del record.", aliases=["data_creazione"]),
            _field(name="updated_at", label="Aggiornato il", data_type="datetime", description="Data e ora dell'ultimo aggiornamento.", aliases=["data_modifica"]),
        ],
    },
    "diario_preposto": {
        "code": "diario_preposto",
        "label": "Diario Preposto",
        "source_app": "diario_preposto",
        "table_name": "diario_preposto_segnalazionepreposto",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": "Segnalazioni sicurezza del preposto. Ogni segnalazione ha un codice univoco e dati di chi ha segnalato.",
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria segnalazione.", aliases=["segnalazione_id"]),
            _field(
                name="codice_identificativo",
                label="Codice",
                data_type="string",
                description="Codice univoco della segnalazione (es. PREP-2026-001).",
                aliases=["codice", "code"],
            ),
            _field(
                name="titolo",
                label="Titolo",
                data_type="string",
                description="Titolo sintetico della segnalazione.",
                aliases=["title", "subject"],
            ),
            _field(
                name="preposto",
                label="Preposto",
                data_type="string",
                description="Nome del preposto responsabile della segnalazione.",
                aliases=["responsabile", "supervisor"],
            ),
            _field(
                name="chi_segnala",
                label="Chi segnala",
                data_type="string",
                description="Nome di chi ha fatto la segnalazione.",
                aliases=["segnalante", "reporter"],
            ),
            _field(
                name="data_segnalazione",
                label="Data segnalazione",
                data_type="datetime",
                description="Data e ora della segnalazione.",
                aliases=["data", "report_date"],
            ),
            _field(
                name="descrizione",
                label="Descrizione",
                data_type="string",
                description="Testo descrittivo della segnalazione.",
                aliases=["body", "content", "testo"],
            ),
            _field(
                name="creato_da_id",
                label="Creato da",
                data_type="int",
                description="Utente Django che ha inserito la segnalazione.",
                aliases=["created_by", "user_id"],
            ),
            _field(name="created_at", label="Creato il", data_type="datetime", description="Data e ora di creazione del record.", aliases=["data_creazione"]),
            _field(name="updated_at", label="Aggiornato il", data_type="datetime", description="Data e ora dell'ultimo aggiornamento.", aliases=["data_modifica"]),
        ],
    },
    "rilevazione_incidenti": {
        "code": "rilevazione_incidenti",
        "label": "Incidenti / Sicurezza",
        "source_app": "rilevazione_incidenti",
        "table_name": "rilevazione_incidenti_rilevazioneincidente",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": (
            "Rilevazioni incidenti e unsafe condition. I campi chiave per trigger sono "
            "`chiusura_rspp` (chiusura) e `approvazione_rls` (approvazione RLS)."
        ),
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria rilevazione.", aliases=["incidente_id"]),
            _field(
                name="nominativo",
                label="Nominativo",
                data_type="string",
                description="Nome del dipendente coinvolto.",
                aliases=["nome", "dipendente", "employee"],
            ),
            _field(
                name="tipologia_scheda",
                label="Tipologia",
                data_type="string",
                description="Tipo: Unsafe Condition, Unsafe Act, Near Miss, Accident.",
                aliases=["tipo", "type", "scheda_tipo"],
            ),
            _field(
                name="reparto",
                label="Reparto",
                data_type="string",
                description="Reparto in cui si è verificato l'evento.",
                aliases=["department", "area"],
            ),
            _field(
                name="data_segnalazione",
                label="Data segnalazione",
                data_type="datetime",
                description="Data e ora della segnalazione.",
                aliases=["data", "report_date"],
            ),
            _field(
                name="approvazione_rls",
                label="Approvazione RLS",
                data_type="string",
                description="Stato approvazione del Rappresentante dei Lavoratori per la Sicurezza.",
                aliases=["rls_status", "approvazione"],
            ),
            _field(
                name="chiusura_rspp",
                label="Chiuso RSPP",
                data_type="bool",
                description="Flag di chiusura da parte del RSPP.",
                aliases=["closed", "rspp_closed", "chiuso"],
            ),
            _field(
                name="data_chiusura_rspp",
                label="Data chiusura RSPP",
                data_type="date",
                description="Data in cui il RSPP ha chiuso la rilevazione.",
                aliases=["closed_at", "data_chiusura"],
            ),
            _field(name="descrizione_attivita", label="Descrizione attivita'", data_type="string", description="Attivita' svolta dal dipendente al momento dell'evento.", aliases=["activity_description"]),
            _field(name="descrizione_avvenimento", label="Descrizione avvenimento", data_type="string", description="Descrizione dell'accaduto in dettaglio.", aliases=["event_description"]),
            _field(name="usa_macchina", label="Usa macchina", data_type="bool", description="Flag: il dipendente stava usando una macchina al momento dell'evento.", aliases=["machine_use"]),
            _field(name="nome_macchina", label="Nome macchina", data_type="string", description="Nome/identificativo della macchina coinvolta.", aliases=["machine_name", "equipment"]),
            _field(name="buono_stato_macchina", label="Macchina in buono stato", data_type="bool", description="Flag: la macchina era in buono stato di manutenzione.", aliases=["machine_ok"]),
            _field(name="utilizzo_dpi", label="Utilizzo DPI", data_type="bool", description="Flag: il dipendente indossava i DPI previsti.", aliases=["dpi_worn", "ppe_used"]),
            _field(name="prima_volta", label="Prima volta", data_type="bool", description="Flag: e' la prima volta che si verifica questo tipo di evento.", aliases=["first_occurrence"]),
            _field(
                name="persone_coinvolte",
                label="Persone coinvolte",
                data_type="string",
                description="Numero o elenco delle persone coinvolte.",
                aliases=["persone", "involved"],
            ),
            _field(name="causa_evento", label="Causa evento", data_type="string", description="Causa principale dell'evento.", aliases=["event_cause", "cause"]),
            _field(name="altre_cause", label="Altre cause", data_type="string", description="Cause secondarie o concorrenti dell'evento.", aliases=["other_causes"]),
            _field(name="misure_tecniche", label="Misure tecniche", data_type="bool", description="Flag: sono necessarie misure tecniche correttive.", aliases=["technical_measures_needed"]),
            _field(name="quali_misure", label="Quali misure", data_type="string", description="Descrizione delle misure correttive da adottare.", aliases=["corrective_measures"]),
            _field(name="note_preposto", label="Note preposto", data_type="string", description="Note inserite dal preposto responsabile.", aliases=["supervisor_notes"]),
            _field(name="note_rspp", label="Note RSPP", data_type="string", description="Note inserite dal RSPP.", aliases=["rspp_notes", "safety_officer_notes"]),
            _field(name="data_approvazione_rls", label="Data approvazione RLS", data_type="date", description="Data in cui il RLS ha approvato la rilevazione.", aliases=["rls_approval_date"]),
            _field(name="why_1", label="Why 1", data_type="string", description="Prima iterazione analisi 5-Whys.", aliases=["why1"]),
            _field(name="why_2", label="Why 2", data_type="string", description="Seconda iterazione analisi 5-Whys.", aliases=["why2"]),
            _field(name="why_3", label="Why 3", data_type="string", description="Terza iterazione analisi 5-Whys.", aliases=["why3"]),
            _field(name="why_4", label="Why 4", data_type="string", description="Quarta iterazione analisi 5-Whys.", aliases=["why4"]),
            _field(name="why_5", label="Why 5", data_type="string", description="Quinta iterazione analisi 5-Whys.", aliases=["why5"]),
            _field(name="partecipanti", label="Partecipanti", data_type="string", description="Elenco partecipanti alla gestione/analisi dell'evento.", aliases=["participants"]),
            _field(name="contatore", label="Contatore", data_type="int", description="Numero progressivo interno (sincronizzazione SharePoint).", aliases=["counter", "sequence"]),
        ],
    },
    "rentri": {
        "code": "rentri",
        "label": "RENTRI / Rifiuti",
        "source_app": "rentri",
        "table_name": "rentri_registrorifiuti",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": "Registro rifiuti normativa RENTRI. Tipi: C (carico), O (scarico), M (rettifica), R (rettifica scarico).",
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria registro.", aliases=["registro_id"]),
            _field(
                name="id_registrazione",
                label="ID Registrazione",
                data_type="string",
                description="Identificativo univoco della registrazione (formato {anno}/{progressivo}).",
                aliases=["codice_registrazione", "reg_id"],
            ),
            _field(
                name="tipo",
                label="Tipo",
                data_type="string",
                description="Tipo movimento: C=carico, O=scarico, M=rettifica, R=rettifica scarico.",
                aliases=["tipo_movimento", "movement_type"],
            ),
            _field(
                name="data",
                label="Data",
                data_type="date",
                description="Data del movimento rifiuti.",
                aliases=["data_movimento", "date"],
            ),
            _field(
                name="codice",
                label="Codice rifiuto",
                data_type="string",
                description="Codice CER/EWC del rifiuto.",
                aliases=["cer", "codice_cer", "waste_code"],
            ),
            _field(
                name="quantita",
                label="Quantita'",
                data_type="float",
                description="Quantità in unità di misura configurata.",
                aliases=["qty", "quantity"],
            ),
            _field(
                name="rentri_si_no",
                label="Flagged RENTRI",
                data_type="bool",
                description="Flag che indica se il movimento deve essere trasmesso a RENTRI.",
                aliases=["rentri_flag", "da_trasmettere"],
            ),
            _field(name="carico_scarico", label="Carico/Scarico", data_type="string", description="Indicazione se e' un movimento di carico o scarico.", aliases=["movement_direction"]),
            _field(name="pericolosita", label="Pericolosita'", data_type="string", description="Classificazione pericolosita' del rifiuto.", aliases=["hazard_class", "hazardous"]),
            _field(name="rettifica_scarico", label="Rettifica scarico", data_type="float", description="Quantita' di rettifica per scarico (tipo M/R).", aliases=["correction_qty"]),
            _field(name="arrivo_fir", label="Arrivo FIR", data_type="string", description="Riferimento al Formulario Identificazione Rifiuti di arrivo.", aliases=["fir_reference"]),
            _field(name="rif_op", label="Riferimento operativo", data_type="string", description="Riferimento operativo interno (OdP, ordine, ecc.).", aliases=["op_ref", "order_reference"]),
            _field(name="note_rentri", label="Note RENTRI", data_type="string", description="Note operative per la trasmissione RENTRI.", aliases=["rentri_notes", "note"]),
            _field(name="salva", label="Salvato definitivo", data_type="bool", description="Flag: il record e' stato consolidato definitivamente.", aliases=["confirmed", "definitive"]),
            _field(
                name="inserito_da",
                label="Inserito da",
                data_type="string",
                description="Nome dell'operatore che ha inserito il movimento.",
                aliases=["operatore", "operator"],
            ),
            _field(name="aggiornato", label="Aggiornato il (legacy)", data_type="datetime", description="Timestamp legacy di aggiornamento del record.", aliases=["last_updated"]),
            _field(name="created_at", label="Creato il", data_type="datetime", description="Data e ora di creazione del record.", aliases=["data_creazione"]),
            _field(name="updated_at", label="Aggiornato il", data_type="datetime", description="Data e ora dell'ultimo aggiornamento.", aliases=["data_modifica"]),
        ],
    },
    "dpi": {
        "code": "dpi",
        "label": "DPI",
        "source_app": "dpi",
        "table_name": "dpi_richiestadpi",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": "Richieste DPI (Dispositivi Protezione Individuale). Il workflow principale è INVIATA → APPROVATA → CONSEGNATA.",
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria richiesta.", aliases=["richiesta_id"]),
            _field(
                name="numero",
                label="Numero richiesta",
                data_type="string",
                description="Numero univoco della richiesta (formato DPI-YYYY-NNNN).",
                aliases=["codice", "request_number"],
            ),
            _field(
                name="stato",
                label="Stato",
                data_type="string",
                description="Stato workflow: INVIATA, APPROVATA, CONSEGNATA, RIFIUTATA, ANNULLATA.",
                aliases=["status", "workflow_status"],
            ),
            _field(
                name="richiedente_legacy_id",
                label="Richiedente",
                data_type="int",
                description="Legacy user ID del richiedente.",
                aliases=["richiedente_id", "user_id", "legacy_user_id"],
            ),
            _field(
                name="richiedente_nome",
                label="Richiedente nome",
                data_type="string",
                description="Nome completo del richiedente.",
                aliases=["nome_richiedente", "requester_name"],
            ),
            _field(
                name="richiedente_email",
                label="Richiedente email",
                data_type="string",
                description="Email del richiedente per notifiche dirette.",
                aliases=["email", "requester_email"],
            ),
            _field(
                name="richiedente_reparto",
                label="Reparto",
                data_type="string",
                description="Reparto di appartenenza del richiedente.",
                aliases=["reparto", "department"],
            ),
            _field(
                name="quantita",
                label="Quantita'",
                data_type="int",
                description="Numero di unità DPI richieste.",
                aliases=["qty", "quantity"],
            ),
            _field(name="motivazione", label="Motivazione", data_type="string", description="Motivazione inserita dal richiedente per la richiesta DPI.", aliases=["reason", "justification"]),
            _field(name="categoria_id", label="Categoria DPI (ID)", data_type="int", description="Categoria DPI richiesta.", aliases=["categoria", "category_id"]),
            _field(
                name="note_gestione",
                label="Note gestione",
                data_type="string",
                description="Note inserite dal gestore durante approvazione/rifiuto.",
                aliases=["note", "manager_notes"],
            ),
            _field(name="created_by_id", label="Creato da (ID)", data_type="int", description="Utente Django che ha creato la richiesta.", aliases=["created_by", "autore_id"]),
            _field(name="created_at", label="Creato il", data_type="datetime", description="Data e ora di creazione della richiesta.", aliases=["data_creazione"]),
            _field(name="updated_at", label="Aggiornato il", data_type="datetime", description="Data e ora dell'ultimo aggiornamento.", aliases=["data_modifica"]),
        ],
    },
    "procedure_campagne": {
        "code": "procedure_campagne",
        "label": "Procedure - Campagne",
        "source_app": "procedure_refresh",
        "table_name": "procedure_refresh_procedurecampaign",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": "Campagne di presa visione procedure (MT/MTSI). Stati: draft → published → closed → archived.",
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria campagna.", aliases=["campaign_id"]),
            _field(
                name="name",
                label="Nome campagna",
                data_type="string",
                description="Nome della campagna di presa visione.",
                aliases=["nome", "titolo", "campaign_name"],
            ),
            _field(
                name="status",
                label="Stato",
                data_type="string",
                description="Stato: draft, published, closed, archived.",
                aliases=["stato", "campaign_status"],
            ),
            _field(
                name="start_date",
                label="Data inizio",
                data_type="date",
                description="Data di inizio della campagna.",
                aliases=["inizio", "data_inizio"],
            ),
            _field(
                name="due_date",
                label="Scadenza",
                data_type="date",
                description="Data di scadenza per il completamento della campagna.",
                aliases=["deadline", "data_scadenza"],
            ),
            _field(
                name="published_at",
                label="Pubblicata il",
                data_type="datetime",
                description="Data e ora di pubblicazione della campagna.",
                aliases=["data_pubblicazione"],
            ),
            _field(
                name="closed_at",
                label="Chiusa il",
                data_type="datetime",
                description="Data e ora di chiusura della campagna.",
                aliases=["data_chiusura"],
            ),
            _field(name="description", label="Descrizione", data_type="string", description="Descrizione estesa della campagna.", aliases=["descrizione", "body"]),
            _field(
                name="created_by_id",
                label="Creata da",
                data_type="int",
                description="Utente Django che ha creato la campagna.",
                aliases=["created_by", "autore_id"],
            ),
            _field(name="created_at", label="Creato il", data_type="datetime", description="Data e ora di creazione del record.", aliases=["data_creazione"]),
            _field(name="updated_at", label="Aggiornato il", data_type="datetime", description="Data e ora dell'ultimo aggiornamento.", aliases=["data_modifica"]),
        ],
    },
    "anagrafica_qualifiche": {
        "code": "anagrafica_qualifiche",
        "label": "Anagrafica - Qualifiche dipendenti",
        "source_app": "anagrafica",
        "table_name": "anagrafica_dipendentequalifica",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": (
            "Qualifiche/certificazioni assegnate ai dipendenti. "
            "Trigger utili: inserimento nuova qualifica, cambio data_scadenza, rinnovo."
        ),
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria qualifica."),
            _field(
                name="legacy_anagrafica_id",
                label="Dipendente (ID legacy)",
                data_type="int",
                description="ID legacy del dipendente titolare della qualifica.",
                aliases=["dipendente_id", "employee_id"],
            ),
            _field(
                name="tipo_id",
                label="Tipo qualifica (ID)",
                data_type="int",
                description="FK al catalogo TipoQualifica.",
                aliases=["tipo", "qualifica_tipo_id"],
            ),
            _field(
                name="data_conseguimento",
                label="Data conseguimento",
                data_type="date",
                description="Data in cui la qualifica è stata ottenuta.",
                aliases=["conseguimento", "data_rilascio"],
            ),
            _field(
                name="data_scadenza",
                label="Data scadenza",
                data_type="date",
                description="Data di scadenza della qualifica. Null se nessuna scadenza automatica.",
                aliases=["scadenza", "expiry_date"],
            ),
            _field(
                name="note",
                label="Note",
                data_type="string",
                description="Note libere sulla qualifica.",
                aliases=["note_qualifica"],
            ),
            _field(
                name="created_at",
                label="Creato il",
                data_type="datetime",
                description="Data e ora di creazione del record.",
                aliases=["data_creazione"],
            ),
        ],
    },
    "anagrafica_visite_mediche": {
        "code": "anagrafica_visite_mediche",
        "label": "Anagrafica - Visite mediche",
        "source_app": "anagrafica",
        "table_name": "anagrafica_visitamedica",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": (
            "Registrazioni visite mediche (idoneità lavorativa). "
            "Trigger utili: nuova visita, cambio esito, avvicinarsi della scadenza."
        ),
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria visita."),
            _field(
                name="legacy_anagrafica_id",
                label="Dipendente (ID legacy)",
                data_type="int",
                description="ID legacy del dipendente sottoposto alla visita.",
                aliases=["dipendente_id", "employee_id"],
            ),
            _field(
                name="tipo_id",
                label="Tipo visita (ID)",
                data_type="int",
                description="FK al catalogo TipoVisitaMedica.",
                aliases=["tipo", "visita_tipo_id"],
            ),
            _field(
                name="data_svolgimento",
                label="Data svolgimento",
                data_type="date",
                description="Data in cui si è svolta la visita medica.",
                aliases=["data_visita", "visit_date"],
            ),
            _field(
                name="data_scadenza",
                label="Data scadenza",
                data_type="date",
                description="Data di scadenza dell'idoneità. Calcolata automaticamente al salvataggio.",
                aliases=["scadenza", "expiry_date"],
            ),
            _field(
                name="esito",
                label="Esito",
                data_type="string",
                description=(
                    "Esito visita: IDONEO, IDONEO_MANS, IDONEO_PRESCR, IDONEO_LIM, "
                    "IDONEO_LIM_PRESCR, NON_IDONEO_TEMP, NON_IDONEO_DEF."
                ),
                aliases=["outcome", "risultato"],
                allowed_values=[
                    "IDONEO", "IDONEO_MANS", "IDONEO_PRESCR", "IDONEO_LIM",
                    "IDONEO_LIM_PRESCR", "NON_IDONEO_TEMP", "NON_IDONEO_DEF",
                ],
                ui_control="select",
            ),
            _field(
                name="prescrizioni",
                label="Prescrizioni",
                data_type="string",
                description="Testo delle prescrizioni mediche.",
                aliases=["prescriptions"],
            ),
            _field(
                name="medico_competente",
                label="Medico competente",
                data_type="string",
                description="Nome del medico competente che ha effettuato la visita.",
                aliases=["medico", "doctor"],
            ),
            _field(
                name="note",
                label="Note",
                data_type="string",
                description="Note libere sulla visita.",
            ),
            _field(
                name="created_at",
                label="Creato il",
                data_type="datetime",
                description="Data e ora di creazione del record.",
                aliases=["data_creazione"],
            ),
            _field(
                name="updated_at",
                label="Aggiornato il",
                data_type="datetime",
                description="Data e ora dell'ultimo aggiornamento.",
                aliases=["data_modifica"],
            ),
        ],
    },
    "anagrafica_formazione_enrollment": {
        "code": "anagrafica_formazione_enrollment",
        "label": "Anagrafica - Iscrizioni corsi formazione",
        "source_app": "anagrafica",
        "table_name": "anagrafica_trainingenrollment",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": (
            "Iscrizioni dipendenti alle sessioni formative. "
            "Trigger utili: cambio `stato` (COMPLETATO, ASSENTE, NON_IDONEO), valorizzazione `data_completamento`."
        ),
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria iscrizione."),
            _field(
                name="sessione_id",
                label="Sessione (ID)",
                data_type="int",
                description="FK alla sessione formativa.",
                aliases=["session_id"],
            ),
            _field(
                name="legacy_anagrafica_id",
                label="Dipendente (ID legacy)",
                data_type="int",
                description="ID legacy del dipendente iscritto.",
                aliases=["dipendente_id", "employee_id"],
            ),
            _field(
                name="assignment_id",
                label="Assegnazione (ID)",
                data_type="int",
                description="FK all'assegnazione corso che ha generato l'iscrizione.",
                aliases=["assignment"],
            ),
            _field(
                name="stato",
                label="Stato",
                data_type="string",
                description="Stato iscrizione: ISCRITTO, IN_CORSO, COMPLETATO, NON_IDONEO, ASSENTE, RITIRATO.",
                aliases=["status", "enrollment_status"],
                allowed_values=["ISCRITTO", "IN_CORSO", "COMPLETATO", "NON_IDONEO", "ASSENTE", "RITIRATO"],
                ui_control="select",
            ),
            _field(
                name="ore_frequentate",
                label="Ore frequentate",
                data_type="float",
                description="Ore totali di frequenza registrate.",
                aliases=["attended_hours"],
            ),
            _field(
                name="percentuale_presenza",
                label="% presenza",
                data_type="float",
                description="Percentuale di presenze sulle lezioni totali.",
                aliases=["attendance_percentage"],
            ),
            _field(
                name="idoneo",
                label="Idoneo",
                data_type="bool",
                description="Flag di idoneità finale al termine del corso.",
                aliases=["passed", "superato"],
            ),
            _field(
                name="esito_esame",
                label="Esito esame",
                data_type="string",
                description="Risultato dell'esame finale (se previsto).",
                aliases=["exam_result"],
            ),
            _field(
                name="data_completamento",
                label="Data completamento",
                data_type="date",
                description="Data in cui il dipendente ha completato il corso.",
                aliases=["completion_date", "data_fine"],
            ),
            _field(
                name="created_at",
                label="Creato il",
                data_type="datetime",
                description="Data e ora di iscrizione.",
                aliases=["data_creazione"],
            ),
            _field(
                name="updated_at",
                label="Aggiornato il",
                data_type="datetime",
                description="Data e ora dell'ultimo aggiornamento.",
                aliases=["data_modifica"],
            ),
        ],
    },
    "anagrafica_formazione_record": {
        "code": "anagrafica_formazione_record",
        "label": "Anagrafica - Record completamento formazione",
        "source_app": "anagrafica",
        "table_name": "anagrafica_trainingemployeerecord",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": (
            "Storico completamenti corso per dipendente. "
            "Include snapshot del corso e del piano al momento del completamento. "
            "Trigger utile: inserimento nuovo record (completamento corso)."
        ),
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria record."),
            _field(
                name="corso_id",
                label="Corso (ID)",
                data_type="int",
                description="FK al corso formativo completato.",
                aliases=["course_id"],
            ),
            _field(
                name="sessione_id",
                label="Sessione (ID)",
                data_type="int",
                description="FK alla sessione in cui è avvenuto il completamento.",
                aliases=["session_id"],
            ),
            _field(
                name="legacy_anagrafica_id",
                label="Dipendente (ID legacy)",
                data_type="int",
                description="ID legacy del dipendente che ha completato il corso.",
                aliases=["dipendente_id", "employee_id"],
            ),
            _field(
                name="data_completamento",
                label="Data completamento",
                data_type="date",
                description="Data in cui il dipendente ha completato il corso.",
                aliases=["completion_date"],
            ),
            _field(
                name="ore_frequentate",
                label="Ore frequentate",
                data_type="float",
                description="Ore totali di frequenza.",
                aliases=["attended_hours"],
            ),
            _field(
                name="idoneo",
                label="Idoneo",
                data_type="bool",
                description="Flag di superamento finale.",
                aliases=["passed", "superato"],
            ),
            _field(
                name="data_scadenza",
                label="Data scadenza",
                data_type="date",
                description="Data di scadenza dell'abilitazione. Null se corso una tantum.",
                aliases=["expiry_date", "scadenza"],
            ),
            _field(
                name="course_code_snapshot",
                label="Codice corso (snapshot)",
                data_type="string",
                description="Codice del corso al momento del completamento (immutabile).",
                aliases=["codice_corso"],
            ),
            _field(
                name="course_title_snapshot",
                label="Titolo corso (snapshot)",
                data_type="string",
                description="Titolo del corso al momento del completamento (immutabile).",
                aliases=["titolo_corso"],
            ),
            _field(
                name="plan_code_snapshot",
                label="Codice piano (snapshot)",
                data_type="string",
                description="Codice del piano formativo al momento del completamento.",
                aliases=["codice_piano"],
            ),
            _field(
                name="plan_name_snapshot",
                label="Nome piano (snapshot)",
                data_type="string",
                description="Nome del piano formativo al momento del completamento.",
                aliases=["nome_piano"],
            ),
            _field(
                name="teacher_name_snapshot",
                label="Docente (snapshot)",
                data_type="string",
                description="Nome del docente al momento del completamento.",
                aliases=["docente_nome"],
            ),
            _field(
                name="created_at",
                label="Creato il",
                data_type="datetime",
                description="Data e ora di creazione del record.",
                aliases=["data_creazione"],
            ),
        ],
    },
    "anagrafica_offboarding": {
        "code": "anagrafica_offboarding",
        "label": "Anagrafica - Pratiche offboarding",
        "source_app": "anagrafica",
        "table_name": "anagrafica_offboardingpratica",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": (
            "Pratiche di uscita dipendente (offboarding). "
            "Trigger utili: apertura pratica (insert), cambio `stato` (CHIUSA, ANNULLATA)."
        ),
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria pratica."),
            _field(
                name="legacy_anagrafica_id",
                label="Dipendente (ID legacy)",
                data_type="int",
                description="ID legacy del dipendente in uscita.",
                aliases=["dipendente_id", "employee_id"],
            ),
            _field(
                name="dipendente_nome",
                label="Dipendente nome",
                data_type="string",
                description="Nome completo del dipendente in uscita (snapshot).",
                aliases=["nome_dipendente", "employee_name"],
            ),
            _field(
                name="reparto",
                label="Reparto",
                data_type="string",
                description="Reparto di appartenenza del dipendente.",
                aliases=["department"],
            ),
            _field(
                name="mansione",
                label="Mansione",
                data_type="string",
                description="Mansione del dipendente.",
                aliases=["job_title", "ruolo"],
            ),
            _field(
                name="motivo",
                label="Motivo",
                data_type="string",
                description="Motivo uscita: licenziamento, dimissioni, fine_contratto, pensionamento, altro.",
                aliases=["reason", "exit_reason"],
                allowed_values=["licenziamento", "dimissioni", "fine_contratto", "pensionamento", "altro"],
                ui_control="select",
            ),
            _field(
                name="data_cessazione_prevista",
                label="Data cessazione prevista",
                data_type="date",
                description="Data prevista per la cessazione del rapporto.",
                aliases=["data_cessazione", "exit_date"],
            ),
            _field(
                name="ultimo_giorno_operativo",
                label="Ultimo giorno operativo",
                data_type="date",
                description="Ultimo giorno effettivo in azienda.",
                aliases=["last_day"],
            ),
            _field(
                name="stato",
                label="Stato",
                data_type="string",
                description="Stato pratica: IN_CORSO, CHIUSA, CHIUSA_CON_ECCEZIONI, ANNULLATA.",
                aliases=["status", "offboarding_status"],
                allowed_values=["IN_CORSO", "CHIUSA", "CHIUSA_CON_ECCEZIONI", "ANNULLATA"],
                ui_control="select",
            ),
            _field(
                name="note_hr",
                label="Note HR",
                data_type="string",
                description="Note interne del responsabile HR.",
                aliases=["hr_notes", "note"],
            ),
            _field(
                name="created_at",
                label="Creato il",
                data_type="datetime",
                description="Data e ora di apertura della pratica.",
                aliases=["data_apertura", "data_creazione"],
            ),
            _field(
                name="updated_at",
                label="Aggiornato il",
                data_type="datetime",
                description="Data e ora dell'ultimo aggiornamento.",
                aliases=["data_modifica"],
            ),
            _field(
                name="closed_at",
                label="Chiuso il",
                data_type="datetime",
                description="Data e ora di chiusura della pratica.",
                aliases=["data_chiusura"],
            ),
        ],
    },
    "anagrafica_fornitori": {
        "code": "anagrafica_fornitori",
        "label": "Anagrafica - Fornitori",
        "source_app": "anagrafica",
        "table_name": "anagrafica_fornitore",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": (
            "Anagrafica fornitori. "
            "Trigger utili: nuovo fornitore (insert), cambio `is_active` (disattivazione/riattivazione)."
        ),
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria fornitore."),
            _field(
                name="ragione_sociale",
                label="Ragione sociale",
                data_type="string",
                description="Denominazione del fornitore.",
                aliases=["nome", "company_name", "supplier_name"],
            ),
            _field(
                name="piva",
                label="Partita IVA",
                data_type="string",
                description="Partita IVA del fornitore.",
                aliases=["vat", "partita_iva"],
            ),
            _field(
                name="email",
                label="Email",
                data_type="string",
                description="Email principale del fornitore.",
                aliases=["email_fornitore", "supplier_email"],
            ),
            _field(
                name="pec",
                label="PEC",
                data_type="string",
                description="Indirizzo PEC del fornitore.",
                aliases=["pec_email"],
            ),
            _field(
                name="telefono",
                label="Telefono",
                data_type="string",
                description="Numero di telefono del fornitore.",
                aliases=["phone"],
            ),
            _field(
                name="categoria",
                label="Categoria",
                data_type="string",
                description="Categoria fornitore: MATERIALI, SERVIZI, ATTREZZATURE, LOGISTICA, IT, MANUTENZIONE, ALTRO.",
                aliases=["category", "supplier_category"],
                allowed_values=["MATERIALI", "SERVIZI", "ATTREZZATURE", "LOGISTICA", "IT", "MANUTENZIONE", "ALTRO"],
                ui_control="select",
            ),
            _field(
                name="is_active",
                label="Attivo",
                data_type="bool",
                description="Flag attivo/disattivo del fornitore.",
                aliases=["active", "attivo"],
            ),
            _field(
                name="note",
                label="Note",
                data_type="string",
                description="Note libere sul fornitore.",
            ),
            _field(
                name="created_at",
                label="Creato il",
                data_type="datetime",
                description="Data e ora di creazione del record fornitore.",
                aliases=["data_creazione"],
            ),
            _field(
                name="updated_at",
                label="Aggiornato il",
                data_type="datetime",
                description="Data e ora dell'ultimo aggiornamento.",
                aliases=["data_modifica"],
            ),
        ],
    },
    "procedure_assegnazioni": {
        "code": "procedure_assegnazioni",
        "label": "Procedure - Assegnazioni",
        "source_app": "procedure_refresh",
        "table_name": "procedure_refresh_procedureassignment",
        "pk_field": "id",
        "supported_operations": ["insert", "update"],
        "description": (
            "Assegnazioni procedure a utenti. Workflow: assigned → opened → read_confirmed (o overdue/cancelled). "
            "Trigger utili: `status` cambia, `read_confirmed_at` valorizzato, `first_opened_at` valorizzato."
        ),
        "fields": [
            _field(name="id", label="ID", data_type="int", description="Chiave primaria assegnazione.", aliases=["assignment_id"]),
            _field(
                name="status",
                label="Stato",
                data_type="string",
                description="Stato: assigned, opened, read_confirmed, overdue, cancelled.",
                aliases=["stato", "assignment_status"],
            ),
            _field(
                name="user_id",
                label="Utente",
                data_type="int",
                description="Utente Django a cui e' assegnata la procedura.",
                aliases=["user", "assegnato_id"],
            ),
            _field(
                name="campaign_id",
                label="Campagna",
                data_type="int",
                description="Campagna a cui appartiene l'assegnazione.",
                aliases=["campaign", "campagna_id"],
            ),
            _field(
                name="due_date",
                label="Scadenza",
                data_type="date",
                description="Data di scadenza per la conferma lettura.",
                aliases=["deadline", "data_scadenza"],
            ),
            _field(
                name="first_opened_at",
                label="Prima apertura",
                data_type="datetime",
                description="Data e ora della prima apertura del documento.",
                aliases=["primo_accesso"],
            ),
            _field(
                name="read_confirmed_at",
                label="Lettura confermata il",
                data_type="datetime",
                description="Data e ora in cui l'utente ha confermato la lettura.",
                aliases=["confermato_il", "confirmed_at"],
            ),
            _field(
                name="read_confirmed_flag",
                label="Lettura confermata",
                data_type="bool",
                description="Flag booleano di conferma lettura.",
                aliases=["confermato", "confirmed"],
            ),
            _field(name="revision_id", label="Revisione (ID)", data_type="int", description="Revisione del documento procedure assegnata.", aliases=["revision", "document_revision_id"]),
            _field(name="assigned_by_id", label="Assegnato da (ID)", data_type="int", description="Utente Django che ha creato l'assegnazione.", aliases=["assigned_by", "assigner_id"]),
            _field(name="assigned_at", label="Assegnato il", data_type="datetime", description="Data e ora di creazione dell'assegnazione.", aliases=["assignment_date", "data_assegnazione"]),
            _field(name="last_opened_at", label="Ultima apertura", data_type="datetime", description="Data e ora dell'ultima apertura del documento.", aliases=["ultimo_accesso"]),
            _field(
                name="open_count",
                label="Numero aperture",
                data_type="int",
                description="Quante volte l'utente ha aperto il documento.",
                aliases=["aperture", "views"],
            ),
            _field(name="user_note", label="Nota utente", data_type="string", description="Nota libera inserita dall'utente al momento della conferma.", aliases=["user_comment", "nota_utente"]),
            _field(name="manager_note", label="Nota manager", data_type="string", description="Nota inserita dal responsabile sull'assegnazione.", aliases=["manager_comment", "nota_manager"]),
            _field(name="created_at", label="Creato il", data_type="datetime", description="Data e ora di creazione del record assegnazione.", aliases=["data_creazione"]),
            _field(name="updated_at", label="Aggiornato il", data_type="datetime", description="Data e ora dell'ultimo aggiornamento.", aliases=["data_modifica"]),
        ],
    },
}


def _normalize_code(code: str | None) -> str:
    return str(code or "").strip().lower()


def _clone_source(source: dict[str, object]) -> dict[str, object]:
    return deepcopy(source)


def get_registered_sources() -> list[dict[str, object]]:
    return [_clone_source(source) for source in _SOURCE_REGISTRY.values()]


def get_source_definition(code: str | None) -> dict[str, object] | None:
    source = _SOURCE_REGISTRY.get(_normalize_code(code))
    if source is None:
        return None
    return _clone_source(source)


def get_source_choices() -> list[tuple[str, str]]:
    return [(source["code"], source["label"]) for source in get_registered_sources()]


def get_source_fields(code: str | None) -> list[dict[str, object]]:
    source = get_source_definition(code)
    if source is None:
        return []
    return list(source.get("fields", []))


def _filter_fields(code: str | None, flag_name: str) -> list[dict[str, object]]:
    return [field for field in get_source_fields(code) if bool(field.get(flag_name))]


def get_trigger_fields(code: str | None) -> list[dict[str, object]]:
    return _filter_fields(code, "usable_in_trigger")


def get_condition_fields(code: str | None) -> list[dict[str, object]]:
    return _filter_fields(code, "usable_in_condition")


def get_template_fields(code: str | None) -> list[dict[str, object]]:
    return _filter_fields(code, "usable_in_template")


def get_action_mapping_fields(code: str | None) -> list[dict[str, object]]:
    return _filter_fields(code, "usable_in_action_mapping")


def build_placeholder_examples(code: str | None) -> list[str]:
    return [f"{{{field['name']}}}" for field in get_template_fields(code)]
