# Generated by Django 5.2.11 on 2026-04-28 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attrezzatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(db_index=True, max_length=80)),
                ('descrizione', models.CharField(blank=True, default='', max_length=255)),
                ('part_number', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('numero_pezzi', models.PositiveIntegerField(blank=True, null=True)),
                ('avanzamento_percentuale', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('da_classificare', 'Da classificare'), ('da_verificare', 'Da verificare'), ('non_disponibile', 'Non disponibile'), ('da_creare', 'Da creare'), ('in_corso', 'In corso'), ('in_attesa', 'In attesa'), ('finita', 'Finita'), ('pronta_produzione', 'Pronta produzione'), ('annullata', 'Annullata'), ('eccezione', 'Eccezione')], db_index=True, default='da_classificare', max_length=40)),
                ('disponibilita_stato', models.CharField(choices=[('da_verificare', 'Da verificare'), ('disponibile', 'Disponibile'), ('non_disponibile', 'Non disponibile'), ('da_creare', 'Da creare'), ('da_modificare', 'Da modificare')], default='da_verificare', max_length=40)),
                ('ordine_visuale', models.IntegerField(blank=True, null=True)),
                ('data_consegna_prevista', models.DateField(blank=True, db_index=True, null=True)),
                ('note_consegna', models.TextField(blank=True, default='')),
                ('note_rocco', models.TextField(blank=True, default='')),
                ('origine_import', models.CharField(blank=True, default='', max_length=120)),
                ('pronta_produzione_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attrezzature_created', to=settings.AUTH_USER_MODEL)),
                ('pronta_produzione_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attrezzature_pronte_produzione', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attrezzature_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attrezzatura',
                'verbose_name_plural': 'Attrezzature',
                'ordering': ['codice', 'part_number', 'id'],
                'permissions': [('attrezzature_view', 'Puo vedere Gestione Attrezzatura'), ('attrezzature_add', 'Puo creare attrezzature'), ('attrezzature_change', 'Puo modificare attrezzature'), ('attrezzature_import', 'Puo importare attrezzature da Excel'), ('attrezzature_export', 'Puo esportare attrezzature'), ('attrezzature_task_view', 'Puo vedere task attrezzature'), ('attrezzature_task_manage', 'Puo gestire task attrezzature'), ('attrezzature_link_kickoff', 'Puo collegare attrezzature a Kickoff'), ('attrezzature_confirm_ready_production', 'Puo confermare pronta produzione')],
            },
        ),
        migrations.CreateModel(
            name='AttrezzaturaAvanzamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato_precedente', models.CharField(blank=True, default='', max_length=40)),
                ('stato_nuovo', models.CharField(blank=True, default='', max_length=40)),
                ('avanzamento_precedente', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avanzamento_nuovo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, default='')),
                ('origine', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attrezzatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avanzamenti', to='attrezzature.attrezzatura')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AttrezzaturaImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('imported', 'Imported'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='preview', max_length=40)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AttrezzaturaImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_sheet', models.CharField(blank=True, default='', max_length=120)),
                ('excel_row_number', models.PositiveIntegerField()),
                ('payload_originale_json', models.JSONField(default=dict)),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
                ('codice_letto', models.CharField(blank=True, default='', max_length=80)),
                ('part_number_letto', models.CharField(blank=True, default='', max_length=120)),
                ('azione', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('unchanged', 'Unchanged'), ('skipped', 'Skipped'), ('warning', 'Warning'), ('error', 'Error')], max_length=40)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attrezzatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='attrezzature.attrezzatura')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='attrezzature.attrezzaturaimportbatch')),
            ],
            options={
                'ordering': ['batch_id', 'excel_row_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttrezzaturaPartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(db_index=True, max_length=120)),
                ('is_principale', models.BooleanField(default=True)),
                ('fonte', models.CharField(blank=True, default='', max_length=80)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attrezzatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_numbers', to='attrezzature.attrezzatura')),
            ],
            options={
                'ordering': ['-is_principale', 'part_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttrezzaturaTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('codice_attrezzo', models.CharField(blank=True, default='', max_length=80)),
                ('tipo', models.CharField(choices=[('verifica_disponibilita', 'Verifica disponibilita'), ('creazione_attrezzo', 'Creazione attrezzo'), ('aggiorna_avanzamento', 'Aggiorna avanzamento'), ('controllo_ritardo', 'Controllo ritardo'), ('conferma_pronta_produzione', 'Conferma pronta produzione')], max_length=50)),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True, default='')),
                ('stato', models.CharField(choices=[('aperta', 'Aperta'), ('in_lavorazione', 'In lavorazione'), ('completata', 'Completata'), ('annullata', 'Annullata'), ('bloccata', 'Bloccata')], default='aperta', max_length=40)),
                ('priorita', models.CharField(choices=[('bassa', 'Bassa'), ('normale', 'Normale'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normale', max_length=30)),
                ('scadenza', models.DateField(blank=True, null=True)),
                ('origine', models.CharField(choices=[('manuale', 'Manuale'), ('kickoff', 'Kickoff'), ('import_excel', 'Import Excel'), ('regola_automatica', 'Regola automatica')], default='manuale', max_length=40)),
                ('external_kickoff_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('external_kickoff_activity_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assegnato_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attrezzatura_tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('attrezzatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='attrezzature.attrezzatura')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attrezzatura_tasks_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attrezzatura_tasks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scadenza', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AttrezzaturaNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('origine', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attrezzatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='attrezzature.attrezzatura')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note', to='attrezzature.attrezzaturatask')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='attrezzatura',
            index=models.Index(fields=['codice'], name='attrezzatur_codice_abd3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='attrezzatura',
            index=models.Index(fields=['part_number'], name='attrezzatur_part_nu_305b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='attrezzatura',
            index=models.Index(fields=['stato'], name='attrezzatur_stato_5aa401_idx'),
        ),
        migrations.AddIndex(
            model_name='attrezzatura',
            index=models.Index(fields=['data_consegna_prevista'], name='attrezzatur_data_co_8c1f43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attrezzaturapartnumber',
            unique_together={('attrezzatura', 'part_number')},
        ),
        migrations.AddIndex(
            model_name='attrezzaturatask',
            index=models.Index(fields=['tipo', 'stato'], name='attrezzatur_tipo_06a469_idx'),
        ),
        migrations.AddIndex(
            model_name='attrezzaturatask',
            index=models.Index(fields=['part_number', 'stato'], name='attrezzatur_part_nu_7ab206_idx'),
        ),
        migrations.AddIndex(
            model_name='attrezzaturatask',
            index=models.Index(fields=['external_kickoff_activity_id'], name='attrezzatur_externa_f0f033_idx'),
        ),
    ]
