# Generated by Django 5.2.11 on 2026-04-30 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrezzature', '0001_initial'),
        ('tasks', '0026_meetingissue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attrezzatura',
            name='blocked_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='attrezzatura',
            name='stato',
            field=models.CharField(choices=[('draft', 'Richiesta'), ('requested', 'Richiesta'), ('checking_available', 'Verifica disponibilità'), ('available', 'Disponibile'), ('to_create', 'Da creare'), ('in_progress', 'In lavorazione'), ('blocked', 'Bloccata'), ('late', 'In ritardo'), ('ready_for_production', 'Pronta per produzione'), ('closed', 'Chiusa'), ('archived', 'Archiviata'), ('da_classificare', 'Da classificare'), ('da_verificare', 'Da verificare'), ('non_disponibile', 'Non disponibile'), ('da_creare', 'Da creare'), ('in_corso', 'In corso'), ('in_attesa', 'In attesa'), ('finita', 'Finita'), ('pronta_produzione', 'Pronta produzione'), ('annullata', 'Annullata'), ('eccezione', 'Eccezione')], db_index=True, default='da_classificare', max_length=40),
        ),
        migrations.CreateModel(
            name='AttrezzaturaKickoffLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('created_from_kickoff', 'Creata da KICK-OFF'), ('linked_existing', 'Collegata esistente'), ('verification_required', 'Verifica richiesta')], db_index=True, default='linked_existing', max_length=40)),
                ('part_number_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attrezzatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kickoff_links', to='attrezzature.attrezzatura')),
                ('attrezzatura_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kickoff_links', to='attrezzature.attrezzaturatask')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attrezzature_links', to='tasks.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attrezzature_links', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Collegamento KICK-OFF attrezzatura',
                'verbose_name_plural': 'Collegamenti KICK-OFF attrezzature',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['task', 'relationship_type'], name='attrezzatur_task_id_af9215_idx'), models.Index(fields=['project', 'relationship_type'], name='attrezzatur_project_2f18d1_idx'), models.Index(fields=['part_number_snapshot'], name='attrezzatur_part_nu_c03046_idx')],
            },
        ),
    ]
