# Generated by Django 5.2.11 on 2026-04-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attrezzature', '0002_attrezzatura_blocked_reason_alter_attrezzatura_stato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attrezzatura',
            name='stato',
            field=models.CharField(choices=[('draft', 'Richiesta'), ('requested', 'Richiesta'), ('checking_available', 'Verifica disponibilità'), ('available', 'Disponibile'), ('to_create', 'Da creare'), ('in_progress', 'In lavorazione'), ('blocked', 'Bloccata'), ('late', 'In ritardo'), ('ready_for_production', 'Pronta per produzione'), ('closed', 'Chiusa'), ('archived', 'Archiviata'), ('da_classificare', 'Da classificare'), ('da_verificare', 'Da verificare'), ('non_disponibile', 'Non disponibile'), ('da_creare', 'Da creare'), ('in_corso', 'In corso'), ('in_attesa', 'In attesa'), ('finita', 'Finita'), ('pronta_produzione', 'Pronta produzione'), ('annullata', 'Annullata'), ('eccezione', 'Eccezione')], db_index=True, default='requested', max_length=40),
        ),
    ]
