# Generated by Django 5.2.16 on 2026-08-03 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0070_ofi_registro_toplevel_nav'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveIntegerField(default=100)),
                ('descrizione', models.TextField()),
                ('reparto', models.CharField(blank=True, default='', max_length=150)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsabile', models.ForeignKey(blank=True, help_text='Dipendente che dovrà eseguire e confermare la mansione a ogni chiusura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_task_templates', to='core.anagraficadipendente')),
            ],
            options={
                'verbose_name': 'Mansione checklist chiusura',
                'verbose_name_plural': 'Mansioni checklist chiusura',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChiusuraEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('aperta', 'Aperta'), ('chiusa', 'Chiusa / archiviata')], db_index=True, default='aperta', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento chiusura aziendale',
                'verbose_name_plural': 'Eventi chiusura aziendale',
                'ordering': ['-data_inizio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChiusuraVoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.PositiveIntegerField(default=100)),
                ('descrizione', models.TextField()),
                ('confermato', models.BooleanField(default=False)),
                ('confermato_il', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('confermato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.anagraficadipendente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci', to='checklist_operativa.chiusuraevento')),
                ('responsabile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_voci_assegnate', to='core.anagraficadipendente')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voci_generate', to='checklist_operativa.checklisttasktemplate')),
            ],
            options={
                'verbose_name': 'Voce checklist chiusura',
                'verbose_name_plural': 'Voci checklist chiusura',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChiusuraProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField()),
                ('proposto_il', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa'), ('approvata', 'Approvata'), ('rifiutata', 'Rifiutata')], db_index=True, default='in_attesa', max_length=10)),
                ('note_admin', models.TextField(blank=True, default='')),
                ('aggiungi_al_template', models.BooleanField(default=False, help_text='Se approvata, crea anche una mansione permanente in configurazione.')),
                ('gestito_il', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposte', to='checklist_operativa.chiusuraevento')),
                ('gestito_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposto_da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_proposte', to=settings.AUTH_USER_MODEL)),
                ('responsabile_suggerito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.anagraficadipendente')),
                ('template_generato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='checklist_operativa.checklisttasktemplate')),
                ('voce_generata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='checklist_operativa.chiusuravoce')),
            ],
            options={
                'verbose_name': 'Proposta voce checklist chiusura',
                'verbose_name_plural': 'Proposte voci checklist chiusura',
                'ordering': ['-proposto_il'],
            },
        ),
    ]
