# Generated by Django 6.0.7 on 2026-07-10 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Macchina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reparto', models.CharField(max_length=60)),
                ('matricola', models.CharField(max_length=40, unique=True)),
                ('modello', models.CharField(blank=True, max_length=60)),
                ('contratto', models.CharField(blank=True, help_text='Stesso contratto = fatturazione in pool', max_length=20)),
                ('fornitore', models.CharField(choices=[('BASE', 'BASE SPA'), ('COPYLAB', 'Copylab')], default='BASE', max_length=10)),
                ('host', models.GenericIPAddressField(blank=True, help_text='IP per lettura SNMP', null=True)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Macchine',
                'ordering': ['reparto'],
            },
        ),
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('data', models.DateField()),
                ('fornitore', models.CharField(default='BASE', max_length=10)),
                ('trimestre', models.CharField(help_text='Es. "2026-Q2"', max_length=8)),
                ('periodo_dal', models.DateField(blank=True, null=True)),
                ('periodo_al', models.DateField(help_text='Data di chiusura letture fornitore')),
            ],
            options={
                'ordering': ['-periodo_al'],
                'unique_together': {('numero', 'trimestre')},
            },
        ),
        migrations.CreateModel(
            name='LetturaContatori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(help_text='Es. "2026-Q2"', max_length=8)),
                ('data', models.DateField(help_text='Data della rilevazione')),
                ('a4_bn', models.PositiveIntegerField(default=0)),
                ('a3_bn', models.PositiveIntegerField(default=0)),
                ('a4_col', models.PositiveIntegerField(default=0)),
                ('a3_col', models.PositiveIntegerField(default=0)),
                ('fonte', models.CharField(choices=[('SNMP', 'SNMP'), ('MANUALE', 'Manuale'), ('FATTURA', 'Da fattura')], default='MANUALE', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('macchina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letture', to='contatori.macchina')),
            ],
            options={
                'verbose_name': 'Lettura contatori',
                'verbose_name_plural': 'Letture contatori',
                'ordering': ['-trimestre', 'macchina__reparto'],
                'unique_together': {('macchina', 'trimestre')},
            },
        ),
        migrations.CreateModel(
            name='RigaFattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratto', models.CharField(max_length=20)),
                ('descrizione', models.CharField(blank=True, max_length=120)),
                ('a4_bn', models.PositiveIntegerField(default=0)),
                ('a3_bn', models.PositiveIntegerField(default=0)),
                ('a4_col', models.PositiveIntegerField(default=0)),
                ('a3_col', models.PositiveIntegerField(default=0)),
                ('fattura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='contatori.fattura')),
            ],
            options={
                'verbose_name': 'Riga fattura',
                'verbose_name_plural': 'Righe fattura',
                'ordering': ['contratto'],
                'unique_together': {('fattura', 'contratto')},
            },
        ),
    ]
