# Generated by Django 5.2.11 on 2026-07-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostazioniSNMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(default='novicromprinter', help_text='Nome community/gruppo SNMP (in lettura)', max_length=60)),
                ('port', models.PositiveIntegerField(default=161)),
                ('timeout', models.PositiveIntegerField(default=3, help_text='Secondi di attesa per macchina')),
                ('version', models.CharField(choices=[('v1', 'SNMPv1'), ('v2c', 'SNMPv2c')], default='v1', max_length=4)),
            ],
            options={
                'verbose_name': 'Impostazioni SNMP',
                'verbose_name_plural': 'Impostazioni SNMP',
            },
        ),
        migrations.AlterField(
            model_name='fattura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='letturacontatori',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='macchina',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rigafattura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
