# Generated by Django 5.2.11 on 2026-07-12 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0080_maintenancerule_execution_mode_and_more'),
        ('contatori', '0003_alter_fattura_id_alter_impostazionisnmp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='macchina',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Asset del registro HUB collegato (match matricola↔serial / host↔IP).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatori_macchine', to='assets.asset'),
        ),
    ]
