# Generated by Django 5.2.11 on 2026-07-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatori', '0004_macchina_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macchina',
            name='modello',
            field=models.CharField(blank=True, choices=[('iR-ADV C5535i', 'Canon iR-ADV C5535i'), ('iR-ADV DX C5840i', 'Canon iR-ADV DX C5840i'), ('iR-ADV DX C3822i', 'Canon iR-ADV DX C3822i')], help_text='Modello con contatori SNMP mappati. Non inserire la marca: serve il modello esatto.', max_length=60),
        ),
    ]
