# Generated by Django 5.2.16 on 2026-09-26 09:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0118_acl_v2_verifiche_impianti'),
        ('contatori', '0005_alter_macchina_modello'),
    ]

    operations = [
        migrations.AddField(
            model_name='macchina',
            name='snmp_stato',
            field=models.CharField(choices=[('MAI', 'Mai interrogato'), ('OK', 'Operativo'), ('WARNING', 'Attenzione'), ('ERROR', 'Errore')], default='MAI', max_length=10),
        ),
        migrations.AddField(
            model_name='macchina',
            name='snmp_tempo_risposta_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macchina',
            name='snmp_ultimo_controllo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='macchina',
            name='snmp_ultimo_errore',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='DispositivoSNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('LETTORE', 'Lettore / terminale'), ('STAMPANTE', 'Stampante / MFC extra'), ('RETE', 'Rete'), ('UPS', 'UPS / alimentazione'), ('AMBIENTE', 'Sensore ambiente'), ('ALTRO', 'Altro dispositivo')], default='LETTORE', max_length=16)),
                ('host', models.GenericIPAddressField(unique=True)),
                ('porta', models.PositiveIntegerField(blank=True, help_text='Vuoto = porta SNMP globale.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('versione', models.CharField(blank=True, choices=[('', 'Usa configurazione globale'), ('v1', 'SNMPv1'), ('v2c', 'SNMPv2c')], help_text='Vuoto = versione SNMP globale.', max_length=4)),
                ('posizione', models.CharField(blank=True, max_length=120)),
                ('produttore', models.CharField(blank=True, max_length=80)),
                ('modello', models.CharField(blank=True, max_length=120)),
                ('matricola', models.CharField(blank=True, max_length=80)),
                ('note', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('snmp_stato', models.CharField(choices=[('MAI', 'Mai interrogato'), ('OK', 'Operativo'), ('WARNING', 'Attenzione'), ('ERROR', 'Errore')], default='MAI', max_length=10)),
                ('snmp_ultimo_controllo', models.DateTimeField(blank=True, null=True)),
                ('snmp_tempo_risposta_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('snmp_ultimo_errore', models.CharField(blank=True, max_length=500)),
                ('sys_name', models.CharField(blank=True, max_length=255)),
                ('sys_description', models.TextField(blank=True)),
                ('sys_object_id', models.CharField(blank=True, max_length=255)),
                ('sys_uptime_seconds', models.PositiveBigIntegerField(blank=True, null=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivi_snmp', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Dispositivo SNMP',
                'verbose_name_plural': 'Dispositivi SNMP',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='RilevazioneSNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rilevata_il', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('stato', models.CharField(choices=[('MAI', 'Mai interrogato'), ('OK', 'Operativo'), ('WARNING', 'Attenzione'), ('ERROR', 'Errore')], max_length=10)),
                ('tempo_risposta_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('errore', models.CharField(blank=True, max_length=500)),
                ('sys_name', models.CharField(blank=True, max_length=255)),
                ('sys_description', models.TextField(blank=True)),
                ('sys_object_id', models.CharField(blank=True, max_length=255)),
                ('sys_uptime_seconds', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rilevazioni', to='contatori.dispositivosnmp')),
            ],
            options={
                'verbose_name': 'Rilevazione SNMP',
                'verbose_name_plural': 'Rilevazioni SNMP',
                'ordering': ['-rilevata_il', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SondaSNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('oid', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Inserisci un OID numerico puntato, ad esempio 1.3.6.1.2.1.1.3.0.', regex='^\\d+(?:\\.\\d+)+$')])),
                ('tipo_valore', models.CharField(choices=[('NUMERO', 'Numero'), ('TESTO', 'Testo'), ('TIMETICKS', 'Tempo (TimeTicks)')], default='NUMERO', max_length=10)),
                ('unita', models.CharField(blank=True, max_length=24)),
                ('fattore', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Moltiplicatore applicato al valore numerico grezzo.', max_digits=14)),
                ('soglia_warning_min', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('soglia_warning_max', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('soglia_critica_min', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('soglia_critica_max', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonde', to='contatori.dispositivosnmp')),
            ],
            options={
                'verbose_name': 'Sonda SNMP',
                'verbose_name_plural': 'Sonde SNMP',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ValoreSNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore_numero', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('valore_testo', models.TextField(blank=True)),
                ('stato', models.CharField(choices=[('MAI', 'Mai interrogato'), ('OK', 'Operativo'), ('WARNING', 'Attenzione'), ('ERROR', 'Errore')], max_length=10)),
                ('errore', models.CharField(blank=True, max_length=500)),
                ('rilevazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valori', to='contatori.rilevazionesnmp')),
                ('sonda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valori', to='contatori.sondasnmp')),
            ],
            options={
                'verbose_name': 'Valore SNMP',
                'verbose_name_plural': 'Valori SNMP',
                'ordering': ['sonda__ordine', 'sonda__nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='sondasnmp',
            constraint=models.UniqueConstraint(fields=('dispositivo', 'oid'), name='contatori_sonda_oid_unico'),
        ),
        migrations.AddConstraint(
            model_name='valoresnmp',
            constraint=models.UniqueConstraint(fields=('rilevazione', 'sonda'), name='contatori_valore_sonda_rilevazione_unico'),
        ),
    ]
