# Generated by Django 5.2.16 on 2026-09-26 14:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatori', '0006_macchina_snmp_stato_macchina_snmp_tempo_risposta_ms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetturaMensileContatori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mese', models.DateField(help_text='Primo giorno del mese di rilevazione')),
                ('rilevata_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('a4_bn', models.PositiveIntegerField()),
                ('a3_bn', models.PositiveIntegerField()),
                ('a4_col', models.PositiveIntegerField()),
                ('a3_col', models.PositiveIntegerField()),
                ('macchina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letture_mensili', to='contatori.macchina')),
            ],
            options={
                'verbose_name': 'Lettura mensile MFC',
                'verbose_name_plural': 'Letture mensili MFC',
                'ordering': ['-mese', 'macchina__reparto'],
                'constraints': [models.UniqueConstraint(fields=('macchina', 'mese'), name='contatori_mfc_mese_unico')],
            },
        ),
    ]
