# Generated by Django 5.2.16 on 2026-09-26 17:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatori', '0007_letturamensilecontatori'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfiloSNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('produttore', models.CharField(db_index=True, max_length=80)),
                ('categoria', models.CharField(choices=[('STAMPANTE', 'Stampante / MFC'), ('FIREWALL', 'Firewall / sicurezza'), ('RETE', 'Switch / router / Wi-Fi'), ('SERVER', 'Server / hypervisor'), ('STORAGE', 'NAS / storage'), ('UPS', 'UPS / alimentazione'), ('AMBIENTE', 'Sensore / ambiente'), ('GENERICO', 'Generico')], db_index=True, default='GENERICO', max_length=16)),
                ('famiglia_modelli', models.CharField(blank=True, max_length=160)),
                ('descrizione', models.TextField(blank=True)),
                ('sys_object_id_prefix', models.CharField(blank=True, help_text='Prefisso enterprise usato per il riconoscimento automatico.', max_length=255, validators=[django.core.validators.RegexValidator(message='Inserisci un OID numerico puntato, ad esempio 1.3.6.1.2.1.1.3.0.', regex='^\\d+(?:\\.\\d+)+$')])),
                ('sys_descr_pattern', models.CharField(blank=True, help_text='Espressione regolare opzionale applicata a sysDescr.', max_length=255)),
                ('versione', models.CharField(blank=True, choices=[('', 'Usa configurazione globale'), ('v1', 'SNMPv1'), ('v2c', 'SNMPv2c')], max_length=4)),
                ('porta', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('timeout', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('precaricato', models.BooleanField(default=False)),
                ('attivo', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profilo SNMP',
                'verbose_name_plural': 'Profili SNMP',
                'ordering': ['produttore', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='dispositivosnmp',
            name='timeout',
            field=models.PositiveIntegerField(blank=True, help_text='Vuoto = timeout del profilo o globale.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='macchina',
            name='snmp_porta',
            field=models.PositiveIntegerField(blank=True, help_text='Vuoto = profilo o configurazione globale.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='macchina',
            name='snmp_timeout',
            field=models.PositiveIntegerField(blank=True, help_text='Vuoto = profilo o configurazione globale.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='macchina',
            name='snmp_versione',
            field=models.CharField(blank=True, choices=[('', 'Usa configurazione globale'), ('v1', 'SNMPv1'), ('v2c', 'SNMPv2c')], help_text='Vuoto = profilo o configurazione globale.', max_length=4),
        ),
        migrations.AddField(
            model_name='sondasnmp',
            name='aggregazione',
            field=models.CharField(choices=[('PRIMO', 'Primo valore'), ('MASSIMO', 'Valore massimo'), ('MINIMO', 'Valore minimo'), ('SOMMA', 'Somma')], default='PRIMO', max_length=10),
        ),
        migrations.AddField(
            model_name='sondasnmp',
            name='modalita',
            field=models.CharField(choices=[('GET', 'GET (OID esatto)'), ('WALK', 'WALK (colonna MIB)')], default='GET', max_length=8),
        ),
        migrations.AlterField(
            model_name='macchina',
            name='modello',
            field=models.CharField(blank=True, help_text='Modello dichiarato dal produttore. Il profilo stabilisce gli OID.', max_length=120),
        ),
        migrations.AddField(
            model_name='dispositivosnmp',
            name='profilo_snmp',
            field=models.ForeignKey(blank=True, help_text='Profilo OID; se vuoto viene proposto automaticamente dopo il primo test.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivi', to='contatori.profilosnmp'),
        ),
        migrations.AddField(
            model_name='macchina',
            name='profilo_snmp',
            field=models.ForeignKey(blank=True, help_text='Profilo OID; se vuoto il portale prova il riconoscimento automatico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macchine', to='contatori.profilosnmp'),
        ),
        migrations.CreateModel(
            name='ColonnaProfiloSNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('oid', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Inserisci un OID numerico puntato, ad esempio 1.3.6.1.2.1.1.3.0.', regex='^\\d+(?:\\.\\d+)+$')])),
                ('tipo_valore', models.CharField(choices=[('NUMERO', 'Numero'), ('TESTO', 'Testo'), ('TIMETICKS', 'Tempo (TimeTicks)')], default='NUMERO', max_length=10)),
                ('modalita', models.CharField(choices=[('GET', 'GET (OID esatto)'), ('WALK', 'WALK (colonna MIB)')], default='GET', max_length=8)),
                ('aggregazione', models.CharField(choices=[('PRIMO', 'Primo valore'), ('MASSIMO', 'Valore massimo'), ('MINIMO', 'Valore minimo'), ('SOMMA', 'Somma')], default='PRIMO', max_length=10)),
                ('unita', models.CharField(blank=True, max_length=24)),
                ('fattore', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('contatore_mfc', models.CharField(blank=True, choices=[('', 'Non e un contatore MFC'), ('a4_bn', 'A4 BN'), ('a3_bn', 'A3 BN'), ('a4_col', 'A4 colore'), ('a3_col', 'A3 colore')], max_length=8)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('attiva', models.BooleanField(default=True)),
                ('profilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colonne', to='contatori.profilosnmp')),
            ],
            options={
                'verbose_name': 'Colonna profilo SNMP',
                'verbose_name_plural': 'Colonne profilo SNMP',
                'ordering': ['ordine', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('profilo', 'oid'), name='contatori_profilo_oid_unico'), models.UniqueConstraint(condition=models.Q(('contatore_mfc__gt', '')), fields=('profilo', 'contatore_mfc'), name='contatori_profilo_contatore_mfc_unico')],
            },
        ),
    ]
