# Generated by Django 5.2.16 on 2026-09-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatori', '0009_seed_profili_snmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivosnmp',
            name='categoria',
            field=models.CharField(choices=[('LETTORE', 'Lettore / terminale'), ('STAMPANTE', 'Stampante / MFC extra'), ('FIREWALL', 'Firewall / sicurezza'), ('RETE', 'Rete'), ('SERVER', 'Server / hypervisor'), ('STORAGE', 'NAS / storage'), ('UPS', 'UPS / alimentazione'), ('AMBIENTE', 'Sensore ambiente'), ('ALTRO', 'Altro dispositivo')], default='LETTORE', max_length=16),
        ),
    ]
