# Generated by Django 5.2.16 on 2026-09-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatori', '0010_alter_dispositivosnmp_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivosnmp',
            name='community',
            field=models.CharField(blank=True, help_text='Vuoto = community globale; usare una community read-only.', max_length=60),
        ),
        migrations.AddField(
            model_name='macchina',
            name='snmp_community',
            field=models.CharField(blank=True, help_text='Vuoto = community globale; usare una community read-only.', max_length=60),
        ),
    ]
