# Generated by Django 5.2.16 on 2026-10-01 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatori', '0013_rilevazionesnmp_dati_stampante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySNMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('segreto_cifrato', models.TextField(editable=False)),
                ('versione', models.CharField(blank=True, choices=[('', 'Versione della scansione'), ('v1', 'SNMPv1'), ('v2c', 'SNMPv2c')], max_length=4)),
                ('porta', models.PositiveIntegerField(blank=True, null=True)),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('attiva', models.BooleanField(default=True)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Community SNMP',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DiscoverySNMP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rete', models.CharField(max_length=64)),
                ('hosts', models.JSONField(default=list)),
                ('community_ids', models.JSONField(default=list)),
                ('versione', models.CharField(max_length=4)),
                ('porta', models.PositiveIntegerField(default=161)),
                ('timeout', models.PositiveIntegerField(default=2)),
                ('stato', models.CharField(choices=[('ATTESA', 'In coda'), ('CORSO', 'In corso'), ('COMPLETA', 'Completata'), ('ERRORE', 'Da riprendere'), ('ANNULLATA', 'Interrotta')], default='ATTESA', max_length=10)),
                ('cursore', models.PositiveIntegerField(default=0)),
                ('candidata', models.PositiveIntegerField(default=0)),
                ('revisione', models.PositiveIntegerField(default=0)),
                ('completati', models.PositiveIntegerField(default=0)),
                ('risultati', models.JSONField(default=list)),
                ('errore', models.CharField(blank=True, max_length=250)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('richiesta_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creata_il'],
            },
        ),
    ]
