# Generated by Django 5.2.16 on 2026-10-01 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatori', '0014_community_discovery_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivosnmp',
            name='community_salvata',
            field=models.ForeignKey(blank=True, help_text='Se selezionata, prevale sulla community manuale e globale.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contatori.communitysnmp'),
        ),
        migrations.AddField(
            model_name='macchina',
            name='community_salvata',
            field=models.ForeignKey(blank=True, help_text='Se selezionata, prevale sulla community manuale e globale.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contatori.communitysnmp'),
        ),
    ]
