# Generated by Django 5.2.16 on 2026-10-02 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatori', '0015_community_salvata_apparati'),
    ]

    operations = [
        migrations.AddField(
            model_name='colonnaprofilosnmp',
            name='fonte',
            field=models.CharField(blank=True, help_text='Origine della verifica (walk apparato/firmware o MIB).', max_length=200),
        ),
        migrations.AddField(
            model_name='colonnaprofilosnmp',
            name='soglia_critica_max',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='colonnaprofilosnmp',
            name='soglia_critica_min',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='colonnaprofilosnmp',
            name='soglia_warning_max',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='colonnaprofilosnmp',
            name='soglia_warning_min',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='colonnaprofilosnmp',
            name='verificata',
            field=models.BooleanField(default=False, help_text='OID confermato su un walk reale o su una MIB ufficiale.'),
        ),
        migrations.AddField(
            model_name='profilosnmp',
            name='oid_riconoscimento',
            field=models.CharField(blank=True, help_text='OID letto con GET durante il riconoscimento: se risponde, il profilo prevale. Per apparati con sysObjectID generico (es. Synology si presenta come net-snmp).', max_length=255, validators=[django.core.validators.RegexValidator(message='Inserisci un OID numerico puntato, ad esempio 1.3.6.1.2.1.1.3.0.', regex='^\\d+(?:\\.\\d+)+$')]),
        ),
        migrations.AlterField(
            model_name='colonnaprofilosnmp',
            name='aggregazione',
            field=models.CharField(choices=[('PRIMO', 'Primo valore'), ('MASSIMO', 'Valore massimo'), ('MINIMO', 'Valore minimo'), ('SOMMA', 'Somma'), ('MEDIA', 'Media')], default='PRIMO', max_length=10),
        ),
        migrations.AlterField(
            model_name='sondasnmp',
            name='aggregazione',
            field=models.CharField(choices=[('PRIMO', 'Primo valore'), ('MASSIMO', 'Valore massimo'), ('MINIMO', 'Valore minimo'), ('SOMMA', 'Somma'), ('MEDIA', 'Media')], default='PRIMO', max_length=10),
        ),
    ]
