# Generated by Django 5.2.16 on 2026-10-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatori', '0017_preset_synology_netsnmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonnaprofilosnmp',
            name='tipo_valore',
            field=models.CharField(choices=[('NUMERO', 'Numero'), ('TESTO', 'Testo'), ('TIMETICKS', 'Tempo (TimeTicks)'), ('ERR_PRT', 'Errori stampante (hrPrinterDetectedErrorState)')], default='NUMERO', max_length=10),
        ),
        migrations.AlterField(
            model_name='sondasnmp',
            name='tipo_valore',
            field=models.CharField(choices=[('NUMERO', 'Numero'), ('TESTO', 'Testo'), ('TIMETICKS', 'Tempo (TimeTicks)'), ('ERR_PRT', 'Errori stampante (hrPrinterDetectedErrorState)')], default='NUMERO', max_length=10),
        ),
    ]
