# Generated by Django 5.2.16 on 2026-10-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatori', '0019_preset_stampanti_verificati'),
    ]

    operations = [
        migrations.AddField(
            model_name='colonnaprofilosnmp',
            name='etichette',
            field=models.CharField(blank=True, help_text='Testo per i codici numerici, es. 1=Normale, 2=Guasto.', max_length=500),
        ),
        migrations.AddField(
            model_name='sondasnmp',
            name='etichette',
            field=models.CharField(blank=True, help_text='Testo per i codici numerici, es. 1=Normale, 2=Guasto.', max_length=500),
        ),
    ]
