# Generated by Django 5.2.16 on 2026-10-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatori', '0023_kyocera_contatori_mfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitysnmp',
            name='versione',
            field=models.CharField(blank=True, choices=[('', 'Versione della scansione'), ('v1', 'SNMPv1'), ('v2c', 'SNMPv2c'), ('v3', 'SNMPv3')], max_length=4),
        ),
        migrations.AlterField(
            model_name='dispositivosnmp',
            name='versione',
            field=models.CharField(blank=True, choices=[('', 'Usa configurazione globale'), ('v1', 'SNMPv1'), ('v2c', 'SNMPv2c'), ('v3', 'SNMPv3')], help_text='Vuoto = versione SNMP globale.', max_length=4),
        ),
        migrations.AlterField(
            model_name='macchina',
            name='snmp_versione',
            field=models.CharField(blank=True, choices=[('', 'Usa configurazione globale'), ('v1', 'SNMPv1'), ('v2c', 'SNMPv2c'), ('v3', 'SNMPv3')], help_text='Vuoto = profilo o configurazione globale.', max_length=4),
        ),
        migrations.AlterField(
            model_name='profilosnmp',
            name='versione',
            field=models.CharField(blank=True, choices=[('', 'Usa configurazione globale'), ('v1', 'SNMPv1'), ('v2c', 'SNMPv2c'), ('v3', 'SNMPv3')], max_length=4),
        ),
    ]
