# Generated by Django 5.2.16 on 2026-10-06 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatori', '0025_acl_consultazione_gestione'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetturaConsumabile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('pct', models.PositiveSmallIntegerField(blank=True, help_text='Livello in %; vuoto se la stampante non lo dichiara', null=True)),
                ('rilevata_il', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('macchina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumabili', to='contatori.macchina')),
            ],
            options={
                'verbose_name': 'Lettura consumabile',
                'verbose_name_plural': 'Letture consumabili',
                'ordering': ['-rilevata_il', 'nome'],
                'indexes': [models.Index(fields=['macchina', 'nome', 'rilevata_il'], name='contatori_cons_mac_nome_dt')],
            },
        ),
    ]
