# Generated by Django 5.2.16 on 2026-10-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatori', '0027_acl_verifica_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivosnmp',
            name='verificato',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='impostazionisnmp',
            name='community',
            field=models.CharField(blank=True, default='', help_text="Community SNMP in sola lettura usata quando l'apparato non ne ha una propria. Vuota = nessuna lettura finché non la imposti.", max_length=60),
        ),
    ]
