from django.urls import path
from . import views

app_name = "contatori"
urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("riconciliazione/", views.riconciliazione, name="riconciliazione"),
    path("riconciliazione/<str:trimestre>/", views.riconciliazione, name="riconciliazione_trim"),
    path("macchina/<int:pk>/", views.macchina_detail, name="macchina"),
    path("lettura/nuova/", views.importa_lettura, name="importa_lettura"),
    path("leggi-snmp/", views.leggi_snmp, name="leggi_snmp"),
    path("macchine/", views.macchine_list, name="macchine"),
    path("macchine/nuova/", views.macchina_edit, name="macchina_nuova"),
    path("macchine/<int:pk>/", views.macchina_edit, name="macchina_edit"),
    path("macchine/<int:pk>/test-snmp/", views.macchina_test_snmp, name="macchina_test_snmp"),
    path("discovery/", views.discovery, name="discovery"),
    path("discovery/<int:pk>/applica-ip/", views.discovery_applica_ip, name="discovery_applica_ip"),
    path("snmp/", views.snmp_centrale, name="snmp_centrale"),
    path("snmp/interroga-tutti/", views.dispositivi_snmp_interroga_tutti,
         name="snmp_interroga_tutti"),
    path("snmp/dispositivi/nuovo/", views.dispositivo_snmp_edit,
         name="snmp_dispositivo_nuovo"),
    path("snmp/dispositivi/<int:pk>/", views.dispositivo_snmp_detail,
         name="snmp_dispositivo"),
    path("snmp/dispositivi/<int:pk>/modifica/", views.dispositivo_snmp_edit,
         name="snmp_dispositivo_edit"),
    path("snmp/dispositivi/<int:pk>/interroga/", views.dispositivo_snmp_interroga,
         name="snmp_dispositivo_interroga"),
    path("snmp/dispositivi/<int:dispositivo_pk>/sonde/nuova/", views.sonda_snmp_edit,
         name="snmp_sonda_nuova"),
    path("snmp/dispositivi/<int:dispositivo_pk>/sonde/<int:pk>/modifica/",
         views.sonda_snmp_edit, name="snmp_sonda_edit"),
    path("macchina/<int:pk>/consumabili/", views.macchina_consumabili, name="macchina_consumabili"),
    path("consumabili/", views.consumabili_flotta, name="consumabili"),
    path("consumabili/<int:pk>/riepilogo/", views.macchina_consumabili_riepilogo, name="consumabili_riepilogo"),
    path("analisi/", views.analisi, name="analisi"),
    path("analisi/export.xlsx", views.export_analisi, name="export_analisi"),
    path("riconciliazione/<str:trimestre>/export.xlsx", views.export_riconciliazione, name="export_riconciliazione"),
]
